CREATE TABLE EN_QUAL_ROLE_T (
	QUAL_ROLE_ID NUMBER(19) NOT NULL,
	ROLE_ID NUMBER(19) NOT NULL,
	ACTV_IND NUMBER(1) NOT NULL,
	QUAL_ROLE_DESC VARCHAR2(2000) NULL,
	DOC_HDR_ID NUMBER(14) NULL,
	FRM_DT DATE NULL,
  	TO_DT DATE NULL,
  	ACTVN_DT DATE NULL,
  	DACTVN_DT DATE NULL,
  	VER_NBR NUMBER(8) DEFAULT 0,
  	CUR_IND NUMBER(1) DEFAULT 0,
  	PREV_VER_ID NUMBER(19),
  	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
  	CONSTRAINT EN_QUAL_ROLE_PK PRIMARY KEY (QUAL_ROLE_ID)
);

CREATE TABLE EN_QUAL_ROLE_MBR_T (
	QUAL_ROLE_MBR_ID NUMBER(19) NOT NULL,
	RSP_ID NUMBER(19) NULL,
	QUAL_ROLE_ID NUMBER(19) NOT NULL,
	MBR_ID VARCHAR2(200) NOT NULL,
	MBR_TYP VARCHAR2(1) NOT NULL,
    DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_QUAL_ROLE_MBR_PK PRIMARY KEY (QUAL_ROLE_MBR_ID)
);

CREATE TABLE EN_QUAL_ROLE_EXT_T (
	QUAL_ROLE_EXT_ID NUMBER(19) NOT NULL,
	QUAL_ROLE_ID NUMBER(19) NOT NULL,
	ROLE_ATTRIB_ID NUMBER(19) NOT NULL,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_QUAL_ROLE_EXT_PK PRIMARY KEY (QUAL_ROLE_EXT_ID)
);

CREATE TABLE EN_QUAL_ROLE_EXT_VAL_T (
	QUAL_ROLE_EXT_VAL_ID NUMBER(19) NOT NULL,
	QUAL_ROLE_EXT_ID NUMBER(19) NOT NULL,
	EXT_KEY VARCHAR2(2000) NOT NULL,
	EXT_VAL VARCHAR2(2000) NOT NULL,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_QUAL_ROLE_EXT_VAL_PK PRIMARY KEY (QUAL_ROLE_EXT_VAL_ID)
);

CREATE TABLE EN_ROLE_T (
	ROLE_ID NUMBER(19) NOT NULL,
	ROLE_NM VARCHAR2(250) NOT NULL,
	ROLE_DESC VARCHAR2(2000) NULL,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_ROLE_T_PK PRIMARY KEY (ROLE_ID)
);

CREATE TABLE EN_ROLE_ATTRIB_T (
	ROLE_ATTRIB_ID NUMBER(19) NOT NULL,
	ROLE_ID NUMBER(19) NOT NULL,
	RULE_ATTRIB_ID NUMBER(19) NOT NULL,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_ROLE_ATTRIB_PK PRIMARY KEY (ROLE_ATTRIB_ID)
);

ALTER TABLE EN_QUAL_ROLE_T ADD CONSTRAINT EN_QUAL_ROLE_TR1 FOREIGN KEY (ROLE_ID) REFERENCES EN_ROLE_T (ROLE_ID) ENABLE;
ALTER TABLE EN_QUAL_ROLE_T ADD CONSTRAINT EN_QUAL_ROLE_TR2 FOREIGN KEY (PREV_VER_ID) REFERENCES EN_QUAL_ROLE_T (QUAL_ROLE_ID) ENABLE;

ALTER TABLE EN_QUAL_ROLE_MBR_T ADD CONSTRAINT EN_QUAL_ROLE_MBR_TR1 FOREIGN KEY (QUAL_ROLE_ID) REFERENCES EN_QUAL_ROLE_T (QUAL_ROLE_ID) ENABLE;

ALTER TABLE EN_QUAL_ROLE_EXT_T ADD CONSTRAINT EN_QUAL_ROLE_EXT_TR1 FOREIGN KEY (QUAL_ROLE_ID) REFERENCES EN_QUAL_ROLE_T (QUAL_ROLE_ID) ENABLE;
ALTER TABLE EN_QUAL_ROLE_EXT_T ADD CONSTRAINT EN_QUAL_ROLE_EXT_TR2 FOREIGN KEY (ROLE_ATTRIB_ID) REFERENCES EN_ROLE_ATTRIB_T (ROLE_ATTRIB_ID) ENABLE;

ALTER TABLE EN_QUAL_ROLE_EXT_VAL_T ADD CONSTRAINT EN_QUAL_ROLE_EXT_VAL_TR1 FOREIGN KEY (QUAL_ROLE_EXT_ID) REFERENCES EN_QUAL_ROLE_EXT_T (QUAL_ROLE_EXT_ID) ENABLE;

ALTER TABLE EN_ROLE_ATTRIB_T ADD CONSTRAINT EN_ROLE_ATTRIB_TR1 FOREIGN KEY (ROLE_ID) REFERENCES EN_ROLE_T (ROLE_ID) ENABLE;
ALTER TABLE EN_ROLE_ATTRIB_T ADD CONSTRAINT EN_ROLE_ATTRIB_TR2 FOREIGN KEY (RULE_ATTRIB_ID) REFERENCES EN_RULE_ATTRIB_T (RULE_ATTRIB_ID) ENABLE;

CREATE UNIQUE INDEX EN_ROLE_TI1 ON EN_ROLE_T (ROLE_NM);
