--
-- Copyright 2005-2011 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

DROP TABLE EN_SERVICE_DEF_T
/
DROP TABLE EN_SERVICE_DEF_INTER_T
/
DROP TABLE EN_ORG_RESP_ID_T
/
DROP TABLE EN_DIRTY_CACHE_T
/
DROP TABLE EN_CACHE_SERVER_T
/
DROP TABLE EN_RULE_ATTRIB_VLD_VAL_T
/
DROP TABLE EN_RULE_ATTRIB_KEY_VAL_T
/
DROP TABLE EN_TRANSACTION_TST_PRSN_T
/
DROP TABLE EN_TRANSACTION_TST_ADDRS_T
/
DROP TABLE EN_MESSAGE_QUE_T
/


DROP TABLE EN_DOC_RTE_TYP_T
/
DROP TABLE EN_DOC_TYP_RTE_LVL_T
/
DROP TABLE EN_USR_T
/
DROP TABLE EN_WRKGRP_EXT_DTA_T
/
DROP TABLE EN_WRKGRP_EXT_T
/
DROP TABLE EN_WRKGRP_MBR_T
/
DROP TABLE EN_WRKGRP_T
/
DROP TABLE EN_WRKGRP_TYP_ATTRIB_T
/
DROP TABLE EN_WRKGRP_TYP_T
/
DROP TABLE FS_CODES_DESC_T
/

DROP TABLE KIM_ENTITY_ATTRIBUTES_T
/
DROP TABLE KIM_GROUPS_GROUPS_T
/
DROP TABLE KIM_GROUPS_PRINCIPALS_T
/
DROP TABLE KIM_GROUP_ATTRIBUTES_T
/
DROP TABLE KIM_GROUP_QLFD_ROLES_T
/
DROP TABLE KIM_GRP_TYP_DFLT_ATTRIBS_T
/
DROP TABLE KIM_NAMESPACE_DFLT_ATTRIBS_T
/
DROP TABLE KIM_ROLE_ATTRIBUTES_T
/
DROP TABLE KOM_ORGANIZATIONS_CONTEXTS_T
/
DROP TABLE KOM_ORGANIZATIONS_T
/
DROP TABLE KOM_ORGANIZATION_CATEGORIES_T
/
DROP TABLE KOM_ORGANIZATION_CONTEXTS_T
/
DROP TABLE KIM_ATTRIBUTE_TYPES_T
/
DROP TABLE KIM_PRNCPL_QLFD_ROLES_T
/
DROP TABLE KIM_ROLES_GROUPS_T
/
DROP TABLE KIM_ROLES_PERMISSIONS_T
/
DROP TABLE KIM_ROLES_PRINCIPALS_T
/
DROP TABLE KIM_ROLES_T
/
DROP TABLE KIM_PRINCIPALS_T
/
DROP TABLE KIM_PERMISSIONS_T
/
DROP TABLE KIM_NAMESPACES_T
/
DROP TABLE KIM_GROUPS_T
/
DROP TABLE KIM_GROUP_TYPES_T
/
DROP TABLE KIM_ENTITYS_T
/
DROP TABLE KIM_ENTITY_TYPES_T
/
DROP TABLE FP_DOC_TYPE_ATTR_T
/
DROP TABLE FP_DOC_TYPE_T
/

-- note that for mysql, these would need to be DROP TABLE statements /

DROP SEQUENCE DIRTY_CACHE_SEQ
/
DROP SEQUENCE EN_SERVICE_DEF_INTERFACE_SEQ
/
DROP SEQUENCE SEQ_DOCUMENT_TYPE_ATTRIBUTE
/
DROP SEQUENCE SEQ_KIM_ATTRIBUTE_TYPES_ID
/
DROP SEQUENCE SEQ_KIM_ENTITYS_ID
/
DROP SEQUENCE SEQ_KIM_ENTITY_ATTRIBS_ID
/
DROP SEQUENCE SEQ_KIM_ENTITY_TYPES_ID
/
DROP SEQUENCE SEQ_KIM_GROUPS_ID
/
DROP SEQUENCE SEQ_KIM_GROUP_ATTRIBUTES_ID
/
DROP SEQUENCE SEQ_KIM_GROUP_QLFD_ROLES_ID
/
DROP SEQUENCE SEQ_KIM_GROUP_TYPES_ID
/
DROP SEQUENCE SEQ_KIM_GRP_TYP_DFLT_ATTR_ID
/
DROP SEQUENCE SEQ_KIM_NAMESPACES_ID
/
DROP SEQUENCE SEQ_KIM_NMSPCE_DFLT_ATTR_ID
/
DROP SEQUENCE SEQ_KIM_PERMISSIONS_ID
/
DROP SEQUENCE SEQ_KIM_PRINCIPALS_ID
/
DROP SEQUENCE SEQ_KIM_PRNCPL_QLFD_ROLES_ID
/
DROP SEQUENCE SEQ_KIM_ROLES_ID
/
DROP SEQUENCE SEQ_KIM_ROLE_ATTRIBUTES_ID
/
DROP SEQUENCE SEQ_KOM_ORGANIZATIONS_ID
/
DROP SEQUENCE SEQ_KOM_ORGNZTNS_CNTXTS_ID
/
DROP SEQUENCE SEQ_KOM_ORGNZTN_CNTXTS_ID
/
DROP SEQUENCE SEQ_KOM_ORGNZTN_CTGRS_ID
/
DROP SEQUENCE SEQ_ROUTE_QUEUE
/
DROP SEQUENCE SEQ_TRANSACTION_TST
/
DROP SEQUENCE SEQ_TRAVEL_DOC_ID
/
DROP SEQUENCE SEQ_TRAVEL_FO_ID
/
