-- Drop Sequences --;

-- Suppress error messages when dropping non-existing tables --;
WHENEVER SQLERROR CONTINUE;

DROP SEQUENCE SEQ_ACTN_ITM;
DROP SEQUENCE SEQ_ACTION_REQUEST;
DROP SEQUENCE SEQ_ACTION_TAKEN;
DROP SEQUENCE SEQ_DOCUMENT_ROUTE_HEADER;
DROP SEQUENCE SEQ_RESPONSIBILITY_ID;
DROP SEQUENCE SEQ_ROUTE_TEMPLATE;
DROP SEQUENCE SEQUENCE_EN_USR;
DROP SEQUENCE SEQ_RTE_NODE;
DROP SEQUENCE SEQ_EN_WRKGRP;
DROP SEQUENCE DIRTY_CACHE_SEQ;
DROP SEQUENCE SEQ_ROUTE_QUEUE;
DROP SEQUENCE SEQ_DOC_NTE;
DROP SEQUENCE SEQ_EN_EDOCLT;
DROP SEQUENCE SEQ_HELP_ENTRY;
DROP SEQUENCE SEQ_RULE_TMPL_OPTN;
DROP SEQUENCE SEQ_SEARCHABLE_ATTRIBUTE_VALUE;
DROP SEQUENCE SEQ_DOCUMENT_TYPE_ATTRIBUTE;
DROP SEQUENCE SEQ_ACTION_LIST_OPTN;
DROP SEQUENCE SERVICE_DEF_SEQ;
DROP SEQUENCE EN_SERVICE_DEF_INTERFACE_SEQ;
DROP SEQUENCE BAM_SEQ;
DROP SEQUENCE BAM_PARAM_SEQ;

-- transaction tests --; 
DROP SEQUENCE SEQ_TRANSACTION_TST;

-- Reinstate error messages and exit --;
WHENEVER SQLERROR EXIT SQL.SQLCODE