CREATE INDEX EN_ACTN_TKN_TI1
 ON EN_ACTN_TKN_T (DOC_HDR_ID, ACTN_TKN_PRSN_EN_ID)
/
CREATE INDEX EN_ACTN_TKN_TI2
 ON EN_ACTN_TKN_T (DOC_HDR_ID, ACTN_TKN_PRSN_EN_ID, ACTN_TKN_CD)
/
CREATE INDEX EN_ACTN_TKN_TI3
 ON EN_ACTN_TKN_T (ACTN_TKN_PRSN_EN_ID)
/
CREATE INDEX EN_ACTN_TKN_TI4
 ON EN_ACTN_TKN_T (ACTN_TKN_DLGTR_PRSN_EN_ID)
/
CREATE INDEX EN_ACTN_TKN_TI5
 ON EN_ACTN_TKN_T (DOC_HDR_ID)
/
