CREATE UNIQUE INDEX EN_DOC_TYP_TI1
      ON EN_DOC_TYP_T (DOC_TYP_NM, DOC_TYP_VER_NBR)
/
CREATE INDEX EN_DOC_TYP_TI2
      ON EN_DOC_TYP_T (DOC_TYP_PARNT_ID)
/
CREATE INDEX EN_DOC_TYP_TI3
      ON EN_DOC_TYP_T (DOC_TYP_ID, DOC_TYP_PARNT_ID)
/
CREATE INDEX EN_DOC_TYP_TI4
      ON EN_DOC_TYP_T (DOC_TYP_PREV_VER)
/
CREATE INDEX EN_DOC_TYP_TI5
      ON EN_DOC_TYP_T (DOC_TYP_CUR_IND)
/
