CREATE INDEX EN_DOC_HDR_EXT_LONG_TI1 ON EN_DOC_HDR_EXT_LONG_T (DOC_HDR_EXT_VAL_KEY, DOC_HDR_EXT_VAL)
/  
CREATE INDEX EN_DOC_HDR_EXT_LONG_TI2 ON EN_DOC_HDR_EXT_LONG_T (DOC_HDR_ID)
/
CREATE INDEX EN_DOC_HDR_EXT_LONG_TI3 ON EN_DOC_HDR_EXT_LONG_T (DOC_HDR_EXT_VAL)
/
