CREATE INDEX EN_DOC_TYP_PROC_TI1 ON EN_DOC_TYP_PROC_T (DOC_TYP_ID)
/
CREATE INDEX EN_DOC_TYP_PROC_TI2 ON EN_DOC_TYP_PROC_T (INIT_RTE_NODE_ID)
/
CREATE INDEX EN_DOC_TYP_PROC_TI3 ON EN_DOC_TYP_PROC_T (PROC_NM)
/
