CREATE INDEX EN_EDL_FIELD_DMP_TI1
      ON EN_EDL_FIELD_DMP_T (DOC_HDR_ID, FLD_NM, SUBSTR(FLD_VAL, 1, 128))
/
CREATE INDEX EN_EDL_FIELD_DMP_TI2
      ON EN_EDL_FIELD_DMP_T (FLD_NM, SUBSTR(FLD_VAL, 1, 128))
/