CREATE INDEX EN_MSG_QUE_TI1 ON EN_MSG_QUE_T (MESSAGE_SERVICE_NM, SERVICE_METHOD_NM)
/
CREATE INDEX EN_MSG_QUE_TI2 ON EN_MSG_QUE_T (MESSAGE_ENTITY_NM, MESSAGE_QUE_STAT_CD, MESSAGE_QUE_IP_NBR, MESSAGE_QUE_DT)
/