CREATE INDEX EN_RTE_BRCH_ST_TI1 ON EN_RTE_BRCH_ST_T (RTE_BRCH_ID, ST_KEY)
/
CREATE INDEX EN_RTE_BRCH_ST_TI2 ON EN_RTE_BRCH_ST_T (RTE_BRCH_ID)
/
CREATE INDEX EN_RTE_BRCH_ST_TI3 ON EN_RTE_BRCH_ST_T (ST_KEY, ST_VAL_TXT)
/
