ALTER TABLE APP_SPONSRD_USER_ATTRIB_DEFS_T 
ADD CONSTRAINT APP_SPONSRD_USER_ATTR_UK1 UNIQUE
(
APPLICATION_ID,
ATTRIBUTE_NAME
) ENABLE
/
ALTER TABLE APP_SPONSRD_USER_ATTRIB_DEFS_T
ADD CONSTRAINT APP_SPONSRD_USER_ATTR_FK1 FOREIGN KEY
(
APPLICATION_ID
)
REFERENCES APPLICATIONS_T
(
ID
) ENABLE
/
ALTER TABLE APP_SPONSRD_USER_ATTRIB_DEFS_T
ADD CONSTRAINT APP_SPONSRD_USER_ATTR_FK2 FOREIGN KEY
(
ATTRIBUTE_TYPE_ID
)
REFERENCES ATTRIBUTE_TYPES_T
(
ID
) ENABLE
/