ALTER TABLE APP_SPSRD_PERSON_ATTR_DEFS_T 
ADD CONSTRAINT APP_SPONSRD_PERSON_ATTR_UK1 UNIQUE
(
APPLICATION_ID,
ATTRIBUTE_NAME
) ENABLE
/
ALTER TABLE APP_SPSRD_PERSON_ATTR_DEFS_T
ADD CONSTRAINT APP_SPSRD_PERSON_ATTR_FK1 FOREIGN KEY
(
APPLICATION_ID
)
REFERENCES APPLICATIONS_T
(
ID
) ENABLE
/
ALTER TABLE APP_SPSRD_PERSON_ATTR_DEFS_T
ADD CONSTRAINT APP_SPSRD_PERSON_ATTR_FK2 FOREIGN KEY
(
ATTRIBUTE_TYPE_ID
)
REFERENCES ATTRIBUTE_TYPES_T
(
ID
) ENABLE
/