ALTER TABLE KIM_GROUP_ATTRIBUTES_T
ADD CONSTRAINT KIM_GROUP_ATTRIBUTES_UK1 UNIQUE
(
GROUP_ID,
ATTRIBUTE_NAME
) ENABLE
/
ALTER TABLE KIM_GROUP_ATTRIBUTES_T
ADD CONSTRAINT KIM_GROUP_ATTRIBUTES_FK1 FOREIGN KEY
(
GROUP_ID
)
REFERENCES KIM_GROUPS_T
(
ID
) ENABLE
/
ALTER TABLE KIM_GROUP_ATTRIBUTES_T
ADD CONSTRAINT KIM_GROUP_ATTRIBUTES_FK2 FOREIGN KEY
(
ATTRIBUTE_TYPE_ID
)
REFERENCES KIM_ATTRIBUTE_TYPES_T
(
ID
) ENABLE
/