ALTER TABLE KIM_NAMESPACE_DFLT_ATTRIBS_T 
ADD CONSTRAINT KIM_NMSPCE_DFLT_ATTR_UK1 UNIQUE
(
NAMESPACE_ID,
ATTRIBUTE_NAME
) ENABLE
/
ALTER TABLE KIM_NAMESPACE_DFLT_ATTRIBS_T
ADD CONSTRAINT KIM_NMSPCE_DFLT_ATTR_FK1 FOREIGN KEY
(
NAMESPACE_ID
)
REFERENCES KIM_NAMESPACES_T
(
ID
) ENABLE
/
ALTER TABLE KIM_NAMESPACE_DFLT_ATTRIBS_T
ADD CONSTRAINT KIM_NMSPCE_DFLT_ATTR_FK2 FOREIGN KEY
(
ATTRIBUTE_TYPE_ID
)
REFERENCES KIM_ATTRIBUTE_TYPES_T
(
ID
) ENABLE
/