ALTER TABLE KIM_ROLES_PERMISSIONS_T
ADD CONSTRAINT KIM_ROLES_PERMISSIONS_FK1 FOREIGN KEY
(
ROLE_ID
)
REFERENCES KIM_ROLES_T
(
ID
) ENABLE
/
ALTER TABLE KIM_ROLES_PERMISSIONS_T
ADD CONSTRAINT KIM_ROLES_PERMISSIONS_FK2 FOREIGN KEY
(
PERMISSION_ID
)
REFERENCES KIM_PERMISSIONS_T
(
ID
) ENABLE
/