ALTER TABLE KIM_ROLES_PRINCIPALS_T
ADD CONSTRAINT KIM_ROLES_PRINCIPALS_FK1 FOREIGN KEY
(
ROLE_ID
)
REFERENCES KIM_ROLES_T
(
ID
) ENABLE
/
ALTER TABLE KIM_ROLES_PRINCIPALS_T
ADD CONSTRAINT KIM_ROLES_PRINCIPALS_FK2 FOREIGN KEY
(
PRINCIPAL_ID
)
REFERENCES KIM_PRINCIPALS_T
(
ID
) ENABLE
/