ALTER TABLE KIM_PERSONS_PRINCIPALS_T
ADD CONSTRAINT KIM_PERSONS_PRINCIPALS_FK1 FOREIGN KEY
(
  PERSON_ID
)
REFERENCES KIM_PERSONS_T
(
 ID
) ENABLE
/
ALTER TABLE KIM_PERSONS_PRINCIPALS_T
ADD CONSTRAINT KIM_PERSONS_PRINCIPALS_FK2 FOREIGN KEY
(
  PRINCIPAL_ID
)
REFERENCES KIM_PRINCIPALS_T
(
 ID
) ENABLE
/
