ALTER TABLE KIM_GROUPS_GROUPS_T
ADD CONSTRAINT KIM_GROUPS_GROUPS_FK1 FOREIGN KEY
(
PARENT_GROUP_ID
)
REFERENCES KIM_GROUPS_T
(
ID
) ENABLE
/
ALTER TABLE KIM_GROUPS_GROUPS_T
ADD CONSTRAINT KIM_GROUPS_GROUPS_FK2 FOREIGN KEY
(
MEMBER_GROUP_ID
)
REFERENCES KIM_GROUPS_T
(
ID
) ENABLE
/