CREATE INDEX EN_DOC_HDR_EXT_DT_TI1 ON EN_DOC_HDR_EXT_DT_T (DOC_HDR_EXT_VAL_KEY, DOC_HDR_EXT_VAL)
/
CREATE INDEX EN_DOC_HDR_EXT_DT_TI2 ON EN_DOC_HDR_EXT_DT_T (DOC_HDR_ID)
/
CREATE INDEX EN_DOC_HDR_EXT_DT_TI3 ON EN_DOC_HDR_EXT_DT_T (DOC_HDR_EXT_VAL)
/
