CREATE INDEX EN_RTE_NODE_INSTN_ST_TI1 ON EN_RTE_NODE_INSTN_ST_T (RTE_NODE_INSTN_ID, ST_KEY)
/
CREATE INDEX EN_RTE_NODE_INSTN_ST_TI2 ON EN_RTE_NODE_INSTN_ST_T (RTE_NODE_INSTN_ID)
/
CREATE INDEX EN_RTE_NODE_INSTN_ST_TI3 ON EN_RTE_NODE_INSTN_ST_T (ST_KEY, ST_VAL_TXT)
/
