CREATE INDEX EN_RTE_NODE_TI1 ON EN_RTE_NODE_T (RTE_NODE_NM, DOC_TYP_ID)
/
CREATE INDEX EN_RTE_NODE_TI2 ON EN_RTE_NODE_T (DOC_TYP_ID, DOC_FNL_APRVR_IND)
/
CREATE INDEX EN_RTE_NODE_TI3 ON EN_RTE_NODE_T (BRCH_PROTO_ID)
/
CREATE INDEX EN_RTE_NODE_TI4 ON EN_RTE_NODE_T (DOC_TYP_ID)
/