CREATE INDEX KIM_PRNCPL_QLFD_ROLES_TI1
 ON KIM_PRNCPL_QLFD_ROLES_T (PRINCIPAL_ID)
/
CREATE INDEX KIM_PRNCPL_QLFD_ROLES_TI2
 ON KIM_PRNCPL_QLFD_ROLES_T (ROLE_ID)
/
CREATE INDEX KIM_PRNCPL_QLFD_ROLES_TI3
 ON KIM_PRNCPL_QLFD_ROLES_T (PRINCIPAL_ID, ROLE_ID)
/