CREATE INDEX KIM_GROUP_QLFD_ROLES_TI1
 ON KIM_GROUP_QLFD_ROLES_T (GROUP_ID)
/
CREATE INDEX KIM_GROUP_QLFD_ROLES_TI2
 ON KIM_GROUP_QLFD_ROLES_T (ROLE_ID)
/
CREATE INDEX KIM_GROUP_QLFD_ROLES_TI3
 ON KIM_GROUP_QLFD_ROLES_T (GROUP_ID, ROLE_ID)
/