CREATE INDEX KEN_NOTIFICATIONSI1 ON NOTIFICATIONS (CONTENT_TYPE_ID)
/

CREATE INDEX KEN_NOTIFICATIONSI2 ON NOTIFICATIONS (PRIORITY_ID)
/

CREATE INDEX KEN_NOTIFICATIONSI3 ON NOTIFICATIONS (PRODUCER_ID)
/