TRUNCATE TABLE BK_BOOK_AUTHOR_T
/
INSERT INTO BK_BOOK_AUTHOR_T (AUTHOR_ID,BOOK_ID)
  VALUES (1,1)
/
INSERT INTO BK_BOOK_AUTHOR_T (AUTHOR_ID,BOOK_ID)
  VALUES (1,2)
/
INSERT INTO BK_BOOK_AUTHOR_T (AUTHOR_ID,BOOK_ID)
  VALUES (2,1)
/
