TRUNCATE TABLE KRCR_CMPNT_SET_T
/
INSERT INTO KRCR_CMPNT_SET_T (CHKSM,CMPNT_SET_ID,LAST_UPDT_TS,VER_NBR)
  VALUES ('YF7O4JRiqftiUrQJzhfwpEPP3Oc=','DD:RICE',STR_TO_DATE( '20111030164958', '%Y%m%d%H%i%s' ),1)
/
INSERT INTO KRCR_CMPNT_SET_T (CHKSM,CMPNT_SET_ID,LAST_UPDT_TS,VER_NBR)
  VALUES ('qTdEjWgfA5vemMSMR8x8vwRzNts=','DD:TRAVEL',STR_TO_DATE( '20121125192538', '%Y%m%d%H%i%s' ),1)
/
