TRUNCATE TABLE KRMS_TERM_RSLVR_PARM_SPEC_T
/
INSERT INTO KRMS_TERM_RSLVR_PARM_SPEC_T (NM,TERM_RSLVR_ID,TERM_RSLVR_PARM_SPEC_ID,VER_NBR)
  VALUES ('Campus Code','T1000','T1000',1)
/
INSERT INTO KRMS_TERM_RSLVR_PARM_SPEC_T (NM,TERM_RSLVR_ID,TERM_RSLVR_PARM_SPEC_ID,VER_NBR)
  VALUES ('Org Code','T1001','T1001',1)
/
INSERT INTO KRMS_TERM_RSLVR_PARM_SPEC_T (NM,TERM_RSLVR_ID,TERM_RSLVR_PARM_SPEC_ID,VER_NBR)
  VALUES ('Principal ID','T1001','T1002',1)
/
