TRUNCATE TABLE KRMS_RULE_T
/
INSERT INTO KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,VER_NBR)
  VALUES ('Y','stub rule lorem ipsum','Rule1','KR-RULE-TEST','T1000','T1000',1)
/
INSERT INTO KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,VER_NBR)
  VALUES ('Y','Frog specimens bogus rule foo','Rule2','KR-RULE-TEST','T1001','T1001',1)
/
INSERT INTO KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,VER_NBR)
  VALUES ('Y','Bloomington campus code rule','Rule3','KR-RULE-TEST','T1002','T1002',1)
/
INSERT INTO KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,VER_NBR)
  VALUES ('Y','check for possible BBQ ingiter hazard','Rule4','KR-RULE-TEST','T1003','T1003',1)
/
INSERT INTO KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,VER_NBR)
  VALUES ('Y','remembered to wear socks','Rule5','KR-RULE-TEST','T1004','T1004',1)
/
INSERT INTO KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,VER_NBR)
  VALUES ('Y','good behavior at carnival','Rule6','KR-RULE-TEST','T1005','T1005',1)
/
INSERT INTO KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,VER_NBR)
  VALUES ('Y','is KRMS in da haus','Rule7','KR-RULE-TEST','T1006','T1006',1)
/
INSERT INTO KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,VER_NBR)
  VALUES ('Y','For testing compound props','CmpdTestRule','KR-RULE-TEST','T1007','T1007',1)
/
INSERT INTO KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,VER_NBR)
  VALUES ('Y','Does PO require my approval','Going Away Party for Travis','KR-RULE-TEST','T1011','T1008',1)
/
