TRUNCATE TABLE KRMS_CNTXT_VLD_TERM_SPEC_T
/
INSERT INTO KRMS_CNTXT_VLD_TERM_SPEC_T (CNTXT_ID,CNTXT_TERM_SPEC_PREREQ_ID,PREREQ,TERM_SPEC_ID)
  VALUES ('CONTEXT1','T1000','N','T1002')
/
INSERT INTO KRMS_CNTXT_VLD_TERM_SPEC_T (CNTXT_ID,CNTXT_TERM_SPEC_PREREQ_ID,PREREQ,TERM_SPEC_ID)
  VALUES ('CONTEXT1','T1001','N','T1003')
/
INSERT INTO KRMS_CNTXT_VLD_TERM_SPEC_T (CNTXT_ID,CNTXT_TERM_SPEC_PREREQ_ID,PREREQ,TERM_SPEC_ID)
  VALUES ('CONTEXT1','T1002','N','T1004')
/
INSERT INTO KRMS_CNTXT_VLD_TERM_SPEC_T (CNTXT_ID,CNTXT_TERM_SPEC_PREREQ_ID,PREREQ,TERM_SPEC_ID)
  VALUES ('CONTEXT1','T1003','N','T1005')
/
INSERT INTO KRMS_CNTXT_VLD_TERM_SPEC_T (CNTXT_ID,CNTXT_TERM_SPEC_PREREQ_ID,PREREQ,TERM_SPEC_ID)
  VALUES ('CONTEXT1','T1004','N','T1006')
/
INSERT INTO KRMS_CNTXT_VLD_TERM_SPEC_T (CNTXT_ID,CNTXT_TERM_SPEC_PREREQ_ID,PREREQ,TERM_SPEC_ID)
  VALUES ('CONTEXT1','T1005','N','T1007')
/
INSERT INTO KRMS_CNTXT_VLD_TERM_SPEC_T (CNTXT_ID,CNTXT_TERM_SPEC_PREREQ_ID,PREREQ,TERM_SPEC_ID)
  VALUES ('CONTEXT1','T1006','N','T1000')
/
INSERT INTO KRMS_CNTXT_VLD_TERM_SPEC_T (CNTXT_ID,CNTXT_TERM_SPEC_PREREQ_ID,PREREQ,TERM_SPEC_ID)
  VALUES ('CONTEXT1','T1007','N','T1001')
/
