TRUNCATE TABLE KRMS_CMPND_PROP_PROPS_T
/
INSERT INTO KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID)
  VALUES ('T1007','T1008')
/
INSERT INTO KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID)
  VALUES ('T1007','T1009')
/
INSERT INTO KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID)
  VALUES ('T1007','T1010')
/
INSERT INTO KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID)
  VALUES ('T1011','T1012')
/
INSERT INTO KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID)
  VALUES ('T1011','T1013')
/
INSERT INTO KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID)
  VALUES ('T1011','T1014')
/
INSERT INTO KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID)
  VALUES ('T1013','T1015')
/
INSERT INTO KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID)
  VALUES ('T1013','T1016')
/
INSERT INTO KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID)
  VALUES ('T1013','T1017')
/
INSERT INTO KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID)
  VALUES ('T1014','T1018')
/
INSERT INTO KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID)
  VALUES ('T1014','T1019')
/
