TRUNCATE TABLE KRMS_ACTN_T
/
INSERT INTO KRMS_ACTN_T (ACTN_ID,DESC_TXT,NM,NMSPC_CD,RULE_ID,SEQ_NO,TYP_ID,VER_NBR)
  VALUES ('T1000','Action Stub for Testing','testAction','KR-RULE-TEST','T1000',1,'T1002',1)
/
