TRUNCATE TABLE TRV_ACCT_TYPE
/
INSERT INTO TRV_ACCT_TYPE (ACCT_TYPE,ACCT_TYPE_NAME,VER_NBR)
  VALUES ('CAT','Clearing Account Type',0)
/
INSERT INTO TRV_ACCT_TYPE (ACCT_TYPE,ACCT_TYPE_NAME,VER_NBR)
  VALUES ('EAT','Expense Account Type',0)
/
INSERT INTO TRV_ACCT_TYPE (ACCT_TYPE,ACCT_TYPE_NAME,VER_NBR)
  VALUES ('IAT',' Income Account Type',0)
/
