insert into EN_APPL_CNST_T values ('Config.Application.RunDocumentTypeConversion', 'true', 0);

CREATE INDEX EN_ACTN_RQST_TI7 ON EN_ACTN_RQST_T (ACTN_RQST_RTE_NODE_INSTN_ID) TABLESPACE EN_IDX01;

CREATE INDEX EN_ACTN_RQST_TI8 ON EN_ACTN_RQST_T (WRKGRP_ID);

CREATE INDEX EN_DOC_HDR_TI9 ON EN_DOC_HDR_T (DOC_APPL_DOC_ID);

CREATE INDEX EN_DOC_TYP_RTE_LVL_TI2 ON EN_DOC_TYP_RTE_LVL_T (DOC_TYP_ID, DOC_RTE_LVL_PRIO_NBR);


CREATE INDEX EN_DOC_HDR_EXT_TI1 ON EN_DOC_HDR_EXT_T (DOC_HDR_EXT_VAL_KEY, DOC_HDR_EXT_VAL);
CREATE INDEX EN_DOC_HDR_EXT_TI2 ON EN_DOC_HDR_EXT_T (DOC_HDR_ID);

CREATE INDEX EN_DOC_RTE_QUE_TI3 ON EN_DOC_RTE_QUE_T (DOC_RTE_QUE_STAT_CD);
CREATE INDEX EN_DOC_RTE_QUE_TI4 ON EN_DOC_RTE_QUE_T (DOC_RTE_QUE_DT);
CREATE INDEX EN_DOC_RTE_QUE_TI5 ON EN_DOC_RTE_QUE_T (DOC_RTE_QUE_STAT_CD, DOC_RTE_QUE_DT);

-- Document Type Process table definition--;
CREATE TABLE EN_DOC_TYP_PROC_T (
	DOC_TYP_PROC_ID				   NUMBER(19) NOT NULL,
	DOC_TYP_ID	            	   NUMBER(19) NOT NULL,
	INIT_RTE_NODE_ID               NUMBER(19) NOT NULL,
	PROC_NM						   VARCHAR2(255) NOT NULL,
	INIT_IND					   NUMBER(1) DEFAULT 0 NOT NULL,
	DB_LOCK_VER_NBR	               NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_DOC_TYP_PROC_T_PK PRIMARY KEY (DOC_TYP_PROC_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE INDEX EN_DOC_TYP_PROC_TI1 ON EN_DOC_TYP_PROC_T (DOC_TYP_ID) TABLESPACE EN_IDX01;
CREATE INDEX EN_DOC_TYP_PROC_TI2 ON EN_DOC_TYP_PROC_T (INIT_RTE_NODE_ID) TABLESPACE EN_IDX01;
CREATE INDEX EN_DOC_TYP_PROC_TI3 ON EN_DOC_TYP_PROC_T (PROC_NM) TABLESPACE EN_IDX01;

-- RouteNode table definition--;
CREATE TABLE EN_RTE_NODE_T (
	RTE_NODE_ID                    NUMBER(19) NOT NULL,
	DOC_TYP_ID                     NUMBER(19),
	RTE_NODE_NM                    VARCHAR2(255) NOT NULL,
	RTE_NODE_TYP				   VARCHAR2(255) NOT NULL,
	DOC_RTE_MTHD_NM                VARCHAR2(255),
	DOC_RTE_MTHD_CD                VARCHAR2(2),
	DOC_FNL_APRVR_IND              NUMBER(1), 
	DOC_MNDTRY_RTE_IND             NUMBER(1), 
	WRKGRP_ID                      NUMBER(14), 
    DOC_ACTVN_TYP_TXT              VARCHAR2(250),
    BRCH_PROTO_ID				   NUMBER(19),
	DB_LOCK_VER_NBR	               NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RTE_NODE_T_PK PRIMARY KEY (RTE_NODE_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE INDEX EN_RTE_NODE_TI1 ON EN_RTE_NODE_T (RTE_NODE_NM, DOC_TYP_ID) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_NODE_TI2 ON EN_RTE_NODE_T (DOC_TYP_ID, DOC_FNL_APRVR_IND) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_NODE_TI3 ON EN_RTE_NODE_T (BRCH_PROTO_ID) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_NODE_TI4 ON EN_RTE_NODE_T (DOC_TYP_ID) TABLESPACE EN_IDX01;

-- RouteNode Link table definition--;
CREATE TABLE EN_RTE_NODE_LNK_T (
	FROM_RTE_NODE_ID        	   NUMBER(19) NOT NULL,
	TO_RTE_NODE_ID          	   NUMBER(19) NOT NULL,
	CONSTRAINT EN_RTE_NODE_LNK_T_PK PRIMARY KEY (FROM_RTE_NODE_ID, TO_RTE_NODE_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE INDEX EN_RTE_NODE_LNK_TI1 ON EN_RTE_NODE_LNK_T (FROM_RTE_NODE_ID);
CREATE INDEX EN_RTE_NODE_LNK_TI2 ON EN_RTE_NODE_LNK_T (TO_RTE_NODE_ID);

-- BranchPrototype table definition--;
CREATE TABLE EN_RTE_BRCH_PROTO_T (
    RTE_BRCH_PROTO_ID			   NUMBER(19) NOT NULL,
    RTE_BRCH_PROTO_NM			   VARCHAR2(255) NOT NULL,
	DB_LOCK_VER_NBR	               NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RTE_BRCH_PROTO_T_PK PRIMARY KEY (RTE_BRCH_PROTO_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE INDEX EN_RTE_BRCH_PROTO_TI1 ON EN_RTE_BRCH_PROTO_T (RTE_BRCH_PROTO_NM) TABLESPACE EN_IDX01;

-- DocumentRouteHeaderValue Initial RouteNodeInstances table definition--;
CREATE TABLE EN_INIT_RTE_NODE_INSTN_T (
	DOC_HDR_ID	            	   	NUMBER(19) NOT NULL,
	RTE_NODE_INSTN_ID             	NUMBER(19) NOT NULL,
	CONSTRAINT EN_INIT_RTE_NODE_INSTN_T_PK PRIMARY KEY (DOC_HDR_ID, RTE_NODE_INSTN_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE INDEX EN_INIT_RTE_NODE_INSTN_TI1 on EN_INIT_RTE_NODE_INSTN_T(DOC_HDR_ID);
CREATE INDEX EN_INIT_RTE_NODE_INSTN_TI2 on EN_INIT_RTE_NODE_INSTN_T(RTE_NODE_INSTN_ID);

-- RouteNodeInstance table definition--;
CREATE TABLE EN_RTE_NODE_INSTN_T (
	RTE_NODE_INSTN_ID              NUMBER(19) NOT NULL,
	DOC_ID						   NUMBER(19) NOT NULL,
	RTE_NODE_ID                    NUMBER(19) NOT NULL,
	BRCH_ID						   NUMBER(19),
	PROC_RTE_NODE_INSTN_ID		   NUMBER(19),
	ACTV_IND					   NUMBER(1) DEFAULT 0 NOT NULL,
    CMPLT_IND					   NUMBER(1) DEFAULT 0 NOT NULL,
    INIT_IND					   NUMBER(1) DEFAULT 0 NOT NULL,
	DB_LOCK_VER_NBR	               NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RTE_NODE_INSTN_T_PK PRIMARY KEY (RTE_NODE_INSTN_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE INDEX EN_RTE_NODE_INSTN_TI1 ON EN_RTE_NODE_INSTN_T (DOC_ID, ACTV_IND, CMPLT_IND) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_NODE_INSTN_TI2 ON EN_RTE_NODE_INSTN_T (RTE_NODE_ID) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_NODE_INSTN_TI3 ON EN_RTE_NODE_INSTN_T (BRCH_ID) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_NODE_INSTN_TI4 ON EN_RTE_NODE_INSTN_T (PROC_RTE_NODE_INSTN_ID) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_NODE_INSTN_TI5 ON EN_RTE_NODE_INSTN_T (DOC_ID) TABLESPACE EN_IDX01;

-- RouteNodeInstance Link table definition--;
CREATE TABLE EN_RTE_NODE_INSTN_LNK_T (
	FROM_RTE_NODE_INSTN_ID   	   NUMBER(19) NOT NULL,
	TO_RTE_NODE_INSTN_ID    	   NUMBER(19) NOT NULL,
	CONSTRAINT EN_RTE_NODE_INSTN_LNK_T_PK PRIMARY KEY (FROM_RTE_NODE_INSTN_ID, TO_RTE_NODE_INSTN_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE INDEX EN_RTE_NODE_INSTN_LNK_TI1 ON EN_RTE_NODE_INSTN_LNK_T (FROM_RTE_NODE_INSTN_ID) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_NODE_INSTN_LNK_TI2 ON EN_RTE_NODE_INSTN_LNK_T (TO_RTE_NODE_INSTN_ID) TABLESPACE EN_IDX01;

-- Branch table definition--;
CREATE TABLE EN_RTE_BRCH_T (
    RTE_BRCH_ID					   NUMBER(19) NOT NULL,
    BRCH_NM						   VARCHAR(255) NOT NULL,
    PARNT_RTE_BRCH_ID			   NUMBER(19),
    INIT_RTE_NODE_INSTN_ID		   NUMBER(19) NOT NULL,
    SPLT_RTE_NODE_INSTN_ID		   NUMBER(19),
    JOIN_RTE_NODE_INSTN_ID		   NUMBER(19),
	DB_LOCK_VER_NBR	               NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RTE_BRCH_T_PK PRIMARY KEY (RTE_BRCH_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE INDEX EN_RTE_BRCH_TI1 ON EN_RTE_BRCH_T (BRCH_NM) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_BRCH_TI2 ON EN_RTE_BRCH_T (PARNT_RTE_BRCH_ID) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_BRCH_TI3 ON EN_RTE_BRCH_T (INIT_RTE_NODE_INSTN_ID) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_BRCH_TI4 ON EN_RTE_BRCH_T (SPLT_RTE_NODE_INSTN_ID) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_BRCH_TI5 ON EN_RTE_BRCH_T (JOIN_RTE_NODE_INSTN_ID) TABLESPACE EN_IDX01;
	
-- Branch state table definition--;
CREATE TABLE EN_RTE_BRCH_ST_T (
	RTE_BRCH_ST_ID				   NUMBER(19) NOT NULL,
    RTE_BRCH_ID			   		   NUMBER(19) NOT NULL,
	ST_KEY						   VARCHAR2(255) NOT NULL,
	ST_VAL_TXT					   VARCHAR2(2000),
	DB_LOCK_VER_NBR	               NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RTE_BRCH_ST_T_PK PRIMARY KEY (RTE_BRCH_ST_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE INDEX EN_RTE_BRCH_ST_TI1 ON EN_RTE_BRCH_ST_T (RTE_BRCH_ID, ST_KEY) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_BRCH_ST_TI2 ON EN_RTE_BRCH_ST_T (RTE_BRCH_ID) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_BRCH_ST_TI3 ON EN_RTE_BRCH_ST_T (ST_KEY, ST_VAL_TXT) TABLESPACE EN_IDX01;

-- Node state table definition--;
CREATE TABLE EN_RTE_NODE_INSTN_ST_T (
	RTE_NODE_INSTN_ST_ID		   NUMBER(19) NOT NULL,
    RTE_NODE_INSTN_ID   		   NUMBER(19) NOT NULL,
	ST_KEY						   VARCHAR2(255) NOT NULL,
	ST_VAL_TXT					   VARCHAR2(2000),
	DB_LOCK_VER_NBR	               NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RTE_NODE_INSTN_ST_T_PK PRIMARY KEY (RTE_NODE_INSTN_ST_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE INDEX EN_RTE_NODE_INSTN_ST_TI1 ON EN_RTE_NODE_INSTN_ST_T (RTE_NODE_INSTN_ID, ST_KEY) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_NODE_INSTN_ST_TI2 ON EN_RTE_NODE_INSTN_ST_T (RTE_NODE_INSTN_ID) TABLESPACE EN_IDX01;
CREATE INDEX EN_RTE_NODE_INSTN_ST_TI3 ON EN_RTE_NODE_INSTN_ST_T (ST_KEY, ST_VAL_TXT) TABLESPACE EN_IDX01;

CREATE SEQUENCE SEQ_RTE_NODE INCREMENT BY 1 START WITH 2000;

-- EDocLite tables --;

-- EDocLite XSLT style table --;
create table en_edoclt_style_t (
  edoclt_style_id number(19) not null,
  edoclt_style_nm varchar(200) not null,
  edoclt_style_xml clob not null,
  edoclt_style_actv_ind number(1) not null,
  db_lock_ver_nbr number(8) default 0,
  CONSTRAINT en_edoclt_style_t PRIMARY KEY (edoclt_style_id)
) TABLESPACE EN01;

-- EDocLite form definition table --;
create table en_edoclt_def_t (
  edoclt_def_id number(19) not null,
  edoclt_def_nm varchar(200) not null,
  edoclt_def_xml clob not null,
  edoclt_def_actv_ind number(1) not null,
  db_lock_ver_nbr number(8) default 0,
  CONSTRAINT en_edoclt_def_t PRIMARY KEY (edoclt_def_id)
)	TABLESPACE EN01;

-- 5th normal form?? -- ;
-- EDocLite doctype->def,style association table --;
create table en_edoclt_assoc_t (
  edoclt_assoc_id number(19) not null,
  edoclt_assoc_doctype_nm varchar(200) not null,
  edoclt_assoc_def_nm varchar(200),  
  edoclt_assoc_style_nm varchar(200), 
  edoclt_assoc_actv_ind number(1) not null,
  db_lock_ver_nbr number(8) default 0,
  CONSTRAINT en_edoclt_assoc_t PRIMARY KEY (edoclt_assoc_id)
) TABLESPACE EN01;

CREATE SEQUENCE seq_en_edoclt INCREMENT BY 1 START WITH 2000;