ALTER TABLE EN_ACTN_RQST_T DROP COLUMN ACTN_RQST_RTE_NODE_INSTN_ID;

DROP INDEX EN_ACTN_RQST_TI7;

ALTER TABLE EN_DOC_TYP_T DROP COLUMN RTE_VER_NBR;

DROP TABLE EN_DOC_TYP_PROC_T
DROP TABLE EN_RTE_NODE_T;
DROP TABLE EN_RTE_NODE_LNK_T;
DROP TABLE EN_RTE_BRCH_PROTO_T;
DROP TABLE EN_INIT_RTE_NODE_INSTN_T;
DROP TABLE EN_RTE_NODE_INSTN_T;
DROP TABLE EN_RTE_NODE_INSTN_LNK_T;
DROP TABLE EN_RTE_BRCH_T;
DROP TABLE EN_RTE_BRCH_ST_T;
DROP TABLE EN_RTE_NODE_INSTN_ST_T;

DROP SEQUENCE SEQ_RTE_NODE;