--
-- Copyright 2005-2011 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

ALTER INDEX FP_DOC_HEADER_TC0 RENAME TO KRNS_DOC_HDR_TC0
/
ALTER INDEX FP_MAINT_DOC_ATTACHMENT_TC0 RENAME TO KRNS_MAINT_DOC_ATT_TC0
/
ALTER INDEX FP_MAINT_LOCK_TC0 RENAME TO KRNS_MAINT_LOCK_TC0
/
ALTER INDEX FP_MAINTENANCE_DOCUMENT_TC0 RENAME TO KRNS_MAINT_DOC_TC0
/
ALTER INDEX FS_ADHOC_RTE_ACTN_RECP_TC0 RENAME TO KRNS_ADHOC_RTE_ACTN_RECIP_TC0
/
ALTER INDEX FS_LOOKUP_RESULTS_MTC0 RENAME TO KRNS_LOOKUP_RSLT_TC0
/
ALTER INDEX FS_LOOKUP_SELECTIONS_MTC0 RENAME TO KRNS_LOOKUP_SEL_TC0
/
ALTER INDEX KNS_PESSIMISTIC_LOCK_TC0 RENAME TO KRNS_PESSIMISTIC_LOCK_TC0
/
ALTER INDEX SH_ATT_TC0 RENAME TO KRNS_ATT_TC0
/
ALTER INDEX SH_NTE_TC0 RENAME TO KRNS_NTE_TC0
/
ALTER INDEX SH_NTE_TYP_TC0 RENAME TO KRNS_NTE_TYP_TC0
/

ALTER TABLE KRNS_LOOKUP_RSLT_T MODIFY PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KRNS_LOOKUP_SEL_T MODIFY PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KRNS_NTE_T MODIFY AUTH_PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T MODIFY PRNCPL_ID VARCHAR2(40)
/
