CREATE INDEX EN_RULE_RSP_TI1 ON EN_RULE_RSP_T (RULE_BASE_VAL_ID);
CREATE INDEX EN_DOC_TYP_ATTRIB_TI1 ON EN_DOC_TYP_ATTRIB_T (DOC_TYP_ID);
CREATE INDEX EN_ACTN_RQST_TI6 ON EN_ACTN_RQST_T (ACTN_RQST_STAT_CD, ACTN_RQST_RESP_ID);