-- Update kim group table so kim type is set to the default value instead of null
-- Alter tables so null kim_type_ids are not allowed
UPDATE KRIM_GRP_T SET KIM_TYP_ID = '1' WHERE KIM_TYPE_ID IS NULL
/
ALTER TABLE KRIM_DLGN_T MODIFY KIM_TYP_ID NOT NULL;
/
ALTER TABLE KRIM_DLGN_MBR_ATTR_DATA_T MODIFY KIM_TYP_ID NOT NULL;
/
ALTER TABLE KRIM_GRP_ATTR_DATA_T MODIFY KIM_TYP_ID NOT NULL;
/
ALTER TABLE KRIM_GRP_T MODIFY KIM_TYP_ID NOT NULL;
/
ALTER TABLE KRIM_PERM_ATTR_DATA_T MODIFY KIM_TYP_ID NOT NULL;
/
ALTER TABLE KRIM_PERM_TMPL_T MODIFY KIM_TYP_ID NOT NULL;
/
ALTER TABLE KRIM_ROLE_MBR_ATTR_DATA_T MODIFY KIM_TYP_ID NOT NULL;
/
ALTER TABLE KRIM_ROLE_T MODIFY KIM_TYP_ID NOT NULL;
/
ALTER TABLE KRIM_RSP_ATTR_DATA_T MODIFY KIM_TYP_ID NOT NULL;
/
ALTER TABLE KRIM_RSP_TMPL_T MODIFY KIM_TYP_ID NOT NULL;
/
ALTER TABLE KRIM_TYP_ATTR_T MODIFY KIM_TYP_ID NOT NULL;