UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='notsys' WHERE PRNCPL_NM='NotSys'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='notsysadm' WHERE PRNCPL_NM='NotSysAdm'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testadmin1' WHERE PRNCPL_NM='TestAdmin1'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testadmin2' WHERE PRNCPL_NM='TestAdmin2'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testuser1' WHERE PRNCPL_NM='TestUser1'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testuser2' WHERE PRNCPL_NM='TestUser2'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testuser3' WHERE PRNCPL_NM='TestUser3'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testuser4' WHERE PRNCPL_NM='TestUser4'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testuser5' WHERE PRNCPL_NM='TestUser5'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testuser6' WHERE PRNCPL_NM='TestUser6'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='newacctusr' WHERE PRNCPL_NM='newAcctUsr'
/

UPDATE KRIM_PRNCPL_T SET PRNCPL_ID='notsys' WHERE PRNCPL_ID='NotSys'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_ID='notsysadm' WHERE PRNCPL_ID='NotSysAdm'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_ID='testadmin1' WHERE PRNCPL_ID='TestAdmin1'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_ID='testadmin2' WHERE PRNCPL_ID='TestAdmin2'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_ID='testuser1' WHERE PRNCPL_ID='TestUser1'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_ID='testuser2' WHERE PRNCPL_ID='TestUser2'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_ID='testuser3' WHERE PRNCPL_ID='TestUser3'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_ID='testuser4' WHERE PRNCPL_ID='TestUser4'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_ID='testuser5' WHERE PRNCPL_ID='TestUser5'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_ID='testuser6' WHERE PRNCPL_ID='TestUser6'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_ID='newaccountuser' WHERE PRNCPL_ID='newAccountUser'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_ID='kuluser' WHERE PRNCPL_ID='KULUSER'
/

