CREATE SEQUENCE TRV_FO_ID_S INCREMENT BY 1 START WITH 1000
/

DELETE FROM KRIM_ENTITY_EMAIL_T where EMAIL_ADDR='KULUSER@indiana.edu'
/

CREATE TABLE KR_KIM_TEST_BO (
    pk VARCHAR2(40),
    prncpl_id VARCHAR2(40)
)
/