UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='notsys' WHERE PRNCPL_NM='NotSys'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='notsysadm' WHERE PRNCPL_NM='NotSysAdm'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testadmin1' WHERE PRNCPL_NM='TestAdmin1'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testadmin2' WHERE PRNCPL_NM='TestAdmin2'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testuser1' WHERE PRNCPL_NM='TestUser1'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testuser2' WHERE PRNCPL_NM='TestUser2'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testuser3' WHERE PRNCPL_NM='TestUser3'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testuser4' WHERE PRNCPL_NM='TestUser4'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testuser5' WHERE PRNCPL_NM='TestUser5'
/
UPDATE KRIM_PRNCPL_T SET PRNCPL_NM='testuser6' WHERE PRNCPL_NM='TestUser6'
/