TRUNCATE TABLE KRNS_SESN_DOC_T
/

DROP TABLE KRNS_SESN_DOC_T
/

CREATE TABLE KRNS_SESN_DOC_T
(SESN_DOC_ID                   VARCHAR2(40) NOT NULL,
DOC_HDR_ID                     VARCHAR2(14) NOT NULL,
PRNCPL_ID                             VARCHAR2(40) NOT NULL,
IP_ADDR                                 VARCHAR2(60) NOT NULL,
SERIALZD_DOC_FRM               BLOB,
LAST_UPDT_DT                   DATE,
CONTENT_ENCRYPTED_IND          CHAR(1) DEFAULT 'N')
/

CREATE INDEX KRNS_SESN_DOC_TI1 ON KRNS_SESN_DOC_T
(
LAST_UPDT_DT                    ASC
)
/

ALTER TABLE KRNS_SESN_DOC_T
ADD CONSTRAINT KRNS_SESN_DOC_TP1
PRIMARY KEY (SESN_DOC_ID, DOC_HDR_ID, PRNCPL_ID, IP_ADDR)
/