ALTER TABLE EN_ACTN_ITM_T RENAME TO KREW_ACTN_ITM_T
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_ASND_DT TO ASND_DT
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_RQST_CD TO RQST_CD
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_DLGN_PRSN_EN_ID TO DLGN_PRNCPL_ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_DLGN_WRKGRP_ID TO DLGN_GRP_ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN DOC_TTL TO DOC_HDR_TTL
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN DOC_TYP_LBL_TXT TO DOC_TYP_LBL
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN DOC_TYP_HDLR_URL_ADDR TO DOC_HDLR_URL
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_RESP_ID TO RSP_ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_ACTN_ITM_T1 
/
CREATE INDEX KREW_ACTN_ITM_T1 ON KREW_ACTN_ITM_T (PRNCPL_ID)
/
DROP INDEX EN_ACTN_ITM_TI2 
/
CREATE INDEX KREW_ACTN_ITM_TI2 ON KREW_ACTN_ITM_T (DOC_HDR_ID)
/
DROP INDEX EN_ACTN_ITM_TI3 
/
CREATE INDEX KREW_ACTN_ITM_TI3 ON KREW_ACTN_ITM_T (ACTN_RQST_ID)
/
DROP INDEX EN_ACTN_ITM_TI4 
/
CREATE INDEX KREW_ACTN_ITM_TI4 ON KREW_ACTN_ITM_T (DLGN_PRNCPL_ID,DLGN_GRP_ID,PRNCPL_ID,DLGN_TYP)
/
DROP INDEX EN_ACTN_ITM_TI5 
/
CREATE INDEX KREW_ACTN_ITM_TI5 ON KREW_ACTN_ITM_T (PRNCPL_ID,DLGN_TYP,DOC_HDR_ID)
/
ALTER TABLE EN_ACTN_RQST_T RENAME TO KREW_ACTN_RQST_T
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_PARNT_ID TO PARNT_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_CD TO ACTN_RQST_CD
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN RULE_BASE_VALUES_ID TO RULE_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_STAT_CD TO STAT_CD
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RESP_ID TO RSP_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RECP_TYP_CD TO RECIP_TYP_CD
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_PRIO_NBR TO PRIO_NBR
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RTE_TYP_NM TO RTE_TYP_NM
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RTE_LVL_NBR TO RTE_LVL_NBR
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RTE_NODE_INSTN_ID TO RTE_NODE_INSTN_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_CRTE_DT TO CRTE_DT
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RESP_DESC TO RSP_DESC
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_IGN_PREV_ACTN_IND TO IGN_PREV_ACTN_IND
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_APPR_PLCY TO APPR_PLCY
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_CUR_IND TO CUR_IND
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_ACTN_RQST_T13 
/
CREATE INDEX KREW_ACTN_RQST_T13 ON KREW_ACTN_RQST_T (ACTN_TKN_ID)
/
DROP INDEX EN_ACTN_RQST_T14 
/
CREATE INDEX KREW_ACTN_RQST_T14 ON KREW_ACTN_RQST_T (PARNT_ID)
/
DROP INDEX EN_ACTN_RQST_TI1 
/
CREATE INDEX KREW_ACTN_RQST_T11 ON KREW_ACTN_RQST_T (DOC_HDR_ID)
/
DROP INDEX EN_ACTN_RQST_TI2 
/
CREATE INDEX KREW_ACTN_RQST_T12 ON KREW_ACTN_RQST_T (PRNCPL_ID)
/
DROP INDEX EN_ACTN_RQST_TI5 
/
CREATE INDEX KREW_ACTN_RQST_T15 ON KREW_ACTN_RQST_T (RSP_ID)
/
DROP INDEX EN_ACTN_RQST_TI6 
/
CREATE INDEX KREW_ACTN_RQST_T16 ON KREW_ACTN_RQST_T (STAT_CD,RSP_ID)
/
DROP INDEX EN_ACTN_RQST_TI7 
/
CREATE INDEX KREW_ACTN_RQST_T17 ON KREW_ACTN_RQST_T (RTE_NODE_INSTN_ID)
/
DROP INDEX EN_ACTN_RQST_TI8 
/
CREATE INDEX KREW_ACTN_RQST_T18 ON KREW_ACTN_RQST_T (GRP_ID)
/
DROP INDEX EN_ACTN_RQST_TI9 
/
CREATE INDEX KREW_ACTN_RQST_T19 ON KREW_ACTN_RQST_T (STAT_CD,DOC_HDR_ID)
/
ALTER TABLE EN_ACTN_TKN_T RENAME TO KREW_ACTN_TKN_T
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_DLGTR_PRSN_EN_ID TO DLGTR_PRNCPL_ID
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_DLGTR_WRKGRP_ID TO DLGTR_GRP_ID
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_CD TO ACTN_CD
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_DT TO ACTN_DT
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_ANNOTN_TXT TO ANNOTN
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_CUR_IND TO CUR_IND
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_ACTN_TKN_TI1 
/
CREATE INDEX KREW_ACTN_TKN_TI1 ON KREW_ACTN_TKN_T (DOC_HDR_ID,PRNCPL_ID)
/
DROP INDEX EN_ACTN_TKN_TI2 
/
CREATE INDEX KREW_ACTN_TKN_TI2 ON KREW_ACTN_TKN_T (DOC_HDR_ID,PRNCPL_ID,ACTN_CD)
/
DROP INDEX EN_ACTN_TKN_TI3 
/
CREATE INDEX KREW_ACTN_TKN_TI3 ON KREW_ACTN_TKN_T (PRNCPL_ID)
/
DROP INDEX EN_ACTN_TKN_TI4 
/
CREATE INDEX KREW_ACTN_TKN_TI4 ON KREW_ACTN_TKN_T (DLGTR_PRNCPL_ID)
/
DROP INDEX EN_ACTN_TKN_TI5 
/
CREATE INDEX KREW_ACTN_TKN_TI5 ON KREW_ACTN_TKN_T (DOC_HDR_ID)
/
ALTER TABLE EN_APPL_CNST_T RENAME TO KREW_APP_CNST_T
/
ALTER TABLE KREW_APP_CNST_T RENAME COLUMN APPL_CNST_VAL_TXT TO VAL
/
ALTER TABLE KREW_APP_CNST_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_ATTACHMENT_T RENAME TO KREW_ATT_T
/
ALTER TABLE KREW_ATT_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_DLGN_RSP_T RENAME TO KREW_DLGN_RSP_T
/
ALTER TABLE KREW_DLGN_RSP_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_DOC_HDR_CNTNT_T RENAME TO KREW_DOC_HDR_CNTNT_T
/
ALTER TABLE EN_DOC_HDR_EXT_DT_T RENAME TO KREW_DOC_HDR_EXT_DT_T
/
ALTER TABLE KREW_DOC_HDR_EXT_DT_T RENAME COLUMN DOC_HDR_EXT_ID TO DOC_HDR_EXT_DT_ID
/
ALTER TABLE KREW_DOC_HDR_EXT_DT_T RENAME COLUMN DOC_HDR_EXT_VAL_KEY TO KEY
/
ALTER TABLE KREW_DOC_HDR_EXT_DT_T RENAME COLUMN DOC_HDR_EXT_VAL TO VAL
/
DROP INDEX EN_DOC_HDR_EXT_DT_TI1 
/
CREATE INDEX KREW_DOC_HDR_EXT_DT_TI1 ON KREW_DOC_HDR_EXT_DT_T (KEY,VAL)
/
DROP INDEX EN_DOC_HDR_EXT_DT_TI2 
/
CREATE INDEX KREW_DOC_HDR_EXT_DT_TI2 ON KREW_DOC_HDR_EXT_DT_T (DOC_HDR_ID)
/
DROP INDEX EN_DOC_HDR_EXT_DT_TI3 
/
CREATE INDEX KREW_DOC_HDR_EXT_DT_TI3 ON KREW_DOC_HDR_EXT_DT_T (VAL)
/
ALTER TABLE EN_DOC_HDR_EXT_FLT_T RENAME TO KREW_DOC_HDR_EXT_FLT_T
/
ALTER TABLE KREW_DOC_HDR_EXT_FLT_T RENAME COLUMN DOC_HDR_EXT_ID TO DOC_HDR_EXT_FLT_ID
/
ALTER TABLE KREW_DOC_HDR_EXT_FLT_T RENAME COLUMN DOC_HDR_EXT_VAL_KEY TO KEY
/
ALTER TABLE KREW_DOC_HDR_EXT_FLT_T RENAME COLUMN DOC_HDR_EXT_VAL TO VAL
/
DROP INDEX EN_DOC_HDR_EXT_FLT_TI1 
/
CREATE INDEX KREW_DOC_HDR_EXT_FLT_TI1 ON KREW_DOC_HDR_EXT_FLT_T (KEY,VAL)
/
DROP INDEX EN_DOC_HDR_EXT_FLT_TI2 
/
CREATE INDEX KREW_DOC_HDR_EXT_FLT_TI2 ON KREW_DOC_HDR_EXT_FLT_T (DOC_HDR_ID)
/
DROP INDEX EN_DOC_HDR_EXT_FLT_TI3 
/
CREATE INDEX KREW_DOC_HDR_EXT_FLT_TI3 ON KREW_DOC_HDR_EXT_FLT_T (VAL)
/
ALTER TABLE EN_DOC_HDR_EXT_LONG_T RENAME TO KREW_DOC_HDR_EXT_LONG_T
/
ALTER TABLE KREW_DOC_HDR_EXT_LONG_T RENAME COLUMN DOC_HDR_EXT_ID TO DOC_HDR_EXT_LONG_ID
/
ALTER TABLE KREW_DOC_HDR_EXT_LONG_T RENAME COLUMN DOC_HDR_EXT_VAL_KEY TO KEY
/
ALTER TABLE KREW_DOC_HDR_EXT_LONG_T RENAME COLUMN DOC_HDR_EXT_VAL TO VAL
/
DROP INDEX EN_DOC_HDR_EXT_LONG_TI1 
/
CREATE INDEX KREW_DOC_HDR_EXT_LONG_TI1 ON KREW_DOC_HDR_EXT_LONG_T (KEY,VAL)
/
DROP INDEX EN_DOC_HDR_EXT_LONG_TI2 
/
CREATE INDEX KREW_DOC_HDR_EXT_LONG_TI2 ON KREW_DOC_HDR_EXT_LONG_T (DOC_HDR_ID)
/
DROP INDEX EN_DOC_HDR_EXT_LONG_TI3 
/
CREATE INDEX KREW_DOC_HDR_EXT_LONG_TI3 ON KREW_DOC_HDR_EXT_LONG_T (VAL)
/
ALTER TABLE EN_DOC_HDR_EXT_T RENAME TO KREW_DOC_HDR_EXT_T
/
ALTER TABLE KREW_DOC_HDR_EXT_T RENAME COLUMN DOC_HDR_EXT_VAL_KEY TO KEY
/
ALTER TABLE KREW_DOC_HDR_EXT_T RENAME COLUMN DOC_HDR_EXT_VAL TO VAL
/
DROP INDEX EN_DOC_HDR_EXT_TI1 
/
CREATE INDEX KREW_DOC_HDR_EXT_TI1 ON KREW_DOC_HDR_EXT_T (KEY,VAL)
/
DROP INDEX EN_DOC_HDR_EXT_TI2 
/
CREATE INDEX KREW_DOC_HDR_EXT_TI2 ON KREW_DOC_HDR_EXT_T (DOC_HDR_ID)
/
DROP INDEX EN_DOC_HDR_EXT_TI3 
/
CREATE INDEX KREW_DOC_HDR_EXT_TI3 ON KREW_DOC_HDR_EXT_T (VAL)
/
ALTER TABLE EN_DOC_HDR_T RENAME TO KREW_DOC_HDR_T
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_RTE_STAT_CD TO DOC_HDR_STAT_CD
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_RTE_LVL_NBR TO RTE_LVL
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_STAT_MDFN_DT TO STAT_MDFN_DT
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_CRTE_DT TO CRTE_DT
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_APRV_DT TO APRV_DT
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_FNL_DT TO FNL_DT
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_RTE_STAT_MDFN_DT TO RTE_STAT_MDFN_DT
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_RTE_LVL_MDFN_DT TO RTE_LVL_MDFN_DT
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_TTL TO TTL
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_APPL_DOC_ID TO APP_DOC_ID
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_INITR_PRSN_EN_ID TO INITR_PRNCPL_ID
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_RTE_USR_PRSN_EN_ID TO RTE_PRNCPL_ID
/
DROP INDEX EN_DOC_HDR_TI1 
/
CREATE INDEX KREW_DOC_HDR_TI1 ON KREW_DOC_HDR_T (DOC_TYP_ID)
/
DROP INDEX EN_DOC_HDR_TI2 
/
CREATE INDEX KREW_DOC_HDR_TI2 ON KREW_DOC_HDR_T (INITR_PRNCPL_ID)
/
DROP INDEX EN_DOC_HDR_TI3 
/
CREATE INDEX KREW_DOC_HDR_TI3 ON KREW_DOC_HDR_T (DOC_HDR_STAT_CD)
/
DROP INDEX EN_DOC_HDR_TI4 
/
CREATE INDEX KREW_DOC_HDR_TI4 ON KREW_DOC_HDR_T (TTL)
/
DROP INDEX EN_DOC_HDR_TI5 
/
CREATE INDEX KREW_DOC_HDR_TI5 ON KREW_DOC_HDR_T (CRTE_DT)
/
DROP INDEX EN_DOC_HDR_TI6 
/
CREATE INDEX KREW_DOC_HDR_TI6 ON KREW_DOC_HDR_T (RTE_STAT_MDFN_DT)
/
DROP INDEX EN_DOC_HDR_TI7 
/
CREATE INDEX KREW_DOC_HDR_TI7 ON KREW_DOC_HDR_T (APRV_DT)
/
DROP INDEX EN_DOC_HDR_TI8 
/
CREATE INDEX KREW_DOC_HDR_TI8 ON KREW_DOC_HDR_T (FNL_DT)
/
DROP INDEX EN_DOC_HDR_TI9 
/
CREATE INDEX KREW_DOC_HDR_TI9 ON KREW_DOC_HDR_T (APP_DOC_ID)
/
ALTER TABLE EN_DOC_NTE_T RENAME TO KREW_DOC_NTE_T
/
ALTER TABLE KREW_DOC_NTE_T RENAME COLUMN DOC_NTE_AUTH_PRSN_EN_ID TO AUTH_PRNCPL_ID
/
ALTER TABLE KREW_DOC_NTE_T RENAME COLUMN DOC_NTE_CRT_DT TO CRT_DT
/
ALTER TABLE KREW_DOC_NTE_T RENAME COLUMN DOC_NTE_TXT TO TXT
/
ALTER TABLE KREW_DOC_NTE_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_DOC_NTE_TI1 
/
CREATE INDEX KREW_DOC_NTE_TI1 ON KREW_DOC_NTE_T (DOC_HDR_ID)
/
ALTER TABLE EN_DOC_TYP_ATTRIB_T RENAME TO KREW_DOC_TYP_ATTR_T
/
ALTER TABLE KREW_DOC_TYP_ATTR_T RENAME COLUMN RULE_ATTRIB_ID TO RULE_ATTR_ID
/
DROP INDEX EN_DOC_TYP_ATTRIB_TI1 
/
CREATE INDEX KREW_DOC_TYP_ATTR_TI1 ON KREW_DOC_TYP_ATTR_T (DOC_TYP_ID)
/
ALTER TABLE EN_DOC_TYP_PLCY_RELN_T RENAME TO KREW_DOC_TYP_PLCY_RELN_T
/
ALTER TABLE KREW_DOC_TYP_PLCY_RELN_T RENAME COLUMN DOC_PLCY_VAL TO PLCY_NM
/
ALTER TABLE KREW_DOC_TYP_PLCY_RELN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_DOC_TYP_PROC_T RENAME TO KREW_DOC_TYP_PROC_T
/
ALTER TABLE KREW_DOC_TYP_PROC_T RENAME COLUMN PROC_NM TO NM
/
ALTER TABLE KREW_DOC_TYP_PROC_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_DOC_TYP_PROC_TI1 
/
CREATE INDEX KREW_DOC_TYP_PROC_TI1 ON KREW_DOC_TYP_PROC_T (DOC_TYP_ID)
/
DROP INDEX EN_DOC_TYP_PROC_TI2 
/
CREATE INDEX KREW_DOC_TYP_PROC_TI2 ON KREW_DOC_TYP_PROC_T (INIT_RTE_NODE_ID)
/
DROP INDEX EN_DOC_TYP_PROC_TI3 
/
CREATE INDEX KREW_DOC_TYP_PROC_TI3 ON KREW_DOC_TYP_PROC_T (NM)
/
ALTER TABLE EN_DOC_TYP_T RENAME TO KREW_DOC_TYP_T
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_PARNT_ID TO PARNT_ID
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_NM TO DOC_TYP_NM
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_CUR_IND TO CUR_IND
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_LBL_TXT TO LBL
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_PREV_VER TO PREV_DOC_TYP_VER_NBR
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_HDLR_URL_ADDR TO DOC_HDLR_URL
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_POST_PRCSR_NM TO POST_PRCSR
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_JNDI_URL_ADDR TO JNDI_URL
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN BLNKT_APPR_WRKGRP_ID TO BLNKT_APPR_GRP_ID
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN RPT_WRKGRP_ID TO RPT_GRP_ID
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN ADV_DOC_SRCH_URL_ADDR TO ADV_DOC_SRCH_URL
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_RTE_VER_NBR TO RTE_VER_NBR
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_NOTIFY_ADDR TO NOTIFY_ADDR
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN MESSAGE_ENTITY_NM TO SVC_NMSPC
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_EMAIL_XSL TO EMAIL_XSL
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_SECURITY_XML TO SEC_XML
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_DOC_TYP_TI2 
/
CREATE INDEX KREW_DOC_TYP_TI2 ON KREW_DOC_TYP_T (PARNT_ID)
/
ALTER TABLE EN_DOC_TYP_T disable CONSTRAINT EN_DOC_TYP_TI1 
/
 ALTER TABLE KREW_DOC_TYP_T ADD  CONSTRAINT KREW_DOC_TYP_TI1 UNIQUE (DOC_TYP_NM,DOC_TYP_VER_NBR)
/
DROP INDEX EN_DOC_TYP_TI3 
/
CREATE INDEX KREW_DOC_TYP_TI3 ON KREW_DOC_TYP_T (DOC_TYP_ID,PARNT_ID)
/
ALTER TABLE EN_DOC_TYP_T disable CONSTRAINT EN_DOC_TYP_TI1 
/
 ALTER TABLE KREW_DOC_TYP_T ADD  CONSTRAINT KREW_DOC_TYP_TI1 UNIQUE (DOC_TYP_NM,DOC_TYP_VER_NBR)
/
DROP INDEX EN_DOC_TYP_TI4 
/
CREATE INDEX KREW_DOC_TYP_TI4 ON KREW_DOC_TYP_T (PREV_DOC_TYP_VER_NBR)
/
ALTER TABLE EN_DOC_TYP_T disable CONSTRAINT EN_DOC_TYP_TI1 
/
 ALTER TABLE KREW_DOC_TYP_T ADD  CONSTRAINT KREW_DOC_TYP_TI1 UNIQUE (DOC_TYP_NM,DOC_TYP_VER_NBR)
/
DROP INDEX EN_DOC_TYP_TI5 
/
CREATE INDEX KREW_DOC_TYP_TI5 ON KREW_DOC_TYP_T (CUR_IND)
/
ALTER TABLE EN_DOC_TYP_T disable CONSTRAINT EN_DOC_TYP_TI1 
/
 ALTER TABLE KREW_DOC_TYP_T ADD  CONSTRAINT KREW_DOC_TYP_TI1 UNIQUE (DOC_TYP_NM,DOC_TYP_VER_NBR)
/
DROP INDEX EN_DOC_TYP_TI6 
/
CREATE INDEX KREW_DOC_TYP_TI6 ON KREW_DOC_TYP_T (DOC_TYP_NM)
/
ALTER TABLE EN_DOC_TYP_T disable CONSTRAINT EN_DOC_TYP_TI1 
/
 ALTER TABLE KREW_DOC_TYP_T ADD  CONSTRAINT KREW_DOC_TYP_TI1 UNIQUE (DOC_TYP_NM,DOC_TYP_VER_NBR)
/
DROP INDEX EN_DOC_TYP_TI7 
/
CREATE INDEX KREW_DOC_TYP_TI7 ON KREW_DOC_TYP_T (RPT_GRP_ID)
/
ALTER TABLE EN_DOC_TYP_T disable CONSTRAINT EN_DOC_TYP_TI1 
/
 ALTER TABLE KREW_DOC_TYP_T ADD  CONSTRAINT KREW_DOC_TYP_TI1 UNIQUE (DOC_TYP_NM,DOC_TYP_VER_NBR)
/
ALTER TABLE EN_EDL_DMP_T RENAME TO KREW_EDL_DMP_T
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DOC_RTE_STAT_CD TO DOC_HDR_STAT_CD
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DOC_MDFN_DT TO DOC_HDR_MDFN_DT
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DOC_CRTE_DT TO DOC_HDR_CRTE_DT
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DOC_TTL TO DOC_HDR_TTL
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DOC_INITR_ID TO DOC_HDR_INITR_PRNCPL_ID
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DOC_CRNT_NODE_NM TO CRNT_NODE_NM
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_EDL_DMP_TI1 
/
CREATE INDEX KREW_EDL_DMP_TI1 ON KREW_EDL_DMP_T (DOC_TYP_NM,DOC_HDR_ID)
/
ALTER TABLE EN_EDL_FIELD_DMP_T RENAME TO KREW_EDL_FLD_DMP_T
/
ALTER TABLE KREW_EDL_FLD_DMP_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_EDOCLT_ASSOC_T RENAME TO KREW_EDL_ASSCTN_T
/
ALTER TABLE KREW_EDL_ASSCTN_T RENAME COLUMN EDOCLT_ASSOC_DOCTYPE_NM TO DOC_TYP_NM
/
ALTER TABLE KREW_EDL_ASSCTN_T RENAME COLUMN EDOCLT_ASSOC_DEF_NM TO EDL_DEF_NM
/
ALTER TABLE KREW_EDL_ASSCTN_T RENAME COLUMN EDOCLT_ASSOC_STYLE_NM TO STYLE_NM
/
ALTER TABLE KREW_EDL_ASSCTN_T RENAME COLUMN EDOCLT_ASSOC_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_EDL_ASSCTN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_EDOCLT_DEF_T RENAME TO KREW_EDL_DEF_T
/
ALTER TABLE KREW_EDL_DEF_T RENAME COLUMN EDOCLT_DEF_NM TO NM
/
ALTER TABLE KREW_EDL_DEF_T RENAME COLUMN EDOCLT_DEF_XML TO XML
/
ALTER TABLE KREW_EDL_DEF_T RENAME COLUMN EDOCLT_DEF_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_EDL_DEF_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_EDOCLT_STYLE_T RENAME TO KREW_STYLE_T
/
ALTER TABLE KREW_STYLE_T RENAME COLUMN EDOCLT_STYLE_NM TO NM
/
ALTER TABLE KREW_STYLE_T RENAME COLUMN EDOCLT_STYLE_XML TO XML
/
ALTER TABLE KREW_STYLE_T RENAME COLUMN EDOCLT_STYLE_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_STYLE_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_HLP_T RENAME TO KREW_HLP_T
/
ALTER TABLE KREW_HLP_T RENAME COLUMN EN_HLP_NM TO NM
/
ALTER TABLE KREW_HLP_T RENAME COLUMN EN_HLP_TXT TO TXT
/
ALTER TABLE KREW_HLP_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_HLP_TI1 
/
CREATE INDEX KREW_HLP_TI1 ON KREW_HLP_T (EN_HLP_KY)
/
ALTER TABLE EN_INIT_RTE_NODE_INSTN_T RENAME TO KREW_INIT_RTE_NODE_INSTN_T
/
DROP INDEX EN_INIT_RTE_NODE_INSTN_TI 
/
CREATE INDEX KREW_INIT_RTE_NODE_INSTN_TI1 ON KREW_INIT_RTE_NODE_INSTN_T (DOC_HDR_ID)
/
DROP INDEX EN_INIT_RTE_NODE_INSTN_TI2 
/
CREATE INDEX KREW_INIT_RTE_NODE_INSTN_TI2 ON KREW_INIT_RTE_NODE_INSTN_T (RTE_NODE_INSTN_ID)
/
ALTER TABLE EN_OUT_BOX_ITM_T RENAME TO KREW_OUT_BOX_ITM_T
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_ASND_DT TO ASND_DT
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_RQST_CD TO RQST_CD
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_DLGN_PRSN_EN_ID TO DLGN_PRNCPL_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_DLGN_WRKGRP_ID TO DLGN_GRP_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN DOC_TTL TO DOC_HDR_TTL
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN DOC_TYP_LBL_TXT TO DOC_TYP_LBL
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN DOC_TYP_HDLR_URL_ADDR TO DOC_HDLR_URL
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_RESP_ID TO RSP_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_OUT_BOX_ITM_TI1 
/
CREATE INDEX KREW_OUT_BOX_ITM_TI1 ON KREW_OUT_BOX_ITM_T (PRNCPL_ID)
/
DROP INDEX EN_OUT_BOX_ITM_TI2 
/
CREATE INDEX KREW_OUT_BOX_ITM_TI2 ON KREW_OUT_BOX_ITM_T (DOC_HDR_ID)
/
DROP INDEX EN_OUT_BOX_ITM_TI3 
/
CREATE INDEX KREW_OUT_BOX_ITM_TI3 ON KREW_OUT_BOX_ITM_T (ACTN_RQST_ID)
/
DROP INDEX EN_OUT_BOX_ITM_TI4 
/
CREATE INDEX KREW_OUT_BOX_ITM_TI4 ON KREW_OUT_BOX_ITM_T (DLGN_PRNCPL_ID,DLGN_GRP_ID,PRNCPL_ID,DLGN_TYP)
/
ALTER TABLE EN_RMV_RPLC_DOC_T RENAME TO KREW_RMV_RPLC_DOC_T
/
ALTER TABLE KREW_RMV_RPLC_DOC_T RENAME COLUMN PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_RMV_RPLC_DOC_T RENAME COLUMN RPLC_PRSN_EN_ID TO RPLC_PRNCPL_ID
/
ALTER TABLE KREW_RMV_RPLC_DOC_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_RMV_RPLC_RULE_T RENAME TO KREW_RMV_RPLC_RULE_T
/
ALTER TABLE EN_RMV_RPLC_WRKGRP_T RENAME TO KREW_RMV_RPLC_GRP_T
/
ALTER TABLE KREW_RMV_RPLC_GRP_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE EN_RTE_BRCH_PROTO_T RENAME TO KREW_RTE_BRCH_PROTO_T
/
ALTER TABLE KREW_RTE_BRCH_PROTO_T RENAME COLUMN RTE_BRCH_PROTO_NM TO BRCH_NM
/
DROP INDEX EN_RTE_BRCH_PROTO_TI1 
/
CREATE INDEX KREW_RTE_BRCH_PROTO_TI1 ON KREW_RTE_BRCH_PROTO_T (BRCH_NM)
/
ALTER TABLE EN_RTE_BRCH_ST_T RENAME TO KREW_RTE_BRCH_ST_T
/
ALTER TABLE KREW_RTE_BRCH_ST_T RENAME COLUMN ST_KEY TO KEY
/
ALTER TABLE KREW_RTE_BRCH_ST_T RENAME COLUMN ST_VAL_TXT TO VAL
/
ALTER TABLE KREW_RTE_BRCH_ST_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_RTE_BRCH_ST_TI1 
/
CREATE INDEX KREW_RTE_BRCH_ST_TI1 ON KREW_RTE_BRCH_ST_T (RTE_BRCH_ID,KEY)
/
DROP INDEX EN_RTE_BRCH_ST_TI2 
/
CREATE INDEX KREW_RTE_BRCH_ST_TI2 ON KREW_RTE_BRCH_ST_T (RTE_BRCH_ID)
/
DROP INDEX EN_RTE_BRCH_ST_TI3 
/
CREATE INDEX KREW_RTE_BRCH_ST_TI3 ON KREW_RTE_BRCH_ST_T (KEY,VAL)
/
ALTER TABLE EN_RTE_BRCH_T RENAME TO KREW_RTE_BRCH_T
/
ALTER TABLE KREW_RTE_BRCH_T RENAME COLUMN BRCH_NM TO NM
/
ALTER TABLE KREW_RTE_BRCH_T RENAME COLUMN PARNT_RTE_BRCH_ID TO PARNT_ID
/
ALTER TABLE KREW_RTE_BRCH_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_RTE_BRCH_TI1 
/
CREATE INDEX KREW_RTE_BRCH_TI1 ON KREW_RTE_BRCH_T (NM)
/
DROP INDEX EN_RTE_BRCH_TI2 
/
CREATE INDEX KREW_RTE_BRCH_TI2 ON KREW_RTE_BRCH_T (PARNT_ID)
/
DROP INDEX EN_RTE_BRCH_TI3 
/
CREATE INDEX KREW_RTE_BRCH_TI3 ON KREW_RTE_BRCH_T (INIT_RTE_NODE_INSTN_ID)
/
DROP INDEX EN_RTE_BRCH_TI4 
/
CREATE INDEX KREW_RTE_BRCH_TI4 ON KREW_RTE_BRCH_T (SPLT_RTE_NODE_INSTN_ID)
/
DROP INDEX EN_RTE_BRCH_TI5 
/
CREATE INDEX KREW_RTE_BRCH_TI5 ON KREW_RTE_BRCH_T (JOIN_RTE_NODE_INSTN_ID)
/
ALTER TABLE EN_RTE_NODE_CFG_PARM_T RENAME TO KREW_RTE_NODE_CFG_PARM_T
/
ALTER TABLE KREW_RTE_NODE_CFG_PARM_T RENAME COLUMN RTE_NODE_CFG_PARM_ND TO RTE_NODE_ID
/
ALTER TABLE KREW_RTE_NODE_CFG_PARM_T RENAME COLUMN RTE_NODE_CFG_PARM_KEY TO KEY
/
ALTER TABLE KREW_RTE_NODE_CFG_PARM_T RENAME COLUMN RTE_NODE_CFG_PARM_VAL TO VAL
/
ALTER TABLE EN_RTE_NODE_INSTN_LNK_T RENAME TO KREW_RTE_NODE_INSTN_LNK_T
/
DROP INDEX EN_RTE_NODE_INSTN_LNK_TI1 
/
CREATE INDEX KREW_RTE_NODE_INSTN_LNK_TI1 ON KREW_RTE_NODE_INSTN_LNK_T (FROM_RTE_NODE_INSTN_ID)
/
DROP INDEX EN_RTE_NODE_INSTN_LNK_TI2 
/
CREATE INDEX KREW_RTE_NODE_INSTN_LNK_TI2 ON KREW_RTE_NODE_INSTN_LNK_T (TO_RTE_NODE_INSTN_ID)
/
ALTER TABLE EN_RTE_NODE_INSTN_ST_T RENAME TO KREW_RTE_NODE_INSTN_ST_T
/
ALTER TABLE KREW_RTE_NODE_INSTN_ST_T RENAME COLUMN ST_KEY TO KEY
/
ALTER TABLE KREW_RTE_NODE_INSTN_ST_T RENAME COLUMN ST_VAL_TXT TO VAL
/
ALTER TABLE KREW_RTE_NODE_INSTN_ST_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_RTE_NODE_INSTN_ST_TI1 
/
CREATE INDEX KREW_RTE_NODE_INSTN_ST_TI1 ON KREW_RTE_NODE_INSTN_ST_T (RTE_NODE_INSTN_ID,KEY)
/
DROP INDEX EN_RTE_NODE_INSTN_ST_TI2 
/
CREATE INDEX KREW_RTE_NODE_INSTN_ST_TI2 ON KREW_RTE_NODE_INSTN_ST_T (RTE_NODE_INSTN_ID)
/
DROP INDEX EN_RTE_NODE_INSTN_ST_TI3 
/
CREATE INDEX KREW_RTE_NODE_INSTN_ST_TI3 ON KREW_RTE_NODE_INSTN_ST_T (KEY,VAL)
/
ALTER TABLE EN_RTE_NODE_INSTN_T RENAME TO KREW_RTE_NODE_INSTN_T
/
ALTER TABLE KREW_RTE_NODE_INSTN_T RENAME COLUMN DOC_ID TO DOC_HDR_ID
/
ALTER TABLE KREW_RTE_NODE_INSTN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_RTE_NODE_INSTN_TI1 
/
CREATE INDEX KREW_RTE_NODE_INSTN_TI1 ON KREW_RTE_NODE_INSTN_T (DOC_HDR_ID,ACTV_IND,CMPLT_IND)
/
DROP INDEX EN_RTE_NODE_INSTN_TI2 
/
CREATE INDEX KREW_RTE_NODE_INSTN_TI2 ON KREW_RTE_NODE_INSTN_T (RTE_NODE_ID)
/
DROP INDEX EN_RTE_NODE_INSTN_TI3 
/
CREATE INDEX KREW_RTE_NODE_INSTN_TI3 ON KREW_RTE_NODE_INSTN_T (BRCH_ID)
/
DROP INDEX EN_RTE_NODE_INSTN_TI4 
/
CREATE INDEX KREW_RTE_NODE_INSTN_TI4 ON KREW_RTE_NODE_INSTN_T (PROC_RTE_NODE_INSTN_ID)
/
ALTER TABLE EN_RTE_NODE_LNK_T RENAME TO KREW_RTE_NODE_LNK_T
/
DROP INDEX EN_RTE_NODE_LNK_TI1 
/
CREATE INDEX KREW_RTE_NODE_LNK_TI1 ON KREW_RTE_NODE_LNK_T (FROM_RTE_NODE_ID)
/
DROP INDEX EN_RTE_NODE_LNK_TI2 
/
CREATE INDEX KREW_RTE_NODE_LNK_TI2 ON KREW_RTE_NODE_LNK_T (TO_RTE_NODE_ID)
/
ALTER TABLE EN_RTE_NODE_T RENAME TO KREW_RTE_NODE_T
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN RTE_NODE_NM TO NM
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN RTE_NODE_TYP TO TYP
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN DOC_RTE_MTHD_NM TO RTE_MTHD_NM
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN DOC_RTE_MTHD_CD TO RTE_MTHD_CD
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN DOC_FNL_APRVR_IND TO FNL_APRVR_IND
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN DOC_MNDTRY_RTE_IND TO MNDTRY_RTE_IND
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN DOC_ACTVN_TYP_TXT TO ACTVN_TYP
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_RTE_NODE_TI1 
/
CREATE INDEX KREW_RTE_NODE_TI1 ON KREW_RTE_NODE_T (NM,DOC_TYP_ID)
/
DROP INDEX EN_RTE_NODE_TI2 
/
CREATE INDEX KREW_RTE_NODE_TI2 ON KREW_RTE_NODE_T (DOC_TYP_ID,FNL_APRVR_IND)
/
DROP INDEX EN_RTE_NODE_TI3 
/
CREATE INDEX KREW_RTE_NODE_TI3 ON KREW_RTE_NODE_T (BRCH_PROTO_ID)
/
DROP INDEX EN_RTE_NODE_TI4 
/
CREATE INDEX KREW_RTE_NODE_TI4 ON KREW_RTE_NODE_T (DOC_TYP_ID)
/
ALTER TABLE EN_RULE_ATTRIB_T RENAME TO KREW_RULE_ATTR_T
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_ID TO RULE_ATTR_ID
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_NM TO NM
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_LBL_TXT TO LBL
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_TYP TO RULE_ATTR_TYP_CD
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_DESC TO DESC
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_CLS_NM TO CLS_NM
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_XML_RTE_TXT TO XML
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN MESSAGE_ENTITY_NM TO SVC_NMSPC
/
ALTER TABLE EN_RULE_BASE_VAL_T RENAME TO KREW_RULE_T
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_ID TO RULE_ID
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_NM TO NM
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_IGNR_PRVS TO IGNR_PRVS
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_FRM_DT TO FRM_DT
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_TO_DT TO TO_DT
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_DACTVN_DT TO DACTVN_DT
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_CUR_IND TO CUR_IND
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_VER_NBR TO RULE_VER_NBR
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_DLGN_IND TO DLGN_IND
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_PREV_VER TO PREV_RULE_VER_NBR
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_ACTVN_DT TO ACTVN_DT
/
ALTER TABLE KREW_RULE_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_RULE_EXPR_T RENAME TO KREW_RULE_EXPR_T
/
ALTER TABLE KREW_RULE_EXPR_T RENAME COLUMN RULE_EXPR_TYP TO TYP
/
ALTER TABLE EN_RULE_EXT_T RENAME TO KREW_RULE_EXT_T
/
ALTER TABLE KREW_RULE_EXT_T RENAME COLUMN RULE_TMPL_ATTRIB_ID TO RULE_TMPL_ATTR_ID
/
ALTER TABLE KREW_RULE_EXT_T RENAME COLUMN RULE_BASE_VAL_ID TO RULE_ID
/
ALTER TABLE KREW_RULE_EXT_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_RULE_EXT_T1 
/
CREATE INDEX KREW_RULE_EXT_T1 ON KREW_RULE_EXT_T (RULE_ID)
/
ALTER TABLE EN_RULE_EXT_VAL_T RENAME TO KREW_RULE_EXT_VAL_T
/
ALTER TABLE KREW_RULE_EXT_VAL_T RENAME COLUMN RULE_EXT_VAL TO VAL
/
ALTER TABLE KREW_RULE_EXT_VAL_T RENAME COLUMN RULE_EXT_VAL_KEY TO KEY
/
ALTER TABLE KREW_RULE_EXT_VAL_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_RULE_EXT_VAL_T1 
/
CREATE INDEX KREW_RULE_EXT_VAL_T1 ON KREW_RULE_EXT_VAL_T (RULE_EXT_ID)
/
DROP INDEX EN_RULE_EXT_VAL_T2 
/
CREATE INDEX KREW_RULE_EXT_VAL_T2 ON KREW_RULE_EXT_VAL_T (RULE_EXT_VAL_ID,KEY)
/
ALTER TABLE EN_RULE_RSP_T RENAME TO KREW_RULE_RSP_T
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_BASE_VAL_ID TO RULE_ID
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_RSP_PRIO_NBR TO PRIO
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN ACTION_RQST_CD TO ACTN_RQST_CD
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_RSP_NM TO NM
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_RSP_TYP TO TYP
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_RSP_APPR_PLCY TO APPR_PLCY
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_RULE_RSP_TI1 
/
CREATE INDEX KREW_RULE_RSP_TI1 ON KREW_RULE_RSP_T (RULE_ID)
/
ALTER TABLE EN_RULE_TMPL_ATTRIB_T RENAME TO KREW_RULE_TMPL_ATTR_T
/
ALTER TABLE KREW_RULE_TMPL_ATTR_T RENAME COLUMN RULE_TMPL_ATTRIB_ID TO RULE_TMPL_ATTR_ID
/
ALTER TABLE KREW_RULE_TMPL_ATTR_T RENAME COLUMN RULE_ATTRIB_ID TO RULE_ATTR_ID
/
ALTER TABLE KREW_RULE_TMPL_ATTR_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_RULE_TMPL_ATTRIB_TI1 
/
CREATE INDEX KREW_RULE_TMPL_ATTR_TI1 ON KREW_RULE_TMPL_ATTR_T (RULE_TMPL_ID)
/
DROP INDEX EN_RULE_TMPL_ATTRIB_TI2 
/
CREATE INDEX KREW_RULE_TMPL_ATTR_TI2 ON KREW_RULE_TMPL_ATTR_T (RULE_ATTR_ID)
/
ALTER TABLE EN_RULE_TMPL_OPTN_T RENAME TO KREW_RULE_TMPL_OPTN_T
/
ALTER TABLE KREW_RULE_TMPL_OPTN_T RENAME COLUMN RULE_TMPL_OPTN_KEY TO KEY
/
ALTER TABLE KREW_RULE_TMPL_OPTN_T RENAME COLUMN RULE_TMPL_OPTN_VAL TO VAL
/
ALTER TABLE KREW_RULE_TMPL_OPTN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_RULE_TMPL_T RENAME TO KREW_RULE_TMPL_T
/
ALTER TABLE KREW_RULE_TMPL_T RENAME COLUMN RULE_TMPL_NM TO NM
/
ALTER TABLE KREW_RULE_TMPL_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_USR_OPTN_T RENAME TO KREW_USR_OPTN_T
/
ALTER TABLE KREW_USR_OPTN_T RENAME COLUMN PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_USR_OPTN_T RENAME COLUMN PRSN_OPTN_VAL TO VAL
/
ALTER TABLE KREW_USR_OPTN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_USR_OPTN_TI1 
/
CREATE INDEX KREW_USR_OPTN_TI1 ON KREW_USR_OPTN_T (PRNCPL_ID)
/
ALTER TABLE EN_BAM_PARAM_T RENAME TO KRSB_BAM_PARM_T
/
ALTER TABLE KRSB_BAM_PARM_T RENAME COLUMN PARAM TO PARM
/
DROP INDEX EN_BAM_PARAM_TI1 
/
CREATE INDEX KREW_BAM_PARM_TI1 ON KRSB_BAM_PARM_T (BAM_ID)
/
ALTER TABLE EN_BAM_T RENAME TO KRSB_BAM_T
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN SERVICE_NM TO SVC_NM
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN SERVICE_URL TO SVC_URL
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN METHOD_NM TO MTHD_NM
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN THREAD_NM TO THRD_NM
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN TARGET_TO_STRING TO TGT_TO_STR
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN SRVR_IND_IND TO SRVR_IND
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN EXCEPTION_TO_STRING TO EXCPN_TO_STR
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN EXCEPTION_MSG TO EXCPN_MSG
/
DROP INDEX EN_BAM_TI1 
/
CREATE INDEX KRSB_BAM_TI1 ON KRSB_BAM_T (SVC_NM,MTHD_NM)
/
DROP INDEX EN_BAM_TI2 
/
CREATE INDEX KRSB_BAM_TI2 ON KRSB_BAM_T (SVC_NM)
/
ALTER TABLE EN_MSG_PAYLOAD_T RENAME TO KRSB_MSG_PYLD_T
/
ALTER TABLE KRSB_MSG_PYLD_T RENAME COLUMN MESSAGE_QUE_ID TO MSG_QUE_ID
/
ALTER TABLE KRSB_MSG_PYLD_T RENAME COLUMN MESSAGE_PAYLOAD TO MSG_PYLD
/
ALTER TABLE EN_MSG_QUE_T RENAME TO KRSB_MSG_QUE_T
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_ID TO MSG_QUE_ID
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_DT TO DT
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_EXP_DT TO EXP_DT
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_PRIO_NBR TO PRIO
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_STAT_CD TO STAT_CD
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_RTRY_CNT TO RTRY_CNT
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_IP_NBR TO IP_NBR
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_SERVICE_NM TO SVC_NM
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_ENTITY_NM TO SVC_NMSPC
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN SERVICE_METHOD_NM TO SVC_MTHD_NM
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN VAL_ONE TO APP_VAL_ONE
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN VAL_TWO TO APP_VAL_TWO
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_MSG_QUE_TI1 
/
CREATE INDEX KRSB_MSG_QUE_TI1 ON KRSB_MSG_QUE_T (SVC_NM,SVC_MTHD_NM)
/
DROP INDEX EN_MSG_QUE_TI2 
/
CREATE INDEX KRSB_MSG_QUE_TI2 ON KRSB_MSG_QUE_T (SVC_NMSPC,STAT_CD,IP_NBR,DT)
/
ALTER TABLE EN_SERVICE_DEF_DUEX_T RENAME TO KRSB_SVC_DEF_T
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_DEF_ID TO SVC_DEF_ID
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_NM TO SVC_NM
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_URL TO SVC_URL
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVER_IP TO SRVR_IP
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN MESSAGE_ENTITY_NM TO SVC_NMSPC
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_ALIVE TO SVC_ALIVE
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_DEFINITION TO SVC_DEF
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_SERVICE_DEF_DUEX_TI1 
/
CREATE INDEX KRSB_SVC_DEF_TI1 ON KRSB_SVC_DEF_T (SRVR_IP,SVC_NMSPC)
/
ALTER TABLE FP_DOC_HEADER_T RENAME TO KRNS_DOC_HDR_T
/
ALTER TABLE KRNS_DOC_HDR_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
ALTER TABLE KRNS_DOC_HDR_T RENAME COLUMN ORG_DOC_NBR TO ORG_DOC_HDR_ID
/
ALTER TABLE KRNS_DOC_HDR_T RENAME COLUMN FDOC_TMPL_NBR TO TMPL_DOC_HDR_ID
/
ALTER TABLE KRNS_DOC_HDR_T RENAME COLUMN FDOC_EXPLAIN_TXT TO EXPLAIN
/
DROP INDEX FP_DOC_HEADER_TI3 
/
CREATE INDEX KRNS_DOC_HDR_TI3 ON KRNS_DOC_HDR_T (ORG_DOC_HDR_ID)
/
ALTER TABLE FP_DOC_HEADER_T disable CONSTRAINT FP_DOC_HEADER_TC0 
/
 ALTER TABLE KRNS_DOC_HDR_T ADD  CONSTRAINT KRNS_DOC_HDR_TI1 UNIQUE (OBJ_ID)
/
ALTER TABLE FP_DOC_TYPE_ATTR_T RENAME TO KRNS_DOC_TYP_ATTR_T
/
ALTER TABLE KRNS_DOC_TYP_ATTR_T RENAME COLUMN ID TO DOC_TYP_ATTR_ID
/
ALTER TABLE KRNS_DOC_TYP_ATTR_T RENAME COLUMN ACTIVE_IND TO ACTV_IND
/
ALTER TABLE KRNS_DOC_TYP_ATTR_T RENAME COLUMN DOC_TYP_ATTR_CD TO CD
/
ALTER TABLE KRNS_DOC_TYP_ATTR_T RENAME COLUMN DOC_TYP_ATTR_VAL TO VAL
/
ALTER TABLE KRNS_DOC_TYP_ATTR_T RENAME COLUMN DOC_TYP_ATTR_LBL TO LBL
/
ALTER TABLE KRNS_DOC_TYP_ATTR_T RENAME COLUMN FDOC_TYP_CD TO DOC_TYP_CD
/
ALTER TABLE FP_DOC_TYPE_T RENAME TO KRNS_DOC_TYP_T
/
ALTER TABLE KRNS_DOC_TYP_T RENAME COLUMN FDOC_TYP_CD TO DOC_TYP_CD
/
ALTER TABLE KRNS_DOC_TYP_T RENAME COLUMN FDOC_NM TO NM
/
ALTER TABLE KRNS_DOC_TYP_T RENAME COLUMN FDOC_TYP_ACTIVE_CD TO ACTV_IND
/
ALTER TABLE FP_MAINTENANCE_DOCUMENT_T RENAME TO KRNS_MAINT_DOC_T
/
ALTER TABLE KRNS_MAINT_DOC_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
ALTER TABLE KRNS_MAINT_DOC_T RENAME COLUMN DOCUMENT_CONTENTS TO DOC_CNTNT
/
ALTER TABLE FP_MAINT_DOC_ATTACHMENT_T RENAME TO KRNS_MAINT_DOC_ATT_T
/
ALTER TABLE KRNS_MAINT_DOC_ATT_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
ALTER TABLE KRNS_MAINT_DOC_ATT_T RENAME COLUMN ATTACHMENT TO ATT_CNTNT
/
ALTER TABLE KRNS_MAINT_DOC_ATT_T RENAME COLUMN FILE_NAME TO FILE_NM
/
ALTER TABLE KRNS_MAINT_DOC_ATT_T RENAME COLUMN CONTENT_TYPE TO CNTNT_TYP
/
ALTER TABLE FP_MAINT_LOCK_T RENAME TO KRNS_MAINT_LOCK_T
/
ALTER TABLE KRNS_MAINT_LOCK_T RENAME COLUMN LOCK_REPRESENTATION_TXT TO MAINT_LOCK_REP_TXT
/
ALTER TABLE KRNS_MAINT_LOCK_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
DROP INDEX FP_MAINT_LOCK_TI2 
/
CREATE INDEX KRNS_MAINT_LOCK_TI2 ON KRNS_MAINT_LOCK_T (DOC_HDR_ID)
/
ALTER TABLE FP_MAINT_LOCK_T disable CONSTRAINT FP_MAINT_LOCK_TC0 
/
 ALTER TABLE KRNS_MAINT_LOCK_T ADD  CONSTRAINT KRNS_MAINT_LOCK_TC1 UNIQUE (OBJ_ID)
/
ALTER TABLE FS_ADHOC_RTE_ACTN_RECP_T RENAME TO KRNS_ADHOC_RTE_ACTN_RECIP_T
/
ALTER TABLE KRNS_ADHOC_RTE_ACTN_RECIP_T RENAME COLUMN ACTN_RQST_RECP_TYP_CD TO RECIP_TYP_CD
/
ALTER TABLE KRNS_ADHOC_RTE_ACTN_RECIP_T RENAME COLUMN ACTN_RQST_RECP_ID TO ACTN_RQST_RECIP_ID
/
ALTER TABLE KRNS_ADHOC_RTE_ACTN_RECIP_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
DROP INDEX FS_ADHOC_RTE_ACTN_RECP_TI2 
/
CREATE INDEX KRNS_ADHOC_RTE_ACTN_RECIP_T2 ON KRNS_ADHOC_RTE_ACTN_RECIP_T (DOC_HDR_ID)
/
ALTER TABLE FS_ADHOC_RTE_ACTN_RECP_T disable CONSTRAINT FS_ADHOC_RTE_ACTN_RECP_TC0 
/
 ALTER TABLE KRNS_ADHOC_RTE_ACTN_RECIP_T ADD  CONSTRAINT KRNS_ADHOC_RTE_ACTN_RECIP_TC1 UNIQUE (OBJ_ID)
/
ALTER TABLE FS_LOOKUP_RESULTS_MT RENAME TO KRNS_LOOKUP_RSLT_T
/
ALTER TABLE KRNS_LOOKUP_RSLT_T RENAME COLUMN LOOKUP_RESULT_SEQUENCE_NBR TO LOOKUP_RSLT_ID
/
ALTER TABLE KRNS_LOOKUP_RSLT_T RENAME COLUMN PERSON_UNVL_ID TO PRNCPL_ID
/
ALTER TABLE KRNS_LOOKUP_RSLT_T RENAME COLUMN LOOKUP_DATE TO LOOKUP_DT
/
ALTER TABLE KRNS_LOOKUP_RSLT_T RENAME COLUMN SERIALIZED_LOOKUP_RESULTS TO SERIALZD_RSLTS
/
ALTER TABLE FS_LOOKUP_SELECTIONS_MT RENAME TO KRNS_LOOKUP_SEL_T
/
ALTER TABLE KRNS_LOOKUP_SEL_T RENAME COLUMN LOOKUP_RESULT_SEQUENCE_NBR TO LOOKUP_RSLT_ID
/
ALTER TABLE KRNS_LOOKUP_SEL_T RENAME COLUMN PERSON_UNVL_ID TO PRNCPL_ID
/
ALTER TABLE KRNS_LOOKUP_SEL_T RENAME COLUMN LOOKUP_DATE TO LOOKUP_DT
/
ALTER TABLE KRNS_LOOKUP_SEL_T RENAME COLUMN SELECTED_OBJ_IDS TO SEL_OBJ_IDS
/
ALTER TABLE KNS_PESSIMISTIC_LOCK_T RENAME TO KRNS_PESSIMISTIC_LOCK_T
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T RENAME COLUMN LOCK_ID TO PESSIMISTIC_LOCK_ID
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T RENAME COLUMN LOCK_DESCRIPTOR TO LOCK_DESC
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T RENAME COLUMN LOCK_GENERATED_TS TO GNRT_DT
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T RENAME COLUMN PERSON_UNVL_ID TO PRNCPL_ID
/
DROP INDEX KNS_PESSIMISTIC_LOCK_TI1 
/
CREATE INDEX KRNS_PESSIMISTIC_LOCK_TI1 ON KRNS_PESSIMISTIC_LOCK_T (DOC_HDR_ID)
/
ALTER TABLE KNS_PESSIMISTIC_LOCK_T disable CONSTRAINT KNS_PESSIMISTIC_LOCK_TC0 
/
 ALTER TABLE KRNS_PESSIMISTIC_LOCK_T ADD  CONSTRAINT KRNS_PESSIMISTIC_LOCK_TC0 UNIQUE (OBJ_ID)
/
DROP INDEX KNS_PESSIMISTIC_LOCK_TI2 
/
CREATE INDEX KRNS_PESSIMISTIC_LOCK_TI2 ON KRNS_PESSIMISTIC_LOCK_T (PRNCPL_ID)
/
ALTER TABLE KNS_PESSIMISTIC_LOCK_T disable CONSTRAINT KNS_PESSIMISTIC_LOCK_TC0 
/
 ALTER TABLE KRNS_PESSIMISTIC_LOCK_T ADD  CONSTRAINT KRNS_PESSIMISTIC_LOCK_TC0 UNIQUE (OBJ_ID)
/
ALTER TABLE KR_KNS_SESN_DOC_T RENAME TO KRNS_SESN_DOC_T
/
ALTER TABLE KRNS_SESN_DOC_T RENAME COLUMN SESSION_ID TO SESN_DOC_ID
/
ALTER TABLE KRNS_SESN_DOC_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
ALTER TABLE KRNS_SESN_DOC_T RENAME COLUMN SERIALIZED_DOC_FRM TO SERIALZD_DOC_FRM
/
ALTER TABLE KRNS_SESN_DOC_T RENAME COLUMN LST_UPDATE_DT TO LAST_UPDT_DT
/
DROP INDEX KR_KNS_SESN_DOC_TI1 
/
CREATE INDEX KRNS_SESN_DOC_TI1 ON KRNS_SESN_DOC_T (LAST_UPDT_DT)
/
ALTER TABLE SH_ATT_T RENAME TO KRNS_ATT_T
/
ALTER TABLE KRNS_ATT_T RENAME COLUMN ATT_MIME_TYP_CD TO MIME_TYP
/
ALTER TABLE KRNS_ATT_T RENAME COLUMN ATT_FL_NM TO FILE_NM
/
ALTER TABLE KRNS_ATT_T RENAME COLUMN ATT_FL_SZ TO FILE_SZ
/
ALTER TABLE SH_NTE_T RENAME TO KRNS_NTE_T
/
ALTER TABLE KRNS_NTE_T RENAME COLUMN NTE_AUTH_ID TO AUTH_PRNCPL_ID
/
ALTER TABLE KRNS_NTE_T RENAME COLUMN NTE_POST_TS TO POST_TS
/
ALTER TABLE KRNS_NTE_T RENAME COLUMN NTE_TYP_CD TO NTE_TYP_CD
/
ALTER TABLE KRNS_NTE_T RENAME COLUMN NTE_TXT TO TXT
/
ALTER TABLE KRNS_NTE_T RENAME COLUMN NTE_PRG_CD TO PRG_CD
/
ALTER TABLE KRNS_NTE_T RENAME COLUMN NTE_TPC_TXT TO TPC_TXT
/
ALTER TABLE SH_NTE_TYP_T RENAME TO KRNS_NTE_TYP_T
/
ALTER TABLE KRNS_NTE_TYP_T RENAME COLUMN NTE_TYP_DESC TO TYP_DESC
/
ALTER TABLE KRNS_NTE_TYP_T RENAME COLUMN NTE_TYP_ACTV_IND TO ACTV_IND
/
ALTER TABLE SH_PARM_DTL_TYP_T RENAME TO KRNS_PARM_DTL_TYP_T
/
ALTER TABLE KRNS_PARM_DTL_TYP_T RENAME COLUMN SH_PARM_NMSPC_CD TO PARM_NMSPC_CD
/
ALTER TABLE KRNS_PARM_DTL_TYP_T RENAME COLUMN SH_PARM_DTL_TYP_CD TO PARM_DTL_TYP_CD
/
ALTER TABLE KRNS_PARM_DTL_TYP_T RENAME COLUMN SH_PARM_DTL_TYP_NM TO NM
/
ALTER TABLE KRNS_PARM_DTL_TYP_T RENAME COLUMN ACTIVE_IND TO ACTV_IND
/
ALTER TABLE SH_PARM_NMSPC_T RENAME TO KRNS_PARM_NMSPC_T
/
ALTER TABLE KRNS_PARM_NMSPC_T RENAME COLUMN SH_PARM_NMSPC_CD TO PARM_NMSPC_CD
/
ALTER TABLE KRNS_PARM_NMSPC_T RENAME COLUMN SH_PARM_NMSPC_NM TO NM
/
ALTER TABLE KRNS_PARM_NMSPC_T RENAME COLUMN ACTIVE_IND TO ACTV_IND
/
ALTER TABLE SH_PARM_T RENAME TO KRNS_PARM_T
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_NMSPC_CD TO PARM_NMSPC_CD
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_DTL_TYP_CD TO PARM_DTL_TYP_CD
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_NM TO PARM_NM
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_TYP_CD TO PARM_TYP_CD
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_TXT TO TXT
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_DESC TO PARM_DESC
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_CONS_CD TO CONS_CD
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN WRKGRP_NM TO GRP_NM
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN ACTIVE_IND TO ACTV_IND
/
ALTER TABLE SH_PARM_TYP_T RENAME TO KRNS_PARM_TYP_T
/
ALTER TABLE KRNS_PARM_TYP_T RENAME COLUMN SH_PARM_TYP_CD TO PARM_TYP_CD
/
ALTER TABLE KRNS_PARM_TYP_T RENAME COLUMN SH_PARM_TYP_NM TO NM
/
ALTER TABLE KRNS_PARM_TYP_T RENAME COLUMN ACTIVE_IND TO ACTV_IND
/
ALTER TABLE SH_USR_PROP_T RENAME TO KRNS_USR_PROP_T
/
ALTER TABLE KRNS_USR_PROP_T RENAME COLUMN PERSON_UNVL_ID TO PRNCPL_ID
/
ALTER TABLE KRNS_USR_PROP_T RENAME COLUMN APPL_MOD_ID TO APP_MOD_ID
/
ALTER TABLE KRNS_USR_PROP_T RENAME COLUMN USR_PROP_VAL TO VAL
/
ALTER TABLE KIM_AUTHN_SESN_PRINCIPAL_T RENAME TO KRIM_AUTHN_SESN_PRNCPL_T
/
ALTER TABLE KRIM_AUTHN_SESN_PRNCPL_T RENAME COLUMN SESN_ID TO AUTHN_SESN_PRNCPL_ID
/
ALTER TABLE KRIM_AUTHN_SESN_PRNCPL_T RENAME COLUMN PRINCIPAL_NAME TO PRNCPL_NM
/
DROP INDEX KIM_AUTHN_SESN_PRINCIPAL_TI2 
/
CREATE INDEX KRIM_AUTHN_SESN_PRNCPL_TI2 ON KRIM_AUTHN_SESN_PRNCPL_T (PRNCPL_NM)
/
ALTER TABLE KIM_AUTHN_SESN_T RENAME TO KRIM_AUTHN_SESN_T
/
ALTER TABLE KRIM_AUTHN_SESN_T RENAME COLUMN ID TO AUTHN_SESN_ID
/
ALTER TABLE KRIM_AUTHN_SESN_T RENAME COLUMN INSERT_DATETIME TO CRTE_DTTM
/
ALTER TABLE KRIM_AUTHN_SESN_T RENAME COLUMN LAST_ACCESS_DATETIME TO LAST_ACC_DTTM
/
ALTER TABLE KRIM_AUTHN_SESN_T RENAME COLUMN MAX_IDLE_TIME TO MAX_IDLE_TM
/
DROP INDEX KIM_AUTHN_SESN_TI1 
/
CREATE INDEX KRIM_AUTHN_SESN_TI1 ON KRIM_AUTHN_SESN_T (LAST_ACC_DTTM)
/
DROP INDEX KIM_AUTHN_SESN_TI2 
/
CREATE INDEX KRIM_AUTHN_SESN_TI2 ON KRIM_AUTHN_SESN_T (CRTE_DTTM)
/
ALTER TABLE KR_QRTZ_BLOB_TRIGGERS RENAME TO KRSB_QRTZ_BLOB_TRIGGERS
/
ALTER TABLE KR_QRTZ_CALENDARS RENAME TO KRSB_QRTZ_CALENDARS
/
ALTER TABLE KR_QRTZ_CRON_TRIGGERS RENAME TO KRSB_QRTZ_CRON_TRIGGERS
/
ALTER TABLE KR_QRTZ_FIRED_TRIGGERS RENAME TO KRSB_QRTZ_FIRED_TRIGGERS
/
DROP INDEX IDX_KR_QRTZ_FT_JOB_GROUP 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI1 ON KRSB_QRTZ_FIRED_TRIGGERS (JOB_GROUP)
/
DROP INDEX IDX_KR_QRTZ_FT_JOB_NAME 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI2 ON KRSB_QRTZ_FIRED_TRIGGERS (JOB_NAME)
/
DROP INDEX IDX_KR_QRTZ_FT_REQ_RECOV 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI3 ON KRSB_QRTZ_FIRED_TRIGGERS (REQUESTS_RECOVERY)
/
DROP INDEX IDX_KR_QRTZ_FT_JOB_STATEFUL 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI4 ON KRSB_QRTZ_FIRED_TRIGGERS (IS_STATEFUL)
/
DROP INDEX IDX_KR_QRTZ_FT_TRIG_GROUP 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI5 ON KRSB_QRTZ_FIRED_TRIGGERS (TRIGGER_GROUP)
/
DROP INDEX IDX_KR_QRTZ_FT_TRIG_INST_NAME 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI6 ON KRSB_QRTZ_FIRED_TRIGGERS (INSTANCE_NAME)
/
DROP INDEX IDX_KR_QRTZ_FT_TRIG_NAME 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI7 ON KRSB_QRTZ_FIRED_TRIGGERS (TRIGGER_NAME)
/
DROP INDEX IDX_KR_QRTZ_FT_TRIG_NM_GP 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI8 ON KRSB_QRTZ_FIRED_TRIGGERS (TRIGGER_NAME,TRIGGER_GROUP)
/
DROP INDEX IDX_KR_QRTZ_FT_TRIG_VOLATILE 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI9 ON KRSB_QRTZ_FIRED_TRIGGERS (IS_VOLATILE)
/
ALTER TABLE KR_QRTZ_JOB_DETAILS RENAME TO KRSB_QRTZ_JOB_DETAILS
/
DROP INDEX IDX_KR_QRTZ_J_REQ_RECOVERY 
/
CREATE INDEX KRSB_QRTZ_JOB_DETAILS_TI1 ON KRSB_QRTZ_JOB_DETAILS (REQUESTS_RECOVERY)
/
ALTER TABLE KR_QRTZ_JOB_LISTENERS RENAME TO KRSB_QRTZ_JOB_LISTENERS
/
ALTER TABLE KR_QRTZ_LOCKS RENAME TO KRSB_QRTZ_LOCKS
/
ALTER TABLE KR_QRTZ_PAUSED_TRIGGER_GRPS RENAME TO KRSB_QRTZ_PAUSED_TRIGGER_GRPS
/
ALTER TABLE KR_QRTZ_SCHEDULER_STATE RENAME TO KRSB_QRTZ_SCHEDULER_STATE
/
ALTER TABLE KR_QRTZ_SIMPLE_TRIGGERS RENAME TO KRSB_QRTZ_SIMPLE_TRIGGERS
/
ALTER TABLE KR_QRTZ_TRIGGERS RENAME TO KRSB_QRTZ_TRIGGERS
/
DROP INDEX IDX_KR_QRTZ_T_NEXT_FIRE_TIME 
/
CREATE INDEX KRSB_QRTZ_TRIGGERS_TI1 ON KRSB_QRTZ_TRIGGERS (NEXT_FIRE_TIME)
/
ALTER TABLE KRSB_QRTZ_TRIGGERS DROP CONSTRAINT KR_QRTZ_TRIGGERS_TR1 
/
ALTER TABLE KRSB_QRTZ_TRIGGERS ADD CONSTRAINT KRSB_QRTZ_TRIGGERS_TR1 FOREIGN KEY  (JOB_NAME,JOB_GROUP) REFERENCES KRSB_QRTZ_JOB_DETAILS (JOB_NAME,JOB_GROUP) 
/
DROP INDEX IDX_KR_QRTZ_T_NFT_ST 
/
CREATE INDEX KRSB_QRTZ_TRIGGERS_TI2 ON KRSB_QRTZ_TRIGGERS (NEXT_FIRE_TIME,TRIGGER_STATE)
/
ALTER TABLE KRSB_QRTZ_TRIGGERS DROP CONSTRAINT KR_QRTZ_TRIGGERS_TR1 
/
ALTER TABLE KRSB_QRTZ_TRIGGERS ADD CONSTRAINT KRSB_QRTZ_TRIGGERS_TR1 FOREIGN KEY  (JOB_NAME,JOB_GROUP) REFERENCES KRSB_QRTZ_JOB_DETAILS (JOB_NAME,JOB_GROUP) 
/
DROP INDEX IDX_KR_QRTZ_T_STATE 
/
CREATE INDEX KRSB_QRTZ_TRIGGERS_TI3 ON KRSB_QRTZ_TRIGGERS (TRIGGER_STATE)
/
ALTER TABLE KRSB_QRTZ_TRIGGERS DROP CONSTRAINT KR_QRTZ_TRIGGERS_TR1 
/
ALTER TABLE KRSB_QRTZ_TRIGGERS ADD CONSTRAINT KRSB_QRTZ_TRIGGERS_TR1 FOREIGN KEY  (JOB_NAME,JOB_GROUP) REFERENCES KRSB_QRTZ_JOB_DETAILS (JOB_NAME,JOB_GROUP) 
/
DROP INDEX IDX_KR_QRTZ_T_VOLATILE 
/
CREATE INDEX KRSB_QRTZ_TRIGGERS_TI4 ON KRSB_QRTZ_TRIGGERS (IS_VOLATILE)
/
ALTER TABLE KRSB_QRTZ_TRIGGERS DROP CONSTRAINT KR_QRTZ_TRIGGERS_TR1 
/
ALTER TABLE KRSB_QRTZ_TRIGGERS ADD CONSTRAINT KRSB_QRTZ_TRIGGERS_TR1 FOREIGN KEY  (JOB_NAME,JOB_GROUP) REFERENCES KRSB_QRTZ_JOB_DETAILS (JOB_NAME,JOB_GROUP) 
/
ALTER TABLE KR_QRTZ_TRIGGERS_LISTENERS RENAME TO KRSB_QRTZ_TRIGGERS_LISTENERS
/
ALTER TABLE KCB_MESSAGES RENAME TO KREN_MSG_T
/
ALTER TABLE KREN_MSG_T RENAME COLUMN ID TO MSG_ID
/
ALTER TABLE KREN_MSG_T RENAME COLUMN ORIGIN_ID TO ORGN_ID
/
ALTER TABLE KREN_MSG_T RENAME COLUMN DELIVERY_TYPE TO DELIV_TYP
/
ALTER TABLE KREN_MSG_T RENAME COLUMN CREATED_DATETIME TO CRTE_DTTM
/
ALTER TABLE KREN_MSG_T RENAME COLUMN TITLE TO TTL
/
ALTER TABLE KREN_MSG_T RENAME COLUMN CHANNEL TO CHNL
/
ALTER TABLE KREN_MSG_T RENAME COLUMN PRODUCER TO PRODCR
/
ALTER TABLE KREN_MSG_T RENAME COLUMN CONTENT TO CNTNT
/
ALTER TABLE KREN_MSG_T RENAME COLUMN CONTENT_TYPE TO CNTNT_TYP
/
ALTER TABLE KREN_MSG_T RENAME COLUMN USER_RECIPIENT_ID TO RECIP_ID
/
ALTER TABLE KREN_MSG_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KCB_MSG_DELIVS RENAME TO KREN_MSG_DELIV_T
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN ID TO MSG_DELIV_ID
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN MESSAGE_ID TO MSG_ID
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN DELIVERER_TYPE_NAME TO TYP_NM
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN DELIVERER_SYSTEM_ID TO SYS_ID
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN DELIVERY_STATUS TO STAT_CD
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN PROCESS_COUNT TO PROC_CNT
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN LOCKED_DATE TO LOCKD_DTTM
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX KCB_MSG_DELIVSI1 
/
CREATE INDEX KREN_MSG_DELIV_TI1 ON KREN_MSG_DELIV_T (MSG_ID)
/
ALTER TABLE KCB_MSG_DELIVS disable CONSTRAINT KCB_MSG_DELIVS_UK1 
/
 ALTER TABLE KREN_MSG_DELIV_T ADD  CONSTRAINT KREN_MSG_DELIV_UK1 UNIQUE (MSG_ID,TYP_NM)
/
ALTER TABLE KREN_MSG_DELIV_T DROP CONSTRAINT KCB_MSG_DELIVS_FK1 
/
ALTER TABLE KREN_MSG_DELIV_T ADD CONSTRAINT KREN_MSG_DELIV_FK1 FOREIGN KEY  (MSG_ID) REFERENCES KREN_MSG_T (ID) 
/
ALTER TABLE KCB_RECIP_DELIVS RENAME TO KREN_RECIP_DELIV_T
/
ALTER TABLE KREN_RECIP_DELIV_T RENAME COLUMN ID TO RECIP_DELIV_ID
/
ALTER TABLE KREN_RECIP_DELIV_T RENAME COLUMN RECIPIENT_ID TO RECIP_ID
/
ALTER TABLE KREN_RECIP_DELIV_T RENAME COLUMN CHANNEL TO CHNL
/
ALTER TABLE KREN_RECIP_DELIV_T RENAME COLUMN DELIVERER_NAME TO NM
/
ALTER TABLE KREN_RECIP_DELIV_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KCB_RECIP_PREFS RENAME TO KREN_RECIP_PREFS_T
/
ALTER TABLE KREN_RECIP_PREFS_T RENAME COLUMN ID TO RECIP_PREFS_ID
/
ALTER TABLE KREN_RECIP_PREFS_T RENAME COLUMN RECIPIENT_ID TO RECIP_ID
/
ALTER TABLE KREN_RECIP_PREFS_T RENAME COLUMN PROPERTY TO PROP
/
ALTER TABLE KREN_RECIP_PREFS_T RENAME COLUMN VALUE TO VAL
/
ALTER TABLE KREN_RECIP_PREFS_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE NOTIFICATION_PRODUCERS RENAME TO KREN_PRODCR_T
/
ALTER TABLE KREN_PRODCR_T RENAME COLUMN ID TO PRODCR_ID
/
ALTER TABLE KREN_PRODCR_T RENAME COLUMN NAME TO NM
/
ALTER TABLE KREN_PRODCR_T RENAME COLUMN DESCRIPTION TO DESC
/
ALTER TABLE KREN_PRODCR_T RENAME COLUMN CONTACT_INFO TO CNTCT_INFO
/
ALTER TABLE NOTIFICATION_CHANNELS RENAME TO KREN_CHNL_T
/
ALTER TABLE KREN_CHNL_T RENAME COLUMN ID TO CHNL_ID
/
ALTER TABLE KREN_CHNL_T RENAME COLUMN NAME TO NM
/
ALTER TABLE KREN_CHNL_T RENAME COLUMN DESCRIPTION TO DESC
/
ALTER TABLE KREN_CHNL_T RENAME COLUMN SUBSCRIBABLE TO SUBSCRB_IND
/
ALTER TABLE NOTIFICATION_PRIORITIES RENAME TO KREN_PRIO_T
/
ALTER TABLE KREN_PRIO_T RENAME COLUMN ID TO PRIO_ID
/
ALTER TABLE KREN_PRIO_T RENAME COLUMN NAME TO NM
/
ALTER TABLE KREN_PRIO_T RENAME COLUMN DESCRIPTION TO DESC
/
ALTER TABLE KREN_PRIO_T RENAME COLUMN PRIORITY_ORDER TO PRIO_ORD
/
ALTER TABLE NOTIFICATION_CONTENT_TYPES RENAME TO KREN_CNTNT_TYP_T
/
ALTER TABLE KREN_CNTNT_TYP_T RENAME COLUMN ID TO CNTNT_TYP_ID
/
ALTER TABLE KREN_CNTNT_TYP_T RENAME COLUMN NAME TO NM
/
ALTER TABLE KREN_CNTNT_TYP_T RENAME COLUMN VERSION TO CNTNT_TYP_VER_NBR
/
ALTER TABLE KREN_CNTNT_TYP_T RENAME COLUMN DESCRIPTION TO DESC
/
ALTER TABLE KREN_CNTNT_TYP_T RENAME COLUMN NAMESPACE TO NMSPC
/
ALTER TABLE NOTIFICATIONS RENAME TO KREN_NTFCTN_T
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN ID TO NTFCTN_ID
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN DELIVERY_TYPE TO DELIV_TYP
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN CREATED_DATETIME TO CRTE_DTTM
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN SEND_DATETIME TO SND_DTTM
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN AUTO_REMOVE_DATETIME TO AUTO_RMV_DTTM
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN PRIORITY_ID TO PRIO_ID
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN TITLE TO TTL
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN CONTENT TO CNTNT
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN CONTENT_TYPE_ID TO CNTNT_TYP_ID
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN NOTIFICATION_CHANNEL_ID TO CHNL_ID
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN PRODUCER_ID TO PRODCR_ID
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN LOCKED_DATE TO LOCKD_DTTM
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX KEN_NOTIFICATIONSI1 
/
CREATE INDEX KREN_NTFCTN_I1 ON KREN_NTFCTN_T (CNTNT_TYP_ID)
/
ALTER TABLE KREN_NTFCTN_T DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK4 
/
ALTER TABLE KREN_NTFCTN_T ADD CONSTRAINT KREN_NTFCTN_FK4 FOREIGN KEY  (PRODCR_ID) REFERENCES KREN_PRODCR_T (ID) 
/
ALTER TABLE KREN_NTFCTN_T DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK2 
/
ALTER TABLE KREN_NTFCTN_T ADD CONSTRAINT KREN_NTFCTN_FK2 FOREIGN KEY  (CNTNT_TYP_ID) REFERENCES KREN_CNTNT_TYP_T (ID) 
/
ALTER TABLE KREN_NTFCTN_T DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK1 
/
ALTER TABLE KREN_NTFCTN_T ADD CONSTRAINT KREN_NTFCTN_FK1 FOREIGN KEY  (CHNL_ID) REFERENCES KREN_CHNL_T (ID) 
/
ALTER TABLE KREN_NTFCTN_T DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK3 
/
ALTER TABLE KREN_NTFCTN_T ADD CONSTRAINT KREN_NTFCTN_FK3 FOREIGN KEY  (PRIO_ID) REFERENCES KREN_PRIO_T (ID) 
/
DROP INDEX KEN_NOTIFICATIONSI2 
/
CREATE INDEX KREN_NTFCTN_I2 ON KREN_NTFCTN_T (PRIO_ID)
/
ALTER TABLE KREN_NTFCTN_T DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK4 
/
ALTER TABLE KREN_NTFCTN_T ADD CONSTRAINT KREN_NTFCTN_FK4 FOREIGN KEY  (PRODCR_ID) REFERENCES KREN_PRODCR_T (ID) 
/
ALTER TABLE KREN_NTFCTN_T DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK2 
/
ALTER TABLE KREN_NTFCTN_T ADD CONSTRAINT KREN_NTFCTN_FK2 FOREIGN KEY  (CNTNT_TYP_ID) REFERENCES KREN_CNTNT_TYP_T (ID) 
/
ALTER TABLE KREN_NTFCTN_T DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK1 
/
ALTER TABLE KREN_NTFCTN_T ADD CONSTRAINT KREN_NTFCTN_FK1 FOREIGN KEY  (CHNL_ID) REFERENCES KREN_CHNL_T (ID) 
/
ALTER TABLE KREN_NTFCTN_T DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK3 
/
ALTER TABLE KREN_NTFCTN_T ADD CONSTRAINT KREN_NTFCTN_FK3 FOREIGN KEY  (PRIO_ID) REFERENCES KREN_PRIO_T (ID) 
/
DROP INDEX KEN_NOTIFICATIONSI3 
/
CREATE INDEX KREN_NTFCTN_I3 ON KREN_NTFCTN_T (PRODCR_ID)
/
ALTER TABLE KREN_NTFCTN_T DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK4 
/
ALTER TABLE KREN_NTFCTN_T ADD CONSTRAINT KREN_NTFCTN_FK4 FOREIGN KEY  (PRODCR_ID) REFERENCES KREN_PRODCR_T (ID) 
/
ALTER TABLE KREN_NTFCTN_T DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK2 
/
ALTER TABLE KREN_NTFCTN_T ADD CONSTRAINT KREN_NTFCTN_FK2 FOREIGN KEY  (CNTNT_TYP_ID) REFERENCES KREN_CNTNT_TYP_T (ID) 
/
ALTER TABLE KREN_NTFCTN_T DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK1 
/
ALTER TABLE KREN_NTFCTN_T ADD CONSTRAINT KREN_NTFCTN_FK1 FOREIGN KEY  (CHNL_ID) REFERENCES KREN_CHNL_T (ID) 
/
ALTER TABLE KREN_NTFCTN_T DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK3 
/
ALTER TABLE KREN_NTFCTN_T ADD CONSTRAINT KREN_NTFCTN_FK3 FOREIGN KEY  (PRIO_ID) REFERENCES KREN_PRIO_T (ID) 
/
ALTER TABLE NOTIFICATION_CHANNEL_PRODUCERS RENAME TO KREN_CHNL_PRODCR_T
/
ALTER TABLE KREN_CHNL_PRODCR_T RENAME COLUMN CHANNEL_ID TO CHNL_ID
/
ALTER TABLE KREN_CHNL_PRODCR_T RENAME COLUMN PRODUCER_ID TO PRODCR_ID
/
DROP INDEX KEN_CHANNEL_PRODUCERSI1 
/
CREATE INDEX KREN_CHNL_PRODCR_TI1 ON KREN_CHNL_PRODCR_T (CHNL_ID)
/
ALTER TABLE KREN_CHNL_PRODCR_T DROP CONSTRAINT NOTIFICATION_CHANNEL_PROD_FK1 
/
ALTER TABLE KREN_CHNL_PRODCR_T ADD CONSTRAINT KREN_CHNL_PRODCR_FK1 FOREIGN KEY  (CHNL_ID) REFERENCES KREN_CHNL_T (ID) 
/
ALTER TABLE KREN_CHNL_PRODCR_T DROP CONSTRAINT NOTIFICATION_CHANNEL_PROD_FK2 
/
ALTER TABLE KREN_CHNL_PRODCR_T ADD CONSTRAINT KREN_CHNL_PRODCR_FK2 FOREIGN KEY  (PRODCR_ID) REFERENCES KREN_PRODCR_T (ID) 
/
DROP INDEX KEN_CHANNEL_PRODUCERSI2 
/
CREATE INDEX KREN_CHNL_PRODCR_TI2 ON KREN_CHNL_PRODCR_T (PRODCR_ID)
/
ALTER TABLE KREN_CHNL_PRODCR_T DROP CONSTRAINT NOTIFICATION_CHANNEL_PROD_FK1 
/
ALTER TABLE KREN_CHNL_PRODCR_T ADD CONSTRAINT KREN_CHNL_PRODCR_FK1 FOREIGN KEY  (CHNL_ID) REFERENCES KREN_CHNL_T (ID) 
/
ALTER TABLE KREN_CHNL_PRODCR_T DROP CONSTRAINT NOTIFICATION_CHANNEL_PROD_FK2 
/
ALTER TABLE KREN_CHNL_PRODCR_T ADD CONSTRAINT KREN_CHNL_PRODCR_FK2 FOREIGN KEY  (PRODCR_ID) REFERENCES KREN_PRODCR_T (ID) 
/
ALTER TABLE NOTIFICATION_MSG_DELIVS RENAME TO KREN_NTFCTN_MSG_DELIV_T
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN ID TO NTFCTN_MSG_DELIV_ID
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN NOTIFICATION_ID TO NTFCTN_ID
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN USER_RECIPIENT_ID TO RECIP_ID
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN MESSAGE_DELIVERY_STATUS TO STAT_CD
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN DELIVERY_SYSTEM_ID TO SYS_ID
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN LOCKED_DATE TO LOCKD_DTTM
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX KEN_MSG_DELIVSI1 
/
CREATE INDEX KREN_MSG_DELIVSI1 ON KREN_NTFCTN_MSG_DELIV_T (NTFCTN_ID)
/
ALTER TABLE NOTIFICATION_MSG_DELIVS disable CONSTRAINT NOTIF_MSG_DELIVS_UK1 
/
 ALTER TABLE KREN_NTFCTN_MSG_DELIV_T ADD  CONSTRAINT KREN_NTFCTN_MSG_DELIVS_UK1 UNIQUE (NTFCTN_ID,USER_RECIPIENT_ID,RECIP_ID)
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T DROP CONSTRAINT NOTIF_MSG_DELIVS_FK1 
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T ADD CONSTRAINT KREN_NTFCTN_MSG_DELIV_FK1 FOREIGN KEY  (NTFCTN_ID) REFERENCES KREN_NTFCTN_T (ID) 
/
ALTER TABLE NOTIFICATION_RECIPIENTS RENAME TO KREN_RECIP_T
/
ALTER TABLE KREN_RECIP_T RENAME COLUMN ID TO RECIP_ID
/
ALTER TABLE KREN_RECIP_T RENAME COLUMN NOTIFICATION_ID TO NTFCTN_ID
/
ALTER TABLE KREN_RECIP_T RENAME COLUMN RECIPIENT_TYPE TO RECIP_TYP_CD
/
ALTER TABLE KREN_RECIP_T RENAME COLUMN RECIPIENT_ID TO RECIP_ID
/
DROP INDEX KEN_RECIPIENTSI1 
/
CREATE INDEX KREN_RECIP_TI1 ON KREN_RECIP_T (NTFCTN_ID)
/
ALTER TABLE NOTIFICATION_RECIPIENTS disable CONSTRAINT NOTIFICATION_RECIPIENTS_UK1 
/
 ALTER TABLE KREN_RECIP_T ADD  CONSTRAINT KREN_RECIP_UK1 UNIQUE (NTFCTN_ID,RECIP_TYP_CD,RECIP_ID)
/
ALTER TABLE KREN_RECIP_T DROP CONSTRAINT NOTIFICATION_RECIPIENTS_N_FK1 
/
ALTER TABLE KREN_RECIP_T ADD CONSTRAINT KREN_RECIP_FK1 FOREIGN KEY  (NTFCTN_ID) REFERENCES KREN_NTFCTN_T (ID) 
/
ALTER TABLE NOTIFICATION_RECIPIENTS_LISTS RENAME TO KREN_RECIP_LIST_T
/
ALTER TABLE KREN_RECIP_LIST_T RENAME COLUMN ID TO RECIP_LIST_ID
/
ALTER TABLE KREN_RECIP_LIST_T RENAME COLUMN CHANNEL_ID TO CHNL_ID
/
ALTER TABLE KREN_RECIP_LIST_T RENAME COLUMN RECIPIENT_TYPE TO RECIP_TYP_CD
/
ALTER TABLE KREN_RECIP_LIST_T RENAME COLUMN RECIPIENT_ID TO RECIP_ID
/
DROP INDEX KEN_RECIPIENTS_LISTSI1 
/
CREATE INDEX KREN_RECIP_LIST_TI1 ON KREN_RECIP_LIST_T (CHNL_ID)
/
ALTER TABLE NOTIFICATION_RECIPIENTS_LISTS disable CONSTRAINT NOTIFICATION_RECIPIENTS_L_UK1 
/
 ALTER TABLE KREN_RECIP_LIST_T ADD  CONSTRAINT KREN_RECIP_LIST_UK1 UNIQUE (CHNL_ID,RECIP_TYP_CD,RECIP_ID)
/
ALTER TABLE KREN_RECIP_LIST_T DROP CONSTRAINT NOTIFICATION_RECIPIENTS_L_FK1 
/
ALTER TABLE KREN_RECIP_LIST_T ADD CONSTRAINT KREN_RECIP_LIST_FK1 FOREIGN KEY  (CHNL_ID) REFERENCES KREN_CHNL_T (ID) 
/
ALTER TABLE NOTIFICATION_REVIEWERS RENAME TO KREN_RVWER_T
/
ALTER TABLE KREN_RVWER_T RENAME COLUMN ID TO RVWER_ID
/
ALTER TABLE KREN_RVWER_T RENAME COLUMN CHANNEL_ID TO CHNL_ID
/
ALTER TABLE KREN_RVWER_T RENAME COLUMN REVIEWER_TYPE TO TYP
/
ALTER TABLE KREN_RVWER_T RENAME COLUMN REVIEWER_ID TO RVWER_ID
/
DROP INDEX KEN_REVIEWERSI1 
/
CREATE INDEX KREN_RVWER_TI1 ON KREN_RVWER_T (CHNL_ID)
/
ALTER TABLE NOTIFICATION_REVIEWERS disable CONSTRAINT NOTIFICATION_REVIEWERS_UK1 
/
 ALTER TABLE KREN_RVWER_T ADD  CONSTRAINT KREN_RVWER_UK1 UNIQUE (CHNL_ID,TYP,RVWER_ID)
/
ALTER TABLE KREN_RVWER_T DROP CONSTRAINT   
/
ALTER TABLE KREN_RVWER_T ADD CONSTRAINT KREN_RVWER_FK1 FOREIGN KEY  (CHNL_ID) REFERENCES KREN_CHNL_T (ID) 
/
ALTER TABLE NOTIFICATION_SENDERS RENAME TO KREN_SNDR_T
/
ALTER TABLE KREN_SNDR_T RENAME COLUMN ID TO SNDR_ID
/
ALTER TABLE KREN_SNDR_T RENAME COLUMN NOTIFICATION_ID TO NTFCTN_ID
/
ALTER TABLE KREN_SNDR_T RENAME COLUMN NAME TO NM
/
DROP INDEX KEN_SENDERSI1 
/
CREATE INDEX KREN_SNDR_TI1 ON KREN_SNDR_T (NTFCTN_ID)
/
ALTER TABLE NOTIFICATION_SENDERS disable CONSTRAINT NOTIFICATION_SENDERS_UK1 
/
 ALTER TABLE KREN_SNDR_T ADD  CONSTRAINT KREN_SNDR_UK1 UNIQUE (NTFCTN_ID,NM)
/
ALTER TABLE KREN_SNDR_T DROP CONSTRAINT NOTIFICATION_SENDERS_NOTI_FK1 
/
ALTER TABLE KREN_SNDR_T ADD CONSTRAINT KREN_SNDR_FK1 FOREIGN KEY  (NTFCTN_ID) REFERENCES KREN_NTFCTN_T (ID) 
/
ALTER TABLE USER_CHANNEL_SUBSCRIPTIONS RENAME TO KREN_CHNL_SUBSCRP_T
/
ALTER TABLE KREN_CHNL_SUBSCRP_T RENAME COLUMN ID TO CHNL_SUBSCRP_ID
/
ALTER TABLE KREN_CHNL_SUBSCRP_T RENAME COLUMN CHANNEL_ID TO CHNL_ID
/
ALTER TABLE KREN_CHNL_SUBSCRP_T RENAME COLUMN USER_ID TO PRNCPL_ID
/
DROP INDEX KEN_USER_CHAN_SUBSI1 
/
CREATE INDEX KREN_CHNL_SUBSCRP_TI1 ON KREN_CHNL_SUBSCRP_T (CHNL_ID)
/
ALTER TABLE USER_CHANNEL_SUBSCRIPTIONS disable CONSTRAINT USER_CHANNEL_SUBSCRIPTION_UK1 
/
 ALTER TABLE KREN_CHNL_SUBSCRP_T ADD  CONSTRAINT KREN_CHNL_SUBSCRP_UK1 UNIQUE (CHNL_ID,PRNCPL_ID)
/
ALTER TABLE KREN_CHNL_SUBSCRP_T DROP CONSTRAINT USER_CHANNEL_SUBSCRIPTION_FK1 
/
ALTER TABLE KREN_CHNL_SUBSCRP_T ADD CONSTRAINT KREN_CHAN_SUBSCRP_FK1 FOREIGN KEY  (CHNL_ID) REFERENCES KREN_CHNL_T (ID) 
/
CREATE SEQUENCE KRSB_BAM_PARM_S START WITH BAM_PARAM_SEQ.NEXTVAL 
/
 DROP SEQUENCE BAM_PARAM_SEQ
/
 CREATE SEQUENCE KRSB_BAM_S START WITH BAM_SEQ.NEXTVAL 
/
 DROP SEQUENCE BAM_SEQ
/
 CREATE SEQUENCE KRSB_SVC_DEF_S START WITH SERVICE_DEF_SEQ.NEXTVAL 
/
 DROP SEQUENCE SERVICE_DEF_SEQ
/
 CREATE SEQUENCE KRNS_DOC_TYP_ATTR_S START WITH FP_DOC_TYPE_ATTR_ID_SEQ.NEXTVAL 
/
 DROP SEQUENCE FP_DOC_TYPE_ATTR_ID_SEQ
/
 CREATE SEQUENCE KRNS_LOCK_S START WITH LOCK_ID_SEQ.NEXTVAL 
/
 DROP SEQUENCE LOCK_ID_SEQ
/
 CREATE SEQUENCE KRNS_LOOKUP_RSLT_S START WITH LOOKUP_RESULT_SEQUENCE_NBR_SEQ.NEXTVAL 
/
 DROP SEQUENCE LOOKUP_RESULT_SEQUENCE_NBR_SEQ
/
 CREATE SEQUENCE KRNS_NTE_S START WITH NTE_ID_SEQ.NEXTVAL 
/
 DROP SEQUENCE NTE_ID_SEQ
/
 CREATE SEQUENCE KREN_MSG_S START WITH KCB_MESSAGES_SEQ.NEXTVAL 
/
 DROP SEQUENCE KCB_MESSAGES_SEQ
/
 CREATE SEQUENCE KREN_MSG_DELIV_S START WITH KCB_MSG_DELIVS_SEQ.NEXTVAL 
/
 DROP SEQUENCE KCB_MSG_DELIVS_SEQ
/
 CREATE SEQUENCE KREN_RECIP_DELIV_S START WITH KCB_RECIP_DELIVS_SEQ.NEXTVAL 
/
 DROP SEQUENCE KCB_RECIP_DELIVS_SEQ
/
 CREATE SEQUENCE KREN_RECIP_PREF_S START WITH KCB_RECIP_PREFS_SEQ.NEXTVAL 
/
 DROP SEQUENCE KCB_RECIP_PREFS_SEQ
/
 CREATE SEQUENCE KREN_NTFCTN_S START WITH NOTIFICATIONS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATIONS_SEQ
/
 CREATE SEQUENCE KREN_CHNL_S START WITH NOTIFICATION_CHANNELS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_CHANNELS_SEQ
/
 CREATE SEQUENCE KREN_CNTNT_TYP_S START WITH NOTIFICATION_CONTENT_TYPES_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_CONTENT_TYPES_SEQ
/
 CREATE SEQUENCE KREN_MSG_DELIV_S START WITH NOTIFICATION_MSG_DELIVS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_MSG_DELIVS_SEQ
/
 CREATE SEQUENCE KREN_PRIO_S START WITH NOTIFICATION_PRIORITIES_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_PRIORITIES_SEQ
/
 CREATE SEQUENCE KREN_PRODCR_S START WITH NOTIFICATION_PRODUCERS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_PRODUCERS_SEQ
/
 CREATE SEQUENCE KREN_RECIP_S START WITH NOTIFICATION_RECIPIENTS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_RECIPIENTS_SEQ
/
 CREATE SEQUENCE KREN_RECIP_LIST_S START WITH NOTIFICATION_RECIPS_LISTS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_RECIPS_LISTS_SEQ
/
 CREATE SEQUENCE KREN_RVWER_S START WITH NOTIFICATION_REVIEWERS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_REVIEWERS_SEQ
/
 CREATE SEQUENCE KREN_SNDR_S START WITH NOTIFICATION_SENDERS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_SENDERS_SEQ
/
 CREATE SEQUENCE KRNS_DOC_TYP_ATTR_S START WITH SEQ_DOCUMENT_TYPE_ATTRIBUTE.NEXTVAL 
/
 DROP SEQUENCE SEQ_DOCUMENT_TYPE_ATTRIBUTE
/
 CREATE SEQUENCE KREN_CHNL_SUBSCRP_S START WITH USER_CHANNEL_SUBSCRIPTIONS_SEQ.NEXTVAL 
/
 DROP SEQUENCE USER_CHANNEL_SUBSCRIPTIONS_SEQ
/
 CREATE SEQUENCE KREW_USR_S START WITH SEQUENCE_EN_USR.NEXTVAL 
/
 DROP SEQUENCE SEQUENCE_EN_USR
/
 CREATE SEQUENCE KREW_ACTN_LIST_OPTN_S START WITH SEQ_ACTION_LIST_OPTN.NEXTVAL 
/
 DROP SEQUENCE SEQ_ACTION_LIST_OPTN
/
 CREATE SEQUENCE KREW_ACTN_RQST_S START WITH SEQ_ACTION_REQUEST.NEXTVAL 
/
 DROP SEQUENCE SEQ_ACTION_REQUEST
/
 CREATE SEQUENCE KREW_ACTN_TKN_S START WITH SEQ_ACTION_TAKEN.NEXTVAL 
/
 DROP SEQUENCE SEQ_ACTION_TAKEN
/
 CREATE SEQUENCE KREW_ACTN_ITM_S START WITH SEQ_ACTN_ITM.NEXTVAL 
/
 DROP SEQUENCE SEQ_ACTN_ITM
/
 CREATE SEQUENCE KREW_DOC_HDR_S START WITH SEQ_DOCUMENT_ROUTE_HEADER.NEXTVAL 
/
 DROP SEQUENCE SEQ_DOCUMENT_ROUTE_HEADER
/
 CREATE SEQUENCE KREW_DOC_NTE_S START WITH SEQ_DOC_NTE.NEXTVAL 
/
 DROP SEQUENCE SEQ_DOC_NTE
/
 CREATE SEQUENCE KREW_EDL_FLD_DMP_S START WITH SEQ_EDL_FIELD_DMP.NEXTVAL 
/
 DROP SEQUENCE SEQ_EDL_FIELD_DMP
/
 CREATE SEQUENCE KREW_EDL_S START WITH SEQ_EN_EDOCLT.NEXTVAL 
/
 DROP SEQUENCE SEQ_EN_EDOCLT
/
 CREATE SEQUENCE KREW_HLP_S START WITH SEQ_HELP_ENTRY.NEXTVAL 
/
 DROP SEQUENCE SEQ_HELP_ENTRY
/
 CREATE SEQUENCE KREW_OUT_BOX_ITM_S START WITH SEQ_OUT_BOX_ITM.NEXTVAL 
/
 DROP SEQUENCE SEQ_OUT_BOX_ITM
/
 CREATE SEQUENCE KREW_RSP_S START WITH SEQ_RESPONSIBILITY_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_RESPONSIBILITY_ID
/
 CREATE SEQUENCE KREW_RTE_TMPL_S START WITH SEQ_ROUTE_TEMPLATE.NEXTVAL 
/
 DROP SEQUENCE SEQ_ROUTE_TEMPLATE
/
 CREATE SEQUENCE KREW_RTE_NODE_S START WITH SEQ_RTE_NODE.NEXTVAL 
/
 DROP SEQUENCE SEQ_RTE_NODE
/
 CREATE SEQUENCE KREW_RTE_NODE_CFG_PARM_S START WITH SEQ_RTE_NODE_CFG_PARM.NEXTVAL 
/
 DROP SEQUENCE SEQ_RTE_NODE_CFG_PARM
/
 CREATE SEQUENCE KREW_RULE_EXPR_PARM_S START WITH SEQ_RULE_EXPR_PARM.NEXTVAL 
/
 DROP SEQUENCE SEQ_RULE_EXPR_PARM
/
 CREATE SEQUENCE KREW_RULE_TMPL_OPTN_S START WITH SEQ_RULE_TMPL_OPTN.NEXTVAL 
/
 DROP SEQUENCE SEQ_RULE_TMPL_OPTN
/
 CREATE SEQUENCE KREW_SRCH_ATTR_S START WITH SEQ_SEARCHABLE_ATTRIBUTE_VALUE.NEXTVAL 
/
 DROP SEQUENCE SEQ_SEARCHABLE_ATTRIBUTE_VALUE
/
 