package org.kuali.rice.krad.data.metadata.impl;

import org.kuali.rice.krad.data.metadata.DataObjectAttribute;

/**
 * Interface implemented by the classes within the provider, but that we don't want to expose to use outside of the
 * krad-data module.
 * 
 * @author Kuali Rice Team (rice.collab@kuali.org)
 */
public interface DataObjectAttributeInternal extends DataObjectAttribute, MetadataCommonInternal {
	/**
	 * If this data object attribute is wrapping another (generated by a lower metadata provider), return that.
	 * 
	 * Returns null if this attribute is not wrapping another.
	 */
	DataObjectAttribute getEmbeddedAttribute();

	void setEmbeddedAttribute(DataObjectAttribute embeddedAttribute);
}
