package org.kuali.rice.krad.data.metadata.impl;

import org.kuali.rice.krad.data.metadata.MetadataCommon;

/**
 * Interface implemented by the classes within the provider, but that we don't want to expose to use outside of the
 * krad-data module.
 * 
 * @author Kuali Rice Team (rice.collab@kuali.org)
 */
public interface MetadataCommonInternal extends MetadataCommon {
	/**
	 * If this data object instance is wrapping another (generated by a lower metadata provider), return that.
	 * 
	 * Returns null if this instance is not wrapping another.
	 */
	MetadataCommon getEmbeddedCommonMetadata();

	void setEmbeddedCommonMetadata(MetadataCommon embeddedCommonMetadata);
}