package org.kuali.rice.core.api.component;

import org.kuali.rice.core.api.CoreConstants;
import org.kuali.rice.core.api.exception.RiceIllegalArgumentException;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import java.util.List;

/**
 * Defines the contract for a service which can be used to interact with the Rice core component store.
 *
 * @author Kuali Rice Team (rice.collab@kuali.org)
 */
@WebService(name = "componentServiceSoap", targetNamespace = CoreConstants.Namespaces.CORE_NAMESPACE_2_0)
@SOAPBinding(style = SOAPBinding.Style.DOCUMENT, use = SOAPBinding.Use.LITERAL, parameterStyle = SOAPBinding.ParameterStyle.WRAPPED)
public interface ComponentService {

    @WebMethod(operationName = "getComponentByCode")
    @WebResult(name = "component")
    Component getComponentByCode(
            @WebParam(name = "namespaceCode") String namespaceCode,
            @WebParam(name = "componentCode") String componentCode
    ) throws RiceIllegalArgumentException;

    @WebMethod(operationName = "getAllComponentsByNamespaceCode")
    @WebResult(name = "components")
    @XmlElementWrapper(name = "components", required = true)
	@XmlElement(name = "component", required = false)
    List<Component> getAllComponentsByNamespaceCode(
            @WebParam(name = "namespaceCode") String namespaceCode
    ) throws RiceIllegalArgumentException;

    @WebMethod(operationName = "getActiveComponentsByNamespaceCode")
    @WebResult(name = "components")
    @XmlElementWrapper(name = "components", required = true)
	@XmlElement(name = "component", required = false)
    List<Component> getActiveComponentsByNamespaceCode(
            @WebParam(name = "namespaceCode") String namespaceCode
    ) throws RiceIllegalArgumentException;

    @WebMethod(operationName = "getPublishedComponentSet")
    @WebResult(name = "components")
    @XmlElementWrapper(name = "components", required = true)
	@XmlElement(name = "component", required = false)
    List<Component> getPublishedComponentSet(
            @WebParam(name = "componentSetId") String componentSetId);

    /**
     * Publishes the given component set to make them available to the component system.  It should only ever be
     * necessary to invoke this service whenever published components for an application change.  However, it is always
     * safe to invoke this method even if the client cannot make this determination as the implementation of this
     * service should be responsible for handling the given information and ignoring it if no publication needs to
     * occur.  To this end, this method should be idempotent.
     *
     * <p>When invoked, the set of components known to the component system for the given component set id will be
     * updated.  Any previously published components for the component set id which are not contained within the given
     * list will have their {@code active} flag set to false.</p>
     *
     * <p>The {@code componentSetId} should be an identifier generated by the client application which uniquely
     * identifies the component set being published (either newly published or updated).  A simple value to use would
     * be the {@code applicationId} of the client application but this would mean an application could only ever publish
     * a single custom component set.  So the {@code applicationId} could also be combined with some additional
     * information on the source of the components being published if a particular application needs to publish custom
     * components from multiple sources.</p>
     *
     * @param componentSetId an id that uniquely identifies this set of components being checked.  The service will use
     * this to track the components being published
     * @param components the components to publish, may be empty or null, in which case all published components for the
     * given component set id will be inactived in the component system
     *
     * @throws RiceIllegalArgumentException if componentSetId is a null or blank value
     */
    @WebMethod(operationName = "publishComponents")
    void publishComponents(
            @WebParam(name = "componentSetId") String componentSetId,
            @WebParam(name = "components") List<Component> components
    ) throws RiceIllegalArgumentException;

}
