CREATE TABLE EN_APPL_CNST_T (
   APPL_CNST_NM          VARCHAR2(100) NOT NULL,
   APPL_CNST_VAL_TXT     VARCHAR2(2000) NULL,
   DB_LOCK_VER_NBR       NUMERIC(8) DEFAULT 0,
   CONSTRAINT EN_APPL_CNST_T_PK PRIMARY KEY (APPL_CNST_NM) USING INDEX
)
/