CREATE TABLE EN_DOC_TYP_ATTRIB_T (
   	DOC_TYP_ATTRIB_ID          	NUMBER(19) NOT NULL,
   	DOC_TYP_ID               	NUMBER(19) NOT NULL,
	RULE_ATTRIB_ID				NUMBER(19) NOT NULL,
	CONSTRAINT EN_DOC_TYP_ATTRIB_T_PK PRIMARY KEY (DOC_TYP_ATTRIB_ID) USING INDEX
)
/