CREATE TABLE EN_ORG_RESP_ID_T (
   ORG_CD                      VARCHAR2(4) NOT NULL,
   FIN_COA_CD                  VARCHAR2(2) NOT NULL,
   ORG_RESP_ID                 NUMBER(14) NOT NULL,
   ORG_RESP_ID_APRVR_TYP_CD    CHAR(1) NOT NULL,
   DB_LOCK_VER_NBR	           NUMBER(8) DEFAULT 0,
   CONSTRAINT EN_ORG_RESP_ID_T_PK PRIMARY KEY (org_cd, fin_coa_cd, ORG_RESP_ID_APRVR_TYP_CD) USING INDEX
)
/