CREATE TABLE EN_RULE_ATTRIB_T (
	RULE_ATTRIB_ID NUMBER(19) NOT NULL,
	RULE_ATTRIB_NM VARCHAR2(255) NOT NULL,
	RULE_ATTRIB_LBL_TXT VARCHAR2(2000) NOT NULL,
	RULE_ATTRIB_TYP VARCHAR2(2000) NOT NULL,
	RULE_ATTRIB_DESC VARCHAR2(2000) NULL,
	RULE_ATTRIB_CLS_NM VARCHAR2(2000) NULL,
	RULE_ATTRIB_XML_RTE_TXT CLOB NULL,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	MESSAGE_ENTITY_NM VARCHAR(10) NULL,
	CONSTRAINT EN_RULE_ATTRIB_PK PRIMARY KEY (RULE_ATTRIB_ID) USING INDEX
)
/