-- Table for RuleExpressionDef; child of EN_RULE_BASE_VAL_T/RuleBaseValue
CREATE TABLE EN_RULE_EXPR_T (
    RULE_EXPR_ID    NUMBER(19) NOT NULL,
    RULE_EXPR_TYP   VARCHAR(256) NOT NULL,
    RULE_EXPR       VARCHAR2(4000),
    CONSTRAINT EN_RULE_EXPR_T_PK PRIMARY KEY (RULE_EXPR_ID) USING INDEX
)
/