CREATE TABLE EN_RULE_RSP_T (
	RULE_RSP_ID NUMBER(19) NOT NULL,
	RSP_ID NUMBER(19) NOT NULL,
	RULE_BASE_VAL_ID NUMBER(19) NOT NULL,
	RULE_RSP_PRIO_NBR NUMBER(5) NULL,
	ACTION_RQST_CD VARCHAR2(2000) NULL,
	RULE_RSP_NM VARCHAR2(200) NULL,
	RULE_RSP_TYP VARCHAR2(1) NULL,
    RULE_RSP_APPR_PLCY CHAR(1) NULL,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RULE_RSP_PK PRIMARY KEY (RULE_RSP_ID) USING INDEX
)
/