CREATE TABLE EN_RULE_TMPL_ATTRIB_T (
	RULE_TMPL_ATTRIB_ID NUMBER(19) NOT NULL,
	RULE_TMPL_ID NUMBER(19) NOT NULL,
	RULE_ATTRIB_ID NUMBER(19) NOT NULL,
	REQ_IND NUMBER(1) NOT NULL,
	ACTV_IND NUMBER(1) NOT NULL,
	DSPL_ORD NUMBER(5) NOT NULL,
	DFLT_VAL VARCHAR2(2000),
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RULE_TMPL_ATTRIB_PK PRIMARY KEY (RULE_TMPL_ATTRIB_ID) USING INDEX
)
/