CREATE TABLE EN_RULE_BASE_VAL_T (
	RULE_BASE_VAL_ID NUMBER(19) NOT NULL,
	RULE_TMPL_ID NUMBER(19) NOT NULL,
	RULE_BASE_VAL_ACTV_IND NUMBER(1) NOT NULL,
	RULE_BASE_VAL_DESC VARCHAR2(2000) NULL,
	RULE_BASE_VAL_IGNR_PRVS NUMBER(1) NOT NULL,
	DOC_TYP_NM VARCHAR2(2000) NOT NULL,
	DOC_HDR_ID NUMBER(14) NULL,
	TMPL_RULE_IND NUMBER(1),
	RULE_BASE_VAL_FRM_DT   DATE NOT NULL,
  RULE_BASE_VAL_TO_DT    DATE NOT NULL,
  RULE_BASE_VAL_DACTVN_DT DATE NULL,
  RULE_BASE_VAL_CUR_IND NUMBER(1) DEFAULT 0,
  RULE_BASE_VAL_VER_NBR NUMBER(8) DEFAULT 0,
  RULE_BASE_VAL_DLGN_IND NUMBER(1),
  RULE_BASE_VAL_PREV_VER NUMBER(19),
  RULE_BASE_VAL_ACTVN_DT DATE NULL,
  DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
  CONSTRAINT EN_RULE_BASE_VAL_PK PRIMARY KEY (RULE_BASE_VAL_ID) USING INDEX
)
/