CREATE TABLE EN_TRANSACTION_TST_ADDRS_T (
	ADDRS_ID NUMBER(19) NOT NULL,
	STREET VARCHAR2(2000),
	CITY VARCHAR2(2000),
	STATE VARCHAR2(2),
	ZIP NUMBER(8),
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_TRANSACTION_TST_ADDRS_T_PK PRIMARY KEY (ADDRS_ID)  USING INDEX
)
/