CREATE TABLE EN_USR_OPTN_T (
   PRSN_EN_ID       VARCHAR2(30) NULL,
   PRSN_OPTN_ID     VARCHAR2(200) NOT NULL,
   PRSN_OPTN_VAL    VARCHAR2(2000) NULL,
   DB_LOCK_VER_NBR  NUMBER(8) DEFAULT 0,
   CONSTRAINT EN_USR_OPTN_T_PK PRIMARY KEY (PRSN_EN_ID, PRSN_OPTN_ID) USING INDEX
)
/