CREATE TABLE EN_WRKGRP_MBR_T (
    WRKGRP_MBR_PRSN_EN_ID     VARCHAR2(30) NOT NULL,
    WRKGRP_ID                 NUMBER(14) NOT NULL,
    WRKGRP_MBR_TYP			  CHAR(1) NOT NULL,
    WRKGRP_VER_NBR            NUMBER(8) DEFAULT 0,
    DB_LOCK_VER_NBR           NUMBER(8) DEFAULT 0,
    CONSTRAINT EN_WRKGRP_MBR_T_PK PRIMARY KEY (WRKGRP_MBR_PRSN_EN_ID, WRKGRP_ID, WRKGRP_VER_NBR) USING INDEX
)
/