CREATE TABLE EN_WRKGRP_TYP_ATTRIB_T (
	WRKGRP_TYP_ATTRIB_ID NUMBER(19) NOT NULL,
	WRKGRP_TYP_ID NUMBER(19) NOT NULL,
	ATTRIB_ID NUMBER(19) NOT NULL,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_WRKGRP_TYP_ATTRIB_PK PRIMARY KEY (WRKGRP_TYP_ATTRIB_ID)
)
/
