CREATE TABLE EN_WRKGRP_EXT_DTA_T (
    WRKGRP_EXT_DTA_ID   NUMBER(19) NOT NULL,
    WRKGRP_EXT_ID       NUMBER(19) NOT NULL,
    EXT_KEY             VARCHAR2(2000) NOT NULL,
	EXT_VAL             VARCHAR2(2000),
	DB_LOCK_VER_NBR     NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_WRKGRP_EXT_DTA_T_PK PRIMARY KEY (WRKGRP_EXT_DTA_ID)
)
/