INSERT INTO KIM_NAMESPACES_T (ID, NAME, DESCRIPTION) VALUES (1, 'KIM', 'This record represents the actual KIM system and must always be loaded by default in order for the system to work properly.');
INSERT INTO KIM_NAMESPACES_T (ID, NAME, DESCRIPTION) VALUES (2, 'Global', 'This record represents the global shared namespace that should house entity attributes and permissions global across all namespaces and not specific to any one namespace.');
INSERT INTO KIM_NAMESPACES_T (ID, NAME, DESCRIPTION) VALUES(100, 'KRA', 'Kuali Research');
INSERT INTO KIM_NAMESPACES_T (ID, NAME, DESCRIPTION) VALUES(101, 'KFS', 'Kuali Finance');

INSERT INTO KIM_ATTRIBUTE_TYPES_T (ID, NAME, DESCRIPTION) VALUES(110, 'Text', 'Alphanumeric');
INSERT INTO KIM_ATTRIBUTE_TYPES_T (ID, NAME, DESCRIPTION) VALUES(111, 'PhoneNumber', 'Phone number');
INSERT INTO KIM_ATTRIBUTE_TYPES_T (ID, NAME, DESCRIPTION) VALUES(112, 'Email', 'Email address');

INSERT INTO KIM_NAMESPACE_DFLT_ATTRIBS_T (ID, NAMESPACE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, DESCRIPTION, REQUIRED, ACTIVE) VALUES(1, 1, 'FirstName', 110, 'First Name', 'Y', 'Y' );
INSERT INTO KIM_NAMESPACE_DFLT_ATTRIBS_T (ID, NAMESPACE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, DESCRIPTION, REQUIRED, ACTIVE) VALUES(120, 100, 'FirstName', 110, 'First Name', 'Y', 'Y' );
INSERT INTO KIM_NAMESPACE_DFLT_ATTRIBS_T (ID, NAMESPACE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, DESCRIPTION, REQUIRED, ACTIVE) VALUES(121, 100, 'WorkNumber', 111, 'Work Number', 'Y', 'Y' );
INSERT INTO KIM_NAMESPACE_DFLT_ATTRIBS_T (ID, NAMESPACE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, DESCRIPTION, REQUIRED, ACTIVE) VALUES(122, 100, 'Email', 112, 'Test case', 'Y', 'Y' );

INSERT INTO KIM_ENTITY_TYPES_T (ID, NAME, DESCRIPTION) values (1, 'Person', 'This entity type represents a person.');
INSERT INTO KIM_ENTITY_TYPES_T (ID, NAME, DESCRIPTION) values (131, 'System', 'This entity type represents another system.');
INSERT INTO KIM_ENTITY_TYPES_T (ID, NAME, DESCRIPTION) values (132, 'Service', 'This entity type represents a service.');
INSERT INTO KIM_ENTITY_TYPES_T (ID, NAME, DESCRIPTION) values (133, 'Process', 'This entity type represents a process.');

INSERT INTO KIM_ENTITYS_T (ID, ENTITY_TYPE_ID) VALUES (140, 1);
INSERT INTO KIM_ENTITYS_T (ID, ENTITY_TYPE_ID) VALUES (141, 1);
INSERT INTO KIM_ENTITYS_T (ID, ENTITY_TYPE_ID) VALUES (142, 131);

INSERT INTO KIM_ENTITY_ATTRIBUTES_T (ID, ENTITY_ID, SPONSOR_NAMESPACE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, ATTRIBUTE_VALUES) VALUES(150, 140, 1,'EmailAddress', 112,'kuali-rice@googlegroups.com');
INSERT INTO KIM_ENTITY_ATTRIBUTES_T (ID, ENTITY_ID, SPONSOR_NAMESPACE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, ATTRIBUTE_VALUES) VALUES(153, 140, 1,'Country', 112,'USA');
INSERT INTO KIM_ENTITY_ATTRIBUTES_T (ID, ENTITY_ID, SPONSOR_NAMESPACE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, ATTRIBUTE_VALUES) VALUES(151, 141, 100,'GroupPhoneNumber', 111,'555-5555');
INSERT INTO KIM_ENTITY_ATTRIBUTES_T (ID, ENTITY_ID, SPONSOR_NAMESPACE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, ATTRIBUTE_VALUES) VALUES(152, 142, 101,'Supervisor', 110,'Aaron Godert');
INSERT INTO KIM_ENTITY_ATTRIBUTES_T (ID, ENTITY_ID, SPONSOR_NAMESPACE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, ATTRIBUTE_VALUES) VALUES(154, 141, 1,'EmailAddress', 112,'kuali-rice@googlegroups.com');

INSERT INTO KIM_PRINCIPALS_T (ID, NAME, ENTITY_ID) VALUES(160, 'jschmoe', 140);
INSERT INTO KIM_PRINCIPALS_T (ID, NAME, ENTITY_ID) VALUES(161, 'jdoe', 141);
INSERT INTO KIM_PRINCIPALS_T (ID, NAME, ENTITY_ID) VALUES(162, 'HAL', 142);

INSERT INTO KIM_GROUP_TYPES_T (ID, NAME, DESCRIPTION, WORKFLOW_DOCUMENT_TYPE) values (1, 'Default', 'This is the standard group type that most groups default to.', 'KIMGroupMaintenanceDocument');
INSERT INTO KIM_GROUP_TYPES_T (ID, NAME, DESCRIPTION, WORKFLOW_DOCUMENT_TYPE) VALUES (310, 'GroupType', 'Group Type', 'GroupTypeDocType');

INSERT INTO KIM_GRP_TYP_DFLT_ATTRIBS_T (ID, GROUP_TYPE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, DESCRIPTION, REQUIRED, ACTIVE) VALUES(1, 310, 'Test Attribute 1', 110, 'Test Attribute 1', 'Y', 'Y' );
INSERT INTO KIM_GRP_TYP_DFLT_ATTRIBS_T (ID, GROUP_TYPE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, DESCRIPTION, REQUIRED, ACTIVE) VALUES(2, 310, 'Test Attribute 2', 110, 'Test Attribute 2', 'Y', 'Y' );

INSERT INTO KIM_GROUPS_T (ID, NAME, DESCRIPTION,GROUP_TYPE_ID) VALUES(300, 'Group1', 'Test group1',310);
INSERT INTO KIM_GROUPS_T (ID, NAME, DESCRIPTION,GROUP_TYPE_ID) VALUES(301, 'Group2', 'Test group2',310);
INSERT INTO KIM_GROUPS_T (ID, NAME, DESCRIPTION,GROUP_TYPE_ID) VALUES(302, 'ParentGroup1', 'Parent Test group1',310);
INSERT INTO KIM_GROUPS_T (ID, NAME, DESCRIPTION,GROUP_TYPE_ID) VALUES(303, 'ParentGroup2', 'Parent Test group2',310);
INSERT INTO KIM_GROUPS_T (ID, NAME, DESCRIPTION,GROUP_TYPE_ID) VALUES(304, 'SiblingGroup1', 'Sibling Test group1',310);
INSERT INTO KIM_GROUPS_T (ID, NAME, DESCRIPTION,GROUP_TYPE_ID) VALUES(305, 'SiblingGroup2', 'Sibling Test group2',310);

INSERT INTO KIM_GROUPS_GROUPS_T (PARENT_GROUP_ID, MEMBER_GROUP_ID) VALUES (301, 302);
INSERT INTO KIM_GROUPS_GROUPS_T (PARENT_GROUP_ID, MEMBER_GROUP_ID) VALUES (302,300);
INSERT INTO KIM_GROUPS_GROUPS_T (PARENT_GROUP_ID, MEMBER_GROUP_ID) VALUES (300,304);
INSERT INTO KIM_GROUPS_GROUPS_T (PARENT_GROUP_ID, MEMBER_GROUP_ID) VALUES (302,301);

INSERT INTO KIM_GROUP_ATTRIBUTES_T (ID, GROUP_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, ATTRIBUTE_VALUES) VALUES (170, 300, 'GroupPhoneNumber', 111, '555-5555');
INSERT INTO KIM_GROUP_ATTRIBUTES_T (ID, GROUP_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, ATTRIBUTE_VALUES) VALUES (171, 300, 'GroupEmail', 112, 'kuali-rice@googlegroups.com');
INSERT INTO KIM_GROUP_ATTRIBUTES_T (ID, GROUP_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, ATTRIBUTE_VALUES) VALUES (172, 302, 'GroupEmail', 112, 'kualidev-rice@googlegroups.com');

INSERT INTO KIM_PERMISSIONS_T (ID, NAME, DESCRIPTION, NAMESPACE_ID) VALUES(1, 'canSave', 'Can save', 1);
INSERT INTO KIM_PERMISSIONS_T (ID, NAME, DESCRIPTION, NAMESPACE_ID) VALUES(180, 'canSave', 'Can save', 100);
INSERT INTO KIM_PERMISSIONS_T (ID, NAME, DESCRIPTION, NAMESPACE_ID) VALUES(181, 'canView', 'Can view', 100);
INSERT INTO KIM_PERMISSIONS_T (ID, NAME, DESCRIPTION, NAMESPACE_ID) VALUES(182, 'canEdit', 'Can edit', 100);


INSERT INTO KIM_ROLES_T (ID, NAME, DESCRIPTION) VALUES (190, 'Dean', 'Dean');
INSERT INTO KIM_ROLES_T (ID, NAME, DESCRIPTION) VALUES (191, 'Director of IT', 'Director of IT');

INSERT INTO KIM_ROLE_ATTRIBUTES_T (ID, ROLE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, ATTRIBUTE_VALUE) VALUES (200, 190, 'Account Number', 110, '12345');
INSERT INTO KIM_ROLE_ATTRIBUTES_T (ID, ROLE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, ATTRIBUTE_VALUE) VALUES (201, 191, 'Account Number', 110, '12346');

INSERT INTO KIM_GROUP_QLFD_ROLES_T (ID, GROUP_ID, ROLE_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES (210, 300, 190, 'Department', 'Finance');
INSERT INTO KIM_GROUP_QLFD_ROLES_T (ID, GROUP_ID, ROLE_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES (211, 300, 190, 'College', 'Arts and Science');
INSERT INTO KIM_GROUP_QLFD_ROLES_T (ID, GROUP_ID, ROLE_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES (212, 301, 190, 'College', 'Arts and Science');

INSERT INTO KIM_PRNCPL_QLFD_ROLES_T (ID, PRINCIPAL_ID, ROLE_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES(220, 160,191,'QualifiedRole', 'Some role');
INSERT INTO KIM_PRNCPL_QLFD_ROLES_T (ID, PRINCIPAL_ID, ROLE_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES(221, 160,190,'QualifiedRole2', 'Some role2');
INSERT INTO KIM_PRNCPL_QLFD_ROLES_T (ID, PRINCIPAL_ID, ROLE_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES(222, 161,190,'QualifiedRole2', 'Some role2');

INSERT INTO KIM_GROUPS_PRINCIPALS_T (GROUP_ID, PRINCIPAL_ID) VALUES (300, 160);
INSERT INTO KIM_GROUPS_PRINCIPALS_T (GROUP_ID, PRINCIPAL_ID) VALUES (302, 160);
INSERT INTO KIM_GROUPS_PRINCIPALS_T (GROUP_ID, PRINCIPAL_ID) VALUES (302, 161);
INSERT INTO KIM_GROUPS_PRINCIPALS_T (GROUP_ID, PRINCIPAL_ID) VALUES (303, 162);

INSERT INTO KIM_ROLES_PRINCIPALS_T (ROLE_ID, PRINCIPAL_ID) VALUES(190,160);
INSERT INTO KIM_ROLES_PRINCIPALS_T (ROLE_ID, PRINCIPAL_ID) VALUES(190,161);

INSERT INTO KIM_ROLES_PERMISSIONS_T (ROLE_ID, PERMISSION_ID) VALUES (190,181);
INSERT INTO KIM_ROLES_PERMISSIONS_T (ROLE_ID, PERMISSION_ID) VALUES (190,180);
INSERT INTO KIM_ROLES_PERMISSIONS_T (ROLE_ID, PERMISSION_ID) VALUES (191,180);
INSERT INTO KIM_ROLES_PERMISSIONS_T (ROLE_ID, PERMISSION_ID) VALUES (191,181);

INSERT INTO KIM_ROLES_GROUPS_T (ROLE_ID, GROUP_ID) VALUES (190, 302);
INSERT INTO KIM_ROLES_GROUPS_T (ROLE_ID, GROUP_ID) VALUES (190, 303);
INSERT INTO KIM_ROLES_GROUPS_T (ROLE_ID, GROUP_ID) VALUES (191, 300);
INSERT INTO KIM_ROLES_GROUPS_T (ROLE_ID, GROUP_ID) VALUES (191, 302);
