INSERT INTO KIM_GROUPS_T (ID, NAME, DESCRIPTION) VALUES(1, 'KIM Test Group', 'Test case');
INSERT INTO KIM_NAMESPACES_T (ID, NAME, DESCRIPTION) VALUES(1, 'KIM Test Namespace', 'Test case');
INSERT INTO KIM_PERMISSIONS_T (ID, NAME, DESCRIPTION, NAMESPACE_ID) VALUES(1, 'KIM Test Permission', 'Test case', 1);
INSERT INTO KIM_ATTRIBUTE_TYPES_T (ID, NAME, DESCRIPTION) VALUES(1, 'KIM Test AttributeType', 'Test case');
INSERT INTO KIM_NAMESPACE_DFLT_ATTRIBS_T (ID, NAMESPACE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, DESCRIPTION, REQUIRED, ACTIVE) VALUES(1, 1, 'KIM Test Namespace Default Attribute', 1, 'Test case', 'Y', 'Y' );
