-- Suppress error messages when dropping non-existing database objects --;
WHENEVER SQLERROR CONTINUE;

DROP TABLE EN_DOC_NTE_T CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_DOC_NTE;
DROP TABLE EN_RULE_TMPL_OPTN_T CASCADE CONSTRAINTS; 
DROP SEQUENCE SEQ_RULE_TMPL_OPTN;
DROP TABLE EN_DOC_HDR_EXT_T CASCADE CONSTRAINTS; 
DROP SEQUENCE SEQ_SEARCHABLE_ATTRIBUTE_VALUE;
DROP TABLE EN_DOC_TYP_ATTRIB_T CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_DOCUMENT_TYPE_ATTRIBUTE;
DROP TABLE EN_HLP_T CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_HELP_ENTRY;

-- Reinstate error messages and exit --;
WHENEVER SQLERROR EXIT SQL.SQLCODE;