--
-- Copyright 2005-2012 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--


--
--     KULRICE-7033: krad travel authorization document tables
--

 CREATE  TABLE `RICE`.`TRVL_ADV_T` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `FDOC_NBR` VARCHAR(45) NULL ,
  `FDOC_LINE_NBR` INT NULL ,
  `TVL_ADV_REQ` DECIMAL NULL ,
  `AR_CUST_ID` VARCHAR(45) NULL ,
  `AR_INV_DOC_NBR` VARCHAR(45) NULL ,
  `DUE_DT` DATE NULL ,
  `PYMT_MTHD` VARCHAR(45) NULL ,
  `FIN_COA_CD` VARCHAR(45) NULL ,
  `ACCOUNT_NBR` VARCHAR(45) NULL ,
  `SUB_ACCT_NBR` VARCHAR(45) NULL ,
  `FIN_OBJECT_CD` VARCHAR(45) NULL ,
  `FIN_SUB_OBJ_CD` VARCHAR(45) NULL ,
  `ADV_PMNT_RSN_CD` VARCHAR(45) NULL ,
  `TRVL_ADV_PLCY` VARCHAR(45) NULL ,
  `ADD_JUST` VARCHAR(45) NULL ,
  `TAX_RAM_NTF_DT` DATE NULL ,
  `OBJ_ID` VARCHAR(45) NULL ,
  `VER_NBR` BIGINT NULL ,
  PRIMARY KEY (`id`) );

   CREATE  TABLE `RICE`.`TRVL_IMP_EXP_T` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `FDOC_NBR` VARCHAR(45) NULL ,
  `FDOC_LINE_NBR` INT NULL ,
  `EXP_TYPE_CD` VARCHAR(45) NULL ,
  `EXP_PARENT_ID` BIGINT NULL ,
  `EXP_DESC` VARCHAR(45) NULL ,
  `EXP_DT` DATE NULL ,
  `EXP_AMT` DECIMAL NULL ,
  `CUR_RT` DECIMAL NULL ,
  `TEM_EXP_TYP_ID` BIGINT NULL ,
  `DV_EXP_CO_NM` VARCHAR(45) NULL ,
  `NON_REIMB_IND` VARCHAR(45) NULL ,
  `TAXABLE_IND` VARCHAR(45) NULL ,
  `MISG_RCPT_IND` VARCHAR(45) NULL ,
  `CONVERTED_AMT` DECIMAL NULL ,
  `RCPT_RQD_IND` VARCHAR(45) NULL ,
  `CARD_TYPE` VARCHAR(45) NULL ,
  `HIST_EXP_ID` BIGINT NULL ,
  `OBJ_ID` VARCHAR(45) NULL ,
  `VER_NBR` BIGINT NULL ,
  PRIMARY KEY (`id`) );

   CREATE  TABLE `RICE`.`TRVL_EXP_T` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `FDOC_NBR` VARCHAR(45) NULL ,
  `FDOC_LINE_NBR` INT NULL ,
  `EXP_TYPE_CD` VARCHAR(45) NULL ,
  `EXP_PARENT_ID` BIGINT NULL ,
  `EXP_DESC` VARCHAR(45) NULL ,
  `EXP_DT` DATE NULL ,
  `EXP_AMT` DECIMAL NULL ,
  `CUR_RT` DECIMAL NULL ,
  `TEM_EXP_TYP_ID` BIGINT NULL ,
  `DV_EXP_CO_NM` VARCHAR(45) NULL ,
  `NON_REIMB_IND` VARCHAR(45) NULL ,
  `TAXABLE_IND` VARCHAR(45) NULL ,
  `MISG_RCPT_IND` VARCHAR(45) NULL ,
  `CONVERTED_AMT` DECIMAL NULL ,
  `AIRFARE_SRC_CD` VARCHAR(45) NULL ,
  `CLASS_SVC_CODE` VARCHAR(45) NULL ,
  `MILEAGE_RT_ID` INT NULL ,
  `MILES` INT NULL ,
  `MILEAGE_OTHR_RT` DECIMAL NULL ,
  `RENTAL_CAR_INSURANCE` VARCHAR(45) NULL ,
  `OBJ_ID` VARCHAR(45) NULL ,
  `VER_NBR` BIGINT NULL ,
  PRIMARY KEY (`id`) );


   CREATE  TABLE `RICE`.`TRVL_PER_DIEM_EXP_T` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `FDOC_NBR` VARCHAR(45) NULL ,
  `MLG_DT` TIMESTAMP NULL ,
  `COUNTRY` VARCHAR(45) NULL ,
  `COUNTY_CD` VARCHAR(45) NULL ,
  `PRI_DEST` VARCHAR(45) NULL ,
  `BREAKFAST_IND` VARCHAR(45) NULL ,
  `LUNCH_IND` VARCHAR(45) NULL ,
  `DINNER_IND` VARCHAR(45) NULL ,
  `BREAKFAST_VAL` DECIMAL NULL ,
  `LUNCH_VAL` DECIMAL NULL ,
  `DINNER_VAL` DECIMAL NULL ,
  `INCIDENTALS_VAL` DECIMAL NULL ,
  `PERSONAL` VARCHAR(45) NULL ,
  `PER_DIEM_ID` INT NULL ,
  `LODGING` DECIMAL NULL ,
  `MILES` INT NULL ,
  `MILEAGE_RT_ID` INT NULL ,
  `ACCOM_TYP_CD` VARCHAR(45) NULL ,
  `ACCOM_NM` VARCHAR(45) NULL ,
  `ACCOM_PH` VARCHAR(45) NULL ,
  `ACCOM_ADDRESS` VARCHAR(45) NULL ,
  `OBJ_ID` VARCHAR(45) NULL ,
  `VER_NBR` BIGINT NULL ,
  PRIMARY KEY (`id`) );


   CREATE  TABLE `RICE`.`TRVL_TRANS_MD_T` (
  `CODE` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `ACTIVE` VARCHAR(45) NOT NULL,
  `OBJ_ID` VARCHAR(45) NULL ,
  `VER_NBR` BIGINT NULL ,
  PRIMARY KEY (`CODE`) );

   CREATE  TABLE `RICE`.`TRVL_TRANS_MD_DTL_T` (
  `FDOC_NBR` VARCHAR(45) NULL ,
  `TRANS_MODE_CD` VARCHAR(45) NULL ,
  `OBJ_ID` VARCHAR(45) NULL ,
  `VER_NBR` BIGINT NULL ,
  PRIMARY KEY (`FDOC_NBR`) );

   CREATE  TABLE `RICE`.`TRVL_PER_DIEM_T` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `TRIP_TYP_CD` INT NULL ,
  `COUNTRY` VARCHAR(45) NULL ,
  `COUNTY_NM` VARCHAR(45) NULL ,
  `COUNTY_CD` VARCHAR(45) NULL ,
  `PRI_DEST` VARCHAR(45) NULL ,
  `ACTV_IND` VARCHAR(45) NULL ,
  `OBJ_ID` VARCHAR(45) NULL ,
  `VER_NBR` BIGINT NULL ,
  PRIMARY KEY (`id`) );

   CREATE  TABLE `RICE`.`TRVL_TRIP_TYP_T` (
  `CODE` VARCHAR(45) NOT NULL ,
  `NM` VARCHAR(45) NULL ,
  `GEN_ENC_IND` VARCHAR(45) NULL ,
  `ENC_BAL_TYP` VARCHAR(45) NULL ,
  `ENC_OBJ_CD` VARCHAR(45) NULL ,
  `CONT_INFO_REQ_IND` VARCHAR(45) NULL ,
  `BLANKET_IND` VARCHAR(45) NULL ,
  `AUTO_TR_LIMIT` DECIMAL NULL ,
  `USE_PER_DIEM` VARCHAR(45) NULL ,
  `TA_REQUIRED` VARCHAR(45) NULL ,
  `PER_DIEM_CALC_METHOD` VARCHAR(45) NULL ,
  `ACTV_IND` VARCHAR(45) NULL ,
  `OBJ_ID` VARCHAR(45) NULL ,
  `VER_NBR` BIGINT NULL ,
  PRIMARY KEY (`CODE`) );

   CREATE  TABLE `RICE`.`TRVL_EM_CONT_T` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `TRAVELER_DTL_ID` INT NULL ,
  `FDOC_NBR` VARCHAR(45) NULL ,
  `FDOC_LINE_NBR` INT NULL ,
  `CONT_REL_TYP_CD` VARCHAR(45) NULL ,
  `CONT_NM` VARCHAR(45) NULL ,
  `PHONE_NBR` VARCHAR(45) NULL ,
  `EMAIL_ADDR` VARCHAR(45) NULL ,
  `PRIMARY_IND` VARCHAR(45) NULL ,
  `OBJ_ID` VARCHAR(45) NULL ,
  `VER_NBR` BIGINT NULL ,
  PRIMARY KEY (`id`) );

   CREATE  TABLE `RICE`.`TRVL_TRAVELER_TYP_T` (
  `CODE` VARCHAR(45) NOT NULL ,
  `SRC_CODE` VARCHAR(45) NULL ,
  `NM` VARCHAR(45) NULL ,
  `ADVANCES_IND` VARCHAR(45) NULL ,
  `ACTV_IND` VARCHAR(45) NULL ,
  `OBJ_ID` VARCHAR(45) NULL ,
  `VER_NBR` BIGINT NULL ,
  PRIMARY KEY (`CODE`) );

   CREATE  TABLE `RICE`.`TRVL_TRAVELER_DTL_T` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `DOC_NBR` VARCHAR(45) NULL ,
  `EMP_PRINCIPAL_ID` VARCHAR(45) NULL ,
  `CUST_NBR` VARCHAR(45) NULL ,
  `FIRST_NM` VARCHAR(45) NULL ,
  `LAST_NM` VARCHAR(45) NULL ,
  `ADDR_LINE_1` VARCHAR(45) NULL ,
  `ADDR_LINE_2` VARCHAR(45) NULL ,
  `CITY_NM` VARCHAR(45) NULL ,
  `POSTAL_STATE_CD` VARCHAR(45) NULL ,
  `POSTAL_CD` VARCHAR(45) NULL ,
  `COUNTRY_CD` VARCHAR(45) NULL ,
  `EMAIL_ADDR` VARCHAR(45) NULL ,
  `PHONE_NBR` VARCHAR(45) NULL ,
  `LIABILITY_INSURANCE` VARCHAR(45) NULL ,
  `TRAVELER_TYP_CD` VARCHAR(45) NULL ,
  `OBJ_ID` VARCHAR(45) NULL ,
  `CITIZENSHIP` VARCHAR(45) NULL ,
  `ACTV_IN` VARCHAR(45) NULL ,
  `VER_NBR` BIGINT NULL ,
  PRIMARY KEY (`id`) );


  CREATE  TABLE `RICE`.`TRVL_AUTH_DOC_T` (
  `FDOC_NBR` VARCHAR(45) NOT NULL ,
  `TRVL_ID` INT NULL ,
  `TEM_PROFILE_ID` INT NULL ,
  `TRAVELER_DTL_ID` INT NULL ,
  `TRIP_TYP_CD` VARCHAR(45) NULL ,
  `TRIP_BGN_DT` TIMESTAMP NULL ,
  `TRIP_END_DT` TIMESTAMP NULL ,
  `EXP_LMT` DECIMAL NULL ,
  `MEAL_WITHOUT_LODGING` VARCHAR(45) NULL ,
  `PRIMARY_DEST_ID` INT NULL ,
  `PRIMARY_DEST_NAME` VARCHAR(45) NULL ,
  `PRIMARY_DEST_CNTRY_S` VARCHAR(45) NULL ,
  `PRIMARY_DEST_CNTY` VARCHAR(45) NULL ,
  `TRIP_DESC` VARCHAR(200) NULL ,
  `DELINQUENT_TR_EXCEPTION` VARCHAR(45) NULL ,
  `PER_DIEM_ADJ` DECIMAL NULL ,
  `CELL_PH_NUM` VARCHAR(45) NULL ,
  `RGN_FAMIL` VARCHAR(45) NULL ,
  `CTZN_CNTRY_CD` VARCHAR(45) NULL ,
  `FDOC_NXT_EXP_NBR` INT NULL ,
  `OBJ_ID` VARCHAR(45) NULL ,
  `CITIZENSHIP` VARCHAR(45) NULL ,
  `VER_NBR` BIGINT NULL ,
  PRIMARY KEY (`FDOC_NBR`) );
