ALTER TABLE KRNS_LOOKUP_RSLT_T MODIFY PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KRNS_LOOKUP_SEL_T MODIFY PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KRNS_NTE_T MODIFY AUTH_PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T MODIFY PRNCPL_ID VARCHAR2(40)
/
