ALTER TABLE KOM_ORGANIZATIONS_CONTEXTS_T
ADD CONSTRAINT KOM_ORGANIZATIONS_CONTEXTS_FK1 FOREIGN KEY
(
ORGANIZATION_ID
)
REFERENCES KOM_ORGANIZATION_T
(
ID
) ENABLE
/
ALTER TABLE KOM_ORGANIZATIONS_CONTEXTS_T
ADD CONSTRAINT KOM_ORGANIZATIONS_CONTEXTS_FK2 FOREIGN KEY
(
CONTEXT_ID
)
REFERENCES KOM_ORGANIZATION_CONTEXT_T
(
ID
) ENABLE
/