ALTER TABLE KOM_ORGANIZATIONS_T
ADD CONSTRAINT KOM_ORGANIZATIONS_UK1 UNIQUE
(
NAME
) ENABLE
/
ALTER TABLE KOM_ORGANIZATIONS_T
ADD CONSTRAINT KOM_ORGANIZATIONS_FK1 FOREIGN KEY
(
CATEGORY_ID
)
REFERENCES KOM_ORGANIZATION_CATEGORIES_T
(
ID
) ENABLE
/