CREATE TABLE KRTST_PARENT_GEN_KEY_T
    ( GENERATED_PK_COL NUMBER(8,0) )
/
CREATE TABLE KRTST_PARENT_GEN_KEY_CHILD_T
    ( GENERATED_PK_COL NUMBER(8,0)
    , CHILDS_PK_COL NUMBER(8,0) )
/
CREATE SEQUENCE KRTST_GENERATED_PK_S START WITH 10000
/
CREATE TABLE KRTST_PARENT_OF_UPDATABLE_T
    ( PK_COL NUMBER(8,0),
    UPDATABLE_CHILD_KEY_COL VARCHAR2(10) )
/
CREATE TABLE KRTST_UPDATABLE_CHILD_T
    ( PK_COL VARCHAR2(10), SOME_DATA_COL VARCHAR2(40) )
/
