CREATE TABLE KRTST_PARENT_GEN_KEY_T
    ( GENERATED_PK_COL DECIMAL(8) )
;
CREATE TABLE KRTST_PARENT_GEN_KEY_CHILD_T
    ( GENERATED_PK_COL DECIMAL(8)
    , CHILDS_PK_COL DECIMAL(8) )
;
CREATE TABLE KRTST_GENERATED_PK_S  ( 
	id	bigint(19) AUTO_INCREMENT NOT NULL,
	PRIMARY KEY(id)
)
ENGINE = MyISAM
AUTO_INCREMENT = 10000
;
CREATE TABLE KRTST_PARENT_OF_UPDATABLE_T
    ( PK_COL DECIMAL(8),
    UPDATABLE_CHILD_KEY_COL VARCHAR(10) )
;
CREATE TABLE KRTST_UPDATABLE_CHILD_T
    ( PK_COL VARCHAR(10), SOME_DATA_COL VARCHAR(40) )
;
