-- Still under discussion - these tables are only referenced by integration tests

-- Having their creation in the appropriate rice-test-tables-*.sql would make them easier
-- to maintain by developers.  (Though 2 copies would need to be maintained.)

DROP TABLE KR_KIM_TEST_BO
/
DROP TABLE ACCT_DD_ATTR_DOC
/
DROP TABLE TST_SEARCH_ATTR_INDX_TST_DOC_T
/
DROP TABLE TRV_MULTI_ATT_SAMPLE
/
DROP TABLE TRV_ATT_SAMPLE
/
DROP TABLE TRV_ACCT_USE_RT_T
/
DROP TABLE TRV_DOC_ACCT
/
DROP TABLE TRVL_PER_DIEM_ID_SEQ
/
DROP TABLE TRVL_PER_DIEM_T
/
DROP TABLE TRVL_TRIP_TYP_T
/
DROP TABLE KRTST_TEST_ANOTHER_REF_OBJ_T
/
DROP TABLE KRTST_TEST_COLL_T
/
DROP TABLE KRTST_TEST_COLL_TWO_T
/
DROP TABLE KRTST_TEST_INDIR_LINK_T
/
DROP TABLE KRTST_TEST_INDIRECT_COLL_T
/
DROP TABLE KRTST_TEST_REF_OBJ_T
/
DROP TABLE KRTST_TEST_TABLE_2_T
/
DROP TABLE KRTST_TEST_TABLE_EXT_T
/
DROP TABLE KRTST_TEST_TABLE_T
/
DROP TABLE KRTST_TEST_YARDO_T
/
