--Create statements for tables, indexes, and sequences--;
CREATE TABLE EN_DOC_NTE_T (
	DOC_NTE_ID                NUMBER(19) NOT NULL,
	DOC_HDR_ID                NUMBER(14) NOT NULL,
	DOC_NTE_AUTH_PRSN_EN_ID   VARCHAR2(30) NOT NULL,
	DOC_NTE_CRT_DT            DATE NOT NULL,
    DOC_NTE_TXT               VARCHAR2(4000),
	DB_LOCK_VER_NBR	          NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_DOC_NTE_T_PK PRIMARY KEY (DOC_NTE_ID)  USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE INDEX EN_DOC_NTE_TI1 ON EN_DOC_NTE_T (DOC_HDR_ID) TABLESPACE EN_IDX01;

CREATE SEQUENCE SEQ_DOC_NTE INCREMENT BY 1 START WITH 2000;

CREATE TABLE EN_RULE_TMPL_OPTN_T (
	RULE_TMPL_OPTN_ID NUMBER(19) NOT NULL,
	RULE_TMPL_ID NUMBER(19) NULL,
	RULE_TMPL_OPTN_KEY VARCHAR2(250) NULL,
	RULE_TMPL_OPTN_VAL VARCHAR2(2000) NULL,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RULE_TMPL_OPTN_T_PK PRIMARY KEY (RULE_TMPL_OPTN_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE SEQUENCE SEQ_RULE_TMPL_OPTN INCREMENT BY 1 START WITH 2000;

CREATE TABLE EN_DOC_HDR_EXT_T (
    DOC_HDR_EXT_ID          NUMBER(19) NOT NULL,
    DOC_HDR_ID              NUMBER(14) NOT NULL,
    DOC_HDR_EXT_VAL_KEY     VARCHAR2(2000) NOT NULL,
    DOC_HDR_EXT_VAL         VARCHAR2(2000) NOT NULL,
    CONSTRAINT EN_DOC_HDR_EXT_T_PK PRIMARY KEY (DOC_HDR_EXT_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE SEQUENCE SEQ_SEARCHABLE_ATTRIBUTE_VALUE INCREMENT BY 1 START WITH 2000;

CREATE TABLE EN_DOC_TYP_ATTRIB_T (
    DOC_TYP_ATTRIB_ID           NUMBER(19) NOT NULL,
    DOC_TYP_ID                  NUMBER(19) NOT NULL,
    RULE_ATTRIB_ID              NUMBER(19) NOT NULL,
    CONSTRAINT EN_DOC_TYP_ATTRIB_T_PK PRIMARY KEY (DOC_TYP_ATTRIB_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE SEQUENCE SEQ_DOCUMENT_TYPE_ATTRIBUTE INCREMENT BY 1 START WITH 2000;

CREATE TABLE EN_HLP_T (
	EN_HLP_ID 			NUMBER(19) NOT NULL,
	EN_HLP_NM     		VARCHAR2(500) NOT NULL,
	EN_HLP_KY			VARCHAR2(500) NOT NULL,
	EN_HLP_TXT       	VARCHAR2(4000) NOT NULL,
	DB_LOCK_VER_NBR	    NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_HLP_T_PK PRIMARY KEY (EN_HLP_ID) USING INDEX TABLESPACE EN_IDX01
) TABLESPACE EN01;

CREATE INDEX EN_HLP_TI1 ON EN_HLP_T (EN_HLP_KY) TABLESPACE EN_IDX01;  

CREATE SEQUENCE SEQ_HELP_ENTRY INCREMENT BY 1 START WITH 100;

--grant privileges to new tables - only needed in production--;
GRANT SELECT ON EN_DOC_NTE_T TO EN_SELECT;
GRANT SELECT ON EN_RULE_TMPL_OPTN_T TO EN_SELECT;
GRANT SELECT ON EN_DOC_HDR_EXT_T TO EN_SELECT;
GRANT SELECT ON EN_DOC_TYP_ATTRIB_T TO EN_SELECT;
GRANT SELECT ON EN_HLP_T TO EN_SELECT;
GRANT SELECT ON EN_ACTN_ITM_T TO EN_SELECT;
GRANT SELECT ON EN_ACTN_RQST_T TO EN_SELECT;
GRANT SELECT ON EN_ACTN_TKN_T TO EN_SELECT;
GRANT SELECT ON EN_DOC_HDR_T TO EN_SELECT;
GRANT SELECT ON EN_DOC_TYP_T TO EN_SELECT;
GRANT SELECT ON EN_DOC_TYP_RTE_LVL_T TO EN_SELECT;
GRANT SELECT ON EN_DOC_TYP_PLCY_RELN_T TO EN_SELECT;
GRANT SELECT ON EN_ORG_RESP_ID_T TO EN_SELECT;
GRANT SELECT ON EN_DOC_RTE_QUE_T TO EN_SELECT;
GRANT SELECT ON EN_DOC_RTE_TYP_T TO EN_SELECT;
GRANT SELECT ON EN_WRKGRP_T TO EN_SELECT;
GRANT SELECT ON EN_WRKGRP_MBR_T TO EN_SELECT;
GRANT SELECT ON EN_USR_OPTN_T TO EN_SELECT;
GRANT SELECT ON EN_APPL_CNST_T TO EN_SELECT;
GRANT SELECT ON EN_USR_T TO EN_SELECT;
GRANT SELECT ON EN_DIRTY_CACHE_T TO EN_SELECT;
GRANT SELECT ON EN_CACHE_SERVER_T TO EN_SELECT;
GRANT SELECT ON EN_RULE_ATTRIB_T TO EN_SELECT;
GRANT SELECT ON EN_RULE_TMPL_T TO EN_SELECT;
GRANT SELECT ON EN_RULE_TMPL_ATTRIB_T TO EN_SELECT;
GRANT SELECT ON EN_RULE_ATTRIB_VLD_VAL_T TO EN_SELECT;
GRANT SELECT ON EN_RULE_ATTRIB_KEY_VAL_T TO EN_SELECT;
GRANT SELECT ON EN_RULE_BASE_VAL_T TO EN_SELECT;
GRANT SELECT ON EN_RULE_RSP_T TO EN_SELECT;
GRANT SELECT ON EN_RULE_EXT_T TO EN_SELECT;
GRANT SELECT ON EN_RULE_EXT_VAL_T TO EN_SELECT;
GRANT SELECT ON EN_DLGN_RSP_T TO EN_SELECT;
GRANT SELECT ON EN_TRANSACTION_TST_PRSN_T TO EN_SELECT;
GRANT SELECT ON EN_TRANSACTION_TST_ADDRS_T TO EN_SELECT;