ALTER TABLE NOTIFICATION_MSG_DELIVS
ADD CONSTRAINT NOTIF_MSG_DELIVS_UK1 UNIQUE
(
NOTIFICATION_ID,
USER_RECIPIENT_ID,
MESSAGE_DELIVERY_TYPE_NAME
)
 ENABLE
/

ALTER TABLE NOTIFICATION_MSG_DELIVS
ADD CONSTRAINT NOTIF_MSG_DELIVS_FK1 FOREIGN KEY
(
NOTIFICATION_ID
)
REFERENCES NOTIFICATIONS
(
ID
) ENABLE
/