ALTER TABLE trv_acct ADD (OBJ_ID VARCHAR2(36))
/
ALTER TABLE trv_acct ADD (VER_NBR NUMBER(8) DEFAULT 0)
/

ALTER TABLE trv_acct_type ADD (OBJ_ID VARCHAR2(36))
/
ALTER TABLE trv_acct_type ADD (VER_NBR NUMBER(8) DEFAULT 0)
/

ALTER TABLE trv_acct_fo ADD (OBJ_ID VARCHAR2(36))
/
ALTER TABLE trv_acct_fo ADD (VER_NBR NUMBER(8) DEFAULT 0)
/

ALTER TABLE trv_acct_ext ADD (OBJ_ID VARCHAR2(36))
/
ALTER TABLE trv_acct_ext ADD (VER_NBR NUMBER(8) DEFAULT 0)
/