ALTER TABLE TRV_ACCT ADD (SUB_ACCT VARCHAR(10))
/
ALTER TABLE TRV_ACCT ADD (SUB_ACCT_NAME VARCHAR(50))
/
ALTER TABLE TRV_ACCT ADD (CREATE_DT DATE)
/
ALTER TABLE TRV_ACCT ADD (SUBSIDIZED_PCT FLOAT)
/