ALTER TABLE KREW_DOC_TYP_T CHANGE SVC_NMSPC APPL_ID VARCHAR(255)
/
ALTER TABLE KREW_RULE_ATTR_T CHANGE SVC_NMSPC APPL_ID VARCHAR(255)
/
ALTER TABLE KRSB_SVC_DEF_T CHANGE APPL_NMSPC APPL_ID VARCHAR(255)
/
ALTER TABLE KRSB_MSG_QUE_T CHANGE SVC_NMSPC APPL_ID VARCHAR(255)
/
ALTER TABLE KRNS_NMSPC_T CHANGE APPL_NMSPC_CD APPL_ID VARCHAR(255)
/
ALTER TABLE KRNS_PARM_T CHANGE APPL_NMSPC_CD APPL_ID VARCHAR(255)
/

RENAME TABLE KRNS_NMSPC_T TO KRCR_NMSPC_T
/
RENAME TABLE KRNS_PARM_TYP_T TO KRCR_PARM_TYP_T
/
RENAME TABLE KRNS_PARM_DTL_TYP_T TO KRCR_PARM_DTL_TYP_T
/
RENAME TABLE KRNS_PARM_T TO KRCR_PARM_T
/

RENAME TABLE KRNS_CAMPUS_T TO KRLC_CMP_T
/
RENAME TABLE KRNS_CMP_TYP_T TO KRLC_CMP_TYP_T
/
RENAME TABLE KR_COUNTRY_T TO KRLC_CNTRY_T
/
RENAME TABLE KR_STATE_T TO KRLC_ST_T
/
RENAME TABLE KR_POSTAL_CODE_T TO KRLC_PSTL_CD_T
/
RENAME TABLE KR_COUNTY_T TO KRLC_CNTY_T
/
