CREATE TABLE KOM_ORGANIZATION_CONTEXT_T (
		ID NUMBER(8) NOT NULL,
		NAME VARCHAR(255) NOT NULL,
		DESCRIPTION VARCHAR(255) NOT NULL,
		CONSTRAINT KOM_ORGANIZATION_CONTEXT_PK PRIMARY KEY (ID)
)
/