CREATE TABLE KOM_ORGANIZATION_T (
		ID NUMBER(8) NOT NULL,
		SHORT_NAME VARCHAR(255) NOT NULL,
		NAME VARCHAR(255) NOT NULL,
		PARENT_ORGANIZATION_ID NUMBER(8),
		CATEGORY_ID NUMBER(8) NOT NULL,
		ACTIVE CHAR(1) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL,
		CONSTRAINT KOM_ORGANIZATION_PK PRIMARY KEY (ID)
)
/