CREATE TABLE EN_ATTACHMENT_T (
	ATTACHMENT_ID				   NUMBER(19) NOT NULL,
	NTE_ID	            	   	   NUMBER(19) NOT NULL,
	FILE_NM			               VARCHAR2(255) NOT NULL,
	FILE_LOC					   VARCHAR2(255) NOT NULL,
	MIME_TYP					   VARCHAR2(255) NOT NULL,
	DB_LOCK_VER_NBR	               NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_ATTACHMENT_T_PK PRIMARY KEY (ATTACHMENT_ID)
)
/