CREATE TABLE EN_BAM_T (
	BAM_ID 				NUMBER(14) NOT NULL,
	SERVICE_NM			VARCHAR2(255) NOT NULL,
	SERVICE_URL			VARCHAR2(500) NOT NULL,
	METHOD_NM			VARCHAR(2000) NOT NULL,
	THREAD_NM			VARCHAR(500) NOT NULL,
	CALL_DT				DATE NOT NULL,
	TARGET_TO_STRING	VARCHAR2(2000) NOT NULL,
	SRVR_IND_IND		NUMBER(1) NOT NULL,
	EXCEPTION_TO_STRING	VARCHAR2(2000),
	EXCEPTION_MSG		CLOB,
	CONSTRAINT EN_BAM_T_PK PRIMARY KEY (BAM_ID)
)
/