CREATE TABLE EN_DOC_TYP_PLCY_RELN_T (
   	DOC_TYP_ID            NUMBER(19) NOT NULL ENABLE,
	DOC_PLCY_NM           VARCHAR2(255) NOT NULL ENABLE,
	DOC_PLCY_VAL          NUMBER(1) NOT NULL ENABLE,
	DB_LOCK_VER_NBR	      NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_DOC_TYP_PLCY_RELN_T_PK PRIMARY KEY (DOC_TYP_ID, DOC_PLCY_NM) USING INDEX
)
/