CREATE TABLE EN_INIT_RTE_NODE_INSTN_T (
	DOC_HDR_ID	            	   	NUMBER(19) NOT NULL,
	RTE_NODE_INSTN_ID             	NUMBER(19) NOT NULL,
	CONSTRAINT EN_INIT_RTE_NODE_INSTN_T_PK PRIMARY KEY (DOC_HDR_ID, RTE_NODE_INSTN_ID) USING INDEX
)
/