CREATE TABLE EN_RTE_BRCH_PROTO_T (
    RTE_BRCH_PROTO_ID			   NUMBER(19) NOT NULL,
    RTE_BRCH_PROTO_NM			   VARCHAR2(255) NOT NULL,
	DB_LOCK_VER_NBR	               NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RTE_BRCH_PROTO_T_PK PRIMARY KEY (RTE_BRCH_PROTO_ID) USING INDEX
)
/