CREATE TABLE EN_RULE_EXT_VAL_T (
	RULE_EXT_VAL_ID NUMBER(19) NOT NULL,
	RULE_EXT_ID NUMBER(19) NOT NULL,
	RULE_EXT_VAL VARCHAR2(2000) NOT NULL,
	RULE_EXT_VAL_KEY VARCHAR2(2000) NOT NULL,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RULE_EXT_VAL_PK PRIMARY KEY (RULE_EXT_VAL_ID)  USING INDEX
)
/