CREATE TABLE EN_RTE_NODE_LNK_T (
	FROM_RTE_NODE_ID        	   NUMBER(19) NOT NULL,
	TO_RTE_NODE_ID          	   NUMBER(19) NOT NULL,
	CONSTRAINT EN_RTE_NODE_LNK_T_PK PRIMARY KEY (FROM_RTE_NODE_ID, TO_RTE_NODE_ID) USING INDEX
)
/