CREATE TABLE EN_RTE_BRCH_T (
    RTE_BRCH_ID					   NUMBER(19) NOT NULL,
    BRCH_NM						   VARCHAR(255) NOT NULL,
    PARNT_RTE_BRCH_ID			   NUMBER(19),
    INIT_RTE_NODE_INSTN_ID		   NUMBER(19) NULL,
    SPLT_RTE_NODE_INSTN_ID		   NUMBER(19),
    JOIN_RTE_NODE_INSTN_ID		   NUMBER(19),
	DB_LOCK_VER_NBR	               NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RTE_BRCH_T_PK PRIMARY KEY (RTE_BRCH_ID) USING INDEX
)
/