CREATE TABLE EN_SERVICE_DEF_INTER_T (
	SERVICE_DEF_INTER_ID		NUMBER(14) NOT NULL,
	SERVICE_DEF_ID			   	   NUMBER(14) NOT NULL,
	SERVICE_INTERFACE 			VARCHAR2(500) NOT NULL,
	DB_LOC_VER_NBR			    NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_SERVICE_DEF_INTER_T_PK PRIMARY KEY (SERVICE_DEF_INTER_ID)
)
/