CREATE TABLE EN_TRANSACTION_TST_PRSN_T (
	PRSN_ID NUMBER(19) NOT NULL,
	FRST_NM VARCHAR2(2000) NOT NULL,
	LST_NM VARCHAR2(2000) NOT NULL,
	EMAIL VARCHAR2(2000),
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_TRANSACTION_TST_PRSN_T_PK PRIMARY KEY (PRSN_ID)  USING INDEX
)
/