INSERT INTO KOM_ORGANIZATION_CATEGORIES_T (ID, NAME) VALUES(1, 'University');
INSERT INTO KOM_ORGANIZATION_CATEGORIES_T (ID, NAME) VALUES(2, 'College');
INSERT INTO KOM_ORGANIZATION_CATEGORIES_T (ID, NAME) VALUES(3, 'Division');
INSERT INTO KOM_ORGANIZATION_CATEGORIES_T (ID, NAME) VALUES(4, 'Admin Department');
INSERT INTO KOM_ORGANIZATION_CATEGORIES_T (ID, NAME) VALUES(5, 'Acad Department');
INSERT INTO KOM_ORGANIZATION_CATEGORIES_T (ID, NAME) VALUES(6, 'Club');

INSERT INTO KOM_ORGANIZATION_CONTEXTS_T (ID, NAME, DESCRIPTION) VALUES (1, 'KFS', 'Kuali Financial Systems');
INSERT INTO KOM_ORGANIZATION_CONTEXTS_T (ID, NAME, DESCRIPTION) VALUES (2, 'KRA', 'Kuali Research Administration');
INSERT INTO KOM_ORGANIZATION_CONTEXTS_T (ID, NAME, DESCRIPTION) VALUES (3, 'KS', 'Kuali Student Services System');
INSERT INTO KOM_ORGANIZATION_CONTEXTS_T (ID, NAME, DESCRIPTION) VALUES (4, 'KEM', 'Kuali Endowment Management');
INSERT INTO KOM_ORGANIZATION_CONTEXTS_T (ID, NAME, DESCRIPTION) VALUES (5, 'HR', 'Human Resources');

INSERT INTO KOM_ORGANIZATIONS_T (ID, SHORT_NAME, NAME, PARENT_ORGANIZATION_ID, CATEGORY_ID, ACTIVE) VALUES (1, 'UC', 'Univ Calif.', null, 1, 'T');
INSERT INTO KOM_ORGANIZATIONS_T (ID, SHORT_NAME, NAME, PARENT_ORGANIZATION_ID, CATEGORY_ID, ACTIVE) VALUES (2, 'UCI', 'Irvine', 1, 1, 'T');
INSERT INTO KOM_ORGANIZATIONS_T (ID, SHORT_NAME, NAME, PARENT_ORGANIZATION_ID, CATEGORY_ID, ACTIVE) VALUES (3, 'UCD', 'Davis', 1, 1, 'T');
INSERT INTO KOM_ORGANIZATIONS_T (ID, SHORT_NAME, NAME, PARENT_ORGANIZATION_ID, CATEGORY_ID, ACTIVE) VALUES (4, 'MTH', 'Dept. of Math', 2, 5, 'T');
INSERT INTO KOM_ORGANIZATIONS_T (ID, SHORT_NAME, NAME, PARENT_ORGANIZATION_ID, CATEGORY_ID, ACTIVE) VALUES (5, 'BSC', 'Business Serivice Center', 3, 4, 'T');

INSERT INTO KOM_ORGANIZATIONS_CONTEXTS_T (ID, ORGANIZATION_ID, CONTEXT_ID, ACTIVE) VALUES (1, 5, 1, 'T');
INSERT INTO KOM_ORGANIZATIONS_CONTEXTS_T (ID, ORGANIZATION_ID, CONTEXT_ID, ACTIVE) VALUES (2, 5, 2, 'T');
INSERT INTO KOM_ORGANIZATIONS_CONTEXTS_T (ID, ORGANIZATION_ID, CONTEXT_ID, ACTIVE) VALUES (3, 4, 2, 'F');
INSERT INTO KOM_ORGANIZATIONS_CONTEXTS_T (ID, ORGANIZATION_ID, CONTEXT_ID, ACTIVE) VALUES (5, 4, 3, 'T');
