INSERT INTO FP_DOC_TYPE_T (FDOC_TYP_CD, FDOC_NM, FDOC_TYP_ACTIVE_CD) VALUES ('KOCD', 'ORGANIZATION CATEGORY', 'Y')
/
INSERT INTO FP_DOC_TYPE_T (FDOC_TYP_CD, FDOC_NM, FDOC_TYP_ACTIVE_CD) VALUES ('KOCT', 'ORGANIZATION CONTEXT', 'Y')
/
INSERT INTO FP_DOC_TYPE_T (FDOC_TYP_CD, FDOC_NM, FDOC_TYP_ACTIVE_CD) VALUES ('KORG', 'ORGANIZATION', 'Y')
/