TRUNCATE TABLE KREW_TYP_ATTR_T DROP STORAGE
/
INSERT INTO KREW_TYP_ATTR_T (ACTV,ATTR_DEFN_ID,SEQ_NO,TYP_ATTR_ID,TYP_ID,VER_NBR)
  VALUES ('Y','1',1,'1','1',1)
/
INSERT INTO KREW_TYP_ATTR_T (ACTV,ATTR_DEFN_ID,SEQ_NO,TYP_ATTR_ID,TYP_ID,VER_NBR)
  VALUES ('Y','2',2,'2','1',1)
/
