TRUNCATE TABLE KRMS_AGENDA_T DROP STORAGE
/
INSERT INTO KRMS_AGENDA_T (ACTV,AGENDA_ID,CNTXT_ID,INIT_AGENDA_ITM_ID,NM,VER_NBR)
  VALUES ('Y','T1000','CONTEXT1','T1000','My Fabulous Agenda',1)
/
INSERT INTO KRMS_AGENDA_T (ACTV,AGENDA_ID,CNTXT_ID,INIT_AGENDA_ITM_ID,NM,TYP_ID,VER_NBR)
  VALUES ('Y','T1001','CONTEXT1','T1007','SimpleAgendaCompoundProp','T1004',1)
/
INSERT INTO KRMS_AGENDA_T (ACTV,AGENDA_ID,CNTXT_ID,INIT_AGENDA_ITM_ID,NM,TYP_ID,VER_NBR)
  VALUES ('Y','T1002','CONTEXT1','T1008','One Big Rule','T1004',1)
/
