TRUNCATE TABLE KRMS_CNTXT_VLD_ACTN_TYP_T DROP STORAGE
/
INSERT INTO KRMS_CNTXT_VLD_ACTN_TYP_T (ACTN_TYP_ID,CNTXT_ID,CNTXT_VLD_ACTN_ID,VER_NBR)
  VALUES ('T1002','CONTEXT1','T1000',1)
/
INSERT INTO KRMS_CNTXT_VLD_ACTN_TYP_T (ACTN_TYP_ID,CNTXT_ID,CNTXT_VLD_ACTN_ID,VER_NBR)
  VALUES ('1000','CONTEXT1','T1001',1)
/
INSERT INTO KRMS_CNTXT_VLD_ACTN_TYP_T (ACTN_TYP_ID,CNTXT_ID,CNTXT_VLD_ACTN_ID,VER_NBR)
  VALUES ('1001','CONTEXT1','T1002',1)
/
INSERT INTO KRMS_CNTXT_VLD_ACTN_TYP_T (ACTN_TYP_ID,CNTXT_ID,CNTXT_VLD_ACTN_ID,VER_NBR)
  VALUES ('1003','CONTEXT1','T1003',1)
/
