--
-- Copyright 2005-2014 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

TRUNCATE TABLE TRAV_DOC_2_ACCOUNTS DROP STORAGE
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2388')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2389')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2390')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2391')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2393')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2396')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2400')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2401')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2402')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2403')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2404')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2405')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2407')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2481')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2482')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2483')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2484')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2500')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2501')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2520')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2521')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2522')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2640')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2692')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2693')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2694')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2695')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a1','2701')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2123')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2387')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2388')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2389')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2390')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2391')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2393')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2396')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2400')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2401')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2402')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2403')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2404')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2405')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2407')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2481')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2482')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2483')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2500')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2501')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2520')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2521')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2522')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a2','2640')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a3','2387')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a3','2480')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a6','2584')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a6','2600')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a6','2601')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a6','2621')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a6','2622')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a6','2623')
/
INSERT INTO TRAV_DOC_2_ACCOUNTS (ACCT_NUM,FDOC_NBR)
  VALUES ('a9','2480')
/
