TRUNCATE TABLE TRV_ACCT_EXT DROP STORAGE
/
INSERT INTO TRV_ACCT_EXT (ACCT_NUM,ACCT_TYPE,VER_NBR)
  VALUES ('a1','IAT',0)
/
INSERT INTO TRV_ACCT_EXT (ACCT_NUM,ACCT_TYPE,VER_NBR)
  VALUES ('a14','CAT',0)
/
INSERT INTO TRV_ACCT_EXT (ACCT_NUM,ACCT_TYPE,VER_NBR)
  VALUES ('a2','EAT',0)
/
INSERT INTO TRV_ACCT_EXT (ACCT_NUM,ACCT_TYPE,VER_NBR)
  VALUES ('a3','IAT',0)
/
INSERT INTO TRV_ACCT_EXT (ACCT_NUM,ACCT_TYPE,VER_NBR)
  VALUES ('a6','CAT',0)
/
INSERT INTO TRV_ACCT_EXT (ACCT_NUM,ACCT_TYPE,VER_NBR)
  VALUES ('a8','EAT',0)
/
INSERT INTO TRV_ACCT_EXT (ACCT_NUM,ACCT_TYPE,VER_NBR)
  VALUES ('a9','CAT',0)
/
