TRUNCATE TABLE TRV_ACCT DROP STORAGE
/
INSERT INTO TRV_ACCT (ACCT_FO_ID,ACCT_NAME,ACCT_NUM,VER_NBR)
  VALUES (1,'a1','a1',0)
/
INSERT INTO TRV_ACCT (ACCT_FO_ID,ACCT_NAME,ACCT_NUM,VER_NBR)
  VALUES (2,'a14','a14',0)
/
INSERT INTO TRV_ACCT (ACCT_FO_ID,ACCT_NAME,ACCT_NUM,VER_NBR)
  VALUES (2,'a2','a2',0)
/
INSERT INTO TRV_ACCT (ACCT_FO_ID,ACCT_NAME,ACCT_NUM,SUB_ACCT,SUB_ACCT_NAME,VER_NBR)
  VALUES (3,'a3','a3','a3-sub','sub-a3',0)
/
INSERT INTO TRV_ACCT (ACCT_FO_ID,ACCT_NAME,ACCT_NUM,SUB_ACCT,SUB_ACCT_NAME,VER_NBR)
  VALUES (2,'a6','a6','a6-sub','sub-a6',0)
/
INSERT INTO TRV_ACCT (ACCT_FO_ID,ACCT_NAME,ACCT_NUM,VER_NBR)
  VALUES (2,'a8','a8',0)
/
INSERT INTO TRV_ACCT (ACCT_FO_ID,ACCT_NAME,ACCT_NUM,VER_NBR)
  VALUES (2,'a9','a9',0)
/
INSERT INTO TRV_ACCT (ACCT_FO_ID,ACCT_NAME,ACCT_NUM,VER_NBR)
  VALUES (1,'a1','a1',0)
/
