TRUNCATE TABLE TRV_ACCT_FO DROP STORAGE
/
INSERT INTO TRV_ACCT_FO (ACCT_FO_ID,ACCT_FO_USER_NAME,VER_NBR)
  VALUES (1,'fred',0)
/
INSERT INTO TRV_ACCT_FO (ACCT_FO_ID,ACCT_FO_USER_NAME,VER_NBR)
  VALUES (2,'fran',0)
/
INSERT INTO TRV_ACCT_FO (ACCT_FO_ID,ACCT_FO_USER_NAME,VER_NBR)
  VALUES (3,'frank',0)
/
