CREATE TABLE EN_RMV_RPLC_DOC_T (
	DOC_HDR_ID			NUMBER(14) NOT NULL,
	OPRN				CHAR(1) NOT NULL,
	PRSN_EN_ID			VARCHAR2(30) NOT NULL,
	RPLC_PRSN_EN_ID     VARCHAR2(30) NULL,
	DB_LOCK_VER_NBR		NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RMV_RPLC_DOC_T_PK PRIMARY KEY (DOC_HDR_ID)
);

CREATE TABLE EN_RMV_RPLC_RULE_T (
	DOC_HDR_ID			NUMBER(14) NOT NULL,
	RULE_ID				NUMBER(19) NOT NULL,
	CONSTRAINT EN_RMV_RPLC_RULE_T_PK PRIMARY KEY (DOC_HDR_ID, RULE_ID)
);

CREATE TABLE EN_RMV_RPLC_WRKGRP_T (
	DOC_HDR_ID			NUMBER(14) NOT NULL,
	WRKGRP_ID			NUMBER(14) NOT NULL,
	CONSTRAINT EN_RMV_RPLC_WRKGRP_T_PK PRIMARY KEY (DOC_HDR_ID, WRKGRP_ID)
);
