/*
 * Copyright 2005-2008 The Kuali Foundation.
 * 
 * Licensed under the Educational Community License, Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.opensource.org/licenses/ecl1.php
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kuali.core.bo.user;

import java.io.Serializable;

import javax.persistence.Column;

import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * This Compound Primary Class has been generated by the rice ojb2jpa Groovy script.  Please
 * note that there are no setter methods, only getters.  This is done purposefully as cpk classes
 * can not change after they have been created.  Also note they require a public no-arg constructor.
 * TODO: Implement the equals() and hashCode() methods. 
 */
public class KualiModuleUserPropertyId implements Serializable {

    private static final long serialVersionUID = 7490519031556403076L;
    
	@Column(name="PERSON_UNVL_ID")
    private String personUniversalIdentifier;
    @Column(name="APPL_MOD_ID")
    private String moduleId;
    @Column(name="USR_PROP_NM")
    private String name;

    public KualiModuleUserPropertyId() {}

    public String getPersonUniversalIdentifier() { return personUniversalIdentifier; }

    public String getModuleId() { return moduleId; }

    public String getName() { return name; }

    public boolean equals(Object o) {
        if (o == this) return true;
        if (!(o instanceof KualiModuleUserPropertyId)) return false;
        if (o == null) return false;
        KualiModuleUserPropertyId pk = (KualiModuleUserPropertyId) o;
        return getPersonUniversalIdentifier() != null && getModuleId() != null && getName() != null && getPersonUniversalIdentifier().equals(pk.getPersonUniversalIdentifier()) && getModuleId().equals(pk.getModuleId()) && getName().equals(pk.getName());        
    }

    public int hashCode() {
    	return new HashCodeBuilder().append(personUniversalIdentifier).append(moduleId).append(name).toHashCode();
    }

}

