CREATE  TABLE TRVL_TRAVELER_TYP_T
  (
    CODE VARCHAR(45) NOT NULL ,
    SRC_CODE VARCHAR(45) NULL ,
    NM VARCHAR(45) NULL ,
    ADVANCES_IND VARCHAR(45) NULL ,
    ACTV_IND VARCHAR(45) NULL ,
    OBJ_ID VARCHAR(45) NULL ,
    VER_NBR DECIMAL(8,0) NULL ,
    CONSTRAINT TRVL_TRAVELER_TYP_T_TC0 UNIQUE (OBJ_ID),
    CONSTRAINT TRVL_TRAVELER_TYP_T_TP1 PRIMARY KEY(CODE)
  )
 /
  insert into TRVL_TRAVELER_TYP_T (CODE, NM, ACTV_IND) values ('NON','NON-Employee','Y')
  /
  Insert into TRVL_TRAVELER_TYP_T (CODE, NM, ACTV_IND) values ('EMP','Employee','Y')
  /
  UPDATE TRVL_TRAVELER_DTL_T SET TRAVELER_TYP_CD='EMP' WHERE ID='1'
  /
