alter table KREW_DOC_HDR_T add column APP_DOC_STATUS varchar(30), add column APP_DOC_STAT_MDFN_DT datetime;
/
create index KREW_DOC_HDR_T10 on KREW_DOC_HDR_T (APP_DOC_STATUS);
/
create index KREW_DOC_HDR_T12 on KREW_DOC_HDR_T (APP_DOC_STAT_MDFN_DT);
/
alter table KREW_DOC_TYP_PLCY_RELN_T add column PLCY_DESC varchar(20)
/
alter table KREW_RTE_NODE_T add column NEXT_DOC_STATUS varchar(30)
/
CREATE TABLE KREW_DOC_TYP_APP_DOC_STAT_T
(
      DOC_TYP_ID DECIMAL(19)
        , DOC_STAT_NM VARCHAR(20)
        , VER_NBR DECIMAL(8) default 0
        , OBJ_ID VARCHAR(36) NOT NULL    
    , CONSTRAINT KREW_DOC_TYP_APP_DOC_STAT_TP1 PRIMARY KEY(DOC_TYP_ID,DOC_STAT_NM)
    , CONSTRAINT KREW_DOC_TYP_APP_DOC_STAT_TC0 UNIQUE (OBJ_ID)
) 
/
create index KREW_DOC_TYP_APP_DOC_STAT_T1 on KREW_DOC_TYP_APP_DOC_STAT_T(DOC_TYP_ID)
/
