ALTER TABLE EN_WRKGRP_TYP_ATTRIB_T ADD CONSTRAINT EN_WRKGRP_TYP_ATTRIB_TR1
FOREIGN KEY (WRKGRP_TYP_ID)
REFERENCES EN_WRKGRP_TYP_T (WRKGRP_TYP_ID)
/

ALTER TABLE EN_WRKGRP_TYP_ATTRIB_T ADD CONSTRAINT EN_WRKGRP_TYP_ATTRIB_TR2
FOREIGN KEY (ATTRIB_ID)
REFERENCES EN_RULE_ATTRIB_T (RULE_ATTRIB_ID)
/
