ALTER TABLE EN_RULE_BASE_VAL_T ADD RULE_NM VARCHAR2(256) NULL
/

ALTER TABLE EN_DOC_TYP_T ADD DOC_TYP_SECURITY_XML CLOB
/

CREATE TABLE EN_DOC_HDR_CNTNT_T (
	DOC_HDR_ID 			    NUMBER(14) NOT NULL,
	DOC_CNTNT_TXT			CLOB NULL,
	CONSTRAINT EN_DOC_HDR_T_CNTNT_PK PRIMARY KEY (DOC_HDR_ID)
)

/

INSERT INTO EN_DOC_HDR_CNTNT_T SELECT DOC_HDR_ID, TO_LOB(DOC_CNTNT_TXT) FROM EN_DOC_HDR_T

/

ALTER TABLE EN_RULE_ATTRIB_T MODIFY ( RULE_ATTRIB_XML_RTE_TXT CLOB )

/

ALTER INDEX EN_RULE_ATTRIB_PK REBUILD

/

ALTER TABLE EN_MESSAGE_QUE_T MODIFY ( MESSAGE_PAYLOAD CLOB )

/

ALTER INDEX EN_MESSAGE_QUE_T_PK REBUILD

/

ALTER TABLE EN_BAM_T MODIFY ( EXCEPTION_MSG CLOB )

/

ALTER INDEX EN_BAM_T_PK REBUILD

/

ALTER TABLE EN_BAM_PARAM_T MODIFY ( PARAM CLOB )

/

ALTER INDEX EN_BAM_PARAM_T_PK REBUILD
 /

ALTER TABLE EN_RTE_BRCH_T MODIFY ( INIT_RTE_NODE_INSTN_ID NUMBER(19) NULL )

/

ALTER TABLE EN_DOC_HDR_T DROP COLUMN DOC_CNTNT_TXT

/

ALTER TABLE EN_DOC_TYP_T ADD DOC_TYP_EMAIL_XSL VARCHAR2(255)

/

ALTER TABLE EN_DOC_TYP_T ADD BLNKT_APPR_PLCY VARCHAR2(10)

/

CREATE TABLE EN_SERVICE_DEF_DUEX_T (
	SERVICE_DEF_ID			   	   NUMBER(14) NOT NULL,
	SERVICE_NM				   	   VARCHAR2(255) NOT NULL,
    SERVICE_URL	            	   VARCHAR2(500) NOT NULL,
	SERVER_IP					   VARCHAR2(40) NOT NULL,
	MESSAGE_ENTITY_NM 		  	   VARCHAR2(10) NOT NULL,
	SERVICE_ALIVE				   NUMBER(1) NOT NULL,
	SERVICE_DEFINITION 		       CLOB NOT NULL,
	DB_LOCK_VER_NBR	               NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_SERVICE_DEF_DUEX_T_PK PRIMARY KEY (SERVICE_DEF_ID)
)

/

CREATE INDEX EN_SERVICE_DEF_DUEX_TI1 ON EN_SERVICE_DEF_DUEX_T (SERVER_IP, MESSAGE_ENTITY_NM)

/
