CREATE OR REPLACE VIEW kr_kim_perm_v AS
SELECT 
	  KR_KIM_PERM_TMPL_T.NAME AS PERM_TEMPLATE_NAME
    , KR_KIM_PERM_T.NAME      AS PERM_NAME
	, KR_KIM_TYPE_T.TYPE_NM   AS PERM_TYPE_NAME 
	, KR_KIM_TYPE_T.SRVC_NM   AS PERM_TYPE_SERVICE_NAME
FROM KR_KIM_PERM_T KR_KIM_PERM_T 
		INNER JOIN KR_KIM_PERM_TMPL_T KR_KIM_PERM_TMPL_T 
		ON KR_KIM_PERM_T.PERM_TMPL_ID = KR_KIM_PERM_TMPL_T.PERM_TMPL_ID 
			INNER JOIN KR_KIM_TYPE_T KR_KIM_TYPE_T 
			ON KR_KIM_PERM_TMPL_T.KIM_TYPE_ID = KR_KIM_TYPE_T.KIM_TYPE_ID
/
CREATE OR REPLACE VIEW kr_kim_perm_attrib_v AS
SELECT 
	  KR_KIM_PERM_TMPL_T.NAME AS PERM_TEMPLATE_NAME
    , KR_KIM_PERM_T.NAME      AS PERM_NAME
	, KR_KIM_PERM_ATTR_DATA_T.ATTRIB_VAL
	, KR_KIM_ATTRIBUTE_T.ATTRIB_NM 
FROM KR_KIM_PERM_T KR_KIM_PERM_T 
		INNER JOIN KR_KIM_PERM_ATTR_DATA_T KR_KIM_PERM_ATTR_DATA_T 
		ON KR_KIM_PERM_T.PERM_ID = KR_KIM_PERM_ATTR_DATA_T.TARGET_PRIMARY_KEY 
			INNER JOIN KR_KIM_ATTRIBUTE_T KR_KIM_ATTRIBUTE_T 
			ON KR_KIM_PERM_ATTR_DATA_T.KIM_ATTRIB_ID = KR_KIM_ATTRIBUTE_T.KIM_ATTRIB_ID 
				INNER JOIN KR_KIM_PERM_TMPL_T KR_KIM_PERM_TMPL_T 
				ON KR_KIM_PERM_T.PERM_TMPL_ID = KR_KIM_PERM_TMPL_T.PERM_TMPL_ID 
					INNER JOIN KR_KIM_TYPE_T KR_KIM_TYPE_T 
					ON KR_KIM_PERM_TMPL_T.KIM_TYPE_ID = KR_KIM_TYPE_T.KIM_TYPE_ID
/
CREATE OR REPLACE VIEW kr_kim_role_perm_v AS
SELECT KR_KIM_ROLE_T.NMSPC_CD             AS role_namespace
	, KR_KIM_ROLE_T.ROLE_NM              AS role_name
	, KR_KIM_TYPE_T.TYPE_NM              AS role_type_name
	, KR_KIM_PERM_TMPL_T.NAME            AS perm_template_name
	, KR_KIM_PERM_T.NAME                 AS perm_name
	, KR_KIM_ATTRIBUTE_T.ATTRIB_NM       AS attribute_name
	, KR_KIM_PERM_ATTR_DATA_T.ATTRIB_VAL AS attribute_value
FROM KR_KIM_PERM_T KR_KIM_PERM_T
		INNER JOIN KR_KIM_PERM_TMPL_T KR_KIM_PERM_TMPL_T
		ON KR_KIM_PERM_T.PERM_TMPL_ID = KR_KIM_PERM_TMPL_T.PERM_TMPL_ID
			LEFT OUTER JOIN KR_KIM_PERM_ATTR_DATA_T KR_KIM_PERM_ATTR_DATA_T
			ON KR_KIM_PERM_T.PERM_ID = KR_KIM_PERM_ATTR_DATA_T.TARGET_PRIMARY_KEY
				INNER JOIN KR_KIM_ATTRIBUTE_T KR_KIM_ATTRIBUTE_T
				ON KR_KIM_PERM_ATTR_DATA_T.KIM_ATTRIB_ID = KR_KIM_ATTRIBUTE_T.KIM_ATTRIB_ID
					INNER JOIN KR_KIM_ROLE_PERM_T KR_KIM_ROLE_PERM_T
					ON KR_KIM_ROLE_PERM_T.PERM_ID = KR_KIM_PERM_T.PERM_ID
						RIGHT OUTER JOIN KR_KIM_ROLE_T KR_KIM_ROLE_T
						ON KR_KIM_ROLE_PERM_T.ROLE_ID = KR_KIM_ROLE_T.ROLE_ID
							LEFT OUTER JOIN KR_KIM_TYPE_T KR_KIM_TYPE_T
							ON KR_KIM_ROLE_T.TYP_ID = KR_KIM_TYPE_T.KIM_TYPE_ID
						ORDER BY KR_KIM_ROLE_T.NMSPC_CD
							, KR_KIM_ROLE_T.ROLE_NM
							, KR_KIM_TYPE_T.TYPE_NM
							, KR_KIM_PERM_T.PERM_ID
							, KR_KIM_PERM_TMPL_T.NAME
							, KR_KIM_PERM_T.NAME
/
CREATE OR REPLACE VIEW kr_kim_role_principal_v AS
SELECT KR_KIM_ROLE_T.NMSPC_CD                 AS namespace_code
	, KR_KIM_ROLE_T.ROLE_NM                  AS role_name
	, KR_KIM_ATTRIBUTE_T.ATTRIB_NM           AS qualifier_name
	, KR_KIM_ROLE_MBR_ATTR_DATA_T.ATTRIB_VAL AS qualifier_value
	, KR_KIM_PRINCIPAL_T.PRNCPL_NM           AS principal_name
	, KR_KIM_ENTITY_NAME_T.FIRST_NM
	, KR_KIM_ENTITY_NAME_T.LAST_NM 
FROM KR_KIM_ROLE_T KR_KIM_ROLE_T 
		LEFT OUTER JOIN KR_KIM_ROLE_PRINCIPAL_T KR_KIM_ROLE_PRINCIPAL_T 
		ON KR_KIM_ROLE_T.ROLE_ID = KR_KIM_ROLE_PRINCIPAL_T.ROLE_ID 
			LEFT OUTER JOIN KR_KIM_ROLE_MBR_ATTR_DATA_T KR_KIM_ROLE_MBR_ATTR_DATA_T 
			ON KR_KIM_ROLE_PRINCIPAL_T.ROLE_MEMBER_ID = KR_KIM_ROLE_MBR_ATTR_DATA_T.
			TARGET_PRIMARY_KEY 
				LEFT OUTER JOIN KR_KIM_ATTRIBUTE_T KR_KIM_ATTRIBUTE_T 
				ON KR_KIM_ROLE_MBR_ATTR_DATA_T.KIM_ATTRIB_ID = KR_KIM_ATTRIBUTE_T.
				KIM_ATTRIB_ID 
					LEFT OUTER JOIN KR_KIM_PRINCIPAL_T KR_KIM_PRINCIPAL_T 
					ON KR_KIM_ROLE_PRINCIPAL_T.PRNCPL_ID = KR_KIM_PRINCIPAL_T.PRNCPL_ID 
						LEFT OUTER JOIN KR_KIM_ENTITY_NAME_T KR_KIM_ENTITY_NAME_T 
						ON KR_KIM_PRINCIPAL_T.ENTITY_ID = KR_KIM_ENTITY_NAME_T.ENTITY_ID 
WHERE (KR_KIM_ENTITY_NAME_T.DFLT_IND = 'Y')
/
CREATE OR REPLACE VIEW kr_kim_role_group_v AS
SELECT KR_KIM_ROLE_T.NMSPC_CD                 AS namespace_code
	, KR_KIM_ROLE_T.ROLE_NM                  AS role_name
	, KR_KIM_GROUP_T.NMSPC_CD                AS group_namespace
	, KR_KIM_GROUP_T.GRP_NM                  AS group_name
	, KR_KIM_ATTRIBUTE_T.ATTRIB_NM           AS qualifier_name
	, KR_KIM_ROLE_MBR_ATTR_DATA_T.ATTRIB_VAL AS qualifier_value 
FROM KR_KIM_ROLE_MBR_ATTR_DATA_T KR_KIM_ROLE_MBR_ATTR_DATA_T 
		RIGHT OUTER JOIN KR_KIM_ROLE_GROUP_T KR_KIM_ROLE_GROUP_T 
		ON KR_KIM_ROLE_MBR_ATTR_DATA_T.TARGET_PRIMARY_KEY = KR_KIM_ROLE_GROUP_T.
		ROLE_MEMBER_ID 
			LEFT OUTER JOIN KR_KIM_ATTRIBUTE_T KR_KIM_ATTRIBUTE_T 
			ON KR_KIM_ROLE_MBR_ATTR_DATA_T.KIM_ATTRIB_ID = KR_KIM_ATTRIBUTE_T.KIM_ATTRIB_ID 
				LEFT OUTER JOIN KR_KIM_ROLE_T KR_KIM_ROLE_T 
				ON KR_KIM_ROLE_T.ROLE_ID = KR_KIM_ROLE_GROUP_T.ROLE_ID 
					INNER JOIN KR_KIM_GROUP_T KR_KIM_GROUP_T 
					ON KR_KIM_ROLE_GROUP_T.GRP_ID = KR_KIM_GROUP_T.GRP_ID
/
CREATE OR REPLACE VIEW kr_kim_principal_v AS
SELECT 
	  KR_KIM_PRINCIPAL_T.PRNCPL_ID
    , KR_KIM_PRINCIPAL_T.PRNCPL_NM AS principal_name
	, KR_KIM_ENTITY_NAME_T.FIRST_NM
	, KR_KIM_ENTITY_NAME_T.LAST_NM
	, KR_KIM_ENTITY_AFLTN_T.AFLTN_TYP_CD
	, KR_KIM_ENTITY_AFLTN_T.CAMPUS_CD
	, KR_KIM_ENTITY_EMP_INFO_T.EMP_STAT_CD
	, KR_KIM_ENTITY_EMP_INFO_T.EMP_TYP_CD 
FROM KR_KIM_ENTITY_AFLTN_T KR_KIM_ENTITY_AFLTN_T 
		RIGHT OUTER JOIN KR_KIM_PRINCIPAL_T KR_KIM_PRINCIPAL_T 
		ON KR_KIM_ENTITY_AFLTN_T.ENTITY_ID = KR_KIM_PRINCIPAL_T.ENTITY_ID 
			RIGHT OUTER JOIN KR_KIM_ENTITY_EMP_INFO_T KR_KIM_ENTITY_EMP_INFO_T 
			ON KR_KIM_ENTITY_EMP_INFO_T.ENTITY_ID = KR_KIM_PRINCIPAL_T.ENTITY_ID 
				LEFT OUTER JOIN KR_KIM_ENTITY_NAME_T KR_KIM_ENTITY_NAME_T 
				ON KR_KIM_PRINCIPAL_T.ENTITY_ID = KR_KIM_ENTITY_NAME_T.ENTITY_ID 
WHERE (KR_KIM_ENTITY_NAME_T.DFLT_IND = 'Y') 
/



