DECLARE
    CURSOR constraint_cursor IS
        SELECT table_name, constraint_name
            FROM user_constraints
            WHERE constraint_type = 'R'
              AND table_name LIKE 'KRIM\_%' ESCAPE '\'; --'
    CURSOR tbls IS 
        SELECT table_name FROM user_tables
            WHERE table_name LIKE 'KRIM\_%' ESCAPE '\'; --'
BEGIN
    FOR r IN constraint_cursor LOOP
        dbms_output.put_line( 'Disabling Constraint: '||r.constraint_name );
        execute immediate 'ALTER TABLE '||r.table_name||' DISABLE CONSTRAINT '||r.constraint_name;
    END LOOP;

    FOR r IN tbls LOOP
        dbms_output.put_line( 'Emptying Table: '||r.table_name );
        EXECUTE IMMEDIATE 'DELETE FROM '||r.table_name;
    END LOOP;

    FOR r IN constraint_cursor LOOP
        dbms_output.put_line( 'Re-Enabling Constraint: '||r.constraint_name );
        execute immediate 'ALTER TABLE '||r.table_name||' ENABLE CONSTRAINT '||r.constraint_name;
    END LOOP;
END;
/

INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','1','Default','KUALI',SYS_GUID(),1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','10','Namespace or Component','KR-KNS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','11','Component Field','KR-KNS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','12','Namespace or Action','KR-KNS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','13','Button','KR-KNS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','14','Edit Mode','KR-KNS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','15','Batch Feed or Job','KR-KNS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','16','Parameter','KR-KNS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','17','Campus','KR-KNS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','18','Role','KR-KIM',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','19','Permission','KR-KIM',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','2','Derived Role: Principal','KR-KIM',SYS_GUID(),'activePrincipalRoleTypeService',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','20','Responsibility','KR-KIM',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','21','Group','KR-KIM',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','22','Entity Type','KR-KIM',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','23','Contracts & Grants Responsibility','KFS-CG',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','24','Research Risk Review','KFS-CG',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','25','Chart','KFS-COA',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','26','Account','KFS-COA',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','27','Organization','KFS-COA',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','28','Organization Hierarchy Security','KFS-SYS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','29','Organization Review','KFS-SYS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','3','Document Type','KR-KEW',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','30','Organization Accounting Review','KFS-SYS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','31','Sub-Fund Review','KFS-COA',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','32','Customer','KFS-PDP',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','33','Commodity Review','KFS-VND',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','34','Contract Manager','KFS-VND',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','35','Sensitive Data','KFS-PURAP',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','36','Module & Organization','KFS-SYS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','37','Vendor Type','KFS-VND',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','38','Derived Role: Accounts Receivable Organization','KFS-AR',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','39','Derived Role: Account','KFS-COA',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','4','Action Request Type','KR-KEW',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','40','Derived Role: Chart','KFS-COA',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','41','Derived Role: Employee','KFS-SYS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','42','Derived Role: Action Request','KR-KEW',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','43','Derived Role: Route Log','KR-KEW',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','44','Namespace','KR-SYS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','45','Derived Role: Permission','KR-KNS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','5','Document Type & Action Request Type','KR-KEW',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','6','Document Type & Existing Records Only','KR-SYS',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','7','Document Type & Routing Node','KR-KEW',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','8','Document Type & Routing Node or State','KR-KEW',SYS_GUID(),'to be filled in by implementing developer',1)
/
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR)
  VALUES ('Y','9','Document Collection','KR-KNS',SYS_GUID(),'to be filled in by implementing developer',1)
/
COMMIT
/









INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','1','Bean Name','beanName','KR-SYS',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','10','Edit Mode','editMode','KR-KNS',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.rice.kns.bo.Parameter','11','parameterName','KR-KNS',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.rice.kns.bo.Campus','12','campusCode','KR-KNS',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.rice.kew.doctype.bo.DocumentType','13','name','KR-KEW',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.rice.kew.doctype.bo.ActionItem','14','actionRequestCd','KR-KEW',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.rice.kew.doctype.bo.DocumentRouteHeaderValue','15','docRouteStatus','KR-KEW',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','16','Route Node Name','routeNodeName','KR-KEW',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.rice.kim.bo.entity.impl.EntityEntityTypeImpl','17','entityTypeCode','KR-KIM',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.rice.kim.bo.role.impl.KimRoleImpl','18','roleName','KR-KIM',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.rice.kim.bo.role.impl.KimPermissionImpl','19','name','KR-KIM',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','2','Action Class','actionClass','KR-SYS',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.rice.kim.bo.role.impl.KimResponsibilityImpl','20','name','KR-KIM',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.rice.kim.bo.group.impl.KimGroupImpl','21','groupName','KR-KIM',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','3','Method to Call','methodToCall','KR-SYS',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.rice.kns.bo.ParameterNamespace','4','parameterNamespaceCode','KR-KNS',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.rice.kns.bo.ParameterDetailType','5','parameterDetailTypeCode','KR-KNS',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','6','Property Name','propertyName','KR-KNS',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','7','Existing Records Only?','existingRecordsOnly','KR-KNS',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','8','Created By Self Only?','createdBySelfOnly','KR-KNS',SYS_GUID(),1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','9','Collection Item Type Code','collectionItemTypeCode','KR-KNS',SYS_GUID(),1)
/
COMMIT
/







INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','13','1','3',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','15','10','8',SYS_GUID(),'c',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','16','11','8',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','13','12','9',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','8','13','9',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','9','14','9',SYS_GUID(),'c',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','4','15','10',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','5','16','10',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','5','17','11',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','6','18','11',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','4','19','12',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','14','2','4',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','2','20','12',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','3','21','13',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','10','22','14',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','4','23','15',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','1','24','15',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','4','25','16',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','5','26','16',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','11','27','16',SYS_GUID(),'c',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','12','28','17',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','4','29','18',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','13','3','5',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','18','30','18',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','4','31','19',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','19','32','19',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','4','33','20',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','20','34','20',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','4','35','21',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','21','36','21',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','17','37','22',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','14','4','5',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','13','5','6',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','13','50','29',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','13','53','30',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','7','6','6',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','4','62','36',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','4','66','44',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','12','67','33',SYS_GUID(),'c',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','13','68','24',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','13','69','31',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','13','7','7',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','13','70','33',SYS_GUID(),'a',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','5','71','22',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','6','72','22',SYS_GUID(),'c',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','16','8','7',SYS_GUID(),'b',1)
/
INSERT INTO KRIM_TYP_ATTR_T (ACTV_IND,KIM_ATTR_DEFN_ID,KIM_TYP_ATTR_ID,KIM_TYP_ID,OBJ_ID,SORT_CD,VER_NBR)
  VALUES ('Y','13','9','8',SYS_GUID(),'a',1)
/
COMMIT
/





INSERT INTO KRIM_ADDR_TYP_T (ACTV_IND,ADDR_TYP_CD,DISPLAY_SORT_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','HM','b',SYSDATE,'Home',SYS_GUID(),1)
/
INSERT INTO KRIM_ADDR_TYP_T (ACTV_IND,ADDR_TYP_CD,DISPLAY_SORT_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','OTH','c',SYSDATE,'Other',SYS_GUID(),1)
/
INSERT INTO KRIM_ADDR_TYP_T (ACTV_IND,ADDR_TYP_CD,DISPLAY_SORT_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','WRK','a',SYSDATE,'Work',SYS_GUID(),1)
/
INSERT INTO KRIM_AFLTN_TYP_T (ACTV_IND,AFLTN_TYP_CD,DISPLAY_SORT_CD,EMP_AFLTN_TYP_IND,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','AFLT','d','N',SYSDATE,'Affiliate',SYS_GUID(),1)
/
INSERT INTO KRIM_AFLTN_TYP_T (ACTV_IND,AFLTN_TYP_CD,DISPLAY_SORT_CD,EMP_AFLTN_TYP_IND,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','FCLTY','b','Y',SYSDATE,'Faculty',SYS_GUID(),1)
/
INSERT INTO KRIM_AFLTN_TYP_T (ACTV_IND,AFLTN_TYP_CD,DISPLAY_SORT_CD,EMP_AFLTN_TYP_IND,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','STAFF','c','Y',SYSDATE,'Staff',SYS_GUID(),1)
/
INSERT INTO KRIM_AFLTN_TYP_T (ACTV_IND,AFLTN_TYP_CD,DISPLAY_SORT_CD,EMP_AFLTN_TYP_IND,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','STDNT','a','N',SYSDATE,'Student',SYS_GUID(),1)
/
INSERT INTO KRIM_EMAIL_TYP_T (ACTV_IND,DISPLAY_SORT_CD,EMAIL_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','b','HM',SYSDATE,'Home',SYS_GUID(),1)
/
INSERT INTO KRIM_EMAIL_TYP_T (ACTV_IND,DISPLAY_SORT_CD,EMAIL_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','c','OTH',SYSDATE,'Other',SYS_GUID(),1)
/
INSERT INTO KRIM_EMAIL_TYP_T (ACTV_IND,DISPLAY_SORT_CD,EMAIL_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','a','WRK',SYSDATE,'Work',SYS_GUID(),1)
/
INSERT INTO KRIM_EMP_STAT_T (ACTV_IND,DISPLAY_SORT_CD,EMP_STAT_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','01','A',SYSDATE,'Active',SYS_GUID(),1)
/
INSERT INTO KRIM_EMP_STAT_T (ACTV_IND,DISPLAY_SORT_CD,EMP_STAT_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','99','D',SYSDATE,'Deceased',SYS_GUID(),1)
/
INSERT INTO KRIM_EMP_STAT_T (ACTV_IND,DISPLAY_SORT_CD,EMP_STAT_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','04','L',SYSDATE,'On Non-Pay Leave',SYS_GUID(),1)
/
INSERT INTO KRIM_EMP_STAT_T (ACTV_IND,DISPLAY_SORT_CD,EMP_STAT_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','03','N',SYSDATE,'Status Not Yet Processed',SYS_GUID(),1)
/
INSERT INTO KRIM_EMP_STAT_T (ACTV_IND,DISPLAY_SORT_CD,EMP_STAT_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','02','P',SYSDATE,'Processing',SYS_GUID(),1)
/
INSERT INTO KRIM_EMP_STAT_T (ACTV_IND,DISPLAY_SORT_CD,EMP_STAT_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','10','R',SYSDATE,'Retired',SYS_GUID(),1)
/
INSERT INTO KRIM_EMP_STAT_T (ACTV_IND,DISPLAY_SORT_CD,EMP_STAT_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','97','T',SYSDATE,'Terminated',SYS_GUID(),1)
/
INSERT INTO KRIM_EMP_STAT_T (ACTV_IND,DISPLAY_SORT_CD,EMP_STAT_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','11','X',SYSDATE,'Retired 2',SYS_GUID(),1)
/
INSERT INTO KRIM_EMP_TYP_T (ACTV_IND,DISPLAY_SORT_CD,EMP_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','02','N',sysdate,'Non-Professional',SYS_GUID(),1)
/
INSERT INTO KRIM_EMP_TYP_T (ACTV_IND,DISPLAY_SORT_CD,EMP_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','99','O',SYSDATE,'Other',SYS_GUID(),1)
/
INSERT INTO KRIM_EMP_TYP_T (ACTV_IND,DISPLAY_SORT_CD,EMP_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','01','P',SYSDATE,'Professional',SYS_GUID(),1)
/
INSERT INTO KRIM_ENT_NM_TYP_T (ACTV_IND,DISPLAY_SORT_CD,ENT_NM_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','c','OTH',sysdate,'Other',SYS_GUID(),1)
/
INSERT INTO KRIM_ENT_NM_TYP_T (ACTV_IND,DISPLAY_SORT_CD,ENT_NM_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','b','PRFR',SYSDATE,'Preferred',SYS_GUID(),1)
/
INSERT INTO KRIM_ENT_NM_TYP_T (ACTV_IND,DISPLAY_SORT_CD,ENT_NM_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','a','PRM',SYSDATE,'Primary',SYS_GUID(),1)
/
INSERT INTO KRIM_ENT_TYP_T (ACTV_IND,DISPLAY_SORT_CD,ENT_TYP_CD,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','01','PERSON','Person',SYS_GUID(),1)
/
INSERT INTO KRIM_ENT_TYP_T (ACTV_IND,DISPLAY_SORT_CD,ENT_TYP_CD,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','02','SYSTEM','System',SYS_GUID(),1)
/
INSERT INTO KRIM_EXT_ID_TYP_T (ACTV_IND,DISPLAY_SORT_CD,ENCR_REQ_IND,EXT_ID_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','05','N','HR',SYSDATE,'Human Resources ID',SYS_GUID(),1)
/
INSERT INTO KRIM_EXT_ID_TYP_T (ACTV_IND,DISPLAY_SORT_CD,ENCR_REQ_IND,EXT_ID_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','06','N','LICENSE',SYSDATE,'Driver''s License',SYS_GUID(),1)
/
INSERT INTO KRIM_EXT_ID_TYP_T (ACTV_IND,DISPLAY_SORT_CD,ENCR_REQ_IND,EXT_ID_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','01','N','LOGON',SYSDATE,'Logon ID',SYS_GUID(),1)
/
INSERT INTO KRIM_EXT_ID_TYP_T (ACTV_IND,DISPLAY_SORT_CD,ENCR_REQ_IND,EXT_ID_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','07','N','RFID',SYSDATE,'RFID Implant',SYS_GUID(),1)
/
INSERT INTO KRIM_EXT_ID_TYP_T (ACTV_IND,DISPLAY_SORT_CD,ENCR_REQ_IND,EXT_ID_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','02','Y','SSN',SYSDATE,'Social Security Number',SYS_GUID(),1)
/
INSERT INTO KRIM_EXT_ID_TYP_T (ACTV_IND,DISPLAY_SORT_CD,ENCR_REQ_IND,EXT_ID_TYP_CD,LAST_UPDT_DT,NM,OBJ_ID,VER_NBR)
  VALUES ('Y','03','Y','TAX',SYSDATE,'Tax ID',SYS_GUID(),1)
/
INSERT INTO KRIM_PHONE_TYP_T (ACTV_IND,DISPLAY_SORT_CD,LAST_UPDT_DT,OBJ_ID,PHONE_TYP_CD,PHONE_TYP_NM,VER_NBR)
  VALUES ('Y','b',SYSDATE,SYS_GUID(),'HM','Home',1)
/
INSERT INTO KRIM_PHONE_TYP_T (ACTV_IND,DISPLAY_SORT_CD,LAST_UPDT_DT,OBJ_ID,PHONE_TYP_CD,PHONE_TYP_NM,VER_NBR)
  VALUES ('Y','c',SYSDATE,SYS_GUID(),'MBL','Mobile',1)
/
INSERT INTO KRIM_PHONE_TYP_T (ACTV_IND,DISPLAY_SORT_CD,LAST_UPDT_DT,OBJ_ID,PHONE_TYP_CD,PHONE_TYP_NM,VER_NBR)
  VALUES ('Y','d',SYSDATE,SYS_GUID(),'OTH','Other',1)
/
INSERT INTO KRIM_PHONE_TYP_T (ACTV_IND,DISPLAY_SORT_CD,LAST_UPDT_DT,OBJ_ID,PHONE_TYP_CD,PHONE_TYP_NM,VER_NBR)
  VALUES ('Y','a',SYSDATE,SYS_GUID(),'WRK','Work',1)
/
COMMIT
/




INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1100',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1101',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1102',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1103',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1104',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1105',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1106',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1107',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1108',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1109',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1110',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1111',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1112',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1113',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1114',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1115',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1116',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1117',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1118',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1119',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1120',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1121',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1122',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1123',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1124',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1125',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1126',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1127',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1128',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1129',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1130',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1131',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1132',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1133',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1134',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1135',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1136',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1137',SYSDATE,SYS_GUID(),1)
/
COMMIT
/







INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1136',SYSDATE,SYS_GUID(),'KULUSER','kuluser',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1131',SYSDATE,SYS_GUID(),'NotSys','NotSys',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1132',SYSDATE,SYS_GUID(),'NotSysAdm','NotSysAdm',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1101',SYSDATE,SYS_GUID(),'TestAdmin1','TestAdmin1',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1102',SYSDATE,SYS_GUID(),'TestAdmin2','TestAdmin2',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1103',SYSDATE,SYS_GUID(),'TestUser1','TestUser1',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1104',SYSDATE,SYS_GUID(),'TestUser2','TestUser2',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1105',SYSDATE,SYS_GUID(),'TestUser3','TestUser3',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1106',SYSDATE,SYS_GUID(),'TestUser4','TestUser4',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1107',SYSDATE,SYS_GUID(),'TestUser5','TestUser5',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1108',SYSDATE,SYS_GUID(),'TestUser6','TestUser6',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1100',SYSDATE,SYS_GUID(),'admin','admin',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1125',SYSDATE,SYS_GUID(),'admin1','admin1',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1126',SYSDATE,SYS_GUID(),'admin2','admin2',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1129',SYSDATE,SYS_GUID(),'dev1','dev1',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1130',SYSDATE,SYS_GUID(),'dev2','dev2',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1135',SYSDATE,SYS_GUID(),'director','director',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1121',SYSDATE,SYS_GUID(),'doug','doug',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1116',SYSDATE,SYS_GUID(),'earl','earl',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1114',SYSDATE,SYS_GUID(),'edna','edna',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1137',SYSDATE,SYS_GUID(),'employee','employee',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1115',SYSDATE,SYS_GUID(),'eric','eric',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1117',SYSDATE,SYS_GUID(),'erin','erin',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1119',SYSDATE,SYS_GUID(),'fran','fran',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1120',SYSDATE,SYS_GUID(),'frank','frank',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1118',SYSDATE,SYS_GUID(),'fred','fred',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1122',SYSDATE,SYS_GUID(),'idm1','idm1',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1123',SYSDATE,SYS_GUID(),'idm2','idm2',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1124',SYSDATE,SYS_GUID(),'idm3','idm3',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1133',SYSDATE,SYS_GUID(),'newAccountUser','newAcctUsr',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1109',SYSDATE,SYS_GUID(),'quickstart','quickstart',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1134',SYSDATE,SYS_GUID(),'supervisor','supervisr',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1127',SYSDATE,SYS_GUID(),'test1','test1',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1128',SYSDATE,SYS_GUID(),'test2','test2',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1110',SYSDATE,SYS_GUID(),'user1','user1',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1111',SYSDATE,SYS_GUID(),'user2','user2',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1112',SYSDATE,SYS_GUID(),'user3','user3',1)
/
INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,VER_NBR)
  VALUES ('Y','1113',SYSDATE,SYS_GUID(),'user4','user4',1)
/
COMMIT
/






TRUNCATE TABLE KRIM_ENTITY_ENT_TYP_T DROP STORAGE
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1200','1100','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1201','1101','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1202','1102','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1203','1103','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1204','1104','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1205','1105','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1206','1106','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1207','1107','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1208','1108','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1209','1109','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1210','1110','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1211','1111','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1212','1112','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1213','1113','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1214','1114','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1215','1115','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1216','1116','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1217','1117','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1218','1118','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1219','1119','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1220','1120','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1221','1121','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1222','1122','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1223','1123','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1224','1124','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1225','1125','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1226','1126','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1227','1127','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1228','1128','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1229','1129','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1230','1130','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1231','1131','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1232','1132','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1233','1133','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1234','1134','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1235','1135','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1236','1136','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ENT_TYPE_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','1237','1137','PERSON',SYSDATE,SYS_GUID(),1)
/
COMMIT
/







INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','admin@localhost','CAMPUS','1200','1100','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-ken-testing@googlegroups.com','CAMPUS','1201','1101','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-ken-testing@googlegroups.com','CAMPUS','1202','1102','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-ken-testing@googlegroups.com','CAMPUS','1203','1103','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-ken-testing@googlegroups.com','CAMPUS','1204','1104','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-ken-testing@googlegroups.com','CAMPUS','1205','1105','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-ken-testing@googlegroups.com','CAMPUS','1206','1106','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-ken-testing@googlegroups.com','CAMPUS','1207','1107','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-ken-testing@googlegroups.com','CAMPUS','1208','1108','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','quickstart@indiana.edu','CAMPUS','1209','1109','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','user1@indiana.edu','CAMPUS','1210','1110','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','user2@indiana.edu','CAMPUS','1211','1111','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','user3@indiana.edu','CAMPUS','1212','1112','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','user4@indiana.edu','CAMPUS','1213','1113','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','edna@localhost.edu','CAMPUS','1214','1114','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','eric@localhost.edu','CAMPUS','1215','1115','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','earl@localhost.edu','CAMPUS','1216','1116','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','erin@localhost.edu','CAMPUS','1217','1117','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','fred@indiana.edu','CAMPUS','1218','1118','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','fran@indiana.edu','CAMPUS','1219','1119','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','frank@indiana.edu','CAMPUS','1220','1120','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','doug@localhost.edu','CAMPUS','1221','1121','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-rice-dev@googlegroups.com','CAMPUS','1222','1122','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-rice-dev@googlegroups.com','CAMPUS','1223','1123','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-rice-dev@googlegroups.com','CAMPUS','1224','1124','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-rice-dev@googlegroups.com','CAMPUS','1225','1125','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-rice-dev@googlegroups.com','CAMPUS','1226','1126','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-rice-dev@googlegroups.com','CAMPUS','1227','1127','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-rice-dev@googlegroups.com','CAMPUS','1228','1128','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-rice-dev@googlegroups.com','CAMPUS','1229','1129','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-rice-dev@googlegroups.com','CAMPUS','1230','1130','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-ken-testing@googlegroups.com','CAMPUS','1231','1131','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','kuali-ken-testing@googlegroups.com','CAMPUS','1232','1132','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','newAccountUser@indiana.edu','CAMPUS','1233','1133','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','supervisor@indiana.edu','CAMPUS','1234','1134','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','director@indiana.edu','CAMPUS','1235','1135','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','KULUSER@indiana.edu','CAMPUS','1236','1136','PERSON',SYSDATE,SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','employee@indiana.edu','CAMPUS','1237','1137','PERSON',SYSDATE,SYS_GUID(),1)
/
COMMIT
/


INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1100','1200','admin','admin',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1101','1201','Test','Admin 1',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1102','1202','Test','Admin 2',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1103','1203','Test','User 1',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1104','1204','Test','User 2',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1105','1205','Test','User 3',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1106','1206','Test','User 4',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1107','1207','Test','User 5',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1108','1208','Test','User 6',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1109','1209','quickstart','quickstart',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1110','1210','User','One',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1111','1211','User','Two',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1112','1212','User','Three',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1113','1213','user4','user4',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1114','1214','Edna','Employee',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1115','1215','Eric','Employee',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1116','1216','Earl','Employee',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1117','1217','Erin','Employee',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1118','1218','fred','fred',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1119','1219','fran','fran',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1120','1220','frank','frank',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1121','1221','Doug','Neidermeyer',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1122','1222','Identity','Manager One',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1123','1223','Identity','Manager Two',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1124','1224','Identity','Manager Three',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1125','1225','Admin','One',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1126','1226','Admin','Two',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1127','1227','Tester','One',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1128','1228','Tester','Two',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1129','1229','Developer','One',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1130','1230','Developer','Two',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1131','1231','Notification','System',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1132','1232','Notification','System Admin',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1133','1233','newAccountUser','newAccountUser',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1134','1234','supervisor','supervisor',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1135','1235','director','director',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1136','1236','KULUSER','KULUSER',SYSDATE,'PFRD',SYS_GUID(),1)
/
INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','1137','1237','employee','employee',SYSDATE,'PFRD',SYS_GUID(),1)
/
COMMIT
/




INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','1','Default','KUALI',SYS_GUID(),'1',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','6','Initiate Document','KR-SYS',SYS_GUID(),'10',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','8','Cancel Document','KR-KEW',SYS_GUID(),'14',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','8','Save Document','KR-KEW',SYS_GUID(),'15',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','8','Edit Document','KR-KNS',SYS_GUID(),'16',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','9','Add Attachment','KR-KNS',SYS_GUID(),'17',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','9','Add Note','KR-KNS',SYS_GUID(),'18',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','9','Delete Attachment','KR-KNS',SYS_GUID(),'19',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','3','Copy Document','KR-KNS',SYS_GUID(),'2',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','9','Delete Note','KR-KNS',SYS_GUID(),'20',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','9','Edit Attachment','KR-KNS',SYS_GUID(),'21',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','9','Edit Note','KR-KNS',SYS_GUID(),'22',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','10','Look Up Records','KR-KNS',SYS_GUID(),'23',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','10','Inquire Into Records','KR-KNS',SYS_GUID(),'24',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','11','View Inquiry or Maintenance Document Field(s)','KR-KNS',SYS_GUID(),'25',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','11','Modify Maintenance Document Field(s)','KR-KNS',SYS_GUID(),'26',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','11','Full Unmask Field','KR-KNS',SYS_GUID(),'27',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','11','Partial Unmask Field','KR-KNS',SYS_GUID(),'28',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','12','Use Screen','KR-KNS',SYS_GUID(),'29',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','3','Administer Routing for Document','KR-KEW',SYS_GUID(),'3',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','13','Perform Custom Maintenance Document Function','KR-KNS',SYS_GUID(),'30',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','14','Use Transactional Document','KR-KNS',SYS_GUID(),'31',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','15','Modify Batch Job','KR-KNS',SYS_GUID(),'32',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','15','Upload Batch Input File(s)','KR-KNS',SYS_GUID(),'33',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','16','Maintain System Parameter','KR-KNS',SYS_GUID(),'34',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','18','Assign Role','KR-KIM',SYS_GUID(),'35',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','19','Grant Permission','KR-KIM',SYS_GUID(),'36',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','20','Grant Responsibility','KR-KIM',SYS_GUID(),'37',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','21','Populate Group','KR-KIM',SYS_GUID(),'38',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','22','Modify Entity','KR-KIM',SYS_GUID(),'39',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','3','Blanket Approve Document','KR-KEW',SYS_GUID(),'4',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','3','Open Document','KR-KNS',SYS_GUID(),'40',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','3','Route Document','KR-KEW',SYS_GUID(),'5',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','4','Take Requested Action','KR-KNS',SYS_GUID(),'8',1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','5','Ad Hoc Review Document','KR-KEW',SYS_GUID(),'9',1)
/
COMMIT
/




INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-KEW',SYS_GUID(),'140','29',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-KSB',SYS_GUID(),'141','29',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-KSB',SYS_GUID(),'142','29',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-KSB',SYS_GUID(),'143','29',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-KSB',SYS_GUID(),'144','29',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-KSB',SYS_GUID(),'145','29',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'146','9',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'147','3',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'148','4',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'149','10',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'150','35',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'151','36',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'152','37',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'153','39',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'154','39',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'155','38',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'156','2',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'157','19',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'158','20',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'159','21',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'160','22',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'161','24',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'162','23',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'163','34',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'164','32',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'165','40',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'166','29',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'167','14',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'168','5',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'169','15',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'170','8',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'171','8',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'172','8',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'173','8',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NM,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','Log In','KUALI',SYS_GUID(),'174','1',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'175','17',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'176','18',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'177','19',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'178','20',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'179','21',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'180','16',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'181','16',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KUALI',SYS_GUID(),'182','22',1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND,NMSPC_CD,OBJ_ID,PERM_ID,PERM_TMPL_ID,VER_NBR)
  VALUES ('Y','KR-SYS',SYS_GUID(),'183','27',1)
/
COMMIT
/





INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','WorkflowAdmin','1','WorkflowAdmin',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Notification system admin group for automation.','2000','NotificationAdmin',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Test group 1 for KEN testing.','2001','TestGroup1',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Test group 2 for KEN testing.','2002','TestGroup2',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','A test workgroup for KEN.','2003','RiceTeam',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Group0','2004','Group0',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Group1','2005','Group1',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Group2','2006','Group2',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Kuali Identity Managers','2007','Kuali Identity Managers',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Kuali Administrators','2008','Kuali Administrators',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Kuali Developers','2009','Kuali Developers',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','2036','TestRouteAGroup123',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','2060','TestAGroupRoutenum1',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','2122','CreatinAGroup4',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','2180','Testify!',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','edoclite documentation uses this. Do not change or delete.','2200','eDoc.Example1.SuperUsers',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','edoclite documentation uses this. Do not change or delete.','2201','eDoc.Example1.defaultExceptions',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Edoclite Documentation workgroup for example edoclite named eDoc.Example1','2202','eDoc.Example1.IUB.Workgroup',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_DESC,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Edoclite Documentation workgroup for example edoclite named eDoc.Example1','2203','eDoc.Example1.IUPUI.Workgroup',SYSDATE,'KFS',SYS_GUID(),1)
/
INSERT INTO KRIM_GRP_T (ACTV_IND,GRP_ID,GRP_NM,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','2260','TestAGroup123',SYSDATE,'KFS',SYS_GUID(),1)
/
COMMIT
/

INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2001','1100',SYSDATE,SYS_GUID(),'TestUser1',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2001','1101',SYSDATE,SYS_GUID(),'TestUser2',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2002','1102',SYSDATE,SYS_GUID(),'TestUser2',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2002','1103',SYSDATE,SYS_GUID(),'TestUser3',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2003','1104',SYSDATE,SYS_GUID(),'TestUser1',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2003','1105',SYSDATE,SYS_GUID(),'TestUser2',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2003','1106',SYSDATE,SYS_GUID(),'TestUser6',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2003','1107',SYSDATE,SYS_GUID(),'TestUser4',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2003','1108',SYSDATE,SYS_GUID(),'TestUser5',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2003','1109',SYSDATE,SYS_GUID(),'quickstart',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2004','1110',SYSDATE,SYS_GUID(),'quickstart',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2004','1111',SYSDATE,SYS_GUID(),'user1',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2004','1112',SYSDATE,SYS_GUID(),'user2',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2005','1113',SYSDATE,SYS_GUID(),'user3',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2006','1114',SYSDATE,SYS_GUID(),'user2',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2007','1115',SYSDATE,SYS_GUID(),'idm1',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2007','1116',SYSDATE,SYS_GUID(),'idm2',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2007','1117',SYSDATE,SYS_GUID(),'idm3',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2008','1118',SYSDATE,SYS_GUID(),'admin1',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2008','1119',SYSDATE,SYS_GUID(),'admin2',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2009','1120',SYSDATE,SYS_GUID(),'dev1',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2009','1121',SYSDATE,SYS_GUID(),'dev2',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2000','1122',SYSDATE,SYS_GUID(),'NotSysAdm',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','1','1123',SYSDATE,SYS_GUID(),'admin',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','1','1124',SYSDATE,SYS_GUID(),'NotSys',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2036','1125',SYSDATE,SYS_GUID(),'user2',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2060','1126',SYSDATE,SYS_GUID(),'user1',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2060','1127',SYSDATE,SYS_GUID(),'user2',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2122','1128',SYSDATE,SYS_GUID(),'admin',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2180','1129',SYSDATE,SYS_GUID(),'admin',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2200','1130',SYSDATE,SYS_GUID(),'user1',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2200','1131',SYSDATE,SYS_GUID(),'user3',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2201','1132',SYSDATE,SYS_GUID(),'user2',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2201','1133',SYSDATE,SYS_GUID(),'user4',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2202','1134',SYSDATE,SYS_GUID(),'user1',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2202','1135',SYSDATE,SYS_GUID(),'user2',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2203','1136',SYSDATE,SYS_GUID(),'user3',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2203','1137',SYSDATE,SYS_GUID(),'user4',1)
/
INSERT INTO KRIM_GRP_PRNCPL_T (ACTV_IND,GRP_ID,GRP_MBR_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,VER_NBR)
  VALUES ('Y','2260','1138',SYSDATE,SYS_GUID(),'admin',1)
/
COMMIT
/



INSERT INTO KRIM_RSP_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','7','Required Review (Action Details at Responsibility Level)','KR-KEW',SYS_GUID(),'1',1)
/
INSERT INTO KRIM_RSP_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','7','Voluntary Review (Action Details at Assignment Level)','KR-KEW',SYS_GUID(),'2',1)
/
INSERT INTO KRIM_RSP_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','7','Resolve Exception Routing','KR-KEW',SYS_GUID(),'3',1)
/
INSERT INTO KRIM_RSP_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','7','Required Review (Action Details at Assignment Level)','KR-KEW',SYS_GUID(),'4',1)
/
INSERT INTO KRIM_RSP_TMPL_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','7','Voluntary Review (Action Details at Responsibility Level)','KR-KEW',SYS_GUID(),'5',1)
/
COMMIT
/

INSERT INTO KRIM_ROLE_T (ACTV_IND,KIM_TYP_ID,LAST_UPDT_DT,NMSPC_CD,OBJ_ID,ROLE_ID,ROLE_NM,VER_NBR)
  VALUES ('Y','2',SYSDATE,'KUALI',SYS_GUID(),'1','User',1)
/
INSERT INTO KRIM_ROLE_PERM_T (ACTV_IND,OBJ_ID,PERM_ID,ROLE_ID,ROLE_PERM_ID,VER_NBR)
  VALUES ('Y',SYS_GUID(),'174','1','1',1)
/
COMMIT
/








INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('180','KR-KEW','4','12',SYS_GUID(),'140',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('181','org.kuali.rice.kew.documentoperation.web.DocumentOperationAction','2','12',SYS_GUID(),'140',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('182','KR-KSB','4','12',SYS_GUID(),'141',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('183','org.kuali.rice.ksb.security.admin.web.JavaSecurityManagementAction','2','12',SYS_GUID(),'141',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('184','KR-KSB','4','12',SYS_GUID(),'142',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('185','org.kuali.rice.ksb.messaging.web.MessageQueueAction','2','12',SYS_GUID(),'142',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('186','KR-KSB','4','12',SYS_GUID(),'143',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('187','org.kuali.rice.ksb.messaging.web.ServiceRegistryAction','2','12',SYS_GUID(),'143',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('188','KR-KSB','4','12',SYS_GUID(),'144',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('189','org.kuali.rice.ksb.messaging.web.ThreadPoolAction','2','12',SYS_GUID(),'144',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('190','KR-KSB','4','12',SYS_GUID(),'145',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('191','org.kuali.rice.ksb.messaging.web.QuartzQueueAction','2','12',SYS_GUID(),'145',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('192','RiceDocument','13','5',SYS_GUID(),'146',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('193','RiceDocument','13','3',SYS_GUID(),'147',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('194','RiceDocument','13','3',SYS_GUID(),'148',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('195','RiceDocument','13','6',SYS_GUID(),'149',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('196','KR*','4','18',SYS_GUID(),'150',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('197','KR*','4','19',SYS_GUID(),'151',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('198','KR*','4','20',SYS_GUID(),'152',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('199','Person','17','22',SYS_GUID(),'153',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('200','System','17','22',SYS_GUID(),'154',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('201','KR*','4','21',SYS_GUID(),'155',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('202','RiceDocument','13','3',SYS_GUID(),'156',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('203','RiceDocument','13','9',SYS_GUID(),'157',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('204','false','8','9',SYS_GUID(),'157',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('205','RiceDocument','13','9',SYS_GUID(),'158',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('206','false','8','9',SYS_GUID(),'158',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('207','RiceDocument','13','9',SYS_GUID(),'159',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('208','false','8','9',SYS_GUID(),'159',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('209','RiceDocument','13','9',SYS_GUID(),'160',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('210','false','8','9',SYS_GUID(),'160',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('211','KR-SYS','4','10',SYS_GUID(),'161',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('212','KR*','5','10',SYS_GUID(),'161',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('213','KR-SYS','4','10',SYS_GUID(),'162',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('214','KR*','5','10',SYS_GUID(),'162',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('215','KR-SYS','4','16',SYS_GUID(),'163',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('216','KR*','5','16',SYS_GUID(),'163',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('217','KR*','4','15',SYS_GUID(),'164',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('218','RiceDocument','13','3',SYS_GUID(),'165',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('219','KR*','4','12',SYS_GUID(),'166',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('220','KualiDocument','13','8',SYS_GUID(),'167',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('221','KualiDocument','13','3',SYS_GUID(),'168',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('222','KualiDocument','13','8',SYS_GUID(),'169',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('223','Approve','14','4',SYS_GUID(),'170',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('224','Complete','14','4',SYS_GUID(),'171',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('225','Clear FYI','14','4',SYS_GUID(),'172',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('226','Acknowledge','14','4',SYS_GUID(),'173',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('227','Kuali Document','13','9',SYS_GUID(),'175',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('228','true','8','9',SYS_GUID(),'175',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('229','Kuali Document','13','9',SYS_GUID(),'176',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('230','true','8','9',SYS_GUID(),'176',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('231','KualiDocument','13','9',SYS_GUID(),'177',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('232','true','8','9',SYS_GUID(),'177',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('233','KualiDocument','13','9',SYS_GUID(),'178',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('234','true','8','9',SYS_GUID(),'178',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('235','KualiDocument','13','9',SYS_GUID(),'179',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('236','true','8','9',SYS_GUID(),'179',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('237','KualiDocument','13','8',SYS_GUID(),'180',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('238','AdHoc','15','8',SYS_GUID(),'180',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('239','KualiDocument','13','8',SYS_GUID(),'181',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('240','Enroute','15','8',SYS_GUID(),'181',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('241','KualiDocument','13','9',SYS_GUID(),'182',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('242','true','8','9',SYS_GUID(),'182',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('243','KimPrincipalImpl','5','11',SYS_GUID(),'183',1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,TARGET_PRIMARY_KEY,VER_NBR)
  VALUES ('244','password','6','11',SYS_GUID(),'183',1)
/
COMMIT
/

