CREATE SEQUENCE kr_kim_entity_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/
CREATE SEQUENCE KR_KIM_PRNCPL_ID_SEQ INCREMENT BY 1
    START WITH 10000000000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/
CREATE SEQUENCE kr_kim_entity_ent_type_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_entity_ext_id_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_entity_afltn_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_entity_name_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_entity_addr_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_entity_phone_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_entity_email_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_entity_emp_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_entity_ctznshp_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_group_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_group_member_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_role_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_role_member_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_role_rel_id_seq INCREMENT BY 1
	START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/



-- New AuthZ 

CREATE SEQUENCE kr_kim_type_id_seq INCREMENT BY 1
    START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_type_attrib_id_seq INCREMENT BY 1
    START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_attrib_id_seq INCREMENT BY 1
    START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_perm_id_seq INCREMENT BY 1
    START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_role_member_id_seq INCREMENT BY 1
    START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_resp_id_seq INCREMENT BY 1
    START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/
CREATE SEQUENCE kr_kim_role_resp_id_seq INCREMENT BY 1
    START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/

CREATE SEQUENCE kr_kim_attrib_data_id_seq INCREMENT BY 1
    START WITH 1000
    NOMAXVALUE NOMINVALUE NOCYCLE
    CACHE 100 ORDER
/
