CREATE TABLE NOTIFICATION_PRIORITIES
(
ID NUMBER(8) NOT NULL,
NAME VARCHAR2(40) NOT NULL,
DESCRIPTION VARCHAR2(500) NOT NULL,
PRIORITY_ORDER NUMBER(4) NOT NULL,
CONSTRAINT NOTIFICATION_PRIORITY_PK PRIMARY KEY (ID)
)
/