CREATE TABLE NOTIFICATION_PRODUCERS
(
ID NUMBER(8) NOT NULL,
NAME VARCHAR2(500) NOT NULL,
DESCRIPTION VARCHAR2(1000) NOT NULL,
CONTACT_INFO VARCHAR2(1000) NOT NULL,
CONSTRAINT NOTIFICATION_PRODUCER_PK PRIMARY KEY (ID)
)
/