CREATE TABLE NOTIFICATION_REVIEWERS
(
ID NUMBER(8) NOT NULL,
CHANNEL_ID NUMBER(8) NOT NULL,
REVIEWER_TYPE VARCHAR2(10) NOT NULL,
REVIEWER_ID VARCHAR2(300) NOT NULL,
CONSTRAINT NOTIFICATION_REVIEWERS_PK PRIMARY KEY (ID)
)
/