CREATE TABLE NOTIFICATION_RECIPIENTS_LISTS
(
ID NUMBER(8) NOT NULL,
CHANNEL_ID NUMBER(8) NOT NULL,
RECIPIENT_TYPE VARCHAR2(10) NOT NULL,
RECIPIENT_ID VARCHAR2(300) NOT NULL,
CONSTRAINT NOTIFICATION_RECIPIENTS_L_PK PRIMARY KEY (ID)
)
/