CREATE TABLE NOTIFICATION_CONTENT_TYPES
(
ID NUMBER(8) NOT NULL,
NAME VARCHAR2(500) NOT NULL,
CUR_IND CHAR DEFAULT 'T' NOT NULL,
VERSION NUMBER(8) DEFAULT '0' NOT NULL,
DESCRIPTION VARCHAR2(1000) NOT NULL,
NAMESPACE VARCHAR2(1000) NOT NULL,
XSD CLOB NOT NULL,
XSL CLOB NOT NULL,
CONSTRAINT NOTIFICATION_CONTENT_TYPE_PK PRIMARY KEY (ID)
)
/