CREATE TABLE NOTIFICATION_CHANNELS
(
ID NUMBER(8) NOT NULL,
NAME VARCHAR2(1000) NOT NULL,
DESCRIPTION VARCHAR2(4000) NOT NULL,
SUBSCRIBABLE CHAR(1) NOT NULL,
CONSTRAINT NOTIFICATION_CHANNELS_PK PRIMARY KEY (ID)
)
/