CREATE TABLE RECIPIENT_PREFERENCES
(
ID NUMBER(8) NOT NULL,
RECIPIENT_TYPE VARCHAR2(10) NOT NULL,
RECIPIENT_ID VARCHAR2(300) NOT NULL,
PROPERTY VARCHAR2(300) NOT NULL,
VALUE VARCHAR2(1000) NOT NULL,
CONSTRAINT RECIPIENT_PREFERENCES_PK PRIMARY KEY (ID)
)
/