CREATE TABLE USER_DELIVERER_CONFIG
(
ID NUMBER(8) NOT NULL,
CHANNEL_ID NUMBER(8) NOT NULL,
USER_ID VARCHAR2(300) NOT NULL,
DELIVERER_NAME VARCHAR2(300) NOT NULL,
CONSTRAINT USER_DELIVERER_CONFIG_PK PRIMARY KEY (ID)
)
/