/*
 * Copyright 2005-2006 The Kuali Foundation.
 * 
 * 
 * Licensed under the Educational Community License, Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.opensource.org/licenses/ecl1.php
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package edu.iu.uis.eden.clientapp.vo;

import java.io.Serializable;

/**
 * Superclass for all Document Events which can be generated by the routing engine.
 * 
 * @author Kuali Rice Team (kuali-rice@googlegroups.com)
 * 
 * @workflow.webservice-object
 */
public abstract class DocumentEventVO implements Serializable {

    public static final String ROUTE_LEVEL_CHANGE = "rt_lvl_change";
    public static final String ROUTE_STATUS_CHANGE = "rt_status_change";
    public static final String DELETE_CHANGE = "delete_document";
    public static final String ACTION_TAKEN = "action_taken";

    private String documentEventCode;
    private Long routeHeaderId;
    private String appDocId;
    
    public DocumentEventVO() {}

    public DocumentEventVO(String documentEventCode) {
        this.documentEventCode = documentEventCode;
    }
    
    public String getAppDocId() {
        return appDocId;
    }

    public void setAppDocId(String appDocId) {
        this.appDocId = appDocId;
    }

    public String getDocumentEventCode() {
        return documentEventCode;
    }

    public void setDocumentEventCode(String documentEventCode) {
        this.documentEventCode = documentEventCode;
    }

    public Long getRouteHeaderId() {
        return routeHeaderId;
    }

    public void setRouteHeaderId(Long routeHeaderId) {
        this.routeHeaderId = routeHeaderId;
    }
    
}