CREATE TABLE EN_RTE_NODE_CFG_PARM_T (
    RTE_NODE_CFG_PARM_ID    NUMBER(19) NOT NULL,
    RTE_NODE_CFG_PARM_ND    NUMBER(19) NOT NULL,
    RTE_NODE_CFG_PARM_KEY   VARCHAR2(255) NOT NULL,
    RTE_NODE_CFG_PARM_VAL   VARCHAR2(4000),
    CONSTRAINT EN_RTE_NODE_CFG_PARM_T_PK PRIMARY KEY (RTE_NODE_CFG_PARM_ID) USING INDEX
)
/

-- Table for RuleExpressionDef; child of EN_RULE_BASE_VAL_T/RuleBaseValue
CREATE TABLE EN_RULE_EXPR_T (
    RULE_EXPR_ID    NUMBER(19) NOT NULL,
    RULE_EXPR_TYP   VARCHAR(256) NOT NULL,
    RULE_EXPR       VARCHAR2(4000),
    CONSTRAINT EN_RULE_EXPR_T_PK PRIMARY KEY (RULE_EXPR_ID) USING INDEX
)
/

CREATE SEQUENCE SEQ_RTE_NODE_CFG_PARM INCREMENT BY 1 START WITH 2000
/

CREATE SEQUENCE SEQ_RULE_EXPR INCREMENT BY 1 START WITH 2000
/

ALTER TABLE EN_RULE_BASE_VAL_T ADD RULE_EXPR_ID NUMBER(19) NULL /
ALTER TABLE EN_RULE_BASE_VAL_T MODIFY (RULE_TMPL_ID NULL) /

ALTER TABLE EN_RULE_BASE_VAL_T ADD CONSTRAINT EN_RULE_BASE_VAL_TR1
FOREIGN KEY (RULE_EXPR_ID)
REFERENCES EN_RULE_EXPR_T (RULE_EXPR_ID)
/