CREATE TABLE FS_LOOKUP_RESULTS_MT (
        LOOKUP_RESULT_SEQUENCE_NBR     VARCHAR2(14) CONSTRAINT FS_LOOKUP_RESULTS_MTN1 NOT NULL, 
        OBJ_ID                         VARCHAR2(36) DEFAULT SYS_GUID() CONSTRAINT FS_LOOKUP_RESULTS_MTN2 NOT NULL,
        VER_NBR                        NUMBER(8) DEFAULT 1 CONSTRAINT FS_LOOKUP_RESULTS_MTN3 NOT NULL,
        PERSON_UNVL_ID                 VARCHAR2(10) CONSTRAINT FS_LOOKUP_RESULTS_MTN4 NOT NULL,
        LOOKUP_DATE                    DATE CONSTRAINT FS_LOOKUP_RESULTS_MTN5 NOT NULL,
        SERIALIZED_LOOKUP_RESULTS      CLOB, 
     CONSTRAINT FS_LOOKUP_RESULTS_MTP1 PRIMARY KEY (
        LOOKUP_RESULT_SEQUENCE_NBR),
     CONSTRAINT FS_LOOKUP_RESULTS_MTC0 UNIQUE (OBJ_ID)
);

CREATE TABLE FS_LOOKUP_SELECTIONS_MT(
        LOOKUP_RESULT_SEQUENCE_NBR VARCHAR2(14) CONSTRAINT FS_LOOKUP_SELECTIONS_MTN1 NOT NULL,
        OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() CONSTRAINT FS_LOOKUP_SELECTIONS_MTN2 NOT NULL,
        VER_NBR NUMBER(8) DEFAULT 1 CONSTRAINT FS_LOOKUP_SELECTIONS_MTN3 NOT NULL,
        PERSON_UNVL_ID VARCHAR2(10) CONSTRAINT FS_LOOKUP_SELECTIONS_MTN4 NOT NULL,
        LOOKUP_DATE DATE CONSTRAINT FS_LOOKUP_SELECTIONS_MTN5 NOT NULL,
        SELECTED_OBJ_IDS CLOB,
     CONSTRAINT FS_LOOKUP_SELECTIONS_MTP1 PRIMARY KEY (
        LOOKUP_RESULT_SEQUENCE_NBR),
     CONSTRAINT FS_LOOKUP_SELECTIONS_MTC0 UNIQUE (OBJ_ID)
);

CREATE TABLE EN_OUT_BOX_ITM_T (
    ACTN_ITM_ID             NUMBER(14) NOT NULL,
    ACTN_ITM_PRSN_EN_ID     VARCHAR2(30) NOT NULL,
    ACTN_ITM_ASND_DT        DATE NOT NULL,
    ACTN_ITM_RQST_CD        CHAR(1) NOT NULL,
    ACTN_RQST_ID            NUMBER(14) NOT NULL,
    DOC_HDR_ID              NUMBER(14) NOT NULL,
    WRKGRP_ID               NUMBER(14) NULL,
    ROLE_NM                 VARCHAR2(2000) NULL,
    ACTN_ITM_DLGN_PRSN_EN_ID VARCHAR2(30) NULL,
    ACTN_ITM_DLGN_WRKGRP_ID NUMBER(14) NULL,
    DOC_TTL                 VARCHAR2(255) NULL,
    DOC_TYP_LBL_TXT         VARCHAR2(255) NOT NULL,
    DOC_TYP_HDLR_URL_ADDR   VARCHAR2(255) NOT NULL,
    DOC_TYP_NM              VARCHAR2(255) NOT NULL,
    ACTN_ITM_RESP_ID        NUMBER(14) NOT NULL,
    DLGN_TYP                VARCHAR2(1) NULL,
    DB_LOCK_VER_NBR         NUMBER(8) DEFAULT 0,
    CONSTRAINT EN_OUT_BOX_ITM_T_PK PRIMARY KEY (ACTN_ITM_ID)  
);

CREATE TABLE EN_RTE_NODE_CFG_PARM_T (
    RTE_NODE_CFG_PARM_ID    NUMBER(19) NOT NULL,
    RTE_NODE_CFG_PARM_ND    NUMBER(19) NOT NULL,
    RTE_NODE_CFG_PARM_KEY   VARCHAR2(255) NOT NULL,
    RTE_NODE_CFG_PARM_VAL   VARCHAR2(4000),
    CONSTRAINT EN_RTE_NODE_CFG_PARM_T_PK PRIMARY KEY (RTE_NODE_CFG_PARM_ID) 
);

CREATE TABLE EN_RULE_EXPR_T (
    RULE_EXPR_ID    NUMBER(19) NOT NULL,
    RULE_EXPR_TYP   VARCHAR(256) NOT NULL,
    RULE_EXPR       VARCHAR2(4000),
    CONSTRAINT EN_RULE_EXPR_T_PK PRIMARY KEY (RULE_EXPR_ID) 
);

ALTER TABLE EN_DOC_TYP_ATTRIB_T ADD ORD_INDX NUMBER(4) DEFAULT 0;
ALTER TABLE EN_RULE_BASE_VAL_T RULE_TMPL_ID NUMBER(19) NULL;
ALTER TABLE EN_RULE_BASE_VAL_T ADD RULE_EXPR_ID NUMBER(19) NULL;

CREATE SEQUENCE SEQ_OUT_BOX_ITM INCREMENT BY 1 START WITH 10000;
CREATE SEQUENCE SEQ_RTE_NODE_CFG_PARM INCREMENT BY 1 START WITH 2000;
CREATE SEQUENCE SEQ_RULE_EXPR INCREMENT BY 1 START WITH 2000;

CREATE INDEX EN_OUT_BOX_ITM_T1 ON EN_OUT_BOX_ITM_T (ACTN_ITM_PRSN_EN_ID);
CREATE INDEX EN_OUT_BOX_ITM_TI2 ON EN_OUT_BOX_ITM_T (DOC_HDR_ID);
CREATE INDEX EN_OUT_BOX_ITM_TI3 ON EN_OUT_BOX_ITM_T (ACTN_RQST_ID);
CREATE INDEX EN_OUT_BOX_ITM_TI4 ON EN_OUT_BOX_ITM_T (ACTN_ITM_DLGN_PRSN_EN_ID, ACTN_ITM_DLGN_WRKGRP_ID, ACTN_ITM_PRSN_EN_ID, DLGN_TYP);

ALTER TABLE EN_RTE_NODE_CFG_PARM_T ADD CONSTRAINT EN_RTE_NODE_CFG_PARM_TR1
FOREIGN KEY (RTE_NODE_CFG_PARM_ND)
REFERENCES EN_RTE_NODE_T (RTE_NODE_ID);

ALTER TABLE EN_RULE_BASE_VAL_T ADD CONSTRAINT EN_RULE_BASE_VAL_TR1
FOREIGN KEY (RULE_EXPR_ID)
REFERENCES EN_RULE_EXPR_T (RULE_EXPR_ID);
