CREATE TABLE EN_DOC_HDR_CNTNT_T (
	DOC_HDR_ID 			    NUMBER(14) NOT NULL,
	DOC_CNTNT_TXT			CLOB NULL,
	CONSTRAINT EN_DOC_HDR_T_CNTNT_PK PRIMARY KEY (DOC_HDR_ID)
)

/

INSERT INTO EN_DOC_HDR_CNTNT_T SELECT DOC_HDR_ID, TO_LOB(DOC_CNTNT_TXT) FROM EN_DOC_HDR_T

/

ALTER TABLE EN_RULE_ATTRIB_T MODIFY ( RULE_ATTRIB_XML_RTE_TXT CLOB )

/

ALTER INDEX EN_RULE_ATTRIB_PK REBUILD

/

ALTER TABLE EN_MESSAGE_QUE_T MODIFY ( MESSAGE_PAYLOAD CLOB )

/

ALTER INDEX EN_MESSAGE_QUE_T_PK REBUILD

/

ALTER TABLE EN_BAM_T MODIFY ( EXCEPTION_MSG CLOB )

/

ALTER INDEX EN_BAM_T_PK REBUILD

/

ALTER TABLE EN_BAM_PARAM_T MODIFY ( PARAM CLOB )

/

ALTER INDEX EN_BAM_PARAM_T_PK REBUILD

/

ALTER TABLE EN_RTE_BRCH_T MODIFY ( INIT_RTE_NODE_INSTN_ID NUMBER(19) NULL )

/

ALTER TABLE EN_RTE_NODE_INSTN_T MODIFY (RTE_NODE_ID NUMBER(19) NULL )

/