--
-- Copyright 2005-2014 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-----------------------------------------------------------------------------
-- KRLC_CMP_T
-----------------------------------------------------------------------------
INSERT INTO KRLC_CMP_T (ACTV_IND,CAMPUS_CD,CAMPUS_NM,CAMPUS_SHRT_NM,CAMPUS_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','BL','BLOOMINGTON','BLOOMINGTON','B','014F3DB2478DA448E043814FD28EA448',1)
/
INSERT INTO KRLC_CMP_T (ACTV_IND,CAMPUS_CD,CAMPUS_NM,CAMPUS_SHRT_NM,CAMPUS_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','BX','BLGTN OFF CAMPUS','BLGTN OFF CA','P','014F3DB24798A448E043814FD28EA448',1)
/
INSERT INTO KRLC_CMP_T (ACTV_IND,CAMPUS_CD,CAMPUS_NM,CAMPUS_SHRT_NM,CAMPUS_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','CO','COLUMBUS','COLUMBUS','F','014F3DB2478EA448E043814FD28EA448',1)
/
INSERT INTO KRLC_CMP_T (ACTV_IND,CAMPUS_CD,CAMPUS_NM,CAMPUS_SHRT_NM,CAMPUS_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','EA','EAST-RICHMOND','EA-RICHMOND','B','014F3DB2478FA448E043814FD28EA448',1)
/
INSERT INTO KRLC_CMP_T (ACTV_IND,CAMPUS_CD,CAMPUS_NM,CAMPUS_SHRT_NM,CAMPUS_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','FW','FORT WAYNE','FORT WAYNE','B','014F3DB24790A448E043814FD28EA448',1)
/
INSERT INTO KRLC_CMP_T (ACTV_IND,CAMPUS_CD,CAMPUS_NM,CAMPUS_SHRT_NM,CAMPUS_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','IN','INDIANAPOLIS','INDIANAPOLIS','B','014F3DB24791A448E043814FD28EA448',1)
/
INSERT INTO KRLC_CMP_T (ACTV_IND,CAMPUS_CD,CAMPUS_NM,CAMPUS_SHRT_NM,CAMPUS_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','KO','KOKOMO','KOKOMO','B','014F3DB24792A448E043814FD28EA448',1)
/
INSERT INTO KRLC_CMP_T (ACTV_IND,CAMPUS_CD,CAMPUS_NM,CAMPUS_SHRT_NM,CAMPUS_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','NW','NORTHWEST-GARY','NW-GARY','B','014F3DB24793A448E043814FD28EA448',1)
/
INSERT INTO KRLC_CMP_T (ACTV_IND,CAMPUS_CD,CAMPUS_NM,CAMPUS_SHRT_NM,CAMPUS_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','OC','OFF CAMPUS','OFF CAMPUS','F','014F3DB24794A448E043814FD28EA448',1)
/
INSERT INTO KRLC_CMP_T (ACTV_IND,CAMPUS_CD,CAMPUS_NM,CAMPUS_SHRT_NM,CAMPUS_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','SB','SOUTH BEND','SOUTH BEND','B','014F3DB24795A448E043814FD28EA448',1)
/
INSERT INTO KRLC_CMP_T (ACTV_IND,CAMPUS_CD,CAMPUS_NM,CAMPUS_SHRT_NM,CAMPUS_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','SE','SOUTHEAST-NEW ALBANY','SE-NEW ALBNY','B','014F3DB24796A448E043814FD28EA448',1)
/
INSERT INTO KRLC_CMP_T (ACTV_IND,CAMPUS_CD,CAMPUS_NM,CAMPUS_SHRT_NM,CAMPUS_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','UA','UNIVERSITY ADMINISTRATION','UNIVER ADMIN','F','014F3DB24797A448E043814FD28EA448',1)
/
