CREATE INDEX EN_ACTN_ITM_T1
 ON EN_ACTN_ITM_T (ACTN_ITM_PRSN_EN_ID)
/
CREATE INDEX EN_ACTN_ITM_TI2
 ON EN_ACTN_ITM_T (DOC_HDR_ID)
/
CREATE INDEX EN_ACTN_ITM_TI3
 ON EN_ACTN_ITM_T (ACTN_RQST_ID)
/
CREATE INDEX EN_ACTN_ITM_TI4
	ON EN_ACTN_ITM_T (ACTN_ITM_DLGN_PRSN_EN_ID, ACTN_ITM_DLGN_WRKGRP_ID, ACTN_ITM_PRSN_EN_ID, DLGN_TYP)
/
