CREATE INDEX EN_RTE_NODE_INSTN_TI1 ON EN_RTE_NODE_INSTN_T (DOC_ID, ACTV_IND, CMPLT_IND)
/
CREATE INDEX EN_RTE_NODE_INSTN_TI2 ON EN_RTE_NODE_INSTN_T (RTE_NODE_ID)
/
CREATE INDEX EN_RTE_NODE_INSTN_TI3 ON EN_RTE_NODE_INSTN_T (BRCH_ID)
/
CREATE INDEX EN_RTE_NODE_INSTN_TI4 ON EN_RTE_NODE_INSTN_T (PROC_RTE_NODE_INSTN_ID)
/
