CREATE TABLE EN_DLGN_RSP_T (
	DLGN_RULE_ID NUMBER(19) NOT NULL,
	RULE_RSP_ID NUMBER(19) NOT NULL,
	DLGN_RULE_BASE_VAL_ID NUMBER(19) NOT NULL,
	DLGN_TYP VARCHAR2(20) NOT NULL,
	DB_LOCK_VER_NBR NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_DLGN_RSP_PK PRIMARY KEY (DLGN_RULE_ID) USING INDEX
)
/