CREATE TABLE EN_DOC_NTE_T (
	DOC_NTE_ID                NUMBER(19) NOT NULL,
	DOC_HDR_ID                NUMBER(14) NOT NULL,
	DOC_NTE_AUTH_PRSN_EN_ID   VARCHAR2(30) NOT NULL,
	DOC_NTE_CRT_DT            DATE NOT NULL,
    DOC_NTE_TXT               VARCHAR2(4000),
	DB_LOCK_VER_NBR	          NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_DOC_NTE_T_PK PRIMARY KEY (DOC_NTE_ID)  USING INDEX
)
/