CREATE TABLE EN_DOC_TYP_PROC_T (
	DOC_TYP_PROC_ID				   NUMBER(19) NOT NULL,
	DOC_TYP_ID	            	   NUMBER(19) NOT NULL,
	INIT_RTE_NODE_ID               NUMBER(19) NOT NULL,
	PROC_NM						   VARCHAR2(255) NOT NULL,
	INIT_IND					   NUMBER(1) DEFAULT 0 NOT NULL,
	DB_LOCK_VER_NBR	               NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_DOC_TYP_PROC_T_PK PRIMARY KEY (DOC_TYP_PROC_ID) USING INDEX
)
/