CREATE TABLE EN_EDL_FIELD_DMP_T (
	EDL_FIELD_DMP_ID NUMBER(14) NOT NULL,
	DOC_HDR_ID NUMBER(14) NOT NULL,
	FLD_NM VARCHAR2(255) NOT NULL,
	FLD_VAL VARCHAR2(4000) NULL,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_EDL_FIELD_DMP_T_PK PRIMARY KEY (EDL_FIELD_DMP_ID)
)
/