CREATE TABLE EN_HLP_T (
	EN_HLP_ID 			NUMBER(19) NOT NULL,
	EN_HLP_NM     		VARCHAR2(500) NOT NULL,
	EN_HLP_KY			VARCHAR2(500) NOT NULL,
	EN_HLP_TXT       	VARCHAR2(4000) NOT NULL,
	DB_LOCK_VER_NBR	    NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_HLP_T_PK PRIMARY KEY (EN_HLP_ID)  USING INDEX
)
/