CREATE TABLE EN_RULE_TMPL_T (
	RULE_TMPL_ID NUMBER(19) NOT NULL,
	RULE_TMPL_NM VARCHAR2(250) NOT NULL,
	RULE_TMPL_DESC VARCHAR2(2000) NULL,
	DLGN_RULE_TMPL_ID NUMBER(19) NULL,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RULE_TMPL_T_PK PRIMARY KEY (RULE_TMPL_ID) USING INDEX
)
/