CREATE TABLE EN_RULE_TMPL_OPTN_T (
	RULE_TMPL_OPTN_ID NUMBER(19) NOT NULL,
	RULE_TMPL_ID NUMBER(19) NULL,
	RULE_TMPL_OPTN_KEY VARCHAR2(250) NULL,
	RULE_TMPL_OPTN_VAL VARCHAR2(2000) NULL,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RULE_TMPL_OPTN_T_PK PRIMARY KEY (RULE_TMPL_OPTN_ID) USING INDEX
)
/