CREATE TABLE EN_RULE_EXT_T (
	RULE_EXT_ID NUMBER(19) NOT NULL,
	RULE_TMPL_ATTRIB_ID NUMBER(19) NOT NULL,
	RULE_BASE_VAL_ID NUMBER(19) NOT NULL,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_RULE_EXT_PK PRIMARY KEY (RULE_EXT_ID) USING INDEX
)
/