CREATE TABLE EN_RTE_NODE_INSTN_LNK_T (
	FROM_RTE_NODE_INSTN_ID   	   NUMBER(19) NOT NULL,
	TO_RTE_NODE_INSTN_ID    	   NUMBER(19) NOT NULL,
	CONSTRAINT EN_RTE_NODE_INSTN_LNK_T_PK PRIMARY KEY (FROM_RTE_NODE_INSTN_ID, TO_RTE_NODE_INSTN_ID) USING INDEX
)
/