CREATE TABLE EN_WRKGRP_TYP_T (
	WRKGRP_TYP_ID NUMBER(19) NOT NULL,
	WRKGRP_TYP_NM VARCHAR2(250) NOT NULL,
	WRKGRP_TYP_LBL VARCHAR2(2000) NOT NULL,
	WRKGRP_TYP_DESC VARCHAR2(2000) NULL,
	DOC_TYP_NM VARCHAR2(255) NULL,
	ACTV_IND NUMBER(1) DEFAULT 1,
	DB_LOCK_VER_NBR	NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_WRKGRP_TYP_T_PK PRIMARY KEY (WRKGRP_TYP_ID)
)
/
