CREATE TABLE EN_WRKGRP_EXT_T (
    WRKGRP_EXT_ID        NUMBER(19) NOT NULL,
    WRKGRP_ID            NUMBER(19) NOT NULL,
    WRKGRP_VER_NBR       NUMBER(8) NOT NULL,
    WRKGRP_TYP_ATTRIB_ID NUMBER(19) NOT NULL,
    DB_LOCK_VER_NBR      NUMBER(8) DEFAULT 0,
    CONSTRAINT EN_WRKGRP_EXT_T_PK PRIMARY KEY (WRKGRP_EXT_ID)
)
/