CREATE TABLE FP_MAINT_LOCK_T (
        LOCK_REPRESENTATION_TXT        VARCHAR2(255) CONSTRAINT FP_MAINT_LOCK_TN1 NOT NULL,
        OBJ_ID                         VARCHAR2(36) DEFAULT SYS_GUID() CONSTRAINT FP_MAINT_LOCK_TN2 NOT NULL,
        VER_NBR                        NUMBER(8) DEFAULT 1 CONSTRAINT FP_MAINT_LOCK_TN3 NOT NULL,
        FDOC_NBR                       VARCHAR2(14) CONSTRAINT FP_MAINT_LOCK_TN4 NOT NULL,
     CONSTRAINT FP_MAINT_LOCK_TP1 PRIMARY KEY (LOCK_REPRESENTATION_TXT),
     CONSTRAINT FP_MAINT_LOCK_TC0 UNIQUE (OBJ_ID)
)
/
