CREATE TABLE KCB_RECIP_DELIVS
(
    ID                  NUMBER(8) NOT NULL,
    RECIPIENT_ID        VARCHAR2(255) NOT NULL,
    CHANNEL             VARCHAR2(255) NOT NULL,
    DELIVERER_NAME      VARCHAR2(255) NOT NULL,
    DB_LOCK_VER_NBR     INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT KCB_RECIP_DELIVS_PK PRIMARY KEY (ID)
)
/
