CREATE TABLE KCB_MSG_DELIVS
(
    ID                      NUMBER(8) NOT NULL,
    MESSAGE_ID              NUMBER(8) NOT NULL,
    DELIVERER_TYPE_NAME     VARCHAR2(255) NOT NULL,
    DELIVERER_SYSTEM_ID     VARCHAR2(255),
    DELIVERY_STATUS         VARCHAR2(15) NOT NULL,
    PROCESS_COUNT           NUMBER(4) DEFAULT 0 NOT NULL,
    LOCKED_DATE             TIMESTAMP NULL,
    DB_LOCK_VER_NBR         INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT KCB_MSG_DELIVS_PK PRIMARY KEY (ID)
)
/
