CREATE TABLE KIM_ENTITYS_T (
        ID NUMBER(8) NOT NULL,
        ENTITY_TYPE_ID NUMBER(8) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_ENTITYS_PK PRIMARY KEY (ID)
)
/