CREATE TABLE KIM_AUTHN_SESN_T (
        ID VARCHAR(256) NOT NULL,
	    INSERT_DATETIME    TIMESTAMP NOT NULL,
	    LAST_ACCESS_DATETIME    TIMESTAMP NOT NULL,
		MAX_IDLE_TIME NUMBER(20) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_AUTHN_SESN_PK PRIMARY KEY (ID)
)
/