CREATE TABLE KIM_PRNCPL_QLFD_ROLES_T (
		ID NUMBER(8) NOT NULL,
        PRINCIPAL_ID NUMBER(8) NOT NULL,
		ROLE_ID NUMBER(8) NOT NULL,
		ATTRIBUTE_NAME VARCHAR(255) NOT NULL,
		ATTRIBUTE_VALUE VARCHAR(255) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_PRNCPL_QLFD_ROLES_PK PRIMARY KEY (ID)
)
/