CREATE TABLE KIM_GROUP_TYPES_T (
        ID NUMBER(8) NOT NULL,
        NAME VARCHAR2(500) NOT NULL,
        DESCRIPTION VARCHAR2(4000),
		WORKFLOW_DOCUMENT_TYPE VARCHAR2(500) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_GROUP_TYPE_PK PRIMARY KEY(ID) 
)
/