CREATE TABLE KIM_AUTHN_SESN_PRINCIPAL_T (
        SESN_ID VARCHAR(256) NOT NULL,
	    PRINCIPAL_NAME VARCHAR(256) NOT NULL,
        CONSTRAINT KIM_AUTHN_SESN_PRINCIPAL_PK PRIMARY KEY (SESN_ID, PRINCIPAL_NAME)
)
/