CREATE TABLE KOM_ORGANIZATIONS_CONTEXTS_T (
		ID NUMBER(8) NOT NULL,
		ORGANIZATION_ID NUMBER(8) NOT NULL,
		CONTEXT_ID NUMBER(8) NOT NULL,
		ACTIVE CHAR(1) NOT NULL,
		CONSTRAINT KOM_ORGANIZATIONS_CONTEXTS_PK PRIMARY KEY (ID)
)
/