CREATE TABLE SH_CMP_TYP_T (
        CAMPUS_TYP_CD                  VARCHAR2(1) CONSTRAINT SH_CMP_TYP_TN1 NOT NULL,
        CMP_TYP_NM                     VARCHAR2(250),
        DOBJ_MAINT_CD_ACTV_IND         VARCHAR2(1) CONSTRAINT SH_CMP_TYP_TN2 NOT NULL,
        OBJ_ID                         VARCHAR2(36) DEFAULT SYS_GUID() CONSTRAINT SH_CMP_TYP_TN3 NOT NULL,
        VER_NBR                        NUMBER(8) DEFAULT 1 CONSTRAINT SH_CMP_TYP_TN4 NOT NULL,
     CONSTRAINT SH_CMP_TYP_TP1 PRIMARY KEY (CAMPUS_TYP_CD),
     CONSTRAINT SH_CMP_TYP_TC0 UNIQUE (OBJ_ID)
)
/