--
-- KULRICE-4794
-- The following statements will change the DOC_HDR_ID from a decimal to a VARCHAR(40) on TRV_DOC_ACCT. 
--

ALTER TABLE TRV_DOC_ACCT RENAME TO OLD_TRV_DOC_ACCT
/
CREATE TABLE TRV_DOC_ACCT(
      DOC_HDR_ID VARCHAR2(40) NOT NULL,
      ACCT_NUM VARCHAR2(10) NOT NULL
)
/
INSERT INTO TRV_DOC_ACCT SELECT * FROM OLD_TRV_DOC_ACCT
/
DROP TABLE OLD_TRV_DOC_ACCT
/
ALTER TABLE TRV_DOC_ACCT ADD CONSTRAINT TRV_DOC_ACCTP1 PRIMARY KEY (DOC_HDR_ID,ACCT_NUM)
/