--
-- Copyright 2005-2015 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

INSERT INTO krew_doc_hdr_t (DOC_HDR_ID,DOC_TYP_ID,DOC_HDR_STAT_CD,RTE_LVL,STAT_MDFN_DT,CRTE_DT,APRV_DT,FNL_DT,RTE_STAT_MDFN_DT,TTL,APP_DOC_ID,DOC_VER_NBR,INITR_PRNCPL_ID,VER_NBR,RTE_PRNCPL_ID,DTYPE,OBJ_ID,APP_DOC_STAT,APP_DOC_STAT_MDFN_DT) VALUES ('test-1','testType','S',0,SYSDATE,SYSDATE,NULL,NULL,SYSDATE,'New AgendaEditor - New Agenda Editor Document ',NULL,1,'admin',5,NULL,NULL,'aa',NULL,NULL)
/
INSERT INTO krew_doc_hdr_t (DOC_HDR_ID,DOC_TYP_ID,DOC_HDR_STAT_CD,RTE_LVL,STAT_MDFN_DT,CRTE_DT,APRV_DT,FNL_DT,RTE_STAT_MDFN_DT,TTL,APP_DOC_ID,DOC_VER_NBR,INITR_PRNCPL_ID,VER_NBR,RTE_PRNCPL_ID,DTYPE,OBJ_ID,APP_DOC_STAT,APP_DOC_STAT_MDFN_DT) VALUES ('test-2','testType','S',0,SYSDATE,SYSDATE,NULL,NULL,SYSDATE,'Travel Authorization Document - Test',NULL,1,'admin',5,NULL,NULL,'bb',NULL,NULL)
/
INSERT INTO krew_doc_hdr_t (DOC_HDR_ID,DOC_TYP_ID,DOC_HDR_STAT_CD,RTE_LVL,STAT_MDFN_DT,CRTE_DT,APRV_DT,FNL_DT,RTE_STAT_MDFN_DT,TTL,APP_DOC_ID,DOC_VER_NBR,INITR_PRNCPL_ID,VER_NBR,RTE_PRNCPL_ID,DTYPE,OBJ_ID,APP_DOC_STAT,APP_DOC_STAT_MDFN_DT) VALUES ('test-3','testType','S',0,SYSDATE,SYSDATE,NULL,NULL,SYSDATE,'Travel Authorization Document - Test',NULL,1,'admin',5,NULL,NULL,'cc',NULL,NULL)
/
INSERT INTO krew_doc_hdr_t (DOC_HDR_ID,DOC_TYP_ID,DOC_HDR_STAT_CD,RTE_LVL,STAT_MDFN_DT,CRTE_DT,APRV_DT,FNL_DT,RTE_STAT_MDFN_DT,TTL,APP_DOC_ID,DOC_VER_NBR,INITR_PRNCPL_ID,VER_NBR,RTE_PRNCPL_ID,DTYPE,OBJ_ID,APP_DOC_STAT,APP_DOC_STAT_MDFN_DT) VALUES ('test-4','testType','I',0,SYSDATE,SYSDATE,NULL,NULL,NULL,NULL,NULL,1,'admin',2,NULL,NULL,'dd',NULL,NULL)
/
INSERT INTO krew_doc_hdr_t (DOC_HDR_ID,DOC_TYP_ID,DOC_HDR_STAT_CD,RTE_LVL,STAT_MDFN_DT,CRTE_DT,APRV_DT,FNL_DT,RTE_STAT_MDFN_DT,TTL,APP_DOC_ID,DOC_VER_NBR,INITR_PRNCPL_ID,VER_NBR,RTE_PRNCPL_ID,DTYPE,OBJ_ID,APP_DOC_STAT,APP_DOC_STAT_MDFN_DT) VALUES ('test-5','testType','I',0,SYSDATE,SYSDATE,NULL,NULL,NULL,NULL,NULL,1,'admin',2,NULL,NULL,'ee',NULL,NULL)
/
INSERT INTO krew_doc_hdr_t (DOC_HDR_ID,DOC_TYP_ID,DOC_HDR_STAT_CD,RTE_LVL,STAT_MDFN_DT,CRTE_DT,APRV_DT,FNL_DT,RTE_STAT_MDFN_DT,TTL,APP_DOC_ID,DOC_VER_NBR,INITR_PRNCPL_ID,VER_NBR,RTE_PRNCPL_ID,DTYPE,OBJ_ID,APP_DOC_STAT,APP_DOC_STAT_MDFN_DT) VALUES ('test-6','testType','F',0,SYSDATE,SYSDATE,SYSDATE,SYSDATE,SYSDATE,'New PeopleFlowBo - Description for Document ',NULL,1,'admin',9,'admin',NULL,'ff',NULL,NULL)
/
INSERT INTO krew_doc_hdr_t (DOC_HDR_ID,DOC_TYP_ID,DOC_HDR_STAT_CD,RTE_LVL,STAT_MDFN_DT,CRTE_DT,APRV_DT,FNL_DT,RTE_STAT_MDFN_DT,TTL,APP_DOC_ID,DOC_VER_NBR,INITR_PRNCPL_ID,VER_NBR,RTE_PRNCPL_ID,DTYPE,OBJ_ID,APP_DOC_STAT,APP_DOC_STAT_MDFN_DT) VALUES ('test-7','testType','F',0,SYSDATE,SYSDATE,SYSDATE,SYSDATE,SYSDATE,'Edit AgendaEditor - Modify Agenda Editor Document ',NULL,1,'admin',9,'admin',NULL,'gg',NULL,NULL)
/
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID,PRNCPL_ID,ASND_DT,RQST_CD,ACTN_RQST_ID,DOC_HDR_ID,ROLE_NM,DLGN_PRNCPL_ID,DOC_HDR_TTL,DOC_TYP_LBL,DOC_HDLR_URL,DOC_TYP_NM,RSP_ID,DLGN_TYP,VER_NBR,DTYPE,GRP_ID,DLGN_GRP_ID,RQST_LBL) VALUES ('test-1','admin',SYSDATE,'C','2369','3046',NULL,NULL,'Rest Test title','KRMS Agenda Editor Maintenance Document','http://localhost:8080/kr-dev/kr-krad/krmsAgendaEditor?methodToCall=docHandler','AgendaEditorMaintenanceDocument','-3',NULL,0,NULL,NULL,NULL,NULL)
/
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID,PRNCPL_ID,ASND_DT,RQST_CD,ACTN_RQST_ID,DOC_HDR_ID,ROLE_NM,DLGN_PRNCPL_ID,DOC_HDR_TTL,DOC_TYP_LBL,DOC_HDLR_URL,DOC_TYP_NM,RSP_ID,DLGN_TYP,VER_NBR,DTYPE,GRP_ID,DLGN_GRP_ID,RQST_LBL) VALUES ('test-2','admin',SYSDATE,'C','2370','3047',NULL,NULL,'Rest Test title','Travel Authorization Document','http://localhost:8080/krad-dev/kr-krad/approval?methodToCall=docHandler','TravelAuthorization','-3',NULL,0,NULL,NULL,NULL,NULL)
/
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID,PRNCPL_ID,ASND_DT,RQST_CD,ACTN_RQST_ID,DOC_HDR_ID,ROLE_NM,DLGN_PRNCPL_ID,DOC_HDR_TTL,DOC_TYP_LBL,DOC_HDLR_URL,DOC_TYP_NM,RSP_ID,DLGN_TYP,VER_NBR,DTYPE,GRP_ID,DLGN_GRP_ID,RQST_LBL) VALUES ('test-3','admin',SYSDATE,'C','2371','3048',NULL,NULL,'Rest Test title','Travel Authorization Document','http://localhost:8080/krad-dev/kr-krad/approval?methodToCall=docHandler','TravelAuthorization','-3',NULL,0,NULL,NULL,NULL,NULL)
/
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID,PRNCPL_ID,ASND_DT,RQST_CD,ACTN_RQST_ID,DOC_HDR_ID,ROLE_NM,DLGN_PRNCPL_ID,DOC_HDR_TTL,DOC_TYP_LBL,DOC_HDLR_URL,DOC_TYP_NM,RSP_ID,DLGN_TYP,VER_NBR,DTYPE,GRP_ID,DLGN_GRP_ID,RQST_LBL) VALUES ('test-4','admin',SYSDATE,'C','2412','3137',NULL,NULL,'Rest Test title','Travel Authorization Document','http://localhost:8080/krad-dev/kr-krad/approval?methodToCall=docHandler','TravelAuthorization','-3',NULL,0,NULL,NULL,NULL,NULL)
/
INSERT INTO krew_doc_typ_t (DOC_TYP_ID,PARNT_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,ACTV_IND,CUR_IND,LBL,PREV_DOC_TYP_VER_NBR,DOC_TYP_DESC,DOC_HDLR_URL,POST_PRCSR,JNDI_URL,BLNKT_APPR_PLCY,ADV_DOC_SRCH_URL,RTE_VER_NBR,NOTIFY_ADDR,APPL_ID,EMAIL_XSL,SEC_XML,VER_NBR,BLNKT_APPR_GRP_ID,RPT_GRP_ID,GRP_ID,HELP_DEF_URL,OBJ_ID,DOC_SEARCH_HELP_URL,DOC_HDR_ID,AUTHORIZER) VALUES ('testType',NULL,'TestRiceDocument',0,1,1,'Workflow Maintenance Document',NULL,'Workflow Maintenance Document','docHandler is now mandatory...','none',NULL,NULL,NULL,'2',NULL,NULL,NULL,NULL,1,'1',NULL,'1','','5b4187a7-3d92-4197-8755-aff2a7f5055c','',NULL,NULL)
/
INSERT INTO krim_grp_t (GRP_ID,VER_NBR,GRP_NM,NMSPC_CD,GRP_DESC,KIM_TYP_ID,ACTV_IND,LAST_UPDT_DT,OBJ_ID) VALUES ('TEST-GROUP-ID-1',1,'TEST-NAME-1','TEST-CODE','TEST-DESC','1','Y',NULL,'aaa')
/
INSERT INTO krim_grp_t (GRP_ID,VER_NBR,GRP_NM,NMSPC_CD,GRP_DESC,KIM_TYP_ID,ACTV_IND,LAST_UPDT_DT,OBJ_ID) VALUES ('TEST-GROUP-ID-2',1,'TEST-NAME-2','TEST-CODE','TEST-DESC','1','Y',NULL,'bbb')
/
INSERT INTO krim_grp_mbr_t (GRP_MBR_ID,GRP_ID,MBR_ID,MBR_TYP_CD,ACTV_FRM_DT,ACTV_TO_DT,LAST_UPDT_DT,OBJ_ID) VALUES ('test-1','TEST-GROUP-ID-1','TEST-MEMBER-ID-1','P',NULL,NULL,NULL,'ccc')
/
INSERT INTO krim_grp_mbr_t (GRP_MBR_ID,GRP_ID,MBR_ID,MBR_TYP_CD,ACTV_FRM_DT,ACTV_TO_DT,LAST_UPDT_DT,OBJ_ID) VALUES ('test-2','TEST-GROUP-ID-1','TEST-GROUP-ID-2','G',NULL,NULL,NULL,'ddd')
/
INSERT INTO krim_grp_mbr_t (GRP_MBR_ID,GRP_ID,MBR_ID,MBR_TYP_CD,ACTV_FRM_DT,ACTV_TO_DT,LAST_UPDT_DT,OBJ_ID) VALUES ('test-3','TEST-GROUP-ID-1','TEST-MEMBER-ID-3','P',NULL,NULL,NULL,'eee')
/
