-- 
-- Copyright 2009 The Kuali Foundation
-- 
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
-- http://www.opensource.org/licenses/ecl2.php
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
-- 

--KULRICE-3635
ALTER TABLE KRIM_PND_ROLE_MBR_MT
DROP COLUMN MBR_NM
/ 

--KULRICE-3636
ALTER INDEX EN_DOC_TYP_TI1 RENAME TO KREW_DOC_TYP_TI1
/
ALTER INDEX EN_RULE_TMPL_TI1 RENAME TO KREW_RULE_TMPL_TI1
/
ALTER INDEX FP_DOC_HEADER_TC0 RENAME TO KRNS_DOC_HDR_TC0
/
ALTER INDEX FP_MAINT_DOC_ATTACHMENT_TC0 RENAME TO KRNS_MAINT_DOC_ATT_TC0
/
ALTER INDEX FP_MAINT_LOCK_TC0 RENAME TO KRNS_MAINT_LOCK_TC0
/
ALTER INDEX FP_MAINTENANCE_DOCUMENT_TC0 RENAME TO KRNS_MAINT_DOC_TC0
/
ALTER INDEX FS_ADHOC_RTE_ACTN_RECP_TC0 RENAME TO KRNS_ADHOC_RTE_ACTN_RECIP_TC0
/
ALTER INDEX FS_LOOKUP_RESULTS_MTC0 RENAME TO KRNS_LOOKUP_RSLT_TC0
/
ALTER INDEX FS_LOOKUP_SELECTIONS_MTC0 RENAME TO KRNS_LOOKUP_SEL_TC0
/
ALTER INDEX KCB_MESSAGES_UK1 RENAME TO KREN_MSG_TC0
/
ALTER INDEX KCB_MSG_DELIVS_UK1 RENAME TO KREN_MSG_DELIV_TC0
/
ALTER INDEX KCB_RECIP_PREFS_UK1 RENAME TO KREN_RECIP_PREFS_TC0
/
ALTER INDEX KNS_PESSIMISTIC_LOCK_TC0 RENAME TO KRNS_PESSIMISTIC_LOCK_TC0
/
ALTER INDEX KR_KIM_ADDR_TYPE_TC0 RENAME TO KRIM_ADDR_TYP_TC0
/
ALTER INDEX KR_KIM_ADDR_TYPE_TC1 RENAME TO KRIM_ADDR_TYP_TC1
/
ALTER INDEX KR_KIM_AFLTN_TYPE_TC0 RENAME TO KRIM_AFLTN_TYP_TC0
/
ALTER INDEX KR_KIM_AFLTN_TYPE_TC1 RENAME TO KRIM_AFLTN_TYP_TC1
/
ALTER INDEX KR_KIM_ATTRIBUTE_TC0 RENAME TO KRIM_ATTR_DEFN_TC0
/
ALTER INDEX KR_KIM_CTZNSHP_STAT_TC0 RENAME TO KRIM_CTZNSHP_STAT_TC0
/
ALTER INDEX KR_KIM_CTZNSHP_STAT_TC1 RENAME TO KRIM_CTZNSHP_STAT_TC1
/
ALTER INDEX KR_KIM_DELE_MBR_ATTR_DATA_TC0 RENAME TO KRIM_DLGN_MBR_ATTR_DATA_TC0
/
ALTER INDEX KR_KIM_DELE_TC0 RENAME TO KRIM_DLGN_TC0
/
ALTER INDEX KR_KIM_EMAIL_TYPE_TC0 RENAME TO KRIM_EMAIL_TYP_TC0
/
ALTER INDEX KR_KIM_EMAIL_TYPE_TC1 RENAME TO KRIM_EMAIL_TYP_TC1
/
ALTER INDEX KR_KIM_EMP_STAT_TC0 RENAME TO KRIM_EMP_STAT_TC0
/
ALTER INDEX KR_KIM_EMP_STAT_TC1 RENAME TO KRIM_EMP_STAT_TC1
/
ALTER INDEX KR_KIM_EMP_TYPE_TC0 RENAME TO KRIM_EMP_TYP_TC0
/
ALTER INDEX KR_KIM_EMP_TYPE_TC1 RENAME TO KRIM_EMP_TYP_TC1
/
ALTER INDEX KR_KIM_ENT_NAME_TYPE_TC0 RENAME TO KRIM_ENT_NM_TYP_TC0
/
ALTER INDEX KR_KIM_ENT_NAME_TYPE_TC1 RENAME TO KRIM_ENT_NM_TYP_TC1
/
ALTER INDEX KR_KIM_ENT_TYPE_TC0 RENAME TO KRIM_ENT_TYP_TC0
/
ALTER INDEX KR_KIM_ENT_TYPE_TC1 RENAME TO KRIM_ENT_TYP_TC1
/
ALTER INDEX KR_KIM_ENTITY_ADDR_TC0 RENAME TO KRIM_ENTITY_ADDR_TC0
/
ALTER INDEX KR_KIM_ENTITY_AFLTN_TC0 RENAME TO KRIM_ENTITY_AFLTN_TC0
/
ALTER INDEX KR_KIM_ENTITY_BIO_TC0 RENAME TO KRIM_ENTITY_BIO_TC0
/
ALTER INDEX KR_KIM_ENTITY_CTZNSHP_TC0 RENAME TO KRIM_ENTITY_CTZNSHP_TC0
/
ALTER INDEX KR_KIM_ENTITY_EMAIL_TC0 RENAME TO KRIM_ENTITY_EMAIL_TC0
/
ALTER INDEX KR_KIM_ENTITY_EMP_INFO_TC0 RENAME TO KRIM_ENTITY_EMP_INFO_TC0
/
ALTER INDEX KR_KIM_ENTITY_EXT_ID_TC0 RENAME TO KRIM_ENTITY_EXT_ID_TC0
/
ALTER INDEX KR_KIM_ENTITY_NAME_TC0 RENAME TO KRIM_ENTITY_NM_TC0
/
ALTER INDEX KR_KIM_ENTITY_PHONE_TC0 RENAME TO KRIM_ENTITY_PHONE_TC0
/
ALTER INDEX KR_KIM_ENTITY_PRIV_PREF_TC0 RENAME TO KRIM_ENTITY_PRIV_PREF_TC0
/
ALTER INDEX KR_KIM_ENTITY_TC0 RENAME TO KRIM_ENTITY_TC0
/
ALTER INDEX KR_KIM_EXT_ID_TYPE_TC0 RENAME TO KRIM_EXT_ID_TYP_TC0
/
ALTER INDEX KR_KIM_EXT_ID_TYPE_TC1 RENAME TO KRIM_EXT_ID_TYP_TC1
/
ALTER INDEX KR_KIM_GROUP_ATTR_DATA_TC0 RENAME TO KRIM_GRP_ATTR_DATA_TC0
/
ALTER INDEX KR_KIM_GROUP_TC0 RENAME TO KRIM_GRP_TC0
/
ALTER INDEX KR_KIM_GROUP_TC1 RENAME TO KRIM_GRP_TC1
/
ALTER INDEX KR_KIM_PERM_ATTR_DATA_TC0 RENAME TO KRIM_PERM_ATTR_DATA_TC0
/
ALTER INDEX KR_KIM_PERM_TC0 RENAME TO KRIM_PERM_TC0
/
ALTER INDEX KR_KIM_PERM_TMPL_TC0 RENAME TO KRIM_PERM_TMPL_TC0
/
ALTER INDEX KR_KIM_PHONE_TYPE_TC0 RENAME TO KRIM_PHONE_TYP_TC0
/
ALTER INDEX KR_KIM_PHONE_TYPE_TC1 RENAME TO KRIM_PHONE_TYP_TC1
/
ALTER INDEX KR_KIM_PRINCIPAL_TC0 RENAME TO KRIM_PRNCPL_TC0
/
ALTER INDEX KR_KIM_PRINCIPAL_TC1 RENAME TO KRIM_PRNCPL_TC1
/
ALTER INDEX KR_KIM_RESP_ATTR_DATA_TC0 RENAME TO KRIM_RSP_ATTR_DATA_TC0
/
ALTER INDEX KR_KIM_RESP_TC0 RENAME TO KRIM_RSP_TC0
/
ALTER INDEX KR_KIM_RESP_TMPL_TC0 RENAME TO KRIM_RSP_TMPL_TC0
/
ALTER INDEX KR_KIM_ROLE_MBR_ATTR_DATA_TC0 RENAME TO KRIM_ROLE_MBR_ATTR_DATA_TC0
/
ALTER INDEX KR_KIM_ROLE_PERM_TC0 RENAME TO KRIM_ROLE_PERM_TC0
/
ALTER INDEX KR_KIM_ROLE_RESP_ACTN_TC0 RENAME TO KRIM_ROLE_RSP_ACTN_TC0
/
ALTER INDEX KR_KIM_ROLE_RESP_TC0 RENAME TO KRIM_ROLE_RSP_TC0
/
ALTER INDEX KR_KIM_ROLE_TC0 RENAME TO KRIM_ROLE_TC0
/
ALTER INDEX KR_KIM_ROLE_TC1 RENAME TO KRIM_ROLE_TC1
/
ALTER INDEX KR_KIM_TYPE_ATTRIBUTE_TC0 RENAME TO KRIM_TYP_ATTR_TC0
/
ALTER INDEX KR_KIM_TYPE_TC0 RENAME TO KRIM_TYP_TC0
/
ALTER INDEX NOTIF_MSG_DELIVS_UK1 RENAME TO KREN_NTFCTN_MSG_DELIV_TC0
/
ALTER INDEX NOTIFICATION_CHANNELS_UK1 RENAME TO KREN_CHNL_TC0
/
ALTER INDEX NOTIFICATION_CONTENT_TYPE_UK1 RENAME TO KREN_CNTNT_TYP_TC0
/
ALTER INDEX NOTIFICATION_PRIORITIES_UK1 RENAME TO KREN_PRIO_TC0
/
ALTER INDEX NOTIFICATION_PRODUCERS_UK1 RENAME TO KREN_PRODCR_TC0
/
ALTER INDEX NOTIFICATION_RECIPIENTS_L_UK1 RENAME TO KREN_RECIP_LIST_TC0
/
ALTER INDEX NOTIFICATION_RECIPIENTS_UK1 RENAME TO KREN_RECIP_TC0
/
ALTER INDEX NOTIFICATION_REVIEWERS_UK1 RENAME TO KREN_RVWER_TC0
/
ALTER INDEX NOTIFICATION_SENDERS_UK1 RENAME TO KREN_SNDR_TC0
/
ALTER INDEX SH_ATT_TC0 RENAME TO KRNS_ATT_TC0
/
ALTER INDEX SH_CAMPUS_TC0 RENAME TO KRNS_CAMPUS_TC0
/
ALTER INDEX SH_CMP_TYP_TC0 RENAME TO KRNS_CMP_TYP_TC0
/
ALTER INDEX SH_NTE_TC0 RENAME TO KRNS_NTE_TC0
/
ALTER INDEX SH_NTE_TYP_TC0 RENAME TO KRNS_NTE_TYP_TC0
/
ALTER INDEX SH_PARM_DTL_TYP_TC0 RENAME TO KRNS_PARM_DTL_TYP_TC0
/
ALTER INDEX SH_PARM_NMSPC_TC0 RENAME TO KRNS_NMSPC_TC0
/
ALTER INDEX SH_PARM_TC0 RENAME TO KRNS_PARM_TC0
/
ALTER INDEX SH_PARM_TYP_TC0 RENAME TO KRNS_PARM_TYP_TC0
/
ALTER INDEX USER_CHANNEL_SUBSCRIPTION_UK1 RENAME TO KREN_CHNL_SUBSCRP_TC0
/ 

