ALTER TABLE KRNS_LOOKUP_RSLT_T MODIFY PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KRNS_LOOKUP_SEL_T MODIFY PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KRNS_NTE_T MODIFY AUTH_PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T MODIFY PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_ACTN_ITM_T MODIFY PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_ACTN_ITM_T MODIFY DLGN_PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_ACTN_RQST_T MODIFY PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_ACTN_TKN_T MODIFY PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_ACTN_TKN_T MODIFY DLGTR_PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_DOC_HDR_T MODIFY INITR_PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_DOC_HDR_T MODIFY RTE_PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_DOC_NTE_T MODIFY AUTH_PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_EDL_DMP_T MODIFY DOC_HDR_INITR_PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_OUT_BOX_ITM_T MODIFY PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_OUT_BOX_ITM_T MODIFY DLGN_PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_RMV_RPLC_DOC_T MODIFY PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_RMV_RPLC_DOC_T MODIFY RPLC_PRNCPL_ID VARCHAR2(40)
/
ALTER TABLE KREW_USR_OPTN_T MODIFY PRNCPL_ID VARCHAR2(40)
/
