ALTER TABLE KIM_ROLE_ATTRIBUTES_T 
ADD CONSTRAINT KIM_ROLE_ATTRIBUTES_UK1 UNIQUE
(
ROLE_ID,
ATTRIBUTE_NAME
) ENABLE
/
ALTER TABLE KIM_ROLE_ATTRIBUTES_T
ADD CONSTRAINT KIM_ROLE_ATTRIBUTES_FK1 FOREIGN KEY
(
ROLE_ID
)
REFERENCES KIM_ROLES_T
(
ID
) ENABLE
/
ALTER TABLE KIM_ROLE_ATTRIBUTES_T
ADD CONSTRAINT KIM_ROLE_ATTRIBUTES_FK2 FOREIGN KEY
(
ATTRIBUTE_TYPE_ID
)
REFERENCES KIM_ATTRIBUTE_TYPES_T
(
ID
) ENABLE
/