ALTER TABLE KIM_GROUP_QLFD_ROLES_T 
ADD CONSTRAINT KIM_GROUP_QLFD_ROLES_UK1 UNIQUE
(
GROUP_ID,
ROLE_ID,
ATTRIBUTE_NAME
) ENABLE
/
ALTER TABLE KIM_GROUP_QLFD_ROLES_T
ADD CONSTRAINT KIM_GROUP_QLFD_ROLES_FK1 FOREIGN KEY
(
GROUP_ID
)
REFERENCES KIM_GROUPS_T
(
ID
) ENABLE
/
ALTER TABLE KIM_GROUP_QLFD_ROLES_T
ADD CONSTRAINT KIM_GROUP_QLFD_ROLES_FK2 FOREIGN KEY
(
ROLE_ID
)
REFERENCES KIM_ROLES_T
(
ID
) ENABLE
/