ALTER TABLE KIM_GRP_TYP_DFLT_ATTRIBS_T 
ADD CONSTRAINT KIM_GRPTYP_DFLT_ATTR_UK1 UNIQUE
(
GROUP_TYPE_ID,
ATTRIBUTE_NAME
) ENABLE
/
ALTER TABLE KIM_GRP_TYP_DFLT_ATTRIBS_T
ADD CONSTRAINT KIM_GRPTYP_DFLT_ATTR_FK1 FOREIGN KEY
(
GROUP_TYPE_ID
)
REFERENCES KIM_GROUP_TYPES_T
(
ID
) ENABLE
/
ALTER TABLE KIM_GRP_TYP_DFLT_ATTRIBS_T
ADD CONSTRAINT KIM_GRPTYP_DFLT_ATTR_FK2 FOREIGN KEY
(
ATTRIBUTE_TYPE_ID
)
REFERENCES KIM_ATTRIBUTE_TYPES_T
(
ID
) ENABLE
/