ALTER TABLE KIM_PERMISSIONS_T 
ADD CONSTRAINT KIM_PERMISSIONS_UK1 UNIQUE
(
NAME,
NAMESPACE_ID
) ENABLE
/
ALTER TABLE KIM_PERMISSIONS_T
ADD CONSTRAINT KIM_PERMISSIONS_FK1 FOREIGN KEY
(
NAMESPACE_ID
)
REFERENCES KIM_NAMESPACES_T
(
ID
) ENABLE
/