ALTER TABLE NOTIFICATION_REVIEWERS
ADD CONSTRAINT NOTIFICATION_REVIEWERS_UK1 UNIQUE
(
CHANNEL_ID,
REVIEWER_TYPE,
REVIEWER_ID
)
 ENABLE
/

ALTER TABLE NOTIFICATION_REVIEWERS
ADD CONSTRAINT NOTIFICATION_REVIEWERS_N_FK1 FOREIGN KEY
(
CHANNEL_ID
)
REFERENCES NOTIFICATION_CHANNELS
(
ID
) ENABLE
/