ALTER TABLE NOTIFICATION_CHANNEL_PRODUCERS
ADD CONSTRAINT NOTIFICATION_CHANNEL_PROD_FK1 FOREIGN KEY
(
CHANNEL_ID
)
REFERENCES NOTIFICATION_CHANNELS
(
ID
) ENABLE
/

ALTER TABLE NOTIFICATION_CHANNEL_PRODUCERS
ADD CONSTRAINT NOTIFICATION_CHANNEL_PROD_FK2 FOREIGN KEY
(
PRODUCER_ID
)
REFERENCES NOTIFICATION_PRODUCERS
(
ID
) ENABLE
/