ALTER TABLE NOTIFICATION_RECIPIENTS
ADD CONSTRAINT NOTIFICATION_RECIPIENTS_UK1 UNIQUE
(
NOTIFICATION_ID,
RECIPIENT_TYPE,
RECIPIENT_ID
)
 ENABLE
/

ALTER TABLE NOTIFICATION_RECIPIENTS
ADD CONSTRAINT NOTIFICATION_RECIPIENTS_N_FK1 FOREIGN KEY
(
NOTIFICATION_ID
)
REFERENCES NOTIFICATIONS
(
ID
) ENABLE
/