ALTER TABLE NOTIFICATION_RECIPIENTS_LISTS
ADD CONSTRAINT NOTIFICATION_RECIPIENTS_L_UK1 UNIQUE
(
CHANNEL_ID,
RECIPIENT_TYPE,
RECIPIENT_ID
)
 ENABLE
/

ALTER TABLE NOTIFICATION_RECIPIENTS_LISTS
ADD CONSTRAINT NOTIFICATION_RECIPIENTS_L_FK1 FOREIGN KEY
(
CHANNEL_ID
)
REFERENCES NOTIFICATION_CHANNELS
(
ID
) ENABLE
/