ALTER TABLE USER_CHANNEL_SUBSCRIPTIONS
ADD CONSTRAINT USER_CHANNEL_SUBSCRIPTION_UK1 UNIQUE
(
CHANNEL_ID,
USER_ID
)
 ENABLE
/

ALTER TABLE USER_CHANNEL_SUBSCRIPTIONS
ADD CONSTRAINT USER_CHANNEL_SUBSCRIPTION_FK1 FOREIGN KEY
(
CHANNEL_ID
)
REFERENCES NOTIFICATION_CHANNELS
(
ID
) ENABLE
/