-- Note: some of these tables were already dropped in previous versions of Rice, so they may or may not be in your database 

DROP TABLE EN_SERVICE_DEF_T
/
DROP TABLE EN_SERVICE_DEF_INTER_T
/
DROP TABLE EN_WRKGRP_EXT_T
/
DROP TABLE EN_WRKGRP_EXT_DTA_T
/
DROP TABLE EN_WRKGRP_TYP_T
/
DROP TABLE EN_WRKGRP_MBR_T
/
DROP TABLE EN_WRKGRP_TYP_ATTRIB_T
/
DROP TABLE EN_ORG_RESP_ID_T
/
DROP TABLE EN_DOC_RTE_TYP_T
/
DROP TABLE EN_WRKGRP_T
/
DROP TABLE EN_USR_T
/
DROP TABLE EN_DIRTY_CACHE_T
/
DROP TABLE EN_CACHE_SERVER_T
/
DROP TABLE EN_RULE_ATTRIB_VLD_VAL_T
/
DROP TABLE EN_RULE_ATTRIB_KEY_VAL_T
/
DROP TABLE EN_TRANSACTION_TST_PRSN_T
/
DROP TABLE EN_TRANSACTION_TST_ADDRS_T
/
DROP TABLE EN_MESSAGE_QUE_T
/