-- update various reference tables so that we can build maintenance docs on top of them

alter table NOTIFICATION_CHANNELS add (OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, VER_NBR NUMBER(8) DEFAULT 1 NOT NULL) /
alter table NOTIFICATION_CONTENT_TYPES add (OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, VER_NBR NUMBER(8) DEFAULT 1 NOT NULL) /
alter table NOTIFICATION_PRODUCERS add (OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, VER_NBR NUMBER(8) DEFAULT 1 NOT NULL) /
alter table NOTIFICATION_PRIORITIES add (OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, VER_NBR NUMBER(8) DEFAULT 1 NOT NULL) /
alter table NOTIFICATION_REVIEWERS add (OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, VER_NBR NUMBER(8) DEFAULT 1 NOT NULL) /
