-- update various reference tables so that we can build maintenance docs on top of them

alter table KREN_CHNL_T add (OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, VER_NBR NUMBER(8) DEFAULT 1 NOT NULL) /
alter table KREN_CNTNT_TYP_T add (OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, VER_NBR NUMBER(8) DEFAULT 1 NOT NULL) /
alter table KREN_PRODCR_T add (OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, VER_NBR NUMBER(8) DEFAULT 1 NOT NULL) /
alter table KREN_PRIO_T add (OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, VER_NBR NUMBER(8) DEFAULT 1 NOT NULL) /
alter table KREN_RVWER_T add (OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, VER_NBR NUMBER(8) DEFAULT 1 NOT NULL) /
