ALTER TABLE EN_ACTN_ITM_T RENAME TO KREW_ACTN_ITM_T
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_ID TO ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_ASND_DT TO ASND_DT
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_RQST_CD TO RQST_CD
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_DLGN_PRSN_EN_ID TO DLGN_PRNCPL_ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_DLGN_WRKGRP_ID TO DLGN_WRKGRP_ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN DOC_TYP_LBL_TXT TO LBL_TXT
/
DROP INDEX EN_ACTN_ITM_T1 
/
CREATE INDEX KREW_ACTN_ITM_T1 ON KREW_ACTN_ITM_T (PRNCPL_ID)
/
DROP INDEX EN_ACTN_ITM_TI2 
/
CREATE INDEX KREW_ACTN_ITM_TI2 ON KREW_ACTN_ITM_T (DOC_HDR_ID)
/
DROP INDEX EN_ACTN_ITM_TI3 
/
CREATE INDEX KREW_ACTN_ITM_TI3 ON KREW_ACTN_ITM_T (ACTN_RQST_ID)
/
DROP INDEX EN_ACTN_ITM_TI4 
/
CREATE INDEX KREW_ACTN_ITM_TI4 ON KREW_ACTN_ITM_T (DLGN_PRNCPL_ID)
/
DROP INDEX EN_ACTN_ITM_TI4 
/
CREATE INDEX KREW_ACTN_ITM_TI4 ON KREW_ACTN_ITM_T (DLGN_PRNCPL_ID,DLGN_WRKGRP_ID)
/
DROP INDEX EN_ACTN_ITM_TI4 
/
CREATE INDEX KREW_ACTN_ITM_TI4 ON KREW_ACTN_ITM_T (DLGN_PRNCPL_ID,DLGN_WRKGRP_ID,PRNCPL_ID)
/
DROP INDEX EN_ACTN_ITM_TI4 
/
CREATE INDEX KREW_ACTN_ITM_TI4 ON KREW_ACTN_ITM_T (DLGN_PRNCPL_ID,DLGN_WRKGRP_ID,PRNCPL_ID,DLGN_TYP)
/
DROP INDEX EN_ACTN_ITM_TI5 
/
CREATE INDEX KREW_ACTN_ITM_TI5 ON KREW_ACTN_ITM_T (PRNCPL_ID)
/
DROP INDEX EN_ACTN_ITM_TI5 
/
CREATE INDEX KREW_ACTN_ITM_TI5 ON KREW_ACTN_ITM_T (PRNCPL_ID,DLGN_TYP)
/
DROP INDEX EN_ACTN_ITM_TI5 
/
CREATE INDEX KREW_ACTN_ITM_TI5 ON KREW_ACTN_ITM_T (PRNCPL_ID,DLGN_TYP,DOC_HDR_ID)
/
ALTER TABLE EN_ACTN_RQST_T RENAME TO KREW_ACTN_RQST_T
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_ID TO ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_PARNT_ID TO PARNT_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_CD TO CD
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_STAT_CD TO STAT_CD
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RESP_ID TO RESP_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RECP_TYP_CD TO RECP_TYP_CD
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_PRIO_NBR TO PRIO_NBR
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RTE_TYP_NM TO RTE_TYP_NM
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RTE_LVL_NBR TO RTE_LVL_NBR
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RTE_NODE_INSTN_ID TO RTE_NODE_INSTN_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_CRTE_DT TO CRTE_DT
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RESP_DESC TO RESP_DESC
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_IGN_PREV_ACTN_IND TO IGN_PREV_ACTN_IND
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_APPR_PLCY TO APPR_PLCY
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_CUR_IND TO CUR_IND
/
DROP INDEX EN_ACTN_RQST_T13 
/
CREATE INDEX KREW_ACTN_RQST_T13 ON KREW_ACTN_RQST_T (ACTN_TKN_ID)
/
DROP INDEX EN_ACTN_RQST_T14 
/
CREATE INDEX KREW_ACTN_RQST_T14 ON KREW_ACTN_RQST_T (PARNT_ID)
/
DROP INDEX EN_ACTN_RQST_TI1 
/
CREATE INDEX KREW_ACTN_RQST_T11 ON KREW_ACTN_RQST_T (DOC_HDR_ID)
/
DROP INDEX EN_ACTN_RQST_TI2 
/
CREATE INDEX KREW_ACTN_RQST_T12 ON KREW_ACTN_RQST_T (PRNCPL_ID)
/
DROP INDEX EN_ACTN_RQST_TI5 
/
CREATE INDEX KREW_ACTN_RQST_T15 ON KREW_ACTN_RQST_T (RESP_ID)
/
DROP INDEX EN_ACTN_RQST_TI6 
/
CREATE INDEX KREW_ACTN_RQST_T16 ON KREW_ACTN_RQST_T (STAT_CD)
/
DROP INDEX EN_ACTN_RQST_TI6 
/
CREATE INDEX KREW_ACTN_RQST_T16 ON KREW_ACTN_RQST_T (STAT_CD,RESP_ID)
/
DROP INDEX EN_ACTN_RQST_TI7 
/
CREATE INDEX KREW_ACTN_RQST_T17 ON KREW_ACTN_RQST_T (RTE_NODE_INSTN_ID)
/
DROP INDEX EN_ACTN_RQST_TI8 
/
CREATE INDEX KREW_ACTN_RQST_T18 ON KREW_ACTN_RQST_T (GRP_ID)
/
DROP INDEX EN_ACTN_RQST_TI9 
/
CREATE INDEX KREW_ACTN_RQST_T19 ON KREW_ACTN_RQST_T (STAT_CD)
/
DROP INDEX EN_ACTN_RQST_TI9 
/
CREATE INDEX KREW_ACTN_RQST_T19 ON KREW_ACTN_RQST_T (STAT_CD,DOC_HDR_ID)
/
ALTER TABLE EN_ACTN_TKN_T RENAME TO KREW_ACTN_TKN_T
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_ID TO ID
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_DLGTR_PRSN_EN_ID TO DLGTR_PRNCPL_ID
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_DLGTR_WRKGRP_ID TO DLGTR_WRKGRP_ID
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_CD TO CD
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_DT TO DT
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_ANNOTN_TXT TO ANNOTN_TXT
/
DROP INDEX EN_ACTN_TKN_TI1 
/
CREATE INDEX KREW_ACTN_TKN_TI1 ON KREW_ACTN_TKN_T (DOC_HDR_ID)
/
DROP INDEX EN_ACTN_TKN_TI1 
/
CREATE INDEX KREW_ACTN_TKN_TI1 ON KREW_ACTN_TKN_T (DOC_HDR_ID,PRNCPL_ID)
/
DROP INDEX EN_ACTN_TKN_TI2 
/
CREATE INDEX KREW_ACTN_TKN_TI2 ON KREW_ACTN_TKN_T (DOC_HDR_ID)
/
DROP INDEX EN_ACTN_TKN_TI2 
/
CREATE INDEX KREW_ACTN_TKN_TI2 ON KREW_ACTN_TKN_T (DOC_HDR_ID,PRNCPL_ID)
/
DROP INDEX EN_ACTN_TKN_TI2 
/
CREATE INDEX KREW_ACTN_TKN_TI2 ON KREW_ACTN_TKN_T (DOC_HDR_ID,PRNCPL_ID,CD)
/
DROP INDEX EN_ACTN_TKN_TI3 
/
CREATE INDEX KREW_ACTN_TKN_TI3 ON KREW_ACTN_TKN_T (PRNCPL_ID)
/
DROP INDEX EN_ACTN_TKN_TI4 
/
CREATE INDEX KREW_ACTN_TKN_TI4 ON KREW_ACTN_TKN_T (DLGTR_PRNCPL_ID)
/
DROP INDEX EN_ACTN_TKN_TI5 
/
CREATE INDEX KREW_ACTN_TKN_TI5 ON KREW_ACTN_TKN_T (DOC_HDR_ID)
/
ALTER TABLE EN_APPL_CNST_T RENAME TO KREW_APPL_CNST_T
/
ALTER TABLE KREW_APPL_CNST_T RENAME COLUMN APPL_CNST_NM TO NM
/
ALTER TABLE KREW_APPL_CNST_T RENAME COLUMN APPL_CNST_VAL_TXT TO VAL_TXT
/
ALTER TABLE EN_ATTACHMENT_T RENAME TO KREW__ATTACHMENT_T
/
ALTER TABLE KREW__ATTACHMENT_T RENAME COLUMN ATTACHMENT_ID TO ID
/
ALTER TABLE EN_BAM_PARAM_T RENAME TO KREW_BAM_PARAM_T
/
ALTER TABLE KREW_BAM_PARAM_T RENAME COLUMN BAM_PARAM_ID TO PARAM_ID
/
ALTER TABLE KREW_BAM_PARAM_T RENAME COLUMN BAM_ID TO ID
/
DROP INDEX EN_BAM_PARAM_TI1 
/
CREATE INDEX KREW_BAM_PARAM_TI1 ON KREW_BAM_PARAM_T (ID)
/
ALTER TABLE EN_BAM_T RENAME TO KREW_BAM_T
/
DROP INDEX EN_BAM_TI1 
/
CREATE INDEX KREW_BAM_TI1 ON KREW_BAM_T (SERVICE_NM)
/
DROP INDEX EN_BAM_TI1 
/
CREATE INDEX KREW_BAM_TI1 ON KREW_BAM_T (SERVICE_NM,METHOD_NM)
/
DROP INDEX EN_BAM_TI2 
/
CREATE INDEX KREW_BAM_TI2 ON KREW_BAM_T (SERVICE_NM)
/
ALTER TABLE EN_DLGN_RSP_T RENAME TO KREW_DLGN_RSP_T
/
ALTER TABLE EN_DOC_HDR_CNTNT_T RENAME TO KREW_DOC_HDR_CNTNT_T
/
ALTER TABLE EN_DOC_HDR_EXT_DT_T RENAME TO KREW_DOC_HDR_EXT_DT_T
/
ALTER TABLE KREW_DOC_HDR_EXT_DT_T RENAME COLUMN DOC_HDR_EXT_ID TO ID
/
ALTER TABLE KREW_DOC_HDR_EXT_DT_T RENAME COLUMN DOC_HDR_EXT_VAL_KEY TO VAL_KEY
/
ALTER TABLE KREW_DOC_HDR_EXT_DT_T RENAME COLUMN DOC_HDR_EXT_VAL TO VAL
/
DROP INDEX EN_DOC_HDR_EXT_DT_TI1 
/
CREATE INDEX KREW_DOC_HDR_EXT_DT_TI1 ON KREW_DOC_HDR_EXT_DT_T (VAL_KEY)
/
DROP INDEX EN_DOC_HDR_EXT_DT_TI1 
/
CREATE INDEX KREW_DOC_HDR_EXT_DT_TI1 ON KREW_DOC_HDR_EXT_DT_T (VAL_KEY,VAL)
/
DROP INDEX EN_DOC_HDR_EXT_DT_TI2 
/
CREATE INDEX KREW_DOC_HDR_EXT_DT_TI2 ON KREW_DOC_HDR_EXT_DT_T (DOC_HDR_ID)
/
DROP INDEX EN_DOC_HDR_EXT_DT_TI3 
/
CREATE INDEX KREW_DOC_HDR_EXT_DT_TI3 ON KREW_DOC_HDR_EXT_DT_T (VAL)
/
ALTER TABLE EN_DOC_HDR_EXT_FLT_T RENAME TO KREW_DOC_HDR_EXT_FLT_T
/
ALTER TABLE KREW_DOC_HDR_EXT_FLT_T RENAME COLUMN DOC_HDR_EXT_ID TO ID
/
ALTER TABLE KREW_DOC_HDR_EXT_FLT_T RENAME COLUMN DOC_HDR_EXT_VAL_KEY TO VAL_KEY
/
ALTER TABLE KREW_DOC_HDR_EXT_FLT_T RENAME COLUMN DOC_HDR_EXT_VAL TO VAL
/
DROP INDEX EN_DOC_HDR_EXT_FLT_TI1 
/
CREATE INDEX KREW_DOC_HDR_EXT_FLT_TI1 ON KREW_DOC_HDR_EXT_FLT_T (VAL_KEY)
/
DROP INDEX EN_DOC_HDR_EXT_FLT_TI1 
/
CREATE INDEX KREW_DOC_HDR_EXT_FLT_TI1 ON KREW_DOC_HDR_EXT_FLT_T (VAL_KEY,VAL)
/
DROP INDEX EN_DOC_HDR_EXT_FLT_TI2 
/
CREATE INDEX KREW_DOC_HDR_EXT_FLT_TI2 ON KREW_DOC_HDR_EXT_FLT_T (DOC_HDR_ID)
/
DROP INDEX EN_DOC_HDR_EXT_FLT_TI3 
/
CREATE INDEX KREW_DOC_HDR_EXT_FLT_TI3 ON KREW_DOC_HDR_EXT_FLT_T (VAL)
/
ALTER TABLE EN_DOC_HDR_EXT_LONG_T RENAME TO KREW_DOC_HDR_EXT_LONG_T
/
ALTER TABLE KREW_DOC_HDR_EXT_LONG_T RENAME COLUMN DOC_HDR_EXT_ID TO ID
/
ALTER TABLE KREW_DOC_HDR_EXT_LONG_T RENAME COLUMN DOC_HDR_EXT_VAL_KEY TO VAL_KEY
/
ALTER TABLE KREW_DOC_HDR_EXT_LONG_T RENAME COLUMN DOC_HDR_EXT_VAL TO VAL
/
DROP INDEX EN_DOC_HDR_EXT_LONG_TI1 
/
CREATE INDEX KREW_DOC_HDR_EXT_LONG_TI1 ON KREW_DOC_HDR_EXT_LONG_T (VAL_KEY)
/
DROP INDEX EN_DOC_HDR_EXT_LONG_TI1 
/
CREATE INDEX KREW_DOC_HDR_EXT_LONG_TI1 ON KREW_DOC_HDR_EXT_LONG_T (VAL_KEY,VAL)
/
DROP INDEX EN_DOC_HDR_EXT_LONG_TI2 
/
CREATE INDEX KREW_DOC_HDR_EXT_LONG_TI2 ON KREW_DOC_HDR_EXT_LONG_T (DOC_HDR_ID)
/
DROP INDEX EN_DOC_HDR_EXT_LONG_TI3 
/
CREATE INDEX KREW_DOC_HDR_EXT_LONG_TI3 ON KREW_DOC_HDR_EXT_LONG_T (VAL)
/
ALTER TABLE EN_DOC_HDR_EXT_T RENAME TO KREW_DOC_HDR_EXT_T
/
ALTER TABLE KREW_DOC_HDR_EXT_T RENAME COLUMN DOC_HDR_EXT_ID TO ID
/
ALTER TABLE KREW_DOC_HDR_EXT_T RENAME COLUMN DOC_HDR_EXT_VAL_KEY TO VAL_KEY
/
ALTER TABLE KREW_DOC_HDR_EXT_T RENAME COLUMN DOC_HDR_EXT_VAL TO VAL
/
DROP INDEX EN_DOC_HDR_EXT_TI1 
/
CREATE INDEX KREW_DOC_HDR_EXT_TI1 ON KREW_DOC_HDR_EXT_T (VAL_KEY)
/
DROP INDEX EN_DOC_HDR_EXT_TI1 
/
CREATE INDEX KREW_DOC_HDR_EXT_TI1 ON KREW_DOC_HDR_EXT_T (VAL_KEY,VAL)
/
DROP INDEX EN_DOC_HDR_EXT_TI2 
/
CREATE INDEX KREW_DOC_HDR_EXT_TI2 ON KREW_DOC_HDR_EXT_T (DOC_HDR_ID)
/
DROP INDEX EN_DOC_HDR_EXT_TI3 
/
CREATE INDEX KREW_DOC_HDR_EXT_TI3 ON KREW_DOC_HDR_EXT_T (VAL)
/
ALTER TABLE EN_DOC_HDR_T RENAME TO KREW_DOC_HDR_T
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_INITR_PRSN_EN_ID TO DOC_INITR_PRNCPL_ID
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_RTE_USR_PRSN_EN_ID TO DOC_RTE_USR_PRNCPL_ID
/
DROP INDEX KREW_DOC_HDR_TI1 
/
CREATE INDEX KREW_DOC_HDR_TI1 ON KREW_DOC_HDR_T (DOC_TYP_ID)
/
DROP INDEX KREW_DOC_HDR_TI2 
/
CREATE INDEX KREW_DOC_HDR_TI2 ON KREW_DOC_HDR_T (DOC_INITR_PRNCPL_ID)
/
DROP INDEX KREW_DOC_HDR_TI3 
/
CREATE INDEX KREW_DOC_HDR_TI3 ON KREW_DOC_HDR_T (DOC_RTE_STAT_CD)
/
DROP INDEX KREW_DOC_HDR_TI4 
/
CREATE INDEX KREW_DOC_HDR_TI4 ON KREW_DOC_HDR_T (DOC_TTL)
/
DROP INDEX KREW_DOC_HDR_TI5 
/
CREATE INDEX KREW_DOC_HDR_TI5 ON KREW_DOC_HDR_T (DOC_CRTE_DT)
/
DROP INDEX KREW_DOC_HDR_TI6 
/
CREATE INDEX KREW_DOC_HDR_TI6 ON KREW_DOC_HDR_T (DOC_RTE_STAT_MDFN_DT)
/
DROP INDEX KREW_DOC_HDR_TI7 
/
CREATE INDEX KREW_DOC_HDR_TI7 ON KREW_DOC_HDR_T (DOC_APRV_DT)
/
DROP INDEX KREW_DOC_HDR_TI8 
/
CREATE INDEX KREW_DOC_HDR_TI8 ON KREW_DOC_HDR_T (DOC_FNL_DT)
/
DROP INDEX KREW_DOC_HDR_TI9 
/
CREATE INDEX KREW_DOC_HDR_TI9 ON KREW_DOC_HDR_T (DOC_APPL_DOC_ID)
/
ALTER TABLE EN_DOC_NTE_T RENAME TO KREW_DOC_NTE_T
/
ALTER TABLE KREW_DOC_NTE_T RENAME COLUMN DOC_NTE_ID TO ID
/
ALTER TABLE KREW_DOC_NTE_T RENAME COLUMN DOC_NTE_AUTH_PRSN_EN_ID TO AUTH_PRNCPL_ID
/
ALTER TABLE KREW_DOC_NTE_T RENAME COLUMN DOC_NTE_CRT_DT TO CRT_DT
/
ALTER TABLE KREW_DOC_NTE_T RENAME COLUMN DOC_NTE_TXT TO TXT
/
DROP INDEX EN_DOC_NTE_TI1 
/
CREATE INDEX KREW_DOC_NTE_TI1 ON KREW_DOC_NTE_T (DOC_HDR_ID)
/
ALTER TABLE DOC_RTE_TYP_T RENAME TO KREW_DOC_RTE_TYP_T
/
ALTER TABLE KREW_DOC_RTE_TYP_T RENAME COLUMN DOC_RTE_TYP_NM TO NM
/
ALTER TABLE KREW_DOC_RTE_TYP_T RENAME COLUMN DOC_RTE_TYP_LBL_TXT TO LBL_TXT
/
ALTER TABLE KREW_DOC_RTE_TYP_T RENAME COLUMN DOC_RTE_MOD_NM TO MOD_NM
/
ALTER TABLE KREW_DOC_RTE_TYP_T RENAME COLUMN DOC_RTE_TYP_DESC TO DESC
/
ALTER TABLE KREW_DOC_RTE_TYP_T RENAME COLUMN DOC_RTE_TYP_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_DOC_RTE_TYP_T RENAME COLUMN DOC_RTE_MOD_JNDI_FTRY_CLS_NM TO MOD_JNDI_FTRY_CLS_NM
/
ALTER TABLE KREW_DOC_RTE_TYP_T RENAME COLUMN DOC_RTE_MOD_JNDI_URL_ADDR TO MOD_JNDI_URL_ADDR
/
ALTER TABLE EN_DOC_TYP_ATTRIB_T RENAME TO KREW_DOC_TYP_ATTRIB_T
/
ALTER TABLE KREW_DOC_TYP_ATTRIB_T RENAME COLUMN DOC_TYP_ATTRIB_ID TO ID
/
ALTER TABLE KREW_DOC_TYP_ATTRIB_T RENAME COLUMN DOC_TYP_ID TO ID
/
DROP INDEX   
/
CREATE INDEX   ON KREW_DOC_TYP_ATTRIB_T (ID)
/
ALTER TABLE EN_DOC_TYP_PLCY_RELN_T RENAME TO KREW_DOC_TYP_PLCY_RELN_T
/
ALTER TABLE KREW_DOC_TYP_PLCY_RELN_T RENAME COLUMN DOC_TYP_ID TO ID
/
ALTER TABLE EN_DOC_TYP_PLCY_RELN_T RENAME TO KREW_DOC_TYP_PLCY_RELN_T
/
ALTER TABLE KREW_DOC_TYP_PLCY_RELN_T RENAME COLUMN DOC_TYP_ID TO ID
/
DROP INDEX EN_DOC_TYP_PROC_TI1 
/
CREATE INDEX EN_DOC_TYP_PROC_TI1 ON KREW_DOC_TYP_PLCY_RELN_T (ID)
/
DROP INDEX EN_DOC_TYP_PROC_TI2 
/
CREATE INDEX EN_DOC_TYP_PROC_TI2 ON KREW_DOC_TYP_PLCY_RELN_T (INIT_RTE_NODE_ID)
/
DROP INDEX EN_DOC_TYP_PROC_TI3 
/
CREATE INDEX EN_DOC_TYP_PROC_TI3 ON KREW_DOC_TYP_PLCY_RELN_T (PROC_NM)
/
ALTER TABLE EN_DOC_TYP_RTE_LVL_T RENAME TO KREW_DOC_TYP_RTE_LVL_T
/
ALTER TABLE KREW_DOC_TYP_RTE_LVL_T RENAME COLUMN DOC_RTE_LVL_ID TO ID
/
ALTER TABLE KREW_DOC_TYP_RTE_LVL_T RENAME COLUMN DOC_TYP_ID TO ID
/
ALTER TABLE KREW_DOC_TYP_RTE_LVL_T RENAME COLUMN DOC_RTE_LVL_NM TO NM
/
ALTER TABLE KREW_DOC_TYP_RTE_LVL_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
DROP INDEX EN_DOC_TYP_RTE_LVL_TI1 
/
CREATE INDEX KREW_DOC_TYP_RTE_LVL_TI1 ON KREW_DOC_TYP_RTE_LVL_T (ID)
/
ALTER TABLE EN_DOC_TYP_T RENAME TO KREW_DOC_TYP_T
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_ID TO ID
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_PARNT_ID TO PARNT_ID
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_NM TO NM
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_VER_NBR TO VER_NBR
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_CUR_IND TO CUR_IND
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_LBL_TXT TO LBL_TXT
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_PREV_VER TO PREV_VER
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_HDLR_URL_ADDR TO HDLR_URL_ADDR
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_POST_PRCSR_NM TO POST_PRCSR_NM
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_JNDI_URL_ADDR TO JNDI_URL_ADDR
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_NOTIFY_ADDR TO NOTIFY_ADDR
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN MESSAGE_ENTITY_NM TO ENTITY_NM
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_EMAIL_XSL TO EMAIL_XSL
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_SECURITY_XML TO SECURITY_XML
/
DROP INDEX EN_DOC_TYP_TI2 
/
CREATE INDEX KREW_DOC_TYP_TI2 ON KREW_DOC_TYP_T (PARNT_ID)
/
DROP INDEX EN_DOC_TYP_TI1 
/
CREATE UNIQUE INDEX KREW_DOC_TYP_TI1 ON KREW_DOC_TYP_T (NM,VER_NBR)
/
DROP INDEX EN_DOC_TYP_TI3 
/
CREATE INDEX KREW_DOC_TYP_TI3 ON KREW_DOC_TYP_T (ID)
/
DROP INDEX EN_DOC_TYP_TI3 
/
CREATE INDEX KREW_DOC_TYP_TI3 ON KREW_DOC_TYP_T (ID,PARNT_ID)
/
DROP INDEX EN_DOC_TYP_TI1 
/
CREATE UNIQUE INDEX KREW_DOC_TYP_TI1 ON KREW_DOC_TYP_T (NM,VER_NBR)
/
DROP INDEX EN_DOC_TYP_TI4 
/
CREATE INDEX KREW_DOC_TYP_TI4 ON KREW_DOC_TYP_T (PREV_VER)
/
DROP INDEX EN_DOC_TYP_TI1 
/
CREATE UNIQUE INDEX KREW_DOC_TYP_TI1 ON KREW_DOC_TYP_T (NM,VER_NBR)
/
DROP INDEX EN_DOC_TYP_TI5 
/
CREATE INDEX KREW_DOC_TYP_TI5 ON KREW_DOC_TYP_T (CUR_IND)
/
DROP INDEX EN_DOC_TYP_TI1 
/
CREATE UNIQUE INDEX KREW_DOC_TYP_TI1 ON KREW_DOC_TYP_T (NM,VER_NBR)
/
DROP INDEX EN_DOC_TYP_TI6 
/
CREATE INDEX KREW_DOC_TYP_TI6 ON KREW_DOC_TYP_T (NM)
/
DROP INDEX EN_DOC_TYP_TI1 
/
CREATE UNIQUE INDEX KREW_DOC_TYP_TI1 ON KREW_DOC_TYP_T (NM,VER_NBR)
/
DROP INDEX EN_DOC_TYP_TI7 
/
CREATE INDEX KREW_DOC_TYP_TI7 ON KREW_DOC_TYP_T (RPT_WRKGRP_ID)
/
DROP INDEX EN_DOC_TYP_TI1 
/
CREATE UNIQUE INDEX KREW_DOC_TYP_TI1 ON KREW_DOC_TYP_T (NM,VER_NBR)
/
ALTER TABLE EN_EDL_DMP_T RENAME TO KREW_EDL_DMP_T
/
DROP INDEX EN_EDL_DMP_TI1 
/
CREATE INDEX KREW_EDL_DMP_TI1 ON KREW_EDL_DMP_T (DOC_TYP_NM)
/
DROP INDEX EN_EDL_DMP_TI1 
/
CREATE INDEX KREW_EDL_DMP_TI1 ON KREW_EDL_DMP_T (DOC_TYP_NM,DOC_HDR_ID)
/
ALTER TABLE EN_EDL_FIELD_DMP_T RENAME TO KREW_EDL_FIELD_DMP_T
/
ALTER TABLE KREW_EDL_FIELD_DMP_T RENAME COLUMN EDL_FIELD_DMP_ID TO ID
/
ALTER TABLE EN_EDOCLT_ASSOC_T RENAME TO KREW_EDOCLT_ASSOC_T
/
ALTER TABLE KREW_EDOCLT_ASSOC_T RENAME COLUMN EDOCLT_ASSOC_ID TO ID
/
ALTER TABLE KREW_EDOCLT_ASSOC_T RENAME COLUMN EDOCLT_ASSOC_DOCTYPE_NM TO NM
/
ALTER TABLE KREW_EDOCLT_ASSOC_T RENAME COLUMN EDOCLT_ASSOC_DEF_NM TO DEF_NM
/
ALTER TABLE KREW_EDOCLT_ASSOC_T RENAME COLUMN EDOCLT_ASSOC_STYLE_NM TO STYLE_NM
/
ALTER TABLE KREW_EDOCLT_ASSOC_T RENAME COLUMN EDOCLT_ASSOC_ACTV_IND TO ACTV_IND
/
ALTER TABLE EN_EDOCLT_DEF_T RENAME TO KREW_EDOCLT_DEF_T
/
ALTER TABLE KREW_EDOCLT_DEF_T RENAME COLUMN EDOCLT_DEF_ID TO ID
/
ALTER TABLE KREW_EDOCLT_DEF_T RENAME COLUMN EDOCLT_DEF_NM TO NM
/
ALTER TABLE KREW_EDOCLT_DEF_T RENAME COLUMN EDOCLT_DEF_XML TO XML
/
ALTER TABLE KREW_EDOCLT_DEF_T RENAME COLUMN EDOCLT_DEF_ACTV_IND TO ACTV_IND
/
ALTER TABLE EN_EDOCLT_STYLE_T RENAME TO KREW_EDOCLT_STYLE_T
/
ALTER TABLE KREW_EDOCLT_STYLE_T RENAME COLUMN EDOCLT_STYLE_ID TO ID
/
ALTER TABLE KREW_EDOCLT_STYLE_T RENAME COLUMN EDOCLT_STYLE_NM TO NM
/
ALTER TABLE KREW_EDOCLT_STYLE_T RENAME COLUMN EDOCLT_STYLE_XML TO XML
/
ALTER TABLE KREW_EDOCLT_STYLE_T RENAME COLUMN EDOCLT_STYLE_ACTV_IND TO ACTV_IND
/
ALTER TABLE EN_HLP_T RENAME TO KREW_HLP_T
/
ALTER TABLE KREW_HLP_T RENAME COLUMN EN_HLP_ID TO ID
/
ALTER TABLE KREW_HLP_T RENAME COLUMN EN_HLP_NM TO NM
/
ALTER TABLE KREW_HLP_T RENAME COLUMN EN_HLP_TXT TO TXT
/
DROP INDEX EN_HLP_TI1 
/
CREATE INDEX KREW_HLP_TI1 ON KREW_HLP_T (KY)
/
ALTER TABLE EN_INIT_RTE_NODE_INSTN_T RENAME TO KREW_INIT_RTE_NODE_INSTN_T
/
DROP INDEX EN_INIT_RTE_NODE_INSTN_TI 
/
CREATE INDEX KREW_INIT_RTE_NODE_INSTN_TI1 ON KREW_INIT_RTE_NODE_INSTN_T (DOC_HDR_ID)
/
DROP INDEX EN_INIT_RTE_NODE_INSTN_TI2 
/
CREATE INDEX KREW_INIT_RTE_NODE_INSTN_TI2 ON KREW_INIT_RTE_NODE_INSTN_T (RTE_NODE_INSTN_ID)
/
ALTER TABLE EN_MSG_PAYLOAD_T RENAME TO KRSB_MSG_PAYLOAD_T
/
ALTER TABLE KRSB_MSG_PAYLOAD_T RENAME COLUMN MESSAGE_QUE_ID TO MSG_QUE_ID
/
ALTER TABLE KRSB_MSG_PAYLOAD_T RENAME COLUMN MESSAGE_PAYLOAD TO MSG_PAYLOAD
/
ALTER TABLE EN_MSG_QUE_T RENAME TO KRSB_MSG_QUE_T
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_ID TO ID
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_DT TO DT
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_EXP_DT TO EXP_DT
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_PRIO_NBR TO PRIO_NBR
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_STAT_CD TO STAT_CD
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_RTRY_CNT TO RTRY_CNT
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_IP_NBR TO IP_NBR
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_SERVICE_NM TO SVC_NM
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_ENTITY_NM TO ENTITY_NM
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN SERVICE_METHOD_NM TO SVC_METH_NM
/
DROP INDEX EN_MSG_QUE_TI1 
/
CREATE INDEX KRSB_MSG_QUE_TI1 ON KRSB_MSG_QUE_T (SVC_NM)
/
DROP INDEX EN_MSG_QUE_TI1 
/
CREATE INDEX KRSB_MSG_QUE_TI1 ON KRSB_MSG_QUE_T (SVC_NM,SVC_METH_NM)
/
DROP INDEX EN_MSG_QUE_TI2 
/
CREATE INDEX KRSB_MSG_QUE_TI2 ON KRSB_MSG_QUE_T (ENTITY_NM)
/
DROP INDEX EN_MSG_QUE_TI2 
/
CREATE INDEX KRSB_MSG_QUE_TI2 ON KRSB_MSG_QUE_T (ENTITY_NM,STAT_CD)
/
DROP INDEX EN_MSG_QUE_TI2 
/
CREATE INDEX KRSB_MSG_QUE_TI2 ON KRSB_MSG_QUE_T (ENTITY_NM,STAT_CD,IP_NBR)
/
DROP INDEX EN_MSG_QUE_TI2 
/
CREATE INDEX KRSB_MSG_QUE_TI2 ON KRSB_MSG_QUE_T (ENTITY_NM,STAT_CD,IP_NBR,MSG_QUE_DT)
/
ALTER TABLE EN_ORG_RESP_ID_T RENAME TO KREW_ORG_RESP_ID_T
/
ALTER TABLE EN_OUT_BOX_ITM_T RENAME TO KREW_OUT_BOX_ITM_T
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_ID TO ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_ASND_DT TO ASND_DT
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_RQST_CD TO RQST_CD
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_RQST_ID TO ACTN_RQST_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN DOC_HDR_ID TO DOC_HDR_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ROLE_NM TO ROLE_NM
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_DLGN_PRSN_EN_ID TO DLGN_PRNCPL_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_DLGN_WRKGRP_ID TO DLGN_WRKGRP_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_RESP_ID TO RESP_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
DROP INDEX EN_OUT_BOX_ITM_TI1 
/
CREATE INDEX KREW_OUT_BOX_ITM_TI1 ON KREW_OUT_BOX_ITM_T (PRNCPL_ID)
/
DROP INDEX EN_OUT_BOX_ITM_TI2 
/
CREATE INDEX KREW_OUT_BOX_ITM_TI2 ON KREW_OUT_BOX_ITM_T (DOC_HDR_ID)
/
DROP INDEX EN_OUT_BOX_ITM_TI3 
/
CREATE INDEX KREW_OUT_BOX_ITM_TI3 ON KREW_OUT_BOX_ITM_T (ACTN_RQST_ID)
/
DROP INDEX EN_OUT_BOX_ITM_TI4 
/
CREATE INDEX KREW_OUT_BOX_ITM_TI4 ON KREW_OUT_BOX_ITM_T (DLGN_PRSN_EN_ID)
/
DROP INDEX EN_OUT_BOX_ITM_TI4 
/
CREATE INDEX KREW_OUT_BOX_ITM_TI4 ON KREW_OUT_BOX_ITM_T (DLGN_PRSN_EN_ID,DLGN_WRKGRP_ID)
/
DROP INDEX EN_OUT_BOX_ITM_TI4 
/
CREATE INDEX KREW_OUT_BOX_ITM_TI4 ON KREW_OUT_BOX_ITM_T (DLGN_PRSN_EN_ID,DLGN_WRKGRP_ID,PRNCPL_ID)
/
DROP INDEX EN_OUT_BOX_ITM_TI4 
/
CREATE INDEX KREW_OUT_BOX_ITM_TI4 ON KREW_OUT_BOX_ITM_T (DLGN_PRSN_EN_ID,DLGN_WRKGRP_ID,PRNCPL_ID,DLGN_TYP)
/
ALTER TABLE EN_RMV_RPLC_DOC_T RENAME TO KREW_RMV_RPLC_DOC_T
/
ALTER TABLE KREW_RMV_RPLC_DOC_T RENAME COLUMN PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE EN_RMV_RPLC_RULE_T RENAME TO KREW_RMV_RPLC_RULE_T
/
ALTER TABLE EN_RMV_RPLC_WRKGRP_T RENAME TO KREW_RMV_RPLC_WRKGRP_T
/
ALTER TABLE KREW_RMV_RPLC_WRKGRP_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE EN_RTE_BRCH_PROTO_T RENAME TO KREW_RTE_BRCH_PROTO_T
/
ALTER TABLE KREW_RTE_BRCH_PROTO_T RENAME COLUMN RTE_BRCH_PROTO_ID TO ID
/
ALTER TABLE KREW_RTE_BRCH_PROTO_T RENAME COLUMN RTE_BRCH_PROTO_NM TO NM
/
DROP INDEX EN_RTE_BRCH_PROTO_TI1 
/
CREATE INDEX KREW_RTE_BRCH_PROTO_TI1 ON KREW_RTE_BRCH_PROTO_T (NM)
/
ALTER TABLE EN_RTE_BRCH_ST_T RENAME TO KREW_RTE_BRCH_ST_T
/
ALTER TABLE KREW_RTE_BRCH_ST_T RENAME COLUMN RTE_BRCH_ST_ID TO ID
/
DROP INDEX EN_RTE_BRCH_ST_TI1 
/
CREATE INDEX KREW_RTE_BRCH_ST_TI1 ON KREW_RTE_BRCH_ST_T (RTE_BRCH_ID)
/
DROP INDEX EN_RTE_BRCH_ST_TI1 
/
CREATE INDEX KREW_RTE_BRCH_ST_TI1 ON KREW_RTE_BRCH_ST_T (RTE_BRCH_ID,ST_KEY)
/
DROP INDEX EN_RTE_BRCH_ST_TI2 
/
CREATE INDEX KREW_RTE_BRCH_ST_TI2 ON KREW_RTE_BRCH_ST_T (RTE_BRCH_ID)
/
DROP INDEX EN_RTE_BRCH_ST_TI3 
/
CREATE INDEX KREW_RTE_BRCH_ST_TI3 ON KREW_RTE_BRCH_ST_T (ST_KEY)
/
DROP INDEX EN_RTE_BRCH_ST_TI3 
/
CREATE INDEX KREW_RTE_BRCH_ST_TI3 ON KREW_RTE_BRCH_ST_T (ST_KEY,ST_VAL_TXT)
/
ALTER TABLE EN_RTE_BRCH_T RENAME TO KREW_RTE_BRCH_T
/
ALTER TABLE KREW_RTE_BRCH_T RENAME COLUMN RTE_BRCH_ID TO ID
/
ALTER TABLE KREW_RTE_BRCH_T RENAME COLUMN BRCH_NM TO NM
/
DROP INDEX EN_RTE_BRCH_TI1 
/
CREATE INDEX KREW_RTE_BRCH_TI1 ON KREW_RTE_BRCH_T (NM)
/
DROP INDEX EN_RTE_BRCH_TI2 
/
CREATE INDEX KREW_RTE_BRCH_TI2 ON KREW_RTE_BRCH_T (PARNT_RTE_BRCH_ID)
/
DROP INDEX EN_RTE_BRCH_TI3 
/
CREATE INDEX KREW_RTE_BRCH_TI3 ON KREW_RTE_BRCH_T (INIT_RTE_NODE_INSTN_ID)
/
DROP INDEX EN_RTE_BRCH_TI4 
/
CREATE INDEX KREW_RTE_BRCH_TI4 ON KREW_RTE_BRCH_T (SPLT_RTE_NODE_INSTN_ID)
/
DROP INDEX EN_RTE_BRCH_TI5 
/
CREATE INDEX KREW_RTE_BRCH_TI5 ON KREW_RTE_BRCH_T (JOIN_RTE_NODE_INSTN_ID)
/
ALTER TABLE EN_RTE_NODE_CFG_PARM_T RENAME TO KREW_RTE_NODE_CFG_PARM_T
/
ALTER TABLE KREW_RTE_NODE_CFG_PARM_T RENAME COLUMN RTE_NODE_CFG_PARM_ID TO ID
/
ALTER TABLE KREW_RTE_NODE_CFG_PARM_T RENAME COLUMN RTE_NODE_CFG_PARM_ND TO ND
/
ALTER TABLE KREW_RTE_NODE_CFG_PARM_T RENAME COLUMN RTE_NODE_CFG_PARM_KEY TO KEY
/
ALTER TABLE KREW_RTE_NODE_CFG_PARM_T RENAME COLUMN RTE_NODE_CFG_PARM_VAL TO VAL
/
ALTER TABLE EN_RTE_NODE_INSTN_LNK_T RENAME TO KREW_RTE_NODE_INSTN_LNK_T
/
DROP INDEX EN_RTE_NODE_INSTN_LNK_TI1 
/
CREATE INDEX KREW_RTE_NODE_INSTN_LNK_TI1 ON KREW_RTE_NODE_INSTN_LNK_T (FROM_RTE_NODE_INSTN_ID)
/
DROP INDEX EN_RTE_NODE_INSTN_LNK_TI2 
/
CREATE INDEX KREW_RTE_NODE_INSTN_LNK_TI2 ON KREW_RTE_NODE_INSTN_LNK_T (TO_RTE_NODE_INSTN_ID)
/
ALTER TABLE EN_RTE_NODE_INSTN_ST_T RENAME TO KREW_RTE_NODE_INSTN_ST_T
/
ALTER TABLE KREW_RTE_NODE_INSTN_ST_T RENAME COLUMN RTE_NODE_INSTN_ST_ID TO ID
/
DROP INDEX EN_RTE_NODE_INSTN_ST_TI1 
/
CREATE INDEX KREW_RTE_NODE_INSTN_ST_TI1 ON KREW_RTE_NODE_INSTN_ST_T (RTE_NODE_INSTN_ID)
/
DROP INDEX EN_RTE_NODE_INSTN_ST_TI1 
/
CREATE INDEX KREW_RTE_NODE_INSTN_ST_TI1 ON KREW_RTE_NODE_INSTN_ST_T (RTE_NODE_INSTN_ID,ST_KEY)
/
DROP INDEX EN_RTE_NODE_INSTN_ST_TI2 
/
CREATE INDEX KREW_RTE_NODE_INSTN_ST_TI2 ON KREW_RTE_NODE_INSTN_ST_T (RTE_NODE_INSTN_ID)
/
DROP INDEX EN_RTE_NODE_INSTN_ST_TI3 
/
CREATE INDEX KREW_RTE_NODE_INSTN_ST_TI3 ON KREW_RTE_NODE_INSTN_ST_T (ST_KEY)
/
DROP INDEX EN_RTE_NODE_INSTN_ST_TI3 
/
CREATE INDEX KREW_RTE_NODE_INSTN_ST_TI3 ON KREW_RTE_NODE_INSTN_ST_T (ST_KEY,ST_VAL_TXT)
/
ALTER TABLE EN_RTE_NODE_INSTN_T RENAME TO KREW_RTE_NODE_INSTN_T
/
DROP INDEX EN_RTE_NODE_INSTN_TI1 
/
CREATE INDEX KREW_RTE_NODE_INSTN_TI1 ON KREW_RTE_NODE_INSTN_T (DOC_ID)
/
DROP INDEX EN_RTE_NODE_INSTN_TI1 
/
CREATE INDEX KREW_RTE_NODE_INSTN_TI1 ON KREW_RTE_NODE_INSTN_T (DOC_ID,ACTV_IND)
/
DROP INDEX EN_RTE_NODE_INSTN_TI1 
/
CREATE INDEX KREW_RTE_NODE_INSTN_TI1 ON KREW_RTE_NODE_INSTN_T (DOC_ID,ACTV_IND,CMPLT_IND)
/
DROP INDEX EN_RTE_NODE_INSTN_TI2 
/
CREATE INDEX KREW_RTE_NODE_INSTN_TI2 ON KREW_RTE_NODE_INSTN_T (RTE_NODE_ID)
/
DROP INDEX EN_RTE_NODE_INSTN_TI3 
/
CREATE INDEX KREW_RTE_NODE_INSTN_TI3 ON KREW_RTE_NODE_INSTN_T (BRCH_ID)
/
DROP INDEX EN_RTE_NODE_INSTN_TI4 
/
CREATE INDEX KREW_RTE_NODE_INSTN_TI4 ON KREW_RTE_NODE_INSTN_T (PROC_RTE_NODE_INSTN_ID)
/
ALTER TABLE EN_RTE_NODE_LNK_T RENAME TO KREW_RTE_NODE_LNK_T
/
DROP INDEX EN_RTE_NODE_LNK_TI1 
/
CREATE INDEX KREW_RTE_NODE_LNK_TI1 ON KREW_RTE_NODE_LNK_T (FROM_RTE_NODE_ID)
/
DROP INDEX EN_RTE_NODE_LNK_TI2 
/
CREATE INDEX KREW_RTE_NODE_LNK_TI2 ON KREW_RTE_NODE_LNK_T (TO_RTE_NODE_ID)
/
ALTER TABLE EN_RTE_NODE_T RENAME TO KREW_RTE_NODE_T
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN RTE_NODE_ID TO ID
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN RTE_NODE_NM TO NM
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
DROP INDEX EN_RTE_NODE_TI1 
/
CREATE INDEX KREW_RTE_NODE_TI1 ON KREW_RTE_NODE_T (NM)
/
DROP INDEX EN_RTE_NODE_TI1 
/
CREATE INDEX KREW_RTE_NODE_TI1 ON KREW_RTE_NODE_T (NM,DOC_TYP_ID)
/
DROP INDEX EN_RTE_NODE_TI2 
/
CREATE INDEX KREW_RTE_NODE_TI2 ON KREW_RTE_NODE_T (DOC_TYP_ID)
/
DROP INDEX EN_RTE_NODE_TI2 
/
CREATE INDEX KREW_RTE_NODE_TI2 ON KREW_RTE_NODE_T (DOC_TYP_ID,DOC_FNL_APRVR_IND)
/
DROP INDEX EN_RTE_NODE_TI3 
/
CREATE INDEX KREW_RTE_NODE_TI3 ON KREW_RTE_NODE_T (BRCH_PROTO_ID)
/
DROP INDEX EN_RTE_NODE_TI4 
/
CREATE INDEX KREW_RTE_NODE_TI4 ON KREW_RTE_NODE_T (DOC_TYP_ID)
/
ALTER TABLE EN_RULE_ATTRIB_KEY_VAL_T RENAME TO KREW_RULE_ATTRIB_KEY_VAL_T
/
ALTER TABLE KREW_RULE_ATTRIB_KEY_VAL_T RENAME COLUMN RULE_ATTRIB_KEY_VAL_ID TO ID
/
ALTER TABLE EN_RULE_ATTRIB_T RENAME TO KREW_RULE_ATTRIB_T
/
ALTER TABLE KREW_RULE_ATTRIB_T RENAME COLUMN RULE_ATTRIB_ID TO ID
/
ALTER TABLE KREW_RULE_ATTRIB_T RENAME COLUMN MESSAGE_ENTITY_NM TO ENTITY_NM
/
ALTER TABLE EN_RULE_ATTRIB_VLD_VAL_T RENAME TO KREW_RULE_ATTRIB_VLD_VAL_T
/
ALTER TABLE KREW_RULE_ATTRIB_VLD_VAL_T RENAME COLUMN RULE_ATTRIB_VLD_VAL_ID TO ID
/
ALTER TABLE KREW_RULE_ATTRIB_VLD_VAL_T RENAME COLUMN RULE_ATTRIB_VLD_VAL_NM TO NM
/
ALTER TABLE KREW_RULE_ATTRIB_VLD_VAL_T RENAME COLUMN RULE_ATTRIB_VLD_VAL_LBL_TXT TO LBL_TXT
/
ALTER TABLE KREW_RULE_ATTRIB_VLD_VAL_T RENAME COLUMN RULE_ATTRIB_VLD_VAL_CUR_IND TO CUR_IND
/
ALTER TABLE KREW_RULE_ATTRIB_VLD_VAL_T RENAME COLUMN RULE_ATTRIB_VLD_VAL_VER_NBR TO VER_NBR
/
ALTER TABLE EN_RULE_BASE_VAL_T RENAME TO KREW_RULE_BASE_VAL_T
/
ALTER TABLE KREW_RULE_BASE_VAL_T RENAME COLUMN RULE_BASE_VAL_ID TO ID
/
ALTER TABLE KREW_RULE_BASE_VAL_T RENAME COLUMN RULE_BASE_VAL_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_RULE_BASE_VAL_T RENAME COLUMN RULE_BASE_VAL_DESC TO VAL_DESC
/
ALTER TABLE KREW_RULE_BASE_VAL_T RENAME COLUMN RULE_BASE_VAL_IGNR_PRVS TO IGNR_PRVS
/
ALTER TABLE KREW_RULE_BASE_VAL_T RENAME COLUMN RULE_BASE_VAL_FRM_DT TO FRM_DT
/
ALTER TABLE KREW_RULE_BASE_VAL_T RENAME COLUMN RULE_BASE_VAL_TO_DT TO TO_DT
/
ALTER TABLE KREW_RULE_BASE_VAL_T RENAME COLUMN RULE_BASE_VAL_DACTVN_DT TO DACTVN_DT
/
ALTER TABLE KREW_RULE_BASE_VAL_T RENAME COLUMN RULE_BASE_VAL_CUR_IND TO CUR_IND
/
ALTER TABLE KREW_RULE_BASE_VAL_T RENAME COLUMN RULE_BASE_VAL_VER_NBR TO VER_NBR
/
ALTER TABLE KREW_RULE_BASE_VAL_T RENAME COLUMN RULE_BASE_VAL_DLGN_IND TO DLGN_IND
/
ALTER TABLE KREW_RULE_BASE_VAL_T RENAME COLUMN RULE_BASE_VAL_PREV_VER TO PREV_VER
/
ALTER TABLE KREW_RULE_BASE_VAL_T RENAME COLUMN RULE_BASE_VAL_ACTVN_DT TO ACTVN_DT
/
ALTER TABLE EN_RULE_EXPR_T RENAME TO KREW_RULE_EXPR_T
/
ALTER TABLE KREW_RULE_EXPR_T RENAME COLUMN RULE_EXPR_ID TO ID
/
ALTER TABLE KREW_RULE_EXPR_T RENAME COLUMN RULE_EXPR_TYP TO TYP
/
ALTER TABLE EN_RULE_EXT_T RENAME TO KREW_RULE_EXT_T
/
ALTER TABLE KREW_RULE_EXT_T RENAME COLUMN RULE_EXT_ID TO ID
/
DROP INDEX EN_RULE_EXT_T1 
/
CREATE INDEX KREW_RULE_EXT_T1 ON KREW_RULE_EXT_T (RULE_BASE_VAL_ID)
/
ALTER TABLE EN_RULE_EXT_VAL_T RENAME TO KREW_RULE_EXT_VAL_T
/
ALTER TABLE KREW_RULE_EXT_VAL_T RENAME COLUMN RULE_EXT_VAL_ID TO ID
/
DROP INDEX EN_RULE_EXT_VAL_T1 
/
CREATE INDEX KREW_RULE_EXT_VAL_T1 ON KREW_RULE_EXT_VAL_T (RULE_EXT_ID)
/
DROP INDEX EN_RULE_EXT_VAL_T2 
/
CREATE INDEX KREW_RULE_EXT_VAL_T2 ON KREW_RULE_EXT_VAL_T (ID)
/
DROP INDEX EN_RULE_EXT_VAL_T2 
/
CREATE INDEX KREW_RULE_EXT_VAL_T2 ON KREW_RULE_EXT_VAL_T (ID,RULE_EXT_VAL_KEY)
/
ALTER TABLE EN_RULE_RSP_T RENAME TO KREW_RULE_RSP_T
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_RSP_ID TO ID
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_RSP_PRIO_NBR TO PRIO_NBR
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_RSP_NM TO NM
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_RSP_TYP TO TYP
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_RSP_APPR_PLCY TO APPR_PLCY
/
DROP INDEX EN_RULE_RSP_TI1 
/
CREATE INDEX KREW_RULE_RSP_TI1 ON KREW_RULE_RSP_T (RULE_BASE_VAL_ID)
/
ALTER TABLE EN_RULE_TMPL_ATTRIB_T RENAME TO KREW_RULE_TMPL_ATTRIB_T
/
ALTER TABLE KREW_RULE_TMPL_ATTRIB_T RENAME COLUMN RULE_TMPL_ATTRIB_ID TO ID
/
DROP INDEX EN_RULE_TMPL_ATTRIB_TI1 
/
CREATE INDEX KREW_RULE_TMPL_ATTRIB_TI1 ON KREW_RULE_TMPL_ATTRIB_T (RULE_TMPL_ID)
/
DROP INDEX EN_RULE_TMPL_ATTRIB_TI2 
/
CREATE INDEX KREW_RULE_TMPL_ATTRIB_TI2 ON KREW_RULE_TMPL_ATTRIB_T (RULE_ATTRIB_ID)
/
ALTER TABLE EN_RULE_TMPL_OPTN_T RENAME TO KREW_RULE_TMPL_OPTN_T
/
ALTER TABLE KREW_RULE_TMPL_OPTN_T RENAME COLUMN RULE_TMPL_OPTN_ID TO ID
/
ALTER TABLE KREW_RULE_TMPL_OPTN_T RENAME COLUMN RULE_TMPL_OPTN_KEY TO KEY
/
ALTER TABLE KREW_RULE_TMPL_OPTN_T RENAME COLUMN RULE_TMPL_OPTN_VAL TO VAL
/
ALTER TABLE EN_RULE_TMPL_T RENAME TO KREW_RULE_TMPL_T
/
ALTER TABLE KREW_RULE_TMPL_T RENAME COLUMN RULE_TMPL_ID TO ID
/
ALTER TABLE KREW_RULE_TMPL_T RENAME COLUMN RULE_TMPL_NM TO NM
/
ALTER TABLE KREW_RULE_TMPL_T RENAME COLUMN RULE_TMPL_DESC TO DESC
/
ALTER TABLE EN_SERVICE_DEF_DUEX_T RENAME TO KRSB_SVC_DEF_T
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_DEF_ID TO ID
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_NM TO SVC_NM
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_URL TO SVC_URL
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN MESSAGE_ENTITY_NM TO ENTITY_NM
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_ALIVE TO SVC_ALIVE
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_DEFINITION TO SVC_DEF
/
DROP INDEX EN_SERVICE_DEF_DUEX_TI1 
/
CREATE INDEX KRSB_SVC_DEF_TI1 ON KRSB_SVC_DEF_T (SERVER_IP)
/
DROP INDEX EN_SERVICE_DEF_DUEX_TI1 
/
CREATE INDEX KRSB_SVC_DEF_TI1 ON KRSB_SVC_DEF_T (SERVER_IP,ENTITY_NM)
/
ALTER TABLE EN_USR_OPTN_T RENAME TO KREW_USR_OPTN_T
/
ALTER TABLE KREW_USR_OPTN_T RENAME COLUMN PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_USR_OPTN_T RENAME COLUMN PRSN_OPTN_ID TO OPTN_ID
/
ALTER TABLE KREW_USR_OPTN_T RENAME COLUMN PRSN_OPTN_VAL TO OPTN_VAL
/
DROP INDEX EN_USR_OPTN_TI1 
/
CREATE INDEX KREW_USR_OPTN_TI1 ON KREW_USR_OPTN_T (PRNCPL_ID)
/
ALTER TABLE EN_USR_T RENAME TO KREW_USR_T
/
ALTER TABLE KREW_USR_T RENAME COLUMN PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_USR_T RENAME COLUMN PRSN_UNIV_ID TO UNIV_ID
/
ALTER TABLE KREW_USR_T RENAME COLUMN PRSN_NTWRK_ID TO NTWRK_ID
/
ALTER TABLE KREW_USR_T RENAME COLUMN PRSN_UNVL_USR_ID TO UNVL_USR_ID
/
ALTER TABLE KREW_USR_T RENAME COLUMN PRSN_EMAIL_ADDR TO EMAIL_ADDR
/
ALTER TABLE KREW_USR_T RENAME COLUMN PRSN_NM TO NM
/
ALTER TABLE KREW_USR_T RENAME COLUMN PRSN_GVN_NM TO GVN_NM
/
ALTER TABLE KREW_USR_T RENAME COLUMN PRSN_LST_NM TO LST_NM
/
ALTER TABLE KREW_USR_T RENAME COLUMN USR_CRTE_DT TO CRTE_DT
/
ALTER TABLE KREW_USR_T RENAME COLUMN USR_LST_UPDT_DT TO LST_UPDT_DT
/
ALTER TABLE EN_WRKGRP_EXT_DTA_T RENAME TO KREW_WRKGRP_EXT_DTA_T
/
ALTER TABLE KREW_WRKGRP_EXT_DTA_T RENAME COLUMN WRKGRP_EXT_DTA_ID TO ID
/
ALTER TABLE KREW_WRKGRP_EXT_DTA_T RENAME COLUMN EXT_KEY TO KEY
/
ALTER TABLE KREW_WRKGRP_EXT_DTA_T RENAME COLUMN EXT_VAL TO VAL
/
ALTER TABLE EN_WRKGRP_EXT_T RENAME TO KREW_WRKGRP_EXT_T
/
ALTER TABLE KREW_WRKGRP_EXT_T RENAME COLUMN WRKGRP_EXT_ID TO ID
/
ALTER TABLE KREW_WRKGRP_EXT_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE EN_WRKGRP_MBR_T RENAME TO KREW_WRKGRP_MBR_T
/
ALTER TABLE KREW_WRKGRP_MBR_T RENAME COLUMN WRKGRP_MBR_PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_WRKGRP_MBR_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE KREW_WRKGRP_MBR_T RENAME COLUMN WRKGRP_MBR_TYP TO TYP
/
ALTER TABLE KREW_WRKGRP_MBR_T RENAME COLUMN WRKGRP_VER_NBR TO VER_NBR
/
DROP INDEX   
/
CREATE INDEX   ON KREW_WRKGRP_MBR_T (PRNCPL_ID)
/
ALTER TABLE EN_WRKGRP_T RENAME TO KREW_WRKGRP_T
/
ALTER TABLE KREW_WRKGRP_T RENAME COLUMN WRKGRP_ID TO ID
/
ALTER TABLE KREW_WRKGRP_T RENAME COLUMN WRKGRP_VER_NBR TO VER_NBR
/
ALTER TABLE KREW_WRKGRP_T RENAME COLUMN WRKGRP_NM TO NM
/
ALTER TABLE KREW_WRKGRP_T RENAME COLUMN WRKGRP_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_WRKGRP_T RENAME COLUMN WRKGRP_TYP_CD TO TYP_CD
/
ALTER TABLE KREW_WRKGRP_T RENAME COLUMN WRKGRP_DESC TO DESC
/
ALTER TABLE KREW_WRKGRP_T RENAME COLUMN WRKGRP_CUR_IND TO CUR_IND
/
DROP INDEX EN_WRKGRP_TI1 
/
CREATE INDEX KREW_WRKGRP_TI1 ON KREW_WRKGRP_T (NM)
/
ALTER TABLE EN_WRKGRP_TYP_ATTRIB_T RENAME TO KREW_WRKGRP_TYP_ATTRIB_T
/
ALTER TABLE KREW_WRKGRP_TYP_ATTRIB_T RENAME COLUMN WRKGRP_TYP_ATTRIB_ID TO ID
/
ALTER TABLE EN_WRKGRP_TYP_T RENAME TO KREW_WRKGRP_TYP_T
/
ALTER TABLE KREW_WRKGRP_TYP_T RENAME COLUMN WRKGRP_TYP_ID TO ID
/
ALTER TABLE KREW_WRKGRP_TYP_T RENAME COLUMN WRKGRP_TYP_NM TO NM
/
ALTER TABLE KREW_WRKGRP_TYP_T RENAME COLUMN WRKGRP_TYP_LBL TO LBL
/
ALTER TABLE KREW_WRKGRP_TYP_T RENAME COLUMN WRKGRP_TYP_DESC TO DESC
/
ALTER TABLE FP_DOC_HEADER_T RENAME TO KRNS_DOC_HEADER_T
/
ALTER TABLE KRNS_DOC_HEADER_T RENAME COLUMN FDOC_NBR TO NBR
/
ALTER TABLE KRNS_DOC_HEADER_T RENAME COLUMN FDOC_DESC TO DESC
/
ALTER TABLE KRNS_DOC_HEADER_T RENAME COLUMN FDOC_TMPL_NBR TO TMPL_NBR
/
ALTER TABLE KRNS_DOC_HEADER_T RENAME COLUMN FDOC_EXPLAIN_TXT TO EXPLAIN_TXT
/
DROP INDEX FP_DOC_HEADER_TI3 
/
CREATE INDEX KRNS_DOC_HEADER_TI3 ON KRNS_DOC_HEADER_T (ORG_DOC_NBR)
/
DROP INDEX FP_DOC_HEADER_TC0 
/
CREATE UNIQUE INDEX KRNS_DOC_HEADER_TI1 ON KRNS_DOC_HEADER_T (OBJ_ID)
/
ALTER TABLE FP_DOC_TYPE_ATTR_T RENAME TO KRNS_DOC_TYPE_ATTR_T
/
ALTER TABLE KRNS_DOC_TYPE_ATTR_T RENAME COLUMN DOC_TYP_ATTR_CD TO CD
/
ALTER TABLE KRNS_DOC_TYPE_ATTR_T RENAME COLUMN DOC_TYP_ATTR_VAL TO VAL
/
ALTER TABLE KRNS_DOC_TYPE_ATTR_T RENAME COLUMN DOC_TYP_ATTR_LBL TO LBL
/
ALTER TABLE KRNS_DOC_TYPE_ATTR_T RENAME COLUMN FDOC_TYP_CD TO DOC_TYP_CD
/
ALTER TABLE FP_DOC_TYPE_T RENAME TO KRNS_DOC_TYPE_T
/
ALTER TABLE KRNS_DOC_TYPE_T RENAME COLUMN FDOC_TYP_CD TO CD
/
ALTER TABLE KRNS_DOC_TYPE_T RENAME COLUMN FDOC_NM TO NM
/
ALTER TABLE KRNS_DOC_TYPE_T RENAME COLUMN FDOC_TYP_ACTIVE_CD TO ACTIVE_CD
/
ALTER TABLE FP_MAINTENANCE_DOCUMENT_T RENAME TO KRNS_MAINT_DOC_T
/
ALTER TABLE KRNS_MAINT_DOC_T RENAME COLUMN FDOC_NBR TO NBR
/
ALTER TABLE KRNS_MAINT_DOC_T RENAME COLUMN DOCUMENT_CONTENTS TO DOC_CONT
/
ALTER TABLE FP_MAINT_DOC_ATTACHMENT_T RENAME TO KRNS_MAINT_DOC_ATTACHMENT_T
/
ALTER TABLE KRNS_MAINT_DOC_ATTACHMENT_T RENAME COLUMN FDOC_NBR TO NBR
/
ALTER TABLE FP_MAINT_LOCK_T RENAME TO KRNS_MAINT_LOCK_T
/
ALTER TABLE KRNS_MAINT_LOCK_T RENAME COLUMN LOCK_REPRESENTATION_TXT TO LOCK_REP_TXT
/
ALTER TABLE KRNS_MAINT_LOCK_T RENAME COLUMN FDOC_NBR TO NBR
/
DROP INDEX FP_MAINT_LOCK_TI2 
/
CREATE INDEX KRNS_MAINT_LOCK_TI2 ON KRNS_MAINT_LOCK_T (NBR)
/
DROP INDEX FP_MAINT_LOCK_TC0 
/
CREATE UNIQUE INDEX KRNS_MAINT_LOCK_TI1 ON KRNS_MAINT_LOCK_T (OBJ_ID)
/
ALTER TABLE FS_ADHOC_RTE_ACTN_RECP_T RENAME TO KRNS_ADHOC_RTE_ACTN_RECP_T
/
ALTER TABLE KRNS_ADHOC_RTE_ACTN_RECP_T RENAME COLUMN FDOC_NBR TO NBR
/
DROP INDEX FS_ADHOC_RTE_ACTN_RECP_TI2 
/
CREATE INDEX KRNS_ADHOC_RTE_ACTN_RECP_TI2 ON KRNS_ADHOC_RTE_ACTN_RECP_T (NBR)
/
DROP INDEX FS_ADHOC_RTE_ACTN_RECP_TC0 
/
CREATE UNIQUE INDEX KRNS_ADHOC_RTE_ACTN_RECP_TI1 ON KRNS_ADHOC_RTE_ACTN_RECP_T (OBJ_ID)
/
ALTER TABLE FS_CODES_DESC_T RENAME TO KRNS_CODES_DESC_T
/
ALTER TABLE FS_LOOKUP_RESULTS_MT RENAME TO KRNS_LOOKUP_RES_T
/
ALTER TABLE KRNS_LOOKUP_RES_T RENAME COLUMN LOOKUP_RESULT_SEQUENCE_NBR TO SEQ_NBR
/
ALTER TABLE FS_LOOKUP_SELECTIONS_MT RENAME TO KRNS_FS_LOOKUP_SEL_T
/
ALTER TABLE KRNS_FS_LOOKUP_SEL_T RENAME COLUMN LOOKUP_RESULT_SEQUENCE_NBR TO RES_SEQ_NBR
/
ALTER TABLE KCB_MESSAGES RENAME TO KREN_MESSAGES_T
/
ALTER TABLE KREN_MESSAGES_T RENAME COLUMN CREATED_DATETIME TO CRTE_DT
/
ALTER TABLE KCB_MSG_DELIVS RENAME TO KREN_MSG_DELIVS_T
/
DROP INDEX KCB_MSG_DELIVSI1 
/
CREATE INDEX KREN_MSG_DELIVS_I1 ON KREN_MSG_DELIVS_T (MESSAGE_ID)
/
DROP INDEX KCB_MSG_DELIVS_UK1 
/
CREATE UNIQUE INDEX KREN_MSG_DELIVS_UK1 ON KREN_MSG_DELIVS_T (MESSAGE_ID,DELIVERER_TYPE_NAME)
/
DROP CONSTRAINT KCB_MSG_DELIVS_FK1 
/
ALTER TABLE KREN_MSG_DELIVS_T ADD CONSTRAINT KREN_MSG_DELIVS_FK1 FOREIGN KEY  (MESSAGE_ID) REFERENCES KREN_MESSAGES_T (ID) 
/
ALTER TABLE KCB_RECIP_DELIVS RENAME TO KREN_RECIP_DELIVS_T
/
ALTER TABLE KCB_RECIP_PREFS RENAME TO KREN_RECIP_PREFS_T
/
ALTER TABLE KIM_ATTRIBUTE_TYPES_T RENAME TO KRIM_ATTRIB_TYP_T
/
ALTER TABLE KIM_AUTHN_SESN_PRINCIPAL_T RENAME TO KRIM_AUTHN_SESN_PRNCPL_T
/
ALTER TABLE KRIM_AUTHN_SESN_PRNCPL_T RENAME COLUMN PRINCIPAL_NAME TO PRNCPL_NM
/
DROP INDEX KIM_AUTHN_SESN_PRINCIPAL_TI1 
/
CREATE INDEX KRIM_AUTHN_SESN_PRNCPL_TI1 ON KRIM_AUTHN_SESN_PRNCPL_T (SESN_ID)
/
DROP INDEX   
/
CREATE INDEX   ON KRIM_AUTHN_SESN_PRNCPL_T (PRNCPL_NM)
/
ALTER TABLE KIM_AUTHN_SESN_T RENAME TO KRIM_AUTHN_SESN_T
/
ALTER TABLE KRIM_AUTHN_SESN_T RENAME COLUMN INSERT_DATETIME TO CRTE_DT
/
ALTER TABLE KRIM_AUTHN_SESN_T RENAME COLUMN LAST_ACCESS_DATETIME TO LAST_ACC_DT
/
DROP INDEX   
/
CREATE INDEX KRIM_AUTHN_SESN_TI1 ON KRIM_AUTHN_SESN_T (LAST_ACC_DT)
/
DROP INDEX   
/
CREATE INDEX KRIM_AUTHN_SESN_TI2 ON KRIM_AUTHN_SESN_T (CRTE_DT)
/
ALTER TABLE KIM_ENTITYS_T RENAME TO KRIM_ENTITYS_T
/
DROP INDEX KIM_ENTITYS_TI1 
/
CREATE INDEX KRIM_ENTITYS_TI1 ON KRIM_ENTITYS_T (ENTITY_TYPE_ID)
/
DROP CONSTRAINT KIM_ENTITYS_T_FK1 
/
ALTER TABLE KRIM_ENTITYS_T ADD CONSTRAINT KRIM_ENTITYS_T_FK1 FOREIGN KEY  (ENTITY_TYPE_ID) REFERENCES KRIM_ENTITY_TYPES_T (ID) 
/
ALTER TABLE KIM_ENTITY_ATTRIBUTES_T RENAME TO KRIM_ENTITY_ATTRIB_T
/
ALTER TABLE KRIM_ENTITY_ATTRIB_T RENAME COLUMN SPONSOR_NAMESPACE_ID TO SPONSOR_NMSPC_ID
/
ALTER TABLE KRIM_ENTITY_ATTRIB_T RENAME COLUMN ATTRIBUTE_NAME TO NM
/
DROP INDEX KIM_ENTITY_ATTRIBUTES_TI1 
/
CREATE INDEX KRIM_ENTITY_ATTRIB_TI1 ON KRIM_ENTITY_ATTRIB_T (ENTITY_ID)
/
DROP INDEX KIM_ENTITY_ATTRIBS_UK1 
/
CREATE UNIQUE INDEX KRIM_ENTITY_ATTRIB_UK1 ON KRIM_ENTITY_ATTRIB_T (ENTITY_ID,SPONSOR_NMSPC_ID,NM)
/
DROP CONSTRAINT KIM_ENTITY_ATTRIBS_FK2 
/
ALTER TABLE KRIM_ENTITY_ATTRIB_T ADD CONSTRAINT KRIM_ENTITY_ATTRIB_TFK2 FOREIGN KEY  (SPONSOR_NMSPC_ID) REFERENCES KRIM_NMSPC_T (ID) 
/
DROP CONSTRAINT KIM_ENTITY_ATTRIBS_FK3 
/
ALTER TABLE KRIM_ENTITY_ATTRIB_T ADD CONSTRAINT KRIM_ENTITY_ATTRIB_FK3 FOREIGN KEY  (ATTRIBUTE_TYPE_ID) REFERENCES KRIM_ATTRIB_TYP_T (ID) 
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_ENTITY_ATTRIB_T ADD CONSTRAINT KRIM_ENTITY_ATTRIB_FK1 FOREIGN KEY  (ENTITY_ID) REFERENCES KRIM_ENTITYS_T (ID) 
/
DROP INDEX KIM_ENTITY_ATTRIBUTES_TI2 
/
CREATE INDEX KRIM_ENTITY_ATTRIB_TI2 ON KRIM_ENTITY_ATTRIB_T (ENTITY_ID)
/
DROP INDEX KIM_ENTITY_ATTRIBUTES_TI2 
/
CREATE INDEX KRIM_ENTITY_ATTRIB_TI2 ON KRIM_ENTITY_ATTRIB_T (ENTITY_ID,SPONSOR_NMSPC_ID)
/
DROP INDEX KIM_ENTITY_ATTRIBS_UK1 
/
CREATE UNIQUE INDEX KRIM_ENTITY_ATTRIB_UK1 ON KRIM_ENTITY_ATTRIB_T (ENTITY_ID,SPONSOR_NMSPC_ID,NM)
/
DROP CONSTRAINT KIM_ENTITY_ATTRIBS_FK2 
/
ALTER TABLE KRIM_ENTITY_ATTRIB_T ADD CONSTRAINT KRIM_ENTITY_ATTRIB_TFK2 FOREIGN KEY  (SPONSOR_NMSPC_ID) REFERENCES KRIM_NMSPC_T (ID) 
/
DROP CONSTRAINT KIM_ENTITY_ATTRIBS_FK3 
/
ALTER TABLE KRIM_ENTITY_ATTRIB_T ADD CONSTRAINT KRIM_ENTITY_ATTRIB_FK3 FOREIGN KEY  (ATTRIBUTE_TYPE_ID) REFERENCES KRIM_ATTRIB_TYP_T (ID) 
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_ENTITY_ATTRIB_T ADD CONSTRAINT KRIM_ENTITY_ATTRIB_FK1 FOREIGN KEY  (ENTITY_ID) REFERENCES KRIM_ENTITYS_T (ID) 
/
ALTER TABLE KIM_ENTITY_TYPES_T RENAME TO KRIM_ENTITY_TYPES_T
/
ALTER TABLE KIM_GROUPS_GROUPS_T RENAME TO KRIM_GROUPS_GROUPS_T
/
ALTER TABLE KIM_GROUPS_PRINCIPALS_T RENAME TO KRIM_GRPS_PRINCIPALS_T
/
ALTER TABLE KIM_GROUPS_T RENAME TO KRIM_GROUPS_T
/
DROP INDEX KIM_GROUPS_TI1 
/
CREATE INDEX KRIM_GROUPS_TI1 ON KRIM_GROUPS_T (NAME)
/
DROP CONSTRAINT KIM_GROUPS_FK1 
/
ALTER TABLE KRIM_GROUPS_T ADD CONSTRAINT KRIM_GROUPS_FK1 FOREIGN KEY  (GROUP_TYPE_ID) REFERENCES KRIM_GROUP_TYP_T (ID) 
/
ALTER TABLE KIM_GROUP_ATTRIBUTES_T RENAME TO KRIM_GROUP_ATTRIB_T
/
DROP INDEX KIM_GROUP_ATTRIBUTES_TI1 
/
CREATE INDEX KRIM_GROUP_ATTRIB_TI1 ON KRIM_GROUP_ATTRIB_T (GRP_ID)
/
DROP INDEX KIM_GROUP_ATTRIBUTES_UK1 
/
CREATE UNIQUE INDEX KRIM_GROUP_ATTRIB_UK1 ON KRIM_GROUP_ATTRIB_T (GRP_ID,ATTRIBUTE_NAME)
/
DROP CONSTRAINT KIM_GROUP_ATTRIBUTES_FK1 
/
ALTER TABLE KRIM_GROUP_ATTRIB_T ADD CONSTRAINT KRIM_GROUP_ATTRIB_FK1 FOREIGN KEY  (GROUP_ID) REFERENCES KRIM_GROUPS_T (ID) 
/
DROP CONSTRAINT KIM_GROUP_ATTRIBUTES_FK2 
/
ALTER TABLE KRIM_GROUP_ATTRIB_T ADD CONSTRAINT KRIM_GROUP_ATTRIB_FK2 FOREIGN KEY  (ATTRIBUTE_TYPE_ID) REFERENCES KRIM_ATTRIB_TYP_T (ID) 
/
ALTER TABLE KIM_GROUP_QLFD_ROLES_T RENAME TO KRIM_GROUP_QLFD_ROLES_T
/
ALTER TABLE KRIM_GROUP_QLFD_ROLES_T RENAME COLUMN GROUP_ID TO GRP_ID
/
DROP INDEX KIM_GROUP_QLFD_ROLES_TI1 
/
CREATE INDEX KRIM_GROUP_QLFD_ROLES_TI1 ON KRIM_GROUP_QLFD_ROLES_T (GRP_ID)
/
DROP INDEX KIM_GROUP_QLFD_ROLES_UK1 
/
CREATE UNIQUE INDEX KRIM_GROUP_QLFD_ROLES_UK1 ON KRIM_GROUP_QLFD_ROLES_T (GRP_ID,ROLE_ID,ATTRIBUTE_NAME)
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_GROUP_QLFD_ROLES_T ADD CONSTRAINT   FOREIGN KEY  (ROLE_ID) REFERENCES KRIM_ROLES_T (ID) 
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_GROUP_QLFD_ROLES_T ADD CONSTRAINT   FOREIGN KEY  (GROUP_ID) REFERENCES KRIM_GROUPS_T (ID) 
/
DROP INDEX   
/
CREATE INDEX KRIM_GROUP_QLFD_ROLES_TI2 ON KRIM_GROUP_QLFD_ROLES_T (ROLE_ID)
/
DROP INDEX KIM_GROUP_QLFD_ROLES_UK1 
/
CREATE UNIQUE INDEX KRIM_GROUP_QLFD_ROLES_UK1 ON KRIM_GROUP_QLFD_ROLES_T (GRP_ID,ROLE_ID,ATTRIBUTE_NAME)
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_GROUP_QLFD_ROLES_T ADD CONSTRAINT   FOREIGN KEY  (ROLE_ID) REFERENCES KRIM_ROLES_T (ID) 
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_GROUP_QLFD_ROLES_T ADD CONSTRAINT   FOREIGN KEY  (GROUP_ID) REFERENCES KRIM_GROUPS_T (ID) 
/
DROP INDEX KIM_GROUP_QLFD_ROLES_TI3 
/
CREATE INDEX KRIM_GROUP_QLFD_ROLES_TI3 ON KRIM_GROUP_QLFD_ROLES_T (GRP_ID)
/
DROP INDEX KIM_GROUP_QLFD_ROLES_TI3 
/
CREATE INDEX KRIM_GROUP_QLFD_ROLES_TI3 ON KRIM_GROUP_QLFD_ROLES_T (GRP_ID,ROLE_ID)
/
DROP INDEX KIM_GROUP_QLFD_ROLES_UK1 
/
CREATE UNIQUE INDEX KRIM_GROUP_QLFD_ROLES_UK1 ON KRIM_GROUP_QLFD_ROLES_T (GRP_ID,ROLE_ID,ATTRIBUTE_NAME)
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_GROUP_QLFD_ROLES_T ADD CONSTRAINT   FOREIGN KEY  (ROLE_ID) REFERENCES KRIM_ROLES_T (ID) 
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_GROUP_QLFD_ROLES_T ADD CONSTRAINT   FOREIGN KEY  (GROUP_ID) REFERENCES KRIM_GROUPS_T (ID) 
/
ALTER TABLE KIM_GROUP_TYPES_T RENAME TO KRIM_GROUP_TYPES_T
/
ALTER TABLE KIM_GRP_TYP_DFLT_ATTRIBS_T RENAME TO KRIM_GRP_TYP_DFLT_ATTRIBS_T
/
ALTER TABLE KIM_NAMESPACES_T RENAME TO KRIM_NMSPC_T
/
ALTER TABLE KIM_NAMESPACE_DFLT_ATTRIBS_T RENAME TO KRIM_NMSPC_DFLT_ATTRIBS_T
/
ALTER TABLE KIM_PERMISSIONS_T RENAME TO KRIM_PERMISSIONS_T
/
DROP INDEX KIM_PERMISSIONS_TI1 
/
CREATE INDEX KRIM_PERMISSIONS_TI1 ON KRIM_PERMISSIONS_T (NAMESPACE_ID)
/
DROP INDEX KIM_PERMISSIONS_UK1 
/
CREATE UNIQUE INDEX KRIM_PERMISSIONS_UK1 ON KRIM_PERMISSIONS_T (NAME,NAMESPACE_ID)
/
DROP CONSTRAINT KIM_PERMISSIONS_FK1 
/
ALTER TABLE KRIM_PERMISSIONS_T ADD CONSTRAINT KRIM_PERMISSIONS_FK1 FOREIGN KEY  (NAMESPACE_ID) REFERENCES KRIM_NMSPC_T (ID) 
/
ALTER TABLE KIM_PRINCIPALS_T RENAME TO KRIM_PRINCIPALS_T
/
DROP INDEX KIM_PRINCIPALS_TI1 
/
CREATE INDEX KRIM_PRINCIPALS_TI1 ON KRIM_PRINCIPALS_T (ENTITY_ID)
/
DROP INDEX KIM_PRINCIPALS_UK1 
/
CREATE UNIQUE INDEX KRIM_PRINCIPALS_UK1 ON KRIM_PRINCIPALS_T (NAME)
/
DROP INDEX KIM_PRINCIPALS_UK2 
/
CREATE UNIQUE INDEX KRIM_PRINCIPALS_UK2 ON KRIM_PRINCIPALS_T (ID,ENTITY_ID)
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_PRINCIPALS_T ADD CONSTRAINT   FOREIGN KEY  (ENTITY_ID) REFERENCES KRIM_ENTITYS_T (ID) 
/
ALTER TABLE KIM_PRNCPL_QLFD_ROLES_T RENAME TO KRIM_PRNCPL_QLFD_ROLES_T
/
DROP INDEX KIM_PRNCPL_QLFD_ROLES_TI1 
/
CREATE INDEX KRIM_PRNCPL_QLFD_ROLES_TI1 ON KRIM_PRNCPL_QLFD_ROLES_T (PRINCIPAL_ID)
/
DROP INDEX KIM_PRNCPL_QLFD_ROLES_UK1 
/
CREATE UNIQUE INDEX KRIM_PRNCPL_QLFD_ROLES_UK1 ON KRIM_PRNCPL_QLFD_ROLES_T (PRINCIPAL_ID,ROLE_ID,ATTRIBUTE_NAME)
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_PRNCPL_QLFD_ROLES_T ADD CONSTRAINT KRIM_PRNCPL_QLFD_ROLES_FK1 FOREIGN KEY  (PRINCIPAL_ID) REFERENCES KRIM_PRINCIPALS_T (ID) 
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_PRNCPL_QLFD_ROLES_T ADD CONSTRAINT   FOREIGN KEY  (ROLE_ID) REFERENCES KRIM_ROLES_T (ID) 
/
DROP INDEX KIM_PRNCPL_QLFD_ROLES_TI2 
/
CREATE INDEX KRIM_PRNCPL_QLFD_ROLES_TI2 ON KRIM_PRNCPL_QLFD_ROLES_T (ROLE_ID)
/
DROP INDEX KIM_PRNCPL_QLFD_ROLES_UK1 
/
CREATE UNIQUE INDEX KRIM_PRNCPL_QLFD_ROLES_UK1 ON KRIM_PRNCPL_QLFD_ROLES_T (PRINCIPAL_ID,ROLE_ID,ATTRIBUTE_NAME)
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_PRNCPL_QLFD_ROLES_T ADD CONSTRAINT KRIM_PRNCPL_QLFD_ROLES_FK1 FOREIGN KEY  (PRINCIPAL_ID) REFERENCES KRIM_PRINCIPALS_T (ID) 
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_PRNCPL_QLFD_ROLES_T ADD CONSTRAINT   FOREIGN KEY  (ROLE_ID) REFERENCES KRIM_ROLES_T (ID) 
/
DROP INDEX KIM_PRNCPL_QLFD_ROLES_TI3 
/
CREATE INDEX KRIM_PRNCPL_QLFD_ROLES_TI3 ON KRIM_PRNCPL_QLFD_ROLES_T (PRINCIPAL_ID)
/
DROP INDEX KIM_PRNCPL_QLFD_ROLES_TI3 
/
CREATE INDEX KRIM_PRNCPL_QLFD_ROLES_TI3 ON KRIM_PRNCPL_QLFD_ROLES_T (PRINCIPAL_ID,ROLE_ID)
/
DROP INDEX KIM_PRNCPL_QLFD_ROLES_UK1 
/
CREATE UNIQUE INDEX KRIM_PRNCPL_QLFD_ROLES_UK1 ON KRIM_PRNCPL_QLFD_ROLES_T (PRINCIPAL_ID,ROLE_ID,ATTRIBUTE_NAME)
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_PRNCPL_QLFD_ROLES_T ADD CONSTRAINT KRIM_PRNCPL_QLFD_ROLES_FK1 FOREIGN KEY  (PRINCIPAL_ID) REFERENCES KRIM_PRINCIPALS_T (ID) 
/
DROP CONSTRAINT   
/
ALTER TABLE KRIM_PRNCPL_QLFD_ROLES_T ADD CONSTRAINT   FOREIGN KEY  (ROLE_ID) REFERENCES KRIM_ROLES_T (ID) 
/
ALTER TABLE KIM_ROLES_GROUPS_T RENAME TO KRIM_ROLES_GROUPS_T
/
ALTER TABLE KRIM_ROLES_GROUPS_T RENAME COLUMN GROUP_ID TO GRP_ID
/
ALTER TABLE KIM_ROLES_PERMISSIONS_T RENAME TO KRIM_ROLES_PERMISSIONS_T
/
ALTER TABLE KIM_ROLES_PRINCIPALS_T RENAME TO KRIM_ROLES_PRINCIPALS_T
/
ALTER TABLE KIM_ROLES_T RENAME TO KRIM_ROLES_T
/
DROP INDEX KIM_ROLES_TI1 
/
CREATE INDEX KRIM_ROLES_TI1 ON KRIM_ROLES_T (NAME)
/
ALTER TABLE KIM_ROLE_ATTRIBUTES_T RENAME TO KRIM_ROLE_ATTRIBS_T
/
DROP INDEX KIM_ROLE_ATTRIBUTES_TI1 
/
CREATE INDEX KRIM_ROLE_ATTRIBS_TI1 ON KRIM_ROLE_ATTRIBS_T (ROLE_ID)
/
DROP INDEX KIM_ROLE_ATTRIBUTES_UK1 
/
CREATE UNIQUE INDEX KRIM_ROLE_ATTRIBS_UK1 ON KRIM_ROLE_ATTRIBS_T (ROLE_ID,ATTRIBUTE_NAME)
/
DROP CONSTRAINT KIM_ROLE_ATTRIBUTES_FK2 
/
ALTER TABLE KRIM_ROLE_ATTRIBS_T ADD CONSTRAINT KRIM_ROLE_ATTRIBS_FK2 FOREIGN KEY  (ATTRIBUTE_TYPE_ID) REFERENCES KRIM_ATTRIB_TYP_T (ID) 
/
DROP CONSTRAINT KIM_ROLE_ATTRIBUTES_FK1 
/
ALTER TABLE KRIM_ROLE_ATTRIBS_T ADD CONSTRAINT KRIM_ROLE_ATTRIBS_FK1 FOREIGN KEY  (ROLE_ID) REFERENCES KRIM_ROLES_T (ID) 
/
ALTER TABLE KNS_PESSIMISTIC_LOCK_T RENAME TO KRNS_PESSIMISTIC_LOCK_T
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T RENAME COLUMN FDOC_NBR TO NBR
/
DROP INDEX KNS_PESSIMISTIC_LOCK_TI1 
/
CREATE INDEX KRNS_PESSIMISTIC_LOCK_TI1 ON KRNS_PESSIMISTIC_LOCK_T (NBR)
/
DROP INDEX KNS_PESSIMISTIC_LOCK_TC0 
/
CREATE UNIQUE INDEX KRNS_PESSIMISTIC_LOCK_TUK1 ON KRNS_PESSIMISTIC_LOCK_T (OBJ_ID)
/
DROP INDEX KNS_PESSIMISTIC_LOCK_TI2 
/
CREATE INDEX KRNS_PESSIMISTIC_LOCK_TI2 ON KRNS_PESSIMISTIC_LOCK_T (PERSON_UNVL_ID)
/
DROP INDEX KNS_PESSIMISTIC_LOCK_TC0 
/
CREATE UNIQUE INDEX KRNS_PESSIMISTIC_LOCK_TUK1 ON KRNS_PESSIMISTIC_LOCK_T (OBJ_ID)
/
ALTER TABLE KOM_ORGANIZATIONS_CONTEXTS_T RENAME TO KROM_ORGNZTNS_CNTXTS_T
/
ALTER TABLE KOM_ORGANIZATIONS_T RENAME TO KROM_ORGNZTNS_T
/
ALTER TABLE KOM_ORGANIZATIONS_CATEGORIES_T RENAME TO KROM_ORGNZTN_CTGRS_T
/
ALTER TABLE KOM_ORGANIZATION_CONTEXTS_T RENAME TO KROM_ORGNZTN_CNTXTS_T
/
ALTER TABLE KR_KNS_SESN_DOC_T RENAME TO KRNS_SESN_DOC_T
/
ALTER TABLE KRNS_SESN_DOC_T RENAME COLUMN FDOC_NBR TO NBR
/
DROP INDEX KR_KNS_SESN_DOC_TI1 
/
CREATE INDEX KRNS_SESN_DOC_TI1 ON KRNS_SESN_DOC_T (LST_UPDATE_DT)
/
ALTER TABLE KR_QRTZ_BLOB_TRIGGERS RENAME TO KRSB_QRTZ_BLOB_TRIGGERS_T
/
ALTER TABLE KR_QRTZ_CALENDARS RENAME TO KRSB_QRTZ_CALENDARS_T
/
ALTER TABLE KR_QRTZ_CRON_TRIGGERS RENAME TO KRSB_QRTZ_CRON_TRIGGERS_T
/
ALTER TABLE KR_QRTZ_FIRED_TRIGGERS RENAME TO KRSB_QRTZ_FIRED_TRIGGERS_T
/
DROP INDEX IDX_KR_QRTZ_FT_JOB_GROUP 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI1 ON KRSB_QRTZ_FIRED_TRIGGERS_T (JOB_GROUP)
/
DROP INDEX IDX_KR_QRTZ_FT_JOB_NAME 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI2 ON KRSB_QRTZ_FIRED_TRIGGERS_T (JOB_NAME)
/
DROP INDEX IDX_KR_QRTZ_FT_REQ_RECOV 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI3 ON KRSB_QRTZ_FIRED_TRIGGERS_T (REQUESTS_RECOVERY)
/
DROP INDEX IDX_KR_QRTZ_FT_JOB_STATEFUL 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI4 ON KRSB_QRTZ_FIRED_TRIGGERS_T (IS_STATEFUL)
/
DROP INDEX IDX_KR_QRTZ_FT_TRIG_GROUP 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI5 ON KRSB_QRTZ_FIRED_TRIGGERS_T (TRIGGER_GROUP)
/
DROP INDEX IDX_KR_QRTZ_FT_TRIG_INST_NAME 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI6 ON KRSB_QRTZ_FIRED_TRIGGERS_T (INSTANCE_NAME)
/
DROP INDEX IDX_KR_QRTZ_FT_TRIG_NAME 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI7 ON KRSB_QRTZ_FIRED_TRIGGERS_T (TRIGGER_NAME)
/
DROP INDEX IDX_KR_QRTZ_FT_TRIG_NM_GP 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI8 ON KRSB_QRTZ_FIRED_TRIGGERS_T (TRIGGER_NAME)
/
DROP INDEX IDX_KR_QRTZ_FT_TRIG_NM_GP 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI8 ON KRSB_QRTZ_FIRED_TRIGGERS_T (TRIGGER_NAME,TRIGGER_GROUP)
/
DROP INDEX IDX_KR_QRTZ_FT_TRIG_VOLATILE 
/
CREATE INDEX KRSB_QRTZ_FIRED_TRIGGERS_TI9 ON KRSB_QRTZ_FIRED_TRIGGERS_T (IS_VOLATILE)
/
ALTER TABLE KR_QRTZ_JOB_DETAILS RENAME TO KRSB_QRTZ_JOB_DETAILS_T
/
DROP INDEX IDX_KR_QRTZ_J_REQ_RECOVERY 
/
CREATE INDEX KRSB_QRTZ_JOB_DETAILS_TI1 ON KRSB_QRTZ_JOB_DETAILS_T (REQUESTS_RECOVERY)
/
ALTER TABLE KR_QRTZ_JOB_LISTENERS RENAME TO KRSB_QRTZ_JOB_LISTENERS_T
/
ALTER TABLE KR_QRTZ_LOCKS RENAME TO KRSB_QRTZ_LOCKS_T
/
ALTER TABLE KR_QRTZ_PAUSED_TRIGGER_GRPS RENAME TO KRSB_QRTZ_PAUSED_TRIGGER_GRPS_T
/
ALTER TABLE KR_QRTZ_SCHEDULER_STATE RENAME TO KRSB_QRTZ_SCHEDULER_STATE_T
/
ALTER TABLE KR_QRTZ_SIMPLE_TRIGGERS RENAME TO KRSB_QRTZ_SIMPLE_TRIGGERS_T
/
ALTER TABLE KR_QRTZ_TRIGGERS RENAME TO KRSB_QRTZ_TRIGGERS_T
/
DROP INDEX IDX_KR_QRTZ_T_NEXT_FIRE_TIME 
/
CREATE INDEX KRSB_QRTZ_TRIGGERS_TI1 ON KRSB_QRTZ_TRIGGERS_T (NEXT_FIRE_TIME)
/
DROP CONSTRAINT KR_QRTZ_TRIGGERS_TR1 
/
ALTER TABLE KRSB_QRTZ_TRIGGERS_T ADD CONSTRAINT KRSB_QRTZ_TRIGGERS_TR1 FOREIGN KEY  (JOB_NAME,JOB_GROUP) REFERENCES KRSB_QRTZ_JOB_DETAILS_T (JOB_NAME,JOB_GROUP) 
/
DROP INDEX IDX_KR_QRTZ_T_NFT_ST 
/
CREATE INDEX KRSB_QRTZ_TRIGGERS_TI2 ON KRSB_QRTZ_TRIGGERS_T (NEXT_FIRE_TIME)
/
DROP INDEX IDX_KR_QRTZ_T_NFT_ST 
/
CREATE INDEX KRSB_QRTZ_TRIGGERS_TI2 ON KRSB_QRTZ_TRIGGERS_T (NEXT_FIRE_TIME,TRIGGER_STATE)
/
DROP CONSTRAINT KR_QRTZ_TRIGGERS_TR1 
/
ALTER TABLE KRSB_QRTZ_TRIGGERS_T ADD CONSTRAINT KRSB_QRTZ_TRIGGERS_TR1 FOREIGN KEY  (JOB_NAME,JOB_GROUP) REFERENCES KRSB_QRTZ_JOB_DETAILS_T (JOB_NAME,JOB_GROUP) 
/
DROP INDEX IDX_KR_QRTZ_T_STATE 
/
CREATE INDEX KRSB_QRTZ_TRIGGERS_TI3 ON KRSB_QRTZ_TRIGGERS_T (TRIGGER_STATE)
/
DROP CONSTRAINT KR_QRTZ_TRIGGERS_TR1 
/
ALTER TABLE KRSB_QRTZ_TRIGGERS_T ADD CONSTRAINT KRSB_QRTZ_TRIGGERS_TR1 FOREIGN KEY  (JOB_NAME,JOB_GROUP) REFERENCES KRSB_QRTZ_JOB_DETAILS_T (JOB_NAME,JOB_GROUP) 
/
DROP INDEX IDX_KR_QRTZ_T_VOLATILE 
/
CREATE INDEX KRSB_QRTZ_TRIGGERS_TI4 ON KRSB_QRTZ_TRIGGERS_T (IS_VOLATILE)
/
DROP CONSTRAINT KR_QRTZ_TRIGGERS_TR1 
/
ALTER TABLE KRSB_QRTZ_TRIGGERS_T ADD CONSTRAINT KRSB_QRTZ_TRIGGERS_TR1 FOREIGN KEY  (JOB_NAME,JOB_GROUP) REFERENCES KRSB_QRTZ_JOB_DETAILS_T (JOB_NAME,JOB_GROUP) 
/
ALTER TABLE KR_QRTZ_TRIGGERS_LISTENERS RENAME TO KRSB_QRTZ_TRIGGERS_LISTENERS_T
/
ALTER TABLE NOTIFICATIONS RENAME TO KREN_NOTIFICATIONS_T
/
ALTER TABLE KREN_NOTIFICATIONS_T RENAME COLUMN CREATED_DATETIME TO CRTE_DT
/
DROP INDEX KEN_NOTIFICATIONSI1 
/
CREATE INDEX KREN_NOTIFICATIONS_I1 ON KREN_NOTIFICATIONS_T (CONTENT_TYPE_ID)
/
DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK4 
/
ALTER TABLE KREN_NOTIFICATIONS_T ADD CONSTRAINT KREN_NOTIFICATIONS_FK4 FOREIGN KEY  (PRODUCER_ID) REFERENCES KREN_PRODUCERS_T (ID) 
/
DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK2 
/
ALTER TABLE KREN_NOTIFICATIONS_T ADD CONSTRAINT KREN_NOTIFICATIONS_FK2 FOREIGN KEY  (CONTENT_TYPE_ID) REFERENCES KREN_CONTENT_TYPES_T (ID) 
/
DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK1 
/
ALTER TABLE KREN_NOTIFICATIONS_T ADD CONSTRAINT KREN_NOTIFICATIONS_FK1 FOREIGN KEY  (NOTIFICATION_CHANNEL_ID) REFERENCES KREN_NOTIFICATIONS_CHANNELS_T (ID) 
/
DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK3 
/
ALTER TABLE KREN_NOTIFICATIONS_T ADD CONSTRAINT KREN_NOTIFICATIONS_FK3 FOREIGN KEY  (PRIORITY_ID) REFERENCES KREN_PRIORITIES_T (ID) 
/
DROP INDEX KEN_NOTIFICATIONSI2 
/
CREATE INDEX KREN_NOTIFICATIONS_I2 ON KREN_NOTIFICATIONS_T (PRIORITY_ID)
/
DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK4 
/
ALTER TABLE KREN_NOTIFICATIONS_T ADD CONSTRAINT KREN_NOTIFICATIONS_FK4 FOREIGN KEY  (PRODUCER_ID) REFERENCES KREN_PRODUCERS_T (ID) 
/
DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK2 
/
ALTER TABLE KREN_NOTIFICATIONS_T ADD CONSTRAINT KREN_NOTIFICATIONS_FK2 FOREIGN KEY  (CONTENT_TYPE_ID) REFERENCES KREN_CONTENT_TYPES_T (ID) 
/
DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK1 
/
ALTER TABLE KREN_NOTIFICATIONS_T ADD CONSTRAINT KREN_NOTIFICATIONS_FK1 FOREIGN KEY  (NOTIFICATION_CHANNEL_ID) REFERENCES KREN_NOTIFICATIONS_CHANNELS_T (ID) 
/
DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK3 
/
ALTER TABLE KREN_NOTIFICATIONS_T ADD CONSTRAINT KREN_NOTIFICATIONS_FK3 FOREIGN KEY  (PRIORITY_ID) REFERENCES KREN_PRIORITIES_T (ID) 
/
DROP INDEX KEN_NOTIFICATIONSI3 
/
CREATE INDEX KREN_NOTIFICATIONS_I3 ON KREN_NOTIFICATIONS_T (PRODUCER_ID)
/
DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK4 
/
ALTER TABLE KREN_NOTIFICATIONS_T ADD CONSTRAINT KREN_NOTIFICATIONS_FK4 FOREIGN KEY  (PRODUCER_ID) REFERENCES KREN_PRODUCERS_T (ID) 
/
DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK2 
/
ALTER TABLE KREN_NOTIFICATIONS_T ADD CONSTRAINT KREN_NOTIFICATIONS_FK2 FOREIGN KEY  (CONTENT_TYPE_ID) REFERENCES KREN_CONTENT_TYPES_T (ID) 
/
DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK1 
/
ALTER TABLE KREN_NOTIFICATIONS_T ADD CONSTRAINT KREN_NOTIFICATIONS_FK1 FOREIGN KEY  (NOTIFICATION_CHANNEL_ID) REFERENCES KREN_NOTIFICATIONS_CHANNELS_T (ID) 
/
DROP CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK3 
/
ALTER TABLE KREN_NOTIFICATIONS_T ADD CONSTRAINT KREN_NOTIFICATIONS_FK3 FOREIGN KEY  (PRIORITY_ID) REFERENCES KREN_PRIORITIES_T (ID) 
/
ALTER TABLE NOTIFICATIONS_CHANNELS RENAME TO KREN_NOTIFICATION_CHANNELS_T
/
ALTER TABLE NOTIFICATION_CHANNEL_PRODUCERS RENAME TO KREN_CHANNEL_PRODUCERS_T
/
DROP INDEX KEN_CHANNEL_PRODUCERSI1 
/
CREATE INDEX KREN_CHANNEL_PRODI1 ON KREN_CHANNEL_PRODUCERS_T (CHANNEL_ID)
/
DROP CONSTRAINT NOTIFICATION_CHANNEL_PROD_FK1 
/
ALTER TABLE KREN_CHANNEL_PRODUCERS_T ADD CONSTRAINT KREN_CHANNEL_PROD_FK1 FOREIGN KEY  (CHANNEL_ID) REFERENCES KREN_NOTIFICATIONS_CHANNELS_T (ID) 
/
DROP CONSTRAINT NOTIFICATION_CHANNEL_PROD_FK2 
/
ALTER TABLE KREN_CHANNEL_PRODUCERS_T ADD CONSTRAINT KREN_CHANNEL_PROD_FK2 FOREIGN KEY  (PRODUCER_ID) REFERENCES KREN_PRODUCERS_T (ID) 
/
DROP INDEX KEN_CHANNEL_PRODUCERSI2 
/
CREATE INDEX KREN_CHANNEL_PRODI2 ON KREN_CHANNEL_PRODUCERS_T (PRODUCER_ID)
/
DROP CONSTRAINT NOTIFICATION_CHANNEL_PROD_FK1 
/
ALTER TABLE KREN_CHANNEL_PRODUCERS_T ADD CONSTRAINT KREN_CHANNEL_PROD_FK1 FOREIGN KEY  (CHANNEL_ID) REFERENCES KREN_NOTIFICATIONS_CHANNELS_T (ID) 
/
DROP CONSTRAINT NOTIFICATION_CHANNEL_PROD_FK2 
/
ALTER TABLE KREN_CHANNEL_PRODUCERS_T ADD CONSTRAINT KREN_CHANNEL_PROD_FK2 FOREIGN KEY  (PRODUCER_ID) REFERENCES KREN_PRODUCERS_T (ID) 
/
ALTER TABLE NOTIFICATION_CONTENT_TYPES RENAME TO KREN_CONTENT_TYPES_T
/
ALTER TABLE NOTIFICATION_MSG_DELIVS RENAME TO KREN_MSG_DELIVS_T
/
DROP INDEX KEN_MSG_DELIVSI1 
/
CREATE INDEX KREN_MSG_DELIVSI1 ON KREN_MSG_DELIVS_T (NOTIFICATION_ID)
/
DROP INDEX NOTIF_MSG_DELIVS_UK1 
/
CREATE UNIQUE INDEX KREN_MSG_DELIVS_UK1 ON KREN_MSG_DELIVS_T (NOTIFICATION_ID,USER_RECIPIENT_ID)
/
DROP CONSTRAINT NOTIF_MSG_DELIVS_FK1 
/
ALTER TABLE KREN_MSG_DELIVS_T ADD CONSTRAINT KREN_MSG_DELIVS_FK1 FOREIGN KEY  (NOTIFICATION_ID) REFERENCES KREN_NOTIFICATIONS_T (ID) 
/
ALTER TABLE NOTIFICATION_PRIORITIES RENAME TO KREN_PRIORITIES_T
/
ALTER TABLE NOTIFICATION_PRODUCERS RENAME TO KREN_PRODUCERS_T
/
ALTER TABLE NOTIFICATION_RECIPIENTS RENAME TO KREN_RECIPIENTS_T
/
DROP INDEX KEN_RECIPIENTSI1 
/
CREATE INDEX KREN_RECIPIENTSI1 ON KREN_RECIPIENTS_T (NOTIFICATION_ID)
/
DROP INDEX NOTIFICATION_RECIPIENTS_UK1 
/
CREATE UNIQUE INDEX KREN_RECIPIENTS_UK1 ON KREN_RECIPIENTS_T (NOTIFICATION_ID,RECIPIENT_TYPE,RECIPIENT_ID)
/
DROP CONSTRAINT NOTIFICATION_RECIPIENTS_N_FK1 
/
ALTER TABLE KREN_RECIPIENTS_T ADD CONSTRAINT KREN_RECIPIENTS_FK1 FOREIGN KEY  (NOTIFICATION_ID) REFERENCES KREN_NOTIFICATIONS_T (ID) 
/
ALTER TABLE NOTIFICATION_RECIPIENTS_LISTS RENAME TO KREN_RECIPIENTS_LISTS_T
/
DROP INDEX KEN_RECIPIENTS_LISTSI1 
/
CREATE INDEX KREN_RECIPIENTS_L_I1 ON KREN_RECIPIENTS_LISTS_T (CHANNEL_ID)
/
DROP INDEX NOTIFICATION_RECIPIENTS_L_UK1 
/
CREATE UNIQUE INDEX KREN_RECIPIENTS_L_UK1 ON KREN_RECIPIENTS_LISTS_T (CHANNEL_ID,RECIPIENT_TYPE,RECIPIENT_ID)
/
DROP CONSTRAINT NOTIFICATION_RECIPIENTS_L_FK1 
/
ALTER TABLE KREN_RECIPIENTS_LISTS_T ADD CONSTRAINT KREN_RECIPIENTS_L_FK1 FOREIGN KEY  (CHANNEL_ID) REFERENCES KREN_NOTIFICATIONS_CHANNELS_T (ID) 
/
ALTER TABLE NOTIFICATION_REVIEWERS RENAME TO KREN_REVIEWERS_T
/
DROP INDEX KEN_REVIEWERSI1 
/
CREATE INDEX KREN_REVIEWERSI1 ON KREN_REVIEWERS_T (CHANNEL_ID)
/
DROP INDEX NOTIFICATION_REVIEWERS_UK1 
/
CREATE UNIQUE INDEX KREN_REVIEWERS_UK1 ON KREN_REVIEWERS_T (CHANNEL_ID,REVIEWER_TYPE,REVIEWER_ID)
/
DROP CONSTRAINT   
/
ALTER TABLE KREN_REVIEWERS_T ADD CONSTRAINT KREN_REVIEWERS_FK1 FOREIGN KEY  (CHANNEL_ID) REFERENCES KREN_NOTIFICATIONS_CHANNELS_T (ID) 
/
ALTER TABLE NOTIFICATION_SENDERS RENAME TO KREN_SENDERS_T
/
DROP INDEX KEN_SENDERSI1 
/
CREATE INDEX KREN_SENDERS_I1 ON KREN_SENDERS_T (NOTIFICATION_ID)
/
DROP INDEX NOTIFICATION_SENDERS_UK1 
/
CREATE UNIQUE INDEX KREN_SENDERS_UK1 ON KREN_SENDERS_T (NOTIFICATION_ID,NAME)
/
DROP CONSTRAINT NOTIFICATION_SENDERS_NOTI_FK1 
/
ALTER TABLE KREN_SENDERS_T ADD CONSTRAINT KREN_SENDERS_FK1 FOREIGN KEY  (NOTIFICATION_ID) REFERENCES KREN_NOTIFICATIONS_T (ID) 
/
ALTER TABLE SH_ATT_T RENAME TO KRNS_ATT_T
/
ALTER TABLE SH_NTE_T RENAME TO KRNS_NTE_T
/
ALTER TABLE SH_NTE_TYP_T RENAME TO KRNS_NTE_TYP_T
/
ALTER TABLE SH_PARM_DTL_TYP_T RENAME TO KRNS_PARM_DTL_TYP_T
/
ALTER TABLE SH_PARM_NMSPC_T RENAME TO KRNS_PARM_NMSPC_T
/
ALTER TABLE SH_PARM_T RENAME TO KRNS_PARM_T
/
ALTER TABLE SH_PARM_TYP_T RENAME TO KRNS_PARM_TYP_T
/
ALTER TABLE SH_USR_PROP_T RENAME TO KRNS_USR_PROP_T
/
ALTER TABLE USER_CHANNEL_SUBSCRIPTIONS RENAME TO KRNS_USR_CHANNEL_SUBSCRIPTIONS_T
/
DROP INDEX KEN_USER_CHAN_SUBSI1 
/
CREATE INDEX KRNS_USR_CHAN_SUBS_I1 ON KRNS_USR_CHANNEL_SUBSCRIPTIONS_T (CHANNEL_ID)
/
DROP INDEX USER_CHANNEL_SUBSCRIPTION_UK1 
/
CREATE UNIQUE INDEX KRNS_USR_CHAN_SUBS_UK1 ON KRNS_USR_CHANNEL_SUBSCRIPTIONS_T (CHANNEL_ID,USER_ID)
/
DROP CONSTRAINT USER_CHANNEL_SUBSCRIPTION_FK1 
/
ALTER TABLE KRNS_USR_CHANNEL_SUBSCRIPTIONS_T ADD CONSTRAINT KRNS_USR_CHAN_SUBS_FK1 FOREIGN KEY  (CHANNEL_ID) REFERENCES KREN_NOTIFICATION_CHANNELS_T (ID) 
/
CREATE SEQUENCE KREW_BAM_PARAM_S START WITH BAM_PARAM_SEQ.NEXTVAL 
/
 DROP SEQUENCE BAM_PARAM_SEQ
/
 CREATE SEQUENCE KREW_BAM_S START WITH BAM_SEQ.NEXTVAL 
/
 DROP SEQUENCE BAM_SEQ
/
 CREATE SEQUENCE KREW_DIRTY_CACHE_S START WITH DIRTY_CACHE_SEQ.NEXTVAL 
/
 DROP SEQUENCE DIRTY_CACHE_SEQ
/
 CREATE SEQUENCE KRSB_SVC_DEF_INT_S START WITH EN_SERVICE_DEF_INTERFACE_SEQ.NEXTVAL 
/
 DROP SEQUENCE EN_SERVICE_DEF_INTERFACE_SEQ
/
 CREATE SEQUENCE KRNS_DOC_TYPE_ATTR_ID_S START WITH FP_DOC_TYPE_ATTR_ID_SEQ.NEXTVAL 
/
 DROP SEQUENCE FP_DOC_TYPE_ATTR_ID_SEQ
/
 CREATE SEQUENCE KREN_MESSAGES_S START WITH KCB_MESSAGES_SEQ.NEXTVAL 
/
 DROP SEQUENCE KCB_MESSAGES_SEQ
/
 CREATE SEQUENCE KREN_MSG_DELIVS_S START WITH KCB_MSG_DELIVS_SEQ.NEXTVAL 
/
 DROP SEQUENCE KCB_MSG_DELIVS_SEQ
/
 CREATE SEQUENCE KREN_RECIP_DELIVS_S START WITH KCB_RECIP_DELIVS_SEQ.NEXTVAL 
/
 DROP SEQUENCE KCB_RECIP_DELIVS_SEQ
/
 CREATE SEQUENCE KREN_RECIP_PREFS_S START WITH KCB_RECIP_PREFS_SEQ.NEXTVAL 
/
 DROP SEQUENCE KCB_RECIP_PREFS_SEQ
/
 CREATE SEQUENCE KRNS_LOCK_ID_S START WITH LOCK_ID_SEQ.NEXTVAL 
/
 DROP SEQUENCE LOCK_ID_SEQ
/
 CREATE SEQUENCE KRNS_LOOKUP_RESULT_SEQ_NBR_S START WITH LOOKUP_RESULT_SEQUENCE_NBR_SEQ.NEXTVAL 
/
 DROP SEQUENCE LOOKUP_RESULT_SEQUENCE_NBR_SEQ
/
 CREATE SEQUENCE KREN_NOTIFICATIONS_S START WITH NOTIFICATIONS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATIONS_SEQ
/
 CREATE SEQUENCE KREN_CHANNELS_S START WITH NOTIFICATION_CHANNELS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_CHANNELS_SEQ
/
 CREATE SEQUENCE KREN_CONTENT_TYPES_S START WITH NOTIFICATION_CONTENT_TYPES_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_CONTENT_TYPES_SEQ
/
 CREATE SEQUENCE KREN_MSG_DELIVS_S START WITH NOTIFICATION_MSG_DELIVS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_MSG_DELIVS_SEQ
/
 CREATE SEQUENCE KREN_PRIORITIES_S START WITH NOTIFICATION_PRIORITIES_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_PRIORITIES_SEQ
/
 CREATE SEQUENCE KREN_PRODUCERS_S START WITH NOTIFICATION_PRODUCERS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_PRODUCERS_SEQ
/
 CREATE SEQUENCE KREN_RECIPIENTS_S START WITH NOTIFICATION_RECIPIENTS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_RECIPIENTS_SEQ
/
 CREATE SEQUENCE KREN_RECIPS_LISTS_S START WITH NOTIFICATION_RECIPS_LISTS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_RECIPS_LISTS_SEQ
/
 CREATE SEQUENCE KREN_REVIEWERS_S START WITH NOTIFICATION_REVIEWERS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_REVIEWERS_SEQ
/
 CREATE SEQUENCE KREN_SENDERS_S START WITH NOTIFICATION_SENDERS_SEQ.NEXTVAL 
/
 DROP SEQUENCE NOTIFICATION_SENDERS_SEQ
/
 CREATE SEQUENCE KREW_NTE_ID_S START WITH NTE_ID_SEQ.NEXTVAL 
/
 DROP SEQUENCE NTE_ID_SEQ
/
 CREATE SEQUENCE KREW_USR_S START WITH SEQUENCE_EN_USR.NEXTVAL 
/
 DROP SEQUENCE SEQUENCE_EN_USR
/
 CREATE SEQUENCE KREW_ACTION_LIST_OPTN_S START WITH SEQ_ACTION_LIST_OPTN.NEXTVAL 
/
 DROP SEQUENCE SEQ_ACTION_LIST_OPTN
/
 CREATE SEQUENCE KREW_ACTION_REQUEST_S START WITH SEQ_ACTION_REQUEST.NEXTVAL 
/
 DROP SEQUENCE SEQ_ACTION_REQUEST
/
 CREATE SEQUENCE KREW_ACTION_TAKEN_S START WITH SEQ_ACTION_TAKEN.NEXTVAL 
/
 DROP SEQUENCE SEQ_ACTION_TAKEN
/
 CREATE SEQUENCE KREW_ACTN_ITM_S START WITH SEQ_ACTN_ITM.NEXTVAL 
/
 DROP SEQUENCE SEQ_ACTN_ITM
/
 CREATE SEQUENCE KREW_DOC_ROUTE_HDR_S START WITH SEQ_DOCUMENT_ROUTE_HEADER.NEXTVAL 
/
 DROP SEQUENCE SEQ_DOCUMENT_ROUTE_HEADER
/
 CREATE SEQUENCE KREW_DOC_TYPE_ATTRIB_S START WITH SEQ_DOCUMENT_TYPE_ATTRIBUTE.NEXTVAL 
/
 DROP SEQUENCE SEQ_DOCUMENT_TYPE_ATTRIBUTE
/
 CREATE SEQUENCE KREW_DOC_NTE_S START WITH SEQ_DOC_NTE.NEXTVAL 
/
 DROP SEQUENCE SEQ_DOC_NTE
/
 CREATE SEQUENCE KREW_EDL_FIELD_DMP_S START WITH SEQ_EDL_FIELD_DMP.NEXTVAL 
/
 DROP SEQUENCE SEQ_EDL_FIELD_DMP
/
 CREATE SEQUENCE KREW_EDOCLT_S START WITH SEQ_EN_EDOCLT.NEXTVAL 
/
 DROP SEQUENCE SEQ_EN_EDOCLT
/
 CREATE SEQUENCE KREW_HELP_ENTRY_S START WITH SEQ_HELP_ENTRY.NEXTVAL 
/
 DROP SEQUENCE SEQ_HELP_ENTRY
/
 CREATE SEQUENCE KRIM_ATTRIB_TYP_ID_S START WITH SEQ_KIM_ATTRIBUTE_TYPES_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_ATTRIBUTE_TYPES_ID
/
 CREATE SEQUENCE KRIM_ENTITYS_ID_S START WITH SEQ_KIM_ENTITYS_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_ENTITYS_ID
/
 CREATE SEQUENCE KRIM_ENTITY_ATTRIBS_ID_S START WITH SEQ_KIM_ENTITY_ATTRIBS_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_ENTITY_ATTRIBS_ID
/
 CREATE SEQUENCE KRIM_ENTITY_TYPES_ID_S START WITH SEQ_KIM_ENTITY_TYPES_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_ENTITY_TYPES_ID
/
 CREATE SEQUENCE KRIM_GROUPS_ID_S START WITH SEQ_KIM_GROUPS_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_GROUPS_ID
/
 CREATE SEQUENCE KRIM_GROUP_ATTRIBS_ID_S START WITH SEQ_KIM_GROUP_ATTRIBUTES_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_GROUP_ATTRIBUTES_ID
/
 CREATE SEQUENCE KRIM_GROUP_QLFD_ROLES_ID_S START WITH SEQ_KIM_GROUP_QLFD_ROLES_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_GROUP_QLFD_ROLES_ID
/
 CREATE SEQUENCE KRIM_GROUP_TYPES_ID_S START WITH SEQ_KIM_GROUP_TYPES_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_GROUP_TYPES_ID
/
 CREATE SEQUENCE KRIM_GRP_TYP_DFLT_ATTR_ID_S START WITH SEQ_KIM_GRP_TYP_DFLT_ATTR_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_GRP_TYP_DFLT_ATTR_ID
/
 CREATE SEQUENCE KRIM_NMSPC_S START WITH SEQ_KIM_NAMESPACES_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_NAMESPACES_ID
/
 CREATE SEQUENCE KRIM_NMSPCE_DFLT_ATTR_ID_S START WITH SEQ_KIM_NMSPCE_DFLT_ATTR_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_NMSPCE_DFLT_ATTR_ID
/
 CREATE SEQUENCE KRIM_PERMISSIONS_ID_S START WITH SEQ_KIM_PERMISSIONS_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_PERMISSIONS_ID
/
 CREATE SEQUENCE KRIM_PRINCIPALS_ID_S START WITH SEQ_KIM_PRINCIPALS_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_PRINCIPALS_ID
/
 CREATE SEQUENCE KRIM_PRNCPL_QLFD_ROLES_ID_S START WITH SEQ_KIM_PRNCPL_QLFD_ROLES_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_PRNCPL_QLFD_ROLES_ID
/
 CREATE SEQUENCE KRIM_ROLES_ID_S START WITH SEQ_KIM_ROLES_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_ROLES_ID
/
 CREATE SEQUENCE KRIM_ROLES_ATTR_ID_S START WITH SEQ_KIM_ROLES_ATTRIBUTES_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KIM_ROLES_ATTRIBUTES_ID
/
 CREATE SEQUENCE KROM_ORGANIZATIONS_ID_S START WITH SEQ_KOM_ORGANIZATIONS_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KOM_ORGANIZATIONS_ID
/
 CREATE SEQUENCE KROM_ORGNZTNS_CNTXTS_ID_S START WITH SEQ_KOM_ORGNZTNS_CNTXTS_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KOM_ORGNZTNS_CNTXTS_ID
/
 CREATE SEQUENCE KROM_ORGNZTN_CNTXTS_ID_S START WITH SEQ_KOM_ORGNZTN_CNTXTS_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KOM_ORGNZTN_CNTXTS_ID
/
 CREATE SEQUENCE KROM_ORGNZTN_CTGRS_ID_S START WITH SEQ_KOM_ORGNZTN_CTGRS_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_KOM_ORGNZTN_CTGRS_ID
/
 CREATE SEQUENCE KREW_OUT_BOX_ITM_S START WITH SEQ_OUT_BOX_ITM.NEXTVAL 
/
 DROP SEQUENCE SEQ_OUT_BOX_ITM
/
 CREATE SEQUENCE KREW_RESPONSIBILITY_ID_S START WITH SEQ_RESPONSIBILITY_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_RESPONSIBILITY_ID
/
 CREATE SEQUENCE KREW_ROUTE_QUEUE_ID_S START WITH SEQ_ROUTE_QUEUE_ID.NEXTVAL 
/
 DROP SEQUENCE SEQ_ROUTE_QUEUE_ID
/
 CREATE SEQUENCE KREW_ROUTE_TEMPLATE_S START WITH SEQ_ROUTE_TEMPLATE.NEXTVAL 
/
 DROP SEQUENCE SEQ_ROUTE_TEMPLATE
/
 CREATE SEQUENCE KREW_RTE_NODE_S START WITH SEQ_RTE_NODE.NEXTVAL 
/
 DROP SEQUENCE SEQ_RTE_NODE
/
 CREATE SEQUENCE KREW_RTE_NODE_CFG_PARM_S START WITH SEQ_RTE_NODE_CFG_PARM.NEXTVAL 
/
 DROP SEQUENCE SEQ_RTE_NODE_CFG_PARM
/
 CREATE SEQUENCE KREW_RULE_EXPR_PARM_S START WITH SEQ_RULE_EXPR_PARM.NEXTVAL 
/
 DROP SEQUENCE SEQ_RULE_EXPR_PARM
/
 CREATE SEQUENCE KREW_RULE_TMPL_OPTN_S START WITH SEQ_RULE_TMPL_OPTN.NEXTVAL 
/
 DROP SEQUENCE SEQ_RULE_TMPL_OPTN
/
 CREATE SEQUENCE KREW_SEARCHABLE_ATTR_VAL_S START WITH SEQ_SEARCHABLE_ATTRIBUTE_VALUE.NEXTVAL 
/
 DROP SEQUENCE SEQ_SEARCHABLE_ATTRIBUTE_VALUE
/
 CREATE SEQUENCE KREW_TRANSACTION_TST_S START WITH SEQ_TRANSACTION_TST.NEXTVAL 
/
 DROP SEQUENCE SEQ_TRANSACTION_TST
/
 CREATE SEQUENCE KRSB_SVC_DEF_S START WITH SERVICE_DEF_SEQ.NEXTVAL 
/
 DROP SEQUENCE SERVICE_DEF_SEQ
/
 CREATE SEQUENCE KREW_USR_CHANNEL_SUBS_S START WITH USER_CHANNEL_SUBSCRIPTIONS_SEQ.NEXTVAL 
/
 DROP SEQUENCE USER_CHANNEL_SUBSCRIPTIONS_SEQ
/
 