INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',0,'docHandler is now mandatory...','Workflow Maintenance Document',2010,'EDENSERVICE-DOCS',0,'1','Workflow Maintenance Document','none','2',6);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,PARNT_ID,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${workflow.url}/DocumentType.do?methodToCall=docHandler','Workflow Maintenance Document Type Document',2011,'EDENSERVICE-DOCS.DocumentType',0,'1','Workflow Maintenance Document Type Document',2682,'edu.iu.uis.eden.doctype.DocumentTypePostProcessor','2',2);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,PARNT_ID,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${workflow.url}/Rule.do?methodToCall=docHandler','Rule Maintenance Document Type Document',2012,'EDENSERVICE-DOCS.RuleDocument',0,'1','Rule Maintenance Document Type Document',2682,'org.kuali.rice.kew.rule.RulePostProcessor','2',2);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,PARNT_ID,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${workflow.url}/Workgroup.do?methodToCall=docHandler','Document to generate a new workgroup',2013,'EDENSERVICE-DOCS.WKGRPREQ',0,'1','Add/modify EDEN workgroup',2682,'org.kuali.rice.kew.workgroup.WorkgroupPostProcessor','1',2);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,PARNT_ID,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${workflow.url}/RemoveReplace.do?methodToCall=docHandler','A document to remove or replace users within rules and workgroups.',2014,'EDENSERVICE-DOCS.RemoveReplaceUser',0,'1','Remove/Replace User',2682,'org.kuali.rice.kew.removereplace.RemoveReplacePostProcessor','1',2);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create or Update a Principal',2015,'KIMPrincipalMaintenanceDocument',0,'1','KIM Principal Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','1',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create or Update a Group',2016,'KIMGroupMaintenanceDocument',0,'1','KIM Group Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','1',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create or Update a Principal',2017,'KIMRoleMaintenanceDocument',0,'1','KIM Role Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','1',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create or Update a Attribute Type',2018,'KIMAttributeTypeMaintenanceDocument',0,'1','KIM Attribute Type Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','1',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create or Update a Namespace',2019,'KIMNamespaceMaintenanceDocument',0,'1','KIM Namespace Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','1',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create or Update a EntityType',2020,'KIMEntityTypeMaintenanceDocument',0,'1','KIM EntityType Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','1',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create or Update a Entity',2021,'KIMEntityMaintenanceDocument',0,'1','KIM Entity Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','1',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create or Update a Group Type',2022,'KIMGroupTypeMaintenanceDocument',0,'1','KIM Group Type Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','1',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${notification.basewebappurl}/DetailView.form','This is the re-usable notification document type that will be used for delivering all notifications with KEW.',2023,'KualiNotification',0,'2000','Notification','org.kuali.rice.ken.postprocessor.kew.NotificationPostProcessor','1',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${notification.basewebappurl}/AdministerNotificationRequest.form','Create a New Notification Request',2024,'SendNotificationRequest',0,'1','Send Notification Request','org.kuali.rice.ken.postprocessor.kew.NotificationSenderFormPostProcessor','2',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create or Update a Organization',2025,'KualiOrganizationMaintenanceDocument',0,'1','Kuali Organization Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','1',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create or Update a Organization Category',2026,'KualiOrganizationCategoryMaintenanceDocument',0,'1','Kuali Organization Category Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','1',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create or Update a Organization Context',2027,'KualiOrganizationContextMaintenanceDocument',0,'1','Kuali Organization Context Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','1',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',0,'${application.url}/travelDocument2.do?methodToCall=docHandler','Create a New Travel Request',2028,'TravelRequest',0,'1','Travel Request','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','2',2);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create a New Travel Account Maintenance Document',2029,'TravelAccountMaintenanceDocument',0,'1','Travel Account Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','2',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create a New Travel Fiscal Officer',2030,'FiscalOfficerMaintenanceDocument',0,'1','Travel Fiscal Officer','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','2',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create/edit parameter namespaces',2031,'ParameterNamespaceMaintenanceDocument',0,'1','Parameter Namespace Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','2',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create/edit a parameter type',2032,'ParameterTypeMaintenanceDocument',0,'1','Parameter Type Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','2',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create/edit a parameter detail type',2033,'ParameterDetailTypeMaintenanceDocument',0,'1','Parameter Detail Type Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','2',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create/edit a parameter',2034,'ParameterMaintenanceDocument',0,'1','Parameter Maintenance Document','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','2',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${kr.url}/maintenance.do?methodToCall=docHandler','Create a Rice User',2035,'RiceUserMaintenanceDocument',0,'1','Create a Rice User','org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor','2',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_PLCY,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'NONE',0,'${workflow.url}/EDocLite','eDoc.Example1 Parent Doctype',2204,'eDoc.Example1.ParentDoctype',0,'2200','eDoc.Example1 Parent Document','org.kuali.rice.kew.edl.EDocLitePostProcessor','2',3);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_PLCY,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,PARNT_ID,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'NONE',0,'${workflow.url}/EDocLite','eDoc.Example1 Request DocumentType',2205,'eDoc.Example1Doctype',0,'2200','eDoc.Example1 Request DocumentType',2206,'org.kuali.rice.kew.edl.EDocLitePostProcessor','2',3);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_PLCY,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,PREV_DOC_TYP_VER_NBR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'NONE',0,'${workflow.url}/EDocLite','eDoc.Example1 Parent Doctype',2206,'eDoc.Example1.ParentDoctype',1,'2200','eDoc.Example1 Parent Document','org.kuali.rice.kew.edl.EDocLitePostProcessor',2204,'2',3);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_PLCY,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,PARNT_ID,POST_PRCSR,PREV_DOC_TYP_VER_NBR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'NONE',0,'${workflow.url}/EDocLite','eDoc.Example1 Request DocumentType',2215,'eDoc.Example1Doctype',1,'2200','eDoc.Example1 Request DocumentType',2217,'org.kuali.rice.kew.edl.EDocLitePostProcessor',2205,'2',4);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_PLCY,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,PREV_DOC_TYP_VER_NBR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'NONE',0,'${workflow.url}/EDocLite','eDoc.Example1 Parent Doctype',2216,'eDoc.Example1.ParentDoctype',2,'2200','eDoc.Example1 Parent Document','org.kuali.rice.kew.edl.EDocLitePostProcessor',2206,'2',2);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_PLCY,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,PREV_DOC_TYP_VER_NBR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'NONE',1,'${workflow.url}/EDocLite','eDoc.Example1 Parent Doctype',2217,'eDoc.Example1.ParentDoctype',3,'2200','eDoc.Example1 Parent Document','org.kuali.rice.kew.edl.EDocLitePostProcessor',2216,'2',3);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',0,'none','SampleThinClientDocument',2280,'SampleThinClientDocument',0,'1','SampleThinClientDocument','org.kuali.rice.kew.postprocessor.DefaultPostProcessor','2',2);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,POST_PRCSR,PREV_DOC_TYP_VER_NBR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'none','SampleThinClientDocument',2282,'SampleThinClientDocument',1,'1','SampleThinClientDocument','org.kuali.rice.kew.postprocessor.DefaultPostProcessor',2280,'2',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_PLCY,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,PARNT_ID,POST_PRCSR,PREV_DOC_TYP_VER_NBR,RTE_VER_NBR,SVC_NMSPC,VER_NBR)
  VALUES (1,'NONE',0,'${workflow.url}/EDocLite','eDoc.Example1 Request DocumentType',2320,'eDoc.Example1Doctype',2,'2200','eDoc.Example1 Request DocumentType',2217,'org.kuali.rice.kew.edl.EDocLitePostProcessor',2215,'2','FooBar',2);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,NOTIFY_ADDR,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'http://localhost:8080/tvl-dev/WorkflowTripDochandler.do','Travel Trip Reimbursement Document',2360,'TravelTripReimbursement',0,'1','Travel Trip Reimbursement','travelbl@indiana.edu','edu.iu.uis.tvl.workflow.routing.TravelPostProcessor','2',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_PLCY,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,PARNT_ID,POST_PRCSR,PREV_DOC_TYP_VER_NBR,RTE_VER_NBR,SVC_NMSPC,VER_NBR)
  VALUES (1,'NONE',1,'${workflow.url}/EDocLite','eDoc.Example1 Request DocumentType',2440,'eDoc.Example1Doctype',3,'2200','eDoc.Example1 Request DocumentType',2217,'org.kuali.rice.kew.edl.EDocLitePostProcessor',2320,'2','FooBar',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,CUR_IND,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,LBL,POST_PRCSR,RTE_VER_NBR,VER_NBR)
  VALUES (1,1,'KualiDocument',2680,'KualiDocument',0,'KualiDocument','none','2',2);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,CUR_IND,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,LBL,PARNT_ID,RTE_VER_NBR,VER_NBR)
  VALUES (1,1,'Parent Document Type for all Rice Documents',2681,'RiceDocument',0,'Rice Document',2680,'2',3);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,PARNT_ID,POST_PRCSR,PREV_DOC_TYP_VER_NBR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'docHandler is now mandatory...','Workflow Maintenance Document',2682,'EDENSERVICE-DOCS',1,'1','Workflow Maintenance Document',2681,'none',2010,'2',1);
INSERT INTO KREW_DOC_TYP_T (ACTV_IND,BLNKT_APPR_GRP_ID,CUR_IND,DOC_HDLR_URL,DOC_TYP_DESC,DOC_TYP_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,GRP_ID,LBL,PARNT_ID,POST_PRCSR,PREV_DOC_TYP_VER_NBR,RTE_VER_NBR,VER_NBR)
  VALUES (1,'1',1,'${application.url}/travelDocument2.do?methodToCall=docHandler','Create a New Travel Request',2683,'TravelRequest',1,'1','Travel Request',2681,'org.kuali.rice.kns.workflow.postprocessor.KualiPostProcessor',2028,'2',1);
