CREATE SEQUENCE KCB_MESSAGES_SEQ INCREMENT BY 1 START WITH 1000
/
CREATE SEQUENCE KCB_MSG_DELIVS_SEQ INCREMENT BY 1 START WITH 1000
/
CREATE TABLE KCB_MESSAGES
(
    ID                  NUMBER(8) NOT NULL,
    DELIVERY_TYPE       VARCHAR2(500) NOT NULL,
    CREATED_DATETIME    TIMESTAMP NOT NULL,
    TITLE               VARCHAR2(255),
    CHANNEL             VARCHAR2(300) NULL,
    PRODUCER            VARCHAR2(300) NULL,
    CONTENT             CLOB NOT NULL,
    CONTENT_TYPE        VARCHAR2(128) NOT NULL,
    USER_RECIPIENT_ID   VARCHAR2(300) NOT NULL,
    DB_LOCK_VER_NBR     INTEGER DEFAULT 0 NOT NULL,

    CONSTRAINT KCB_MESSAGES_PK PRIMARY KEY (ID)
)
/
CREATE TABLE KCB_MSG_DELIVS
(
    ID                      NUMBER(8) NOT NULL,
    MESSAGE_ID              NUMBER(8) NOT NULL,
    DELIVERER_TYPE_NAME     VARCHAR2(500) NOT NULL,
    DELIVERER_SYSTEM_ID     VARCHAR2(300),
    DELIVERY_STATUS         VARCHAR2(15) NOT NULL, 
    DB_LOCK_VER_NBR         INTEGER DEFAULT 0 NOT NULL,

    CONSTRAINT KCB_MSG_DELIVS_PK PRIMARY KEY (ID)
)
/
ALTER TABLE KCB_MSG_DELIVS
ADD CONSTRAINT KCB_MSG_DELIVS_UK1 UNIQUE
(
MESSAGE_ID,
DELIVERER_TYPE_NAME
)
 ENABLE
/

ALTER TABLE KCB_MSG_DELIVS
ADD CONSTRAINT KCB_MSG_DELIVS_FK1 FOREIGN KEY
(
MESSAGE_ID
)
REFERENCES KCB_MESSAGES
(
ID
) ENABLE
/