ALTER TABLE NOTIFICATION_CONTENT_TYPES ADD (
   VERSION NUMBER(8) DEFAULT '0' NOT NULL,
   CUR_IND CHAR DEFAULT 'T' NOT NULL) /

UPDATE NOTIFICATION_CONTENT_TYPES SET VERSION = 0 WHERE VERSION = NULL /
UPDATE NOTIFICATION_CONTENT_TYPES SET CUR_IND = 'T' WHERE CUR_IND = NULL /

ALTER TABLE NOTIFICATION_CONTENT_TYPES
DROP CONSTRAINT NOTIFICATION_CONTENT_TYPE_UK1 /

ALTER TABLE NOTIFICATION_CONTENT_TYPES
ADD CONSTRAINT NOTIFICATION_CONTENT_TYPE_UK1 UNIQUE
(
NAME, VERSION
)
 ENABLE
/

drop table RECIPIENT_PREFERENCES cascade constraints /

DROP SEQUENCE RECIPIENT_PREFERENCES_SEQ /

drop table USER_DELIVERER_CONFIG cascade constraints /

DROP SEQUENCE USER_DELIVERER_CONFIG_SEQ /

alter table NOTIFICATION_MSG_DELIVS DROP CONSTRAINT NOTIF_MSG_DELIVS_UK1 /

ALTER TABLE NOTIFICATION_MSG_DELIVS
ADD CONSTRAINT NOTIF_MSG_DELIVS_UK1 UNIQUE
(
NOTIFICATION_ID,
USER_RECIPIENT_ID
)
 ENABLE
/

alter table NOTIFICATION_MSG_DELIVS drop column MESSAGE_DELIVERY_TYPE_NAME /


CREATE INDEX KEN_NOTIFICATIONSI1 ON NOTIFICATIONS (CONTENT_TYPE_ID)
/

CREATE INDEX KEN_NOTIFICATIONSI2 ON NOTIFICATIONS (PRIORITY_ID)
/

CREATE INDEX KEN_NOTIFICATIONSI3 ON NOTIFICATIONS (PRODUCER_ID)
/
CREATE INDEX KEN_CHANNEL_PRODUCERSI1 ON NOTIFICATION_CHANNEL_PRODUCERS (CHANNEL_ID)
/

CREATE INDEX KEN_CHANNEL_PRODUCERSI2 ON NOTIFICATION_CHANNEL_PRODUCERS (PRODUCER_ID)
/
CREATE INDEX KEN_MSG_DELIVSI1 ON NOTIFICATION_MSG_DELIVS (NOTIFICATION_ID)
/
CREATE INDEX KEN_RECIPIENTSI1 ON NOTIFICATION_RECIPIENTS (NOTIFICATION_ID)
/
CREATE INDEX KEN_RECIPIENTS_LISTSI1 ON NOTIFICATION_RECIPIENTS_LISTS (CHANNEL_ID)
/
CREATE INDEX KEN_REVIEWERSI1 ON NOTIFICATION_REVIEWERS (CHANNEL_ID)
/
CREATE INDEX KEN_SENDERSI1 ON NOTIFICATION_SENDERS (NOTIFICATION_ID)
/
CREATE INDEX KEN_USER_CHAN_SUBSI1 ON USER_CHANNEL_SUBSCRIPTIONS (CHANNEL_ID)
/