------------------ KIM UPGRADE -----------------------
-- KIM TABLE DROPS --
DROP TABLE KIM_PERSON_QUALIFIED_ROLE_T CASCADE CONSTRAINTS
/
DROP TABLE KIM_GROUP_QUALIFIED_ROLE_T CASCADE CONSTRAINTS
/
DROP TABLE KIM_GROUPS_PERSONS_T CASCADE CONSTRAINTS
/
DROP TABLE KIM_ROLES_PERSONS_T CASCADE CONSTRAINTS
/
DROP TABLE KIM_PERSON_ATTRIBUTES_T CASCADE CONSTRAINTS
/
DROP TABLE KIM_PERSONS_T CASCADE CONSTRAINTS
/

-- KIM SEQUENCES DROP --
DROP SEQUENCE SEQ_KIM_PERSON_ATTRIBUTES_ID
/
DROP SEQUENCE SEQ_KIM_PERSONS_ID
/
DROP SEQUENCE SEQ_KIM_PRSN_QUAL_GRP_ID
/
DROP SEQUENCE SEQ_KIM_PRSN_QUAL_RL_ID
/

-- KIM SEQUENCES CREATE --
CREATE SEQUENCE SEQ_KIM_ENTITY_TYPES_ID INCREMENT BY 1 START WITH 1000
/
CREATE SEQUENCE SEQ_KIM_ENTITYS_ID INCREMENT BY 1 START WITH 1000
/
CREATE SEQUENCE SEQ_KIM_ENTITY_ATTRIBS_ID INCREMENT BY 1 START WITH 1000
/
CREATE SEQUENCE SEQ_KIM_PRINCIPALS_ID INCREMENT BY 1 START WITH 1000
/
CREATE SEQUENCE SEQ_KIM_PRNCPL_QLFD_ROLES_ID INCREMENT BY 1 START WITH 1000
/
CREATE SEQUENCE SEQ_KIM_GROUP_QLFD_ROLES_ID INCREMENT BY 1 START WITH 1000
/

-- KIM_PRINCIPALS --
CREATE TABLE KIM_PRINCIPALS_T (
        ID NUMBER(8) NOT NULL,
        NAME VARCHAR2(500) NOT NULL,
        ENTITY_ID NUMBER(8) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL,
        CONSTRAINT KIM_PRINCIPALS_PK PRIMARY KEY (ID)
)
/

ALTER TABLE KIM_PRINCIPALS_T
ADD CONSTRAINT KIM_PRINCIPALS_UK1 UNIQUE
(
NAME
) ENABLE
/

ALTER TABLE KIM_PRINCIPALS_T
ADD CONSTRAINT KIM_PRINCIPALS_UK2 UNIQUE
(
ID,
ENTITY_ID
) ENABLE
/

CREATE INDEX KIM_PRINCIPALS_TI1 ON KIM_PRINCIPALS_T (ENTITY_ID)
/

-- KIM_GROUPS_PRINCIPALS --
CREATE TABLE KIM_GROUPS_PRINCIPALS_T (
        GROUP_ID NUMBER(8) NOT NULL,
        PRINCIPAL_ID NUMBER(8) NOT NULL,
        OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL,
        CONSTRAINT KIM_GROUPS_PRINCIPALS_PK PRIMARY KEY (GROUP_ID, PRINCIPAL_ID)
)
/

ALTER TABLE KIM_GROUPS_PRINCIPALS_T
ADD CONSTRAINT KIM_GROUPS_PRINCIPALS_FK1 FOREIGN KEY
(
GROUP_ID
)
REFERENCES KIM_GROUPS_T
(
ID
) ENABLE
/

ALTER TABLE KIM_GROUPS_PRINCIPALS_T
ADD CONSTRAINT KIM_GROUPS_PRINCIPALS_FK2 FOREIGN KEY
(
PRINCIPAL_ID
)
REFERENCES KIM_PRINCIPALS_T
(
ID
) ENABLE
/

-- KIM_ENTITY_TYPES --
CREATE TABLE KIM_ENTITY_TYPES_T (
        ID NUMBER(8) NOT NULL,
        NAME VARCHAR2(500) NOT NULL,
        DESCRIPTION VARCHAR2(4000),
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_ENTITY_TYPES_PK PRIMARY KEY (ID)
)
/

ALTER TABLE KIM_ENTITY_TYPES_T 
ADD CONSTRAINT KIM_ENTITY_TYPES_UK1 UNIQUE
(
NAME
) ENABLE
/

-- KIM_ENTITYS --
CREATE TABLE KIM_ENTITYS_T (
        ID NUMBER(8) NOT NULL,
        ENTITY_TYPE_ID NUMBER(8) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_ENTITYS_PK PRIMARY KEY (ID)
)
/

ALTER TABLE KIM_ENTITYS_T
ADD CONSTRAINT KIM_ENTITYS_FK1 FOREIGN KEY
(
ENTITY_TYPE_ID
)
REFERENCES KIM_ENTITY_TYPES_T
(
ID
) ENABLE
/

CREATE INDEX KIM_ENTITYS_TI1 ON KIM_ENTITYS_T (ENTITY_TYPE_ID)
/

-- KIM_ENTITY_ATTRIBUTES --
CREATE TABLE KIM_ENTITY_ATTRIBUTES_T (
        ID NUMBER(8) NOT NULL,
        ENTITY_ID NUMBER(8) NOT NULL,
        SPONSOR_NAMESPACE_ID NUMBER(8) NOT NULL,
        ATTRIBUTE_NAME VARCHAR2(500) NOT NULL,
        ATTRIBUTE_TYPE_ID NUMBER(8) NOT NULL,
        ATTRIBUTE_VALUES VARCHAR2(4000),
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_ENTITY_ATTRIBUTES_PK PRIMARY KEY (ID)
)
/

ALTER TABLE KIM_ENTITY_ATTRIBUTES_T 
ADD CONSTRAINT KIM_ENTITY_ATTRIBS_UK1 UNIQUE
(
ENTITY_ID,
SPONSOR_NAMESPACE_ID,
ATTRIBUTE_NAME
) ENABLE
/

ALTER TABLE KIM_ENTITY_ATTRIBUTES_T
ADD CONSTRAINT KIM_ENTITY_ATTRIBS_FK1 FOREIGN KEY
(
ENTITY_ID
)
REFERENCES KIM_ENTITYS_T
(
ID
) ENABLE
/

ALTER TABLE KIM_ENTITY_ATTRIBUTES_T
ADD CONSTRAINT KIM_ENTITY_ATTRIBS_FK2 FOREIGN KEY
(
SPONSOR_NAMESPACE_ID
)
REFERENCES KIM_NAMESPACES_T
(
ID
) ENABLE
/

CREATE INDEX KIM_ENTITY_ATTRIBUTES_TI1 ON KIM_ENTITY_ATTRIBUTES_T (ENTITY_ID)
/
CREATE INDEX KIM_ENTITY_ATTRIBUTES_TI2 ON KIM_ENTITY_ATTRIBUTES_T (ENTITY_ID, SPONSOR_NAMESPACE_ID)
/

-- KIM_PRNCPL_QLFD_ROLES --
CREATE TABLE KIM_PRNCPL_QLFD_ROLES_T (
		ID NUMBER(8) NOT NULL,
        PRINCIPAL_ID NUMBER(8) NOT NULL,
		ROLE_ID NUMBER(8) NOT NULL,
		ATTRIBUTE_NAME VARCHAR(255) NOT NULL,
		ATTRIBUTE_VALUE VARCHAR(255) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_PRNCPL_QLFD_ROLES_PK PRIMARY KEY (ID)
)
/

ALTER TABLE KIM_PRNCPL_QLFD_ROLES_T 
ADD CONSTRAINT KIM_PRNCPL_QLFD_ROLES_UK1 UNIQUE
(
PRINCIPAL_ID,
ROLE_ID,
ATTRIBUTE_NAME
) ENABLE
/

ALTER TABLE KIM_PRNCPL_QLFD_ROLES_T
ADD CONSTRAINT KIM_PRNCPL_QLFD_ROLES_FK1 FOREIGN KEY
(
PRINCIPAL_ID
)
REFERENCES KIM_PRINCIPALS_T
(
ID
) ENABLE
/

ALTER TABLE KIM_PRNCPL_QLFD_ROLES_T
ADD CONSTRAINT KIM_PRNCPL_QLFD_ROLES_FK2 FOREIGN KEY
(
ROLE_ID
)
REFERENCES KIM_ROLES_T
(
ID
) ENABLE
/

CREATE INDEX KIM_PRNCPL_QLFD_ROLES_TI1 ON KIM_PRNCPL_QLFD_ROLES_T (PRINCIPAL_ID)
/
CREATE INDEX KIM_PRNCPL_QLFD_ROLES_TI2 ON KIM_PRNCPL_QLFD_ROLES_T (ROLE_ID)
/
CREATE INDEX KIM_PRNCPL_QLFD_ROLES_TI3 ON KIM_PRNCPL_QLFD_ROLES_T (PRINCIPAL_ID, ROLE_ID)
/

-- KIM_GROUP_QLFD_ROLES --
CREATE TABLE KIM_GROUP_QLFD_ROLES_T (
		ID NUMBER(8) NOT NULL,
        GROUP_ID NUMBER(8) NOT NULL,
		ROLE_ID NUMBER(8) NOT NULL,
		ATTRIBUTE_NAME VARCHAR(255) NOT NULL,
		ATTRIBUTE_VALUE VARCHAR(255) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_GROUP_QLFD_ROLES_PK PRIMARY KEY (ID)
)
/

ALTER TABLE KIM_GROUP_QLFD_ROLES_T 
ADD CONSTRAINT KIM_GROUP_QLFD_ROLES_UK1 UNIQUE
(
GROUP_ID,
ROLE_ID,
ATTRIBUTE_NAME
) ENABLE
/

ALTER TABLE KIM_GROUP_QLFD_ROLES_T
ADD CONSTRAINT KIM_GROUP_QLFD_ROLES_FK1 FOREIGN KEY
(
GROUP_ID
)
REFERENCES KIM_GROUPS_T
(
ID
) ENABLE
/

ALTER TABLE KIM_GROUP_QLFD_ROLES_T
ADD CONSTRAINT KIM_GROUP_QLFD_ROLES_FK2 FOREIGN KEY
(
ROLE_ID
)
REFERENCES KIM_ROLES_T
(
ID
) ENABLE
/

CREATE INDEX KIM_GROUP_QLFD_ROLES_TI1 ON KIM_GROUP_QLFD_ROLES_T (GROUP_ID)
/
CREATE INDEX KIM_GROUP_QLFD_ROLES_TI2 ON KIM_GROUP_QLFD_ROLES_T (ROLE_ID)
/
CREATE INDEX KIM_GROUP_QLFD_ROLES_TI3 ON KIM_GROUP_QLFD_ROLES_T (GROUP_ID, ROLE_ID)
/

-- KIM_ROLES_PRINCIPALS --
CREATE TABLE KIM_ROLES_PRINCIPALS_T (
        ROLE_ID NUMBER(8) NOT NULL,
        PRINCIPAL_ID NUMBER(8) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_ROLES_PRINCIPALS_PK PRIMARY KEY (ROLE_ID, PRINCIPAL_ID)
)
/

ALTER TABLE KIM_ROLES_PRINCIPALS_T
ADD CONSTRAINT KIM_ROLES_PRINCIPALS_FK1 FOREIGN KEY
(
ROLE_ID
)
REFERENCES KIM_ROLES_T
(
ID
) ENABLE
/

ALTER TABLE KIM_ROLES_PRINCIPALS_T
ADD CONSTRAINT KIM_ROLES_PRINCIPALS_FK2 FOREIGN KEY
(
PRINCIPAL_ID
)
REFERENCES KIM_PRINCIPALS_T
(
ID
) ENABLE
/

-- KIM BOOTSTRAP DATA --
INSERT INTO KIM_ENTITY_TYPES_T values (1, 'Person', 'This entity represents a person in the system.', SYS_GUID(), 1)
/
INSERT INTO FP_DOC_TYPE_T values ('KPMD', SYS_GUID(), 1, 'KR', 'PRINCIPAL', 'N', 'Y', 'N', 0, 'N', 'N')
/
INSERT INTO FP_DOC_TYPE_T values ('KGMD', SYS_GUID(), 1, 'KR', 'GROUP', 'N', 'Y', 'N', 0, 'N', 'N')
/
INSERT INTO FP_DOC_TYPE_T values ('KRMD', SYS_GUID(), 1, 'KR', 'ROLE', 'N', 'Y', 'N', 0, 'N', 'N')
/
INSERT INTO FP_DOC_TYPE_T values ('KGAM', SYS_GUID(), 1, 'KR', 'GROUP ATTRIBUTE', 'N', 'Y', 'N', 0, 'N', 'N')
/

COMMIT
/