
ALTER TABLE KIM_GROUPS_PERSONS_T DROP CONSTRAINT KIM_GROUPS_PERSONS_FK1;
ALTER TABLE KIM_GROUPS_PERSONS_T DROP CONSTRAINT KIM_GROUPS_PERSONS_FK2;
DROP TABLE KIM_GROUPS_PERSONS_T;

CREATE TABLE KIM_PRINCIPALS_T (
        ID NUMBER(8) NOT NULL,
        NAME VARCHAR2(500) NOT NULL,
        OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL,
        CONSTRAINT KIM_PRINCIPALS_PK PRIMARY KEY (ID)
);

ALTER TABLE KIM_PRINCIPALS_T
ADD CONSTRAINT KIM_PRINCIPALS_UK1 UNIQUE
(
NAME
) ENABLE;
CREATE SEQUENCE SEQ_KIM_PRINCIPALS_ID INCREMENT BY 1 START WITH 1000;
CREATE INDEX KIM_PRINCIPALS_TI1 ON KIM_PRINCIPALS_T (NAME);


CREATE TABLE KIM_GROUPS_PRINCIPALS_T (
        GROUP_ID NUMBER(8) NOT NULL,
        PRINCIPAL_ID NUMBER(8) NOT NULL,
        OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL,
        CONSTRAINT KIM_GROUPS_PRINCIPALS_PK PRIMARY KEY (GROUP_ID, PRINCIPAL_ID)
);

ALTER TABLE KIM_GROUPS_PRINCIPALS_T
ADD CONSTRAINT KIM_GROUPS_PRINCIPALS_FK1 FOREIGN KEY
(
GROUP_ID
)
REFERENCES KIM_GROUPS_T
(
ID
) ENABLE;

ALTER TABLE KIM_GROUPS_PRINCIPALS_T
ADD CONSTRAINT KIM_GROUPS_PRINCIPALS_FK2 FOREIGN KEY
(
PRINCIPAL_ID
)
REFERENCES KIM_PRINCIPALS_T
(
ID
) ENABLE;

COMMIT;
