--
-- Copyright 2005-2014 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-----------------------------------------------------------------------------
-- KRCR_CMPNT_SET_T
-----------------------------------------------------------------------------
INSERT INTO KRCR_CMPNT_SET_T (CHKSM,CMPNT_SET_ID,LAST_UPDT_TS,VER_NBR)
  VALUES ('YF7O4JRiqftiUrQJzhfwpEPP3Oc=','DD:RICE',TO_DATE( '20111030164958', 'YYYYMMDDHH24MISS' ),1)
/
INSERT INTO KRCR_CMPNT_SET_T (CHKSM,CMPNT_SET_ID,LAST_UPDT_TS,VER_NBR)
  VALUES ('qTdEjWgfA5vemMSMR8x8vwRzNts=','DD:TRAVEL',TO_DATE( '20121125192538', 'YYYYMMDDHH24MISS' ),1)
/

-----------------------------------------------------------------------------
-- KRCR_DRVD_CMPNT_T
-----------------------------------------------------------------------------
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('AdHocRoutePerson','DD:TRAVEL','Ad Hoc Route Person','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('AdHocRouteWorkgroup','DD:TRAVEL','Ad Hoc Route Workgroup','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('Attachment','DD:TRAVEL','Attachment','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('AttachmentSample','DD:TRAVEL','Attachment Sample','KR-SAP')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('AttributeReferenceDummy','DD:TRAVEL','Attribute Reference Dummy','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('AttributeReferenceElements','DD:TRAVEL','Attribute Reference Elements','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('BookOrder','DD:TRAVEL','BookOrder','KR-SAP')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('BusinessObjectAttributeEntry','DD:TRAVEL','Business Object Attribute Entry','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('CampusBo','DD:TRAVEL','Campus','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('CampusTypeBo','DD:TRAVEL','Campus Type','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('ComponentBo','DD:TRAVEL','Component','KR-CR')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('ComponentBo','DD:RICE','Component','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('ContextBo','DD:TRAVEL','Context','krms')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('CountryBo','DD:TRAVEL','Country','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('CountyBo','DD:TRAVEL','County','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('DelegateTypeBo','DD:TRAVEL','Delegations','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('DocumentHeader','DD:TRAVEL','Document Header','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('DocumentRouteHeaderValue','DD:TRAVEL','Document','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('DocumentSearchCriteriaBo','DD:TRAVEL','Document','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('DocumentType','DD:TRAVEL','Document Type','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('EDocLiteAssociation','DD:TRAVEL','eDoc Lite Association','KR-EDL')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('EDocLiteDefinition','DD:TRAVEL','eDoc Lite Definition','KR-EDL')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('EntityAddressTypeBo','DD:TRAVEL','Address Type','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('EntityAffiliationTypeBo','DD:TRAVEL','Affiliation Type','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('EntityCitizenshipStatusBo','DD:TRAVEL','Citizenship Status','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('EntityEmailTypeBo','DD:TRAVEL','Email Type','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('EntityEmploymentStatusBo','DD:TRAVEL','Employee Status','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('EntityEmploymentTypeBo','DD:TRAVEL','Employee Type','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('EntityExternalIdentifierTypeBo','DD:TRAVEL','External Identifier Type','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('EntityNameTypeBo','DD:TRAVEL','Entity Name Type','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('EntityPhoneTypeBo','DD:TRAVEL','Phone Type','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('EntityTypeBo','DD:TRAVEL','Entity Type','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('FiscalOfficer','DD:TRAVEL','Fiscal Officer','KR-SAP')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('FiscalOfficer','DD:RICE','Fiscal Officer','tv')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('GenericPermissionBo','DD:TRAVEL','Permission','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('GroupBo','DD:TRAVEL','Group','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('GroupDocumentMember','DD:TRAVEL','Names','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('GroupDocumentQualifier','DD:TRAVEL','Group Qualifier','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('GroupRuleResponsibility','DD:TRAVEL','Group Rule Responsibility','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('IdentityManagementGroup','DD:TRAVEL','Group','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('IdentityManagementPerson','DD:TRAVEL','Person','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('IdentityManagementRole','DD:TRAVEL','Role','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('KimAttributeBo','DD:TRAVEL','Kim Attribute Definition','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('KimAttributeDataBo','DD:TRAVEL','Attribute Data','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('KimAttributes','DD:TRAVEL','KIM Attributes','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('KimDocumentRoleMember','DD:TRAVEL','Names','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('KimDocumentRoleQualifier','DD:TRAVEL','Role Qualifier','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('KimDocumentRoleResponsibilityAction','DD:TRAVEL','Role Responsibility Action','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('KimTypeBo','DD:TRAVEL','Kim Types','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('MultiAttachmentSample','DD:TRAVEL','Attachment Sample','KR-SAP')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('NamespaceBo','DD:TRAVEL','Namespace','KR-CR')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('NamespaceBo','DD:RICE','Namespace','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('Note','DD:TRAVEL','Note','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('NoteType','DD:TRAVEL','Note Type','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('ParameterBo','DD:TRAVEL','Parameter','KR-CR')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('ParameterBo','DD:RICE','Parameter','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('ParameterTypeBo','DD:TRAVEL','Parameter Type','KR-CR')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('ParameterTypeBo','DD:RICE','Parameter Type','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PeopleFlowBo','DD:TRAVEL','People Flow','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PeopleFlowDelegateBo','DD:TRAVEL','People Flow Delegate','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PeopleFlowMemberBo','DD:TRAVEL','People Flow Member','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PermissionAttributeBo','DD:TRAVEL','Permission Attribute Data','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PermissionBo','DD:TRAVEL','Permission','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PermissionTemplateBo','DD:TRAVEL','Permission Templates','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PersonDocumentAddress','DD:TRAVEL','Names','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PersonDocumentAffiliation','DD:TRAVEL','Entity Affiliation','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PersonDocumentCitizenship','DD:TRAVEL','Entity Citizenship','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PersonDocumentEmail','DD:TRAVEL','Names','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PersonDocumentEmploymentInfo','DD:TRAVEL','Entity Employment','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PersonDocumentGroup','DD:TRAVEL','Names','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PersonDocumentName','DD:TRAVEL','Names','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PersonDocumentPhone','DD:TRAVEL','Names','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PersonDocumentPrivacy','DD:TRAVEL','Names','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PersonDocumentRole','DD:TRAVEL','Names','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PersonImpl','DD:TRAVEL','Person','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PersonRuleResponsibility','DD:TRAVEL','Person Rule Responsibility','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PessimisticLock','DD:TRAVEL','Pessimistic Lock','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('PostalCodeBo','DD:TRAVEL','Postal Code','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('ResponsibilityAttributeBo','DD:TRAVEL','Responsibility Attribute Data','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('ResponsibilityBo','DD:TRAVEL','Responsibility','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('ResponsibilityTemplateBo','DD:TRAVEL','Responsibility Templates','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('ReviewResponsibilityBo','DD:TRAVEL','Review Responsibility','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('RoleBo','DD:TRAVEL','Names','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('RoleDocumentDelegationMember','DD:TRAVEL','Delegation Members','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('RoleDocumentDelegationMemberQualifier','DD:TRAVEL','Role Qualifier','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('RoleMemberBo','DD:TRAVEL','Names','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('RoleRuleResponsibility','DD:TRAVEL','Role Rule Responsibility','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('Rule','DD:TRAVEL','Rule Maintenance Document Type Document','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('RuleAttribute','DD:TRAVEL','Rule Attribute','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('RuleBaseValues','DD:TRAVEL','Rule','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('RuleDelegationBo','DD:TRAVEL','Delegation Rule','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('RuleTemplateAttributeBo','DD:TRAVEL','Rule Template Attribute','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('RuleTemplateBo','DD:TRAVEL','Rule Template','KR-WKFLW')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('StateBo','DD:TRAVEL','State','KR-NS')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('StyleBo','DD:RICE','Stylesheet','KR-CORE')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('StyleBo','DD:TRAVEL','Stylesheet','KR-CR')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('Travel2','DD:TRAVEL','Travel Request','KR-SAP')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('TravelAccount','DD:TRAVEL','Travel Account','KR-SAP')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('TravelAccount','DD:RICE','Travel Account','tv')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('TravelAccountExtension','DD:TRAVEL','Travel Account Extension','KR-SAP')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('TravelAccountExtension','DD:RICE','Travel Account Extension','tv')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('TravelAccountType','DD:TRAVEL','Travel Account Type','KR-SAP')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('TravelAccountType','DD:RICE','Travel Account Type','tv')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('TravelAccountUseRate','DD:TRAVEL','Travel Account Use Rate','KR-SAP')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('TravelAccountUseRate','DD:RICE','Travel Account Use Rate','tv')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('TravelAuthorization','DD:TRAVEL','TravelAuthorization','KR-SAP')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('UberPermissionBo','DD:TRAVEL','Permission','KR-IDM')
/
INSERT INTO KRCR_DRVD_CMPNT_T (CMPNT_CD,CMPNT_SET_ID,NM,NMSPC_CD)
  VALUES ('UberResponsibilityBo','DD:TRAVEL','Responsibility','KR-IDM')
/
