CREATE TABLE EN_SERVICE_DEF_DUEX_T (
	SERVICE_DEF_ID			   	   NUMBER(14) NOT NULL,
	SERVICE_NM				   	   VARCHAR2(255) NOT NULL,
    SERVICE_URL	            	   VARCHAR2(500) NOT NULL,
	SERVER_IP					   VARCHAR2(40) NOT NULL,
	MESSAGE_ENTITY_NM 		  	   VARCHAR2(10) NOT NULL,
	SERVICE_ALIVE				   NUMBER(1) NOT NULL,
	SERVICE_DEFINITION 		       CLOB NOT NULL,
	DB_LOCK_VER_NBR	               NUMBER(8) DEFAULT 0,
	CONSTRAINT EN_SERVICE_DEF_DUEX_T_PK PRIMARY KEY (SERVICE_DEF_ID)
)

/

CREATE INDEX EN_SERVICE_DEF_DUEX_TI1 ON EN_SERVICE_DEF_DUEX_T (SERVER_IP, MESSAGE_ENTITY_NM)

/

