CREATE TABLE KCB_RECIP_PREFS
(
    ID                  NUMBER(8) NOT NULL,
    RECIPIENT_ID        VARCHAR2(300) NOT NULL,
    PROPERTY            VARCHAR2(300) NOT NULL,
    VALUE               VARCHAR2(1000) NOT NULL,
    DB_LOCK_VER_NBR     INTEGER DEFAULT 0 NOT NULL,

    CONSTRAINT KCB_RECIP_PREFS_PK PRIMARY KEY (ID)
)
/