-- Disable constraints for the duration of this script
DECLARE 
   CURSOR constraint_cursor IS 
      SELECT table_name, constraint_name 
         FROM user_constraints 
         WHERE constraint_type = 'R'
           AND status = 'ENABLED';
BEGIN 
   FOR r IN constraint_cursor LOOP
      execute immediate 'ALTER TABLE '||r.table_name||' DISABLE CONSTRAINT '||r.constraint_name; 
   END LOOP; 
END;
/

DROP TABLE KREN_CHNL_PRODCR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_CHNL_SUBSCRP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_CHNL_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_CNTNT_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_MSG_DELIV_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_MSG_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_NTFCTN_MSG_DELIV_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_NTFCTN_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_PRIO_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_PRODCR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_RECIP_DELIV_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_RECIP_LIST_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_RECIP_PREFS_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_RECIP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_RVWER_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREN_SNDR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_ACTN_ITM_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_ACTN_RQST_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_ACTN_TKN_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_ATT_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_DLGN_RSP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_DOC_HDR_CNTNT_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_DOC_HDR_EXT_DT_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_DOC_HDR_EXT_FLT_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_DOC_HDR_EXT_LONG_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_DOC_HDR_EXT_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_DOC_HDR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_DOC_NTE_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_DOC_TYP_ATTR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_DOC_TYP_PLCY_RELN_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_DOC_TYP_PROC_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_DOC_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_EDL_ASSCTN_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ROLE_PERM_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ROLE_RSP_ACTN_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ROLE_RSP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ROLE_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_RSP_ATTR_DATA_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_RSP_RQRD_ATTR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_RSP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_RSP_TMPL_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_TYP_ATTR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRNS_CAMPUS_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRNS_CMP_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRNS_NMSPC_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRNS_PARM_DTL_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRNS_PARM_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRNS_PARM_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRSB_SVC_DEF_T CASCADE CONSTRAINTS
 /
 DROP TABLE KR_COUNTRY_T CASCADE CONSTRAINTS
 /
 DROP TABLE KR_COUNTY_T CASCADE CONSTRAINTS
 /
 DROP TABLE KR_POSTAL_CODE_T CASCADE CONSTRAINTS
 /
 DROP TABLE KR_STATE_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENTITY_CTZNSHP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENTITY_EMAIL_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENTITY_EMP_INFO_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENTITY_ENT_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENTITY_EXT_ID_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENTITY_NM_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENTITY_PHONE_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENTITY_PRIV_PREF_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENTITY_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENT_NM_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENT_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_EXT_ID_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_GRP_ATTR_DATA_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_GRP_DOCUMENT_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_GRP_MBR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_GRP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PERM_ATTR_DATA_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PERM_RQRD_ATTR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PERM_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PERM_TMPL_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PERSON_DOCUMENT_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PHONE_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_ADDR_MT CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_AFLTN_MT CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_CTZNSHP_MT CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_DLGN_MBR_ATTR_DATA_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_DLGN_MBR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_DLGN_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_EMAIL_MT CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_EMP_INFO_MT CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_GRP_ATTR_DATA_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_GRP_MBR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_GRP_PRNCPL_MT CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_NM_MT CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_PHONE_MT CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_PRIV_PREF_MT CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_ROLE_MBR_ATTR_DATA_MT CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_ROLE_MBR_MT CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_ROLE_MT CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_ROLE_PERM_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_ROLE_RSP_ACTN_MT CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PND_ROLE_RSP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_PRNCPL_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ROLE_DOCUMENT_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ROLE_MBR_ATTR_DATA_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ROLE_MBR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_EDL_DEF_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_EDL_DMP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_EDL_FLD_DMP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_HLP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_INIT_RTE_NODE_INSTN_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_OUT_BOX_ITM_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RMV_RPLC_DOC_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RMV_RPLC_GRP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RMV_RPLC_RULE_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RTE_BRCH_PROTO_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RTE_BRCH_ST_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RTE_BRCH_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RTE_NODE_CFG_PARM_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RTE_NODE_INSTN_LNK_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RTE_NODE_INSTN_ST_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RTE_NODE_INSTN_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RTE_NODE_LNK_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RTE_NODE_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RULE_ATTR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RULE_EXPR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RULE_EXT_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RULE_EXT_VAL_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RULE_RSP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RULE_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RULE_TMPL_ATTR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RULE_TMPL_OPTN_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_RULE_TMPL_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_STYLE_T CASCADE CONSTRAINTS
 /
 DROP TABLE KREW_USR_OPTN_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ADDR_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_AFLTN_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ATTR_DEFN_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_CTZNSHP_STAT_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_DLGN_MBR_ATTR_DATA_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_DLGN_MBR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_DLGN_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_EMAIL_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_EMP_STAT_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_EMP_TYP_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENTITY_ADDR_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENTITY_AFLTN_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENTITY_BIO_T CASCADE CONSTRAINTS
 /
 DROP TABLE KRIM_ENTITY_CACHE_T CASCADE CONSTRAINTS
 /

/* Re-enable constraints */
DECLARE 
   CURSOR constraint_cursor IS 
      SELECT table_name, constraint_name 
         FROM user_constraints 
         WHERE constraint_type = 'R'
           AND status <> 'ENABLED';
BEGIN 
   FOR r IN constraint_cursor LOOP
      execute immediate 'ALTER TABLE '||r.table_name||' ENABLE CONSTRAINT '||r.constraint_name; 
   END LOOP; 
END;
/
