CREATE TABLE GROUPS_PERSONS_T (
        GROUP_ID NUMBER(8) NOT NULL,
        PERSON_ID NUMBER(8) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT GROUPS_PERSONS_PK PRIMARY KEY (GROUP_ID, PERSON_ID)
)
/