CREATE TABLE KIM_PERSON_ATTRIBUTES_T (
        ID NUMBER(8) NOT NULL,
        PERSON_ID NUMBER(8) NOT NULL,
        SPONSOR_NAMESPACE_ID NUMBER(8) NOT NULL,
        ATTRIBUTE_NAME VARCHAR2(500) NOT NULL,
        ATTRIBUTE_TYPE_ID NUMBER(8) NOT NULL,
        ATTRIBUTE_VALUES VARCHAR2(4000),
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_PERSON_ATTRIBUTES_PK PRIMARY KEY (ID)
)
/