CREATE TABLE KIM_PERSON_QUALIFIED_ROLE_T (
		ID NUMBER(8) NOT NULL,
        PERSON_ID NUMBER(8) NOT NULL,
		ROLE_ID NUMBER(8) NOT NULL,
		ROLE_ATTRIBUTE_ID NUMBER(8) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_PERSON_QUALIFIED_ROLE_PK PRIMARY KEY (PERSON_ID, ROLE_ID, ROLE_ATTRIBUTE_ID)
)
/