CREATE TABLE KIM_PERSON_QUALIFIED_GROUP_T (
		ID NUMBER(8) NOT NULL,
        PERSON_ID NUMBER(8) NOT NULL,
		GROUP_ID NUMBER(8) NOT NULL,
		GROUP_ATTRIBUTE_ID NUMBER(8) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_PERSON_QUALIFIED_GROUP_PK PRIMARY KEY (PERSON_ID, GROUP_ID, GROUP_ATTRIBUTE_ID)
)
/