CREATE TABLE KIM_GROUPS_GROUPS_T (
        PARENT_GROUP_ID NUMBER(8) NOT NULL,
        MEMBER_GROUP_ID NUMBER(8) NOT NULL, 
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_GROUPS_GROUPS_PK PRIMARY KEY (PARENT_GROUP_ID, MEMBER_GROUP_ID)
)
/