CREATE TABLE KIM_NAMESPACE_DFLT_ATTRIBS_T (
        ID NUMBER(8) NOT NULL,
        NAMESPACE_ID NUMBER(8) NOT NULL,
        ATTRIBUTE_NAME VARCHAR2(500) NOT NULL,
        ATTRIBUTE_TYPE_ID NUMBER(8) NOT NULL,
        DESCRIPTION VARCHAR(4000),
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_NMSPCE_DFLT_ATTR_PK PRIMARY KEY (ID)
)
/