CREATE TABLE KIM_ROLES_GROUPS_T (
        ROLE_ID NUMBER(8) NOT NULL,
        GROUP_ID NUMBER(8) NOT NULL, 
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_ROLES_GROUPS_PK PRIMARY KEY (ROLE_ID, GROUP_ID)
)
/