CREATE TABLE KIM_GROUP_QUALIFIED_ROLE_T (
		ID NUMBER(8) NOT NULL,
        GROUP_ID NUMBER(8) NOT NULL,
		ROLE_ID NUMBER(8) NOT NULL,
		ATTRIBUTE_NAME VARCHAR(255) NOT NULL,
		ATTRIBUTE_VALUE VARCHAR(255) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT KIM_GROUP_QUALIFIED_ROLE_PK PRIMARY KEY (GROUP_ID, ROLE_ID)
)
/