CREATE TABLE ROLES_USERS_T (
        ROLE_ID NUMBER(8) NOT NULL,
        USER_ID NUMBER(8) NOT NULL,
		OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL, 
        VER_NBR NUMBER(8) DEFAULT 1 NOT NULL, 
        CONSTRAINT ROLES_USERS_PK PRIMARY KEY (ROLE_ID, USER_ID)
)
/