--
-- Copyright 2005-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--


-- TRVL_EXP_ITM_T

CREATE TABLE TRVL_EXP_ITM_T  (
    EXP_ITM_ID    VARCHAR2(40) NOT NULL,
    OBJ_ID        VARCHAR2(36) NOT NULL,
    VER_NBR       NUMBER(8,0) DEFAULT 1 NOT NULL,
    EXP_TYP_CD    VARCHAR2(40) NOT NULL,
    EXP_AMT       NUMBER(19,2) NOT NULL,
    EXP_DESC      VARCHAR2(255) NOT NULL,
    EXP_DT        DATE NULL,
    EXP_REIMB     VARCHAR2(1) DEFAULT 'Y' NULL,
    EXP_TXBL      VARCHAR2(1) DEFAULT 'Y' NULL,
    PRIMARY KEY(EXP_ITM_ID),
    CONSTRAINT TRVL_EXP_ITEM_TC0 UNIQUE (OBJ_ID)
)
/

CREATE SEQUENCE TRVL_EXP_ITM_ID_S START WITH 10000
/

INSERT INTO TRVL_EXP_ITM_T (EXP_ITM_ID, OBJ_ID,VER_NBR,EXP_TYP_CD,EXP_AMT,EXP_DESC, EXP_DT, EXP_REIMB, EXP_TXBL)
VALUES (TRVL_EXP_ITM_ID_S.NEXTVAL, sys_guid(), 1,'ME', 30, 'Family Related', SYSDATE, 'Y','Y')
/

-- TRVL_MLG_RT_T

CREATE TABLE TRVL_MLG_RT_T  (
    MLG_RT_ID     VARCHAR2(40) NOT NULL,
    MLG_RT_CD     VARCHAR2(40) NOT NULL,
    OBJ_ID        VARCHAR2(36) NOT NULL,
    VER_NBR      NUMBER(8,0) DEFAULT 1 NOT NULL,
    MLG_RT_NM     VARCHAR2(40) NOT NULL,
    MLG_RT      NUMBER(8,0) NOT NULL,
    ACTV_IND      VARCHAR2(1) DEFAULT 'Y' NULL,
    CONSTRAINT TRVL_MLG_RT_TP1 PRIMARY KEY(MLG_RT_ID),
    CONSTRAINT TRVL_MIL_RT_TC0 UNIQUE (OBJ_ID)
)
/


CREATE SEQUENCE TRVL_MLG_RT_ID_S START WITH 10001
/

INSERT INTO TRVL_MLG_RT_T (MLG_RT_ID, MLG_RT_CD, OBJ_ID, VER_NBR, MLG_RT_NM, MLG_RT, ACTV_IND)
VALUES (10000, 'DO', sys_guid(), 1,'Domestic', 30, 'Y')
/

-- TRVL_DEST_T

CREATE TABLE TRVL_DEST_T (
    TRVL_DEST_ID  VARCHAR2(40) NOT NULL,
    TRVL_TYP_CD   VARCHAR2(40) NOT NULL,
    OBJ_ID        VARCHAR2(36) NOT NULL,
    VER_NBR      NUMBER(8,0) DEFAULT 1 NOT NULL,
    DEST_NM       VARCHAR2(40) NOT NULL,
    POSTAL_CNTRY_CD VARCHAR2(40) NOT NULL,
    POSTAL_STATE_CD  VARCHAR2(40) NOT NULL,
    ACTV_IND      VARCHAR2(1) DEFAULT 'Y' NOT NULL ,
    PRIMARY KEY(TRVL_DEST_ID),
    CONSTRAINT TRVL_DEST_TC0 UNIQUE (OBJ_ID)
)
/

CREATE SEQUENCE TRVL_DEST_ID_S START WITH 10000
/

INSERT INTO TRVL_DEST_T (TRVL_DEST_ID, TRVL_TYP_CD, OBJ_ID, VER_NBR, DEST_NM, POSTAL_CNTRY_CD, POSTAL_STATE_CD, ACTV_IND)
VALUES (TRVL_DEST_ID_S.NEXTVAL, 'IS', sys_guid(), 1, 'Colorado', 'US', 'CO', 'Y')
/

-- TRVL_PD_EXP_T

CREATE TABLE TRVL_PD_EXP_T  (
    PD_EXP_ID     VARCHAR2(40) NOT NULL,
    OBJ_ID      	VARCHAR2(36) NOT NULL,
    VER_NBR     	NUMBER(8,0) DEFAULT 1 NOT NULL ,
    PD_DT         DATE NULL,
    BKFST_VAL     NUMBER(19,2)  NOT NULL,
    LNCH_VAL      NUMBER(19,2)  NOT NULL,
    DNNR_VAL      NUMBER(19,2)  NOT NULL,
    INCD_VAL      NUMBER(19,2)  NOT NULL,
    MLG_RT_ID     VARCHAR2(40) NOT NULL,
    MLG_EST       NUMBER(8,0) NOT NULL,
	  PRIMARY KEY( PD_EXP_ID ),
    CONSTRAINT TRVL_PD_EXP_TC0 UNIQUE (OBJ_ID),
    CONSTRAINT TRVL_PD_EXP_FK1 FOREIGN KEY ( MLG_RT_ID )
    REFERENCES TRVL_MLG_RT_T ( MLG_RT_ID )
)
/

CREATE SEQUENCE TRVL_PD_EXP_ID_S START WITH 10000
/

INSERT INTO TRVL_PD_EXP_T (PD_EXP_ID, OBJ_ID, VER_NBR, PD_DT, BKFST_VAL, LNCH_VAL, DNNR_VAL, INCD_VAL, MLG_RT_ID, MLG_EST)
VALUES (TRVL_PD_EXP_ID_S.NEXTVAL, sys_guid(), 1, SYSDATE, 10.00, 10.00, 15.00, 20.00, 10000, 30)
/

CREATE TABLE TRVL_CO_T (
    CO_ID         VARCHAR2(40) NOT NULL,
    CO_NM         VARCHAR2(40) NOT NULL,
    OBJ_ID        VARCHAR2(36) NOT NULL,
    VER_NBR       NUMBER(8,0) DEFAULT 1 NOT NULL,
    ACTV_IND      VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    PRIMARY KEY(CO_ID),
    CONSTRAINT TRVL_CO_TC0 UNIQUE (OBJ_ID)
)
/

CREATE SEQUENCE TRVL_CO_ID_S START WITH 10000
/

INSERT INTO TRVL_CO_T (CO_ID, CO_NM,OBJ_ID,VER_NBR, ACTV_IND )
VALUES (TRVL_CO_ID_S.NEXTVAL, 'Value Rentals', sys_guid(), 1, 'Y')
/
