--
-- Copyright 2005-2011 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

INSERT INTO KRNS_CAMPUS_T(CAMPUS_CD, CAMPUS_NM, CAMPUS_SHRT_NM, CAMPUS_TYP_CD, OBJ_ID, VER_NBR)
  VALUES('BL', 'BLOOMINGTON', 'BLOOMINGTON', 'B', '014F3DB2478DA448E043814FD28EA448', 1)
/
INSERT INTO KRNS_CAMPUS_T(CAMPUS_CD, CAMPUS_NM, CAMPUS_SHRT_NM, CAMPUS_TYP_CD, OBJ_ID, VER_NBR)
  VALUES('CO', 'COLUMBUS', 'COLUMBUS', 'F', '014F3DB2478EA448E043814FD28EA448', 1)
/
INSERT INTO KRNS_CAMPUS_T(CAMPUS_CD, CAMPUS_NM, CAMPUS_SHRT_NM, CAMPUS_TYP_CD, OBJ_ID, VER_NBR)
  VALUES('EA', 'EAST-RICHMOND', 'EA-RICHMOND', 'B', '014F3DB2478FA448E043814FD28EA448', 1)
/
INSERT INTO KRNS_CAMPUS_T(CAMPUS_CD, CAMPUS_NM, CAMPUS_SHRT_NM, CAMPUS_TYP_CD, OBJ_ID, VER_NBR)
  VALUES('FW', 'FORT WAYNE', 'FORT WAYNE', 'B', '014F3DB24790A448E043814FD28EA448', 1)
/
INSERT INTO KRNS_CAMPUS_T(CAMPUS_CD, CAMPUS_NM, CAMPUS_SHRT_NM, CAMPUS_TYP_CD, OBJ_ID, VER_NBR)
  VALUES('IN', 'INDIANAPOLIS', 'INDIANAPOLIS', 'B', '014F3DB24791A448E043814FD28EA448', 1)
/
INSERT INTO KRNS_CAMPUS_T(CAMPUS_CD, CAMPUS_NM, CAMPUS_SHRT_NM, CAMPUS_TYP_CD, OBJ_ID, VER_NBR)
  VALUES('KO', 'KOKOMO', 'KOKOMO', 'B', '014F3DB24792A448E043814FD28EA448', 1)
/
INSERT INTO KRNS_CAMPUS_T(CAMPUS_CD, CAMPUS_NM, CAMPUS_SHRT_NM, CAMPUS_TYP_CD, OBJ_ID, VER_NBR)
  VALUES('NW', 'NORTHWEST-GARY', 'NW-GARY', 'B', '014F3DB24793A448E043814FD28EA448', 1)
/
INSERT INTO KRNS_CAMPUS_T(CAMPUS_CD, CAMPUS_NM, CAMPUS_SHRT_NM, CAMPUS_TYP_CD, OBJ_ID, VER_NBR)
  VALUES('OC', 'OFF CAMPUS', 'OFF CAMPUS', 'F', '014F3DB24794A448E043814FD28EA448', 1)
/
INSERT INTO KRNS_CAMPUS_T(CAMPUS_CD, CAMPUS_NM, CAMPUS_SHRT_NM, CAMPUS_TYP_CD, OBJ_ID, VER_NBR)
  VALUES('SB', 'SOUTH BEND', 'SOUTH BEND', 'B', '014F3DB24795A448E043814FD28EA448', 1)
/
INSERT INTO KRNS_CAMPUS_T(CAMPUS_CD, CAMPUS_NM, CAMPUS_SHRT_NM, CAMPUS_TYP_CD, OBJ_ID, VER_NBR)
  VALUES('SE', 'SOUTHEAST-NEW ALBANY', 'SE-NEW ALBNY', 'B', '014F3DB24796A448E043814FD28EA448', 1)
/
INSERT INTO KRNS_CAMPUS_T(CAMPUS_CD, CAMPUS_NM, CAMPUS_SHRT_NM, CAMPUS_TYP_CD, OBJ_ID, VER_NBR)
  VALUES('UA', 'UNIVERSITY ADMINISTRATION', 'UNIVER ADMIN', 'F', '014F3DB24797A448E043814FD28EA448', 1)
/
INSERT INTO KRNS_CAMPUS_T(CAMPUS_CD, CAMPUS_NM, CAMPUS_SHRT_NM, CAMPUS_TYP_CD, OBJ_ID, VER_NBR)
  VALUES('BX', 'BLGTN OFF CAMPUS', 'BLGTN OFF CA', 'P', '014F3DB24798A448E043814FD28EA448', 1)
/
INSERT INTO KRNS_CAMPUS_T(CAMPUS_CD, CAMPUS_NM, CAMPUS_SHRT_NM, CAMPUS_TYP_CD, OBJ_ID, VER_NBR)
  VALUES('IX', 'indianapolis off campus test', 'indy off cmp', 'P', 'DD09D1AE-CD52-07FC-2BCF-9FA6D95BD484', 2)
/
