create table TST_SEARCH_ATTR_INDX_TST_DOC_T (
    DOC_HDR_ID VARCHAR2(14),
	OBJ_ID VARCHAR2(36),
	VER_NBR NUMBER(14),
	RTE_LVL_CNT NUMBER(14),
	CNSTNT_STR VARCHAR2(50),
    RTD_STR VARCHAR2(50),
    HLD_RTD_STR VARCHAR2(50),
    RD_ACCS_CNT NUMBER(14),
    CONSTRAINT TST_SEARCH_ATTR_INDX_TST_DOC_T PRIMARY KEY (DOC_HDR_ID)
)