-- KULRICE-3692 -- Eliminate unnecessary deserialization of ServiceDefinition objects
DELETE FROM KRSB_SVC_DEF_T
/
ALTER TABLE KRSB_SVC_DEF_T DROP (SVC_DEF)
/
ALTER TABLE KRSB_SVC_DEF_T ADD (
	FLT_SVC_DEF_ID NUMBER(14, 0) NOT NULL,
	SVC_DEF_CHKSM VARCHAR2(30) NOT NULL
)
/
CREATE UNIQUE INDEX KRSB_SVC_DEF_TI2 ON KRSB_SVC_DEF_T (FLT_SVC_DEF_ID)
/
CREATE TABLE KRSB_FLT_SVC_DEF_T (
	FLT_SVC_DEF_ID NUMBER(14, 0),
	FLT_SVC_DEF CLOB NOT NULL,
	CONSTRAINT KRSB_FLT_SVC_DEF_TP1 PRIMARY KEY (FLT_SVC_DEF_ID)
)
/
CREATE SEQUENCE KRSB_FLT_SVC_DEF_S START WITH 1000 INCREMENT BY 1
