/* contains consolidated and cleaned up sql from 10-02-2009.sql, 10-05-2009.sql, KewApplicationStatus-KULRICE-2805.sql, KULRICE-3794.sql */

alter table KREW_DOC_HDR_T add (APP_DOC_STAT varchar2(64), APP_DOC_STAT_MDFN_DT date)
/
create index KREW_DOC_HDR_T10 on KREW_DOC_HDR_T (APP_DOC_STAT)
/
create index KREW_DOC_HDR_T12 on KREW_DOC_HDR_T (APP_DOC_STAT_MDFN_DT)
/
alter table KREW_DOC_TYP_PLCY_RELN_T add PLCY_VAL varchar2(64)
/
alter table KREW_RTE_NODE_T add NEXT_DOC_STAT varchar2(64)
/
CREATE TABLE KREW_DOC_TYP_APP_DOC_STAT_T
(
      DOC_TYP_ID NUMBER(19)
        , DOC_STAT_NM VARCHAR2(64)
        , VER_NBR NUMBER(8) default 0
        , OBJ_ID VARCHAR2(36) NOT NULL    
    , CONSTRAINT KREW_DOC_TYP_APP_DOC_STAT_TP1 PRIMARY KEY(DOC_TYP_ID,DOC_STAT_NM)
    , CONSTRAINT KREW_DOC_TYP_APP_DOC_STAT_TC0 UNIQUE (OBJ_ID)
) 
/
create index KREW_DOC_TYP_APP_DOC_STAT_T1 on KREW_DOC_TYP_APP_DOC_STAT_T(DOC_TYP_ID)
/

CREATE TABLE KREW_APP_DOC_STAT_TRAN_T
(
      APP_DOC_STAT_TRAN_ID NUMBER(19) PRIMARY KEY,
      DOC_HDR_ID NUMBER(14),
      APP_DOC_STAT_FROM VARCHAR2(64),
      APP_DOC_STAT_TO VARCHAR2(64),
      STAT_TRANS_DATE DATE,
      VER_NBR NUMBER(8) default 0,
      OBJ_ID VARCHAR2(36) NOT NULL,
      CONSTRAINT KREW_APP_DOC_STAT_TRAN_TC0 UNIQUE (OBJ_ID)
)
/
CREATE INDEX KREW_APP_DOC_STAT_TI1 ON KREW_APP_DOC_STAT_TRAN_T (DOC_HDR_ID, STAT_TRANS_DATE)
/
CREATE INDEX KREW_APP_DOC_STAT_TI2 ON KREW_APP_DOC_STAT_TRAN_T (DOC_HDR_ID, APP_DOC_STAT_FROM)
/
CREATE INDEX KREW_APP_DOC_STAT_TI3 ON KREW_APP_DOC_STAT_TRAN_T (DOC_HDR_ID, APP_DOC_STAT_TO)
/ 



create sequence krew_doc_lnk_s increment by 1 start with 2000 cache 20
/
create table krew_doc_lnk_t(

           DOC_LNK_ID NUMBER(19),
           ORGN_DOC_ID NUMBER(14) NOT NULL,
           DEST_DOC_ID NUMBER(14) NOT NULL, 
           
           CONSTRAINT KREW_DOC_LNK_TP1 PRIMARY KEY (DOC_LNK_ID)
)
/
create INDEX KREW_DOC_LNK_TI1 on krew_doc_lnk_t(ORGN_DOC_ID)
/



delete from KREW_STYLE_T where NM = 'widgets'
/
