--
-- Copyright 2009 The Kuali Foundation
-- 
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
-- http://www.opensource.org/licenses/ecl2.php
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
-- DO NOT add comments before the blank line below, or they will disappear.
ALTER TABLE EN_ACTN_ITM_T RENAME TO KREW_ACTN_ITM_T
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_ASND_DT TO ASND_DT
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_RQST_CD TO RQST_CD
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_DLGN_PRSN_EN_ID TO DLGN_PRNCPL_ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN DOC_TTL TO DOC_HDR_TTL
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN DOC_TYP_LBL_TXT TO DOC_TYP_LBL
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN DOC_TYP_HDLR_URL_ADDR TO DOC_HDLR_URL
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_RESP_ID TO RSP_ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE KREW_ACTN_ITM_T RENAME COLUMN ACTN_ITM_DLGN_WRKGRP_ID TO DLGN_GRP_ID
/
ALTER INDEX EN_ACTN_ITM_T1 RENAME TO KREW_ACTN_ITM_T1
/
ALTER INDEX EN_ACTN_ITM_TI2 RENAME TO KREW_ACTN_ITM_TI2
/
ALTER INDEX EN_ACTN_ITM_TI3 RENAME TO KREW_ACTN_ITM_TI3
/
ALTER INDEX EN_ACTN_ITM_TI5 RENAME TO KREW_ACTN_ITM_TI5
/
ALTER TABLE EN_ACTN_RQST_T RENAME TO KREW_ACTN_RQST_T
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_PARNT_ID TO PARNT_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN RULE_BASE_VALUES_ID TO RULE_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_STAT_CD TO STAT_CD
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RESP_ID TO RSP_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RECP_TYP_CD TO RECIP_TYP_CD
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_PRIO_NBR TO PRIO_NBR
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RTE_TYP_NM TO RTE_TYP_NM
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RTE_LVL_NBR TO RTE_LVL_NBR
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RTE_NODE_INSTN_ID TO RTE_NODE_INSTN_ID
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_CRTE_DT TO CRTE_DT
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_RESP_DESC TO RSP_DESC_TXT
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_IGN_PREV_ACTN_IND TO FRC_ACTN
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_APPR_PLCY TO APPR_PLCY
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN ACTN_RQST_CUR_IND TO CUR_IND
/
ALTER TABLE KREW_ACTN_RQST_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER INDEX EN_ACTN_RQST_TI1 RENAME TO KREW_ACTN_RQST_T11
/
ALTER INDEX EN_ACTN_RQST_TI2 RENAME TO KREW_ACTN_RQST_T12
/
ALTER INDEX EN_ACTN_RQST_T13 RENAME TO KREW_ACTN_RQST_T13
/
ALTER INDEX EN_ACTN_RQST_T14 RENAME TO KREW_ACTN_RQST_T14
/
ALTER INDEX EN_ACTN_RQST_TI5 RENAME TO KREW_ACTN_RQST_T15
/
ALTER INDEX EN_ACTN_RQST_TI6 RENAME TO KREW_ACTN_RQST_T16
/
ALTER INDEX EN_ACTN_RQST_TI7 RENAME TO KREW_ACTN_RQST_T17
/
ALTER INDEX EN_ACTN_RQST_TI8 RENAME TO KREW_ACTN_RQST_T18
/
ALTER INDEX EN_ACTN_RQST_TI9 RENAME TO KREW_ACTN_RQST_T19
/
ALTER TABLE EN_ACTN_TKN_T RENAME TO KREW_ACTN_TKN_T
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_DLGTR_PRSN_EN_ID TO DLGTR_PRNCPL_ID
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_DLGTR_WRKGRP_ID TO DLGTR_GRP_ID
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_CD TO ACTN_CD
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_DT TO ACTN_DT
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_ANNOTN_TXT TO ANNOTN
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN ACTN_TKN_CUR_IND TO CUR_IND
/
ALTER TABLE KREW_ACTN_TKN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_ACTN_TKN_TI1 RENAME TO KREW_ACTN_TKN_TI1
/
ALTER INDEX EN_ACTN_TKN_TI2 RENAME TO KREW_ACTN_TKN_TI2
/
ALTER INDEX EN_ACTN_TKN_TI3 RENAME TO KREW_ACTN_TKN_TI3
/
ALTER INDEX EN_ACTN_TKN_TI4 RENAME TO KREW_ACTN_TKN_TI4
/
ALTER INDEX EN_ACTN_TKN_TI5 RENAME TO KREW_ACTN_TKN_TI5
/
ALTER TABLE EN_ATTACHMENT_T RENAME TO KREW_ATT_T
/
ALTER TABLE KREW_ATT_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_DLGN_RSP_T RENAME TO KREW_DLGN_RSP_T
/
ALTER TABLE KREW_DLGN_RSP_T RENAME COLUMN RULE_RSP_ID TO RSP_ID
/
ALTER TABLE KREW_DLGN_RSP_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_DOC_HDR_CNTNT_T RENAME TO KREW_DOC_HDR_CNTNT_T
/
ALTER TABLE EN_DOC_HDR_EXT_DT_T RENAME TO KREW_DOC_HDR_EXT_DT_T
/
ALTER TABLE KREW_DOC_HDR_EXT_DT_T RENAME COLUMN DOC_HDR_EXT_ID TO DOC_HDR_EXT_DT_ID
/
ALTER TABLE KREW_DOC_HDR_EXT_DT_T RENAME COLUMN DOC_HDR_EXT_VAL_KEY TO KEY_CD
/
ALTER TABLE KREW_DOC_HDR_EXT_DT_T RENAME COLUMN DOC_HDR_EXT_VAL TO VAL
/
ALTER INDEX EN_DOC_HDR_EXT_DT_TI1 RENAME TO KREW_DOC_HDR_EXT_DT_TI1
/
ALTER INDEX EN_DOC_HDR_EXT_DT_TI2 RENAME TO KREW_DOC_HDR_EXT_DT_TI2
/
ALTER INDEX EN_DOC_HDR_EXT_DT_TI3 RENAME TO KREW_DOC_HDR_EXT_DT_TI3
/
ALTER TABLE EN_DOC_HDR_EXT_FLT_T RENAME TO KREW_DOC_HDR_EXT_FLT_T
/
ALTER TABLE KREW_DOC_HDR_EXT_FLT_T RENAME COLUMN DOC_HDR_EXT_ID TO DOC_HDR_EXT_FLT_ID
/
ALTER TABLE KREW_DOC_HDR_EXT_FLT_T RENAME COLUMN DOC_HDR_EXT_VAL_KEY TO KEY_CD
/
ALTER TABLE KREW_DOC_HDR_EXT_FLT_T RENAME COLUMN DOC_HDR_EXT_VAL TO VAL
/
ALTER INDEX EN_DOC_HDR_EXT_FLT_TI1 RENAME TO KREW_DOC_HDR_EXT_FLT_TI1
/
ALTER INDEX EN_DOC_HDR_EXT_FLT_TI2 RENAME TO KREW_DOC_HDR_EXT_FLT_TI2
/
ALTER INDEX EN_DOC_HDR_EXT_FLT_TI3 RENAME TO KREW_DOC_HDR_EXT_FLT_TI3
/
ALTER TABLE EN_DOC_HDR_EXT_LONG_T RENAME TO KREW_DOC_HDR_EXT_LONG_T
/
ALTER TABLE KREW_DOC_HDR_EXT_LONG_T RENAME COLUMN DOC_HDR_EXT_ID TO DOC_HDR_EXT_LONG_ID
/
ALTER TABLE KREW_DOC_HDR_EXT_LONG_T RENAME COLUMN DOC_HDR_EXT_VAL_KEY TO KEY_CD
/
ALTER TABLE KREW_DOC_HDR_EXT_LONG_T RENAME COLUMN DOC_HDR_EXT_VAL TO VAL
/
ALTER INDEX EN_DOC_HDR_EXT_LONG_TI1 RENAME TO KREW_DOC_HDR_EXT_LONG_TI1
/
ALTER INDEX EN_DOC_HDR_EXT_LONG_TI2 RENAME TO KREW_DOC_HDR_EXT_LONG_TI2
/
ALTER INDEX EN_DOC_HDR_EXT_LONG_TI3 RENAME TO KREW_DOC_HDR_EXT_LONG_TI3
/
ALTER TABLE EN_DOC_HDR_EXT_T RENAME TO KREW_DOC_HDR_EXT_T
/
ALTER TABLE KREW_DOC_HDR_EXT_T RENAME COLUMN DOC_HDR_EXT_VAL_KEY TO KEY_CD
/
ALTER TABLE KREW_DOC_HDR_EXT_T RENAME COLUMN DOC_HDR_EXT_VAL TO VAL
/
ALTER INDEX EN_DOC_HDR_EXT_TI1 RENAME TO KREW_DOC_HDR_EXT_TI1
/
ALTER INDEX EN_DOC_HDR_EXT_TI2 RENAME TO KREW_DOC_HDR_EXT_TI2
/
ALTER INDEX EN_DOC_HDR_EXT_TI3 RENAME TO KREW_DOC_HDR_EXT_TI3
/
ALTER TABLE EN_DOC_HDR_T RENAME TO KREW_DOC_HDR_T
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_RTE_STAT_CD TO DOC_HDR_STAT_CD
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_RTE_LVL_NBR TO RTE_LVL
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_STAT_MDFN_DT TO STAT_MDFN_DT
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_CRTE_DT TO CRTE_DT
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_APRV_DT TO APRV_DT
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_FNL_DT TO FNL_DT
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_RTE_STAT_MDFN_DT TO RTE_STAT_MDFN_DT
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_RTE_LVL_MDFN_DT TO RTE_LVL_MDFN_DT
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_TTL TO TTL
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_APPL_DOC_ID TO APP_DOC_ID
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_INITR_PRSN_EN_ID TO INITR_PRNCPL_ID
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KREW_DOC_HDR_T RENAME COLUMN DOC_RTE_USR_PRSN_EN_ID TO RTE_PRNCPL_ID
/
ALTER INDEX EN_DOC_HDR_TI1 RENAME TO KREW_DOC_HDR_TI1
/
ALTER INDEX EN_DOC_HDR_TI2 RENAME TO KREW_DOC_HDR_TI2
/
ALTER INDEX EN_DOC_HDR_TI3 RENAME TO KREW_DOC_HDR_TI3
/
ALTER INDEX EN_DOC_HDR_TI4 RENAME TO KREW_DOC_HDR_TI4
/
ALTER INDEX EN_DOC_HDR_TI5 RENAME TO KREW_DOC_HDR_TI5
/
ALTER INDEX EN_DOC_HDR_TI6 RENAME TO KREW_DOC_HDR_TI6
/
ALTER INDEX EN_DOC_HDR_TI7 RENAME TO KREW_DOC_HDR_TI7
/
ALTER INDEX EN_DOC_HDR_TI8 RENAME TO KREW_DOC_HDR_TI8
/
ALTER INDEX EN_DOC_HDR_TI9 RENAME TO KREW_DOC_HDR_TI9
/
ALTER TABLE EN_DOC_NTE_T RENAME TO KREW_DOC_NTE_T
/
ALTER TABLE KREW_DOC_NTE_T RENAME COLUMN DOC_NTE_AUTH_PRSN_EN_ID TO AUTH_PRNCPL_ID
/
ALTER TABLE KREW_DOC_NTE_T RENAME COLUMN DOC_NTE_CRT_DT TO CRT_DT
/
ALTER TABLE KREW_DOC_NTE_T RENAME COLUMN DOC_NTE_TXT TO TXT
/
ALTER TABLE KREW_DOC_NTE_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_DOC_NTE_TI1 RENAME TO KREW_DOC_NTE_TI1
/
ALTER TABLE EN_DOC_TYP_ATTRIB_T RENAME TO KREW_DOC_TYP_ATTR_T
/
ALTER TABLE KREW_DOC_TYP_ATTR_T RENAME COLUMN RULE_ATTRIB_ID TO RULE_ATTR_ID
/
ALTER INDEX EN_DOC_TYP_ATTRIB_TI1 RENAME TO KREW_DOC_TYP_ATTR_TI1
/
ALTER TABLE EN_DOC_TYP_PLCY_RELN_T RENAME TO KREW_DOC_TYP_PLCY_RELN_T
/
ALTER TABLE KREW_DOC_TYP_PLCY_RELN_T RENAME COLUMN DOC_PLCY_VAL TO PLCY_NM
/
ALTER TABLE KREW_DOC_TYP_PLCY_RELN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_DOC_TYP_PROC_T RENAME TO KREW_DOC_TYP_PROC_T
/
ALTER TABLE KREW_DOC_TYP_PROC_T RENAME COLUMN PROC_NM TO NM
/
ALTER TABLE KREW_DOC_TYP_PROC_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_DOC_TYP_PROC_TI1 RENAME TO KREW_DOC_TYP_PROC_TI1
/
ALTER INDEX EN_DOC_TYP_PROC_TI2 RENAME TO KREW_DOC_TYP_PROC_TI2
/
ALTER INDEX EN_DOC_TYP_PROC_TI3 RENAME TO KREW_DOC_TYP_PROC_TI3
/
ALTER TABLE EN_DOC_TYP_T RENAME TO KREW_DOC_TYP_T
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_PARNT_ID TO PARNT_ID
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_CUR_IND TO CUR_IND
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_LBL_TXT TO LBL
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_PREV_VER TO PREV_DOC_TYP_VER_NBR
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_HDLR_URL_ADDR TO DOC_HDLR_URL
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_POST_PRCSR_NM TO POST_PRCSR
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_JNDI_URL_ADDR TO JNDI_URL
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN ADV_DOC_SRCH_URL_ADDR TO ADV_DOC_SRCH_URL
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_RTE_VER_NBR TO RTE_VER_NBR
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_NOTIFY_ADDR TO NOTIFY_ADDR
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN MESSAGE_ENTITY_NM TO SVC_NMSPC
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_EMAIL_XSL TO EMAIL_XSL
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DOC_TYP_SECURITY_XML TO SEC_XML
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN BLNKT_APPR_WRKGRP_ID TO BLNKT_APPR_GRP_ID
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN RPT_WRKGRP_ID TO RPT_GRP_ID
/
ALTER TABLE KREW_DOC_TYP_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER INDEX EN_DOC_TYP_TI2 RENAME TO KREW_DOC_TYP_TI2
/
ALTER INDEX EN_DOC_TYP_TI3 RENAME TO KREW_DOC_TYP_TI3
/
ALTER INDEX EN_DOC_TYP_TI4 RENAME TO KREW_DOC_TYP_TI4
/
ALTER INDEX EN_DOC_TYP_TI5 RENAME TO KREW_DOC_TYP_TI5
/
ALTER INDEX EN_DOC_TYP_TI6 RENAME TO KREW_DOC_TYP_TI6
/
ALTER TABLE KREW_DOC_TYP_T RENAME CONSTRAINT EN_DOC_TYP_TI1 TO KREW_DOC_TYP_TI1
/
ALTER TABLE EN_EDL_DMP_T RENAME TO KREW_EDL_DMP_T
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DOC_RTE_STAT_CD TO DOC_HDR_STAT_CD
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DOC_MDFN_DT TO DOC_HDR_MDFN_DT
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DOC_CRTE_DT TO DOC_HDR_CRTE_DT
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DOC_TTL TO DOC_HDR_TTL
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DOC_INITR_ID TO DOC_HDR_INITR_PRNCPL_ID
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DOC_CRNT_NODE_NM TO CRNT_NODE_NM
/
ALTER TABLE KREW_EDL_DMP_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_EDL_DMP_TI1 RENAME TO KREW_EDL_DMP_TI1
/
ALTER TABLE EN_EDL_FIELD_DMP_T RENAME TO KREW_EDL_FLD_DMP_T
/
ALTER TABLE KREW_EDL_FLD_DMP_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_EDOCLT_ASSOC_T RENAME TO KREW_EDL_ASSCTN_T
/
ALTER TABLE KREW_EDL_ASSCTN_T RENAME COLUMN EDOCLT_ASSOC_DOCTYPE_NM TO DOC_TYP_NM
/
ALTER TABLE KREW_EDL_ASSCTN_T RENAME COLUMN EDOCLT_ASSOC_DEF_NM TO EDL_DEF_NM
/
ALTER TABLE KREW_EDL_ASSCTN_T RENAME COLUMN EDOCLT_ASSOC_STYLE_NM TO STYLE_NM
/
ALTER TABLE KREW_EDL_ASSCTN_T RENAME COLUMN EDOCLT_ASSOC_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_EDL_ASSCTN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_EDOCLT_DEF_T RENAME TO KREW_EDL_DEF_T
/
ALTER TABLE KREW_EDL_DEF_T RENAME COLUMN EDOCLT_DEF_NM TO NM
/
ALTER TABLE KREW_EDL_DEF_T RENAME COLUMN EDOCLT_DEF_XML TO XML
/
ALTER TABLE KREW_EDL_DEF_T RENAME COLUMN EDOCLT_DEF_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_EDL_DEF_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_EDOCLT_STYLE_T RENAME TO KREW_STYLE_T
/
ALTER TABLE KREW_STYLE_T RENAME COLUMN EDOCLT_STYLE_ID TO STYLE_ID
/
ALTER TABLE KREW_STYLE_T RENAME COLUMN EDOCLT_STYLE_NM TO NM
/
ALTER TABLE KREW_STYLE_T RENAME COLUMN EDOCLT_STYLE_XML TO XML
/
ALTER TABLE KREW_STYLE_T RENAME COLUMN EDOCLT_STYLE_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_STYLE_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_HLP_T RENAME TO KREW_HLP_T
/
ALTER TABLE KREW_HLP_T RENAME COLUMN EN_HLP_ID TO HLP_ID
/
ALTER TABLE KREW_HLP_T RENAME COLUMN EN_HLP_NM TO NM
/
ALTER TABLE KREW_HLP_T RENAME COLUMN EN_HLP_KY TO KEY_CD
/
ALTER TABLE KREW_HLP_T RENAME COLUMN EN_HLP_TXT TO HLP_TXT
/
ALTER TABLE KREW_HLP_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_HLP_TI1 RENAME TO KREW_HLP_TI1
/
ALTER TABLE EN_INIT_RTE_NODE_INSTN_T RENAME TO KREW_INIT_RTE_NODE_INSTN_T
/
ALTER INDEX EN_INIT_RTE_NODE_INSTN_TI1 RENAME TO KREW_INIT_RTE_NODE_INSTN_TI1
/
ALTER INDEX EN_INIT_RTE_NODE_INSTN_TI2 RENAME TO KREW_INIT_RTE_NODE_INSTN_TI2
/
ALTER TABLE EN_OUT_BOX_ITM_T RENAME TO KREW_OUT_BOX_ITM_T
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_ASND_DT TO ASND_DT
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_RQST_CD TO RQST_CD
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_DLGN_PRSN_EN_ID TO DLGN_PRNCPL_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN DOC_TTL TO DOC_HDR_TTL
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN DOC_TYP_LBL_TXT TO DOC_TYP_LBL
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN DOC_TYP_HDLR_URL_ADDR TO DOC_HDLR_URL
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_RESP_ID TO RSP_ID
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KREW_OUT_BOX_ITM_T RENAME COLUMN ACTN_ITM_DLGN_WRKGRP_ID TO DLGN_GRP_ID
/
ALTER INDEX EN_OUT_BOX_ITM_T1 RENAME TO KREW_OUT_BOX_ITM_TI1
/
ALTER INDEX EN_OUT_BOX_ITM_TI2 RENAME TO KREW_OUT_BOX_ITM_TI2
/
ALTER INDEX EN_OUT_BOX_ITM_TI3 RENAME TO KREW_OUT_BOX_ITM_TI3
/
ALTER TABLE EN_RMV_RPLC_DOC_T RENAME TO KREW_RMV_RPLC_DOC_T
/
ALTER TABLE KREW_RMV_RPLC_DOC_T RENAME COLUMN PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_RMV_RPLC_DOC_T RENAME COLUMN RPLC_PRSN_EN_ID TO RPLC_PRNCPL_ID
/
ALTER TABLE KREW_RMV_RPLC_DOC_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_RMV_RPLC_RULE_T RENAME TO KREW_RMV_RPLC_RULE_T
/
ALTER TABLE EN_RMV_RPLC_WRKGRP_T RENAME TO KREW_RMV_RPLC_GRP_T
/
ALTER TABLE KREW_RMV_RPLC_GRP_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER TABLE EN_RTE_BRCH_PROTO_T RENAME TO KREW_RTE_BRCH_PROTO_T
/
ALTER TABLE KREW_RTE_BRCH_PROTO_T RENAME COLUMN RTE_BRCH_PROTO_NM TO BRCH_NM
/
ALTER TABLE KREW_RTE_BRCH_PROTO_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_RTE_BRCH_PROTO_TI1 RENAME TO KREW_RTE_BRCH_PROTO_TI1
/
ALTER TABLE EN_RTE_BRCH_ST_T RENAME TO KREW_RTE_BRCH_ST_T
/
ALTER TABLE KREW_RTE_BRCH_ST_T RENAME COLUMN ST_KEY TO KEY_CD
/
ALTER TABLE KREW_RTE_BRCH_ST_T RENAME COLUMN ST_VAL_TXT TO VAL
/
ALTER TABLE KREW_RTE_BRCH_ST_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_RTE_BRCH_ST_TI1 RENAME TO KREW_RTE_BRCH_ST_TI1
/
ALTER INDEX EN_RTE_BRCH_ST_TI2 RENAME TO KREW_RTE_BRCH_ST_TI2
/
ALTER INDEX EN_RTE_BRCH_ST_TI3 RENAME TO KREW_RTE_BRCH_ST_TI3
/
ALTER TABLE EN_RTE_BRCH_T RENAME TO KREW_RTE_BRCH_T
/
ALTER TABLE KREW_RTE_BRCH_T RENAME COLUMN BRCH_NM TO NM
/
ALTER TABLE KREW_RTE_BRCH_T RENAME COLUMN PARNT_RTE_BRCH_ID TO PARNT_ID
/
ALTER TABLE KREW_RTE_BRCH_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_RTE_BRCH_TI1 RENAME TO KREW_RTE_BRCH_TI1
/
ALTER INDEX EN_RTE_BRCH_TI2 RENAME TO KREW_RTE_BRCH_TI2
/
ALTER INDEX EN_RTE_BRCH_TI3 RENAME TO KREW_RTE_BRCH_TI3
/
ALTER INDEX EN_RTE_BRCH_TI4 RENAME TO KREW_RTE_BRCH_TI4
/
ALTER INDEX EN_RTE_BRCH_TI5 RENAME TO KREW_RTE_BRCH_TI5
/
ALTER TABLE EN_RTE_NODE_CFG_PARM_T RENAME TO KREW_RTE_NODE_CFG_PARM_T
/
ALTER TABLE KREW_RTE_NODE_CFG_PARM_T RENAME COLUMN RTE_NODE_CFG_PARM_ND TO RTE_NODE_ID
/
ALTER TABLE KREW_RTE_NODE_CFG_PARM_T RENAME COLUMN RTE_NODE_CFG_PARM_KEY TO KEY_CD
/
ALTER TABLE KREW_RTE_NODE_CFG_PARM_T RENAME COLUMN RTE_NODE_CFG_PARM_VAL TO VAL
/
ALTER TABLE EN_RTE_NODE_INSTN_LNK_T RENAME TO KREW_RTE_NODE_INSTN_LNK_T
/
ALTER INDEX EN_RTE_NODE_INSTN_LNK_TI1 RENAME TO KREW_RTE_NODE_INSTN_LNK_TI1
/
ALTER INDEX EN_RTE_NODE_INSTN_LNK_TI2 RENAME TO KREW_RTE_NODE_INSTN_LNK_TI2
/
ALTER TABLE EN_RTE_NODE_INSTN_ST_T RENAME TO KREW_RTE_NODE_INSTN_ST_T
/
ALTER TABLE KREW_RTE_NODE_INSTN_ST_T RENAME COLUMN ST_KEY TO KEY_CD
/
ALTER TABLE KREW_RTE_NODE_INSTN_ST_T RENAME COLUMN ST_VAL_TXT TO VAL
/
ALTER TABLE KREW_RTE_NODE_INSTN_ST_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_RTE_NODE_INSTN_ST_TI1 RENAME TO KREW_RTE_NODE_INSTN_ST_TI1
/
ALTER INDEX EN_RTE_NODE_INSTN_ST_TI2 RENAME TO KREW_RTE_NODE_INSTN_ST_TI2
/
ALTER INDEX EN_RTE_NODE_INSTN_ST_TI3 RENAME TO KREW_RTE_NODE_INSTN_ST_TI3
/
ALTER TABLE EN_RTE_NODE_INSTN_T RENAME TO KREW_RTE_NODE_INSTN_T
/
ALTER TABLE KREW_RTE_NODE_INSTN_T RENAME COLUMN DOC_ID TO DOC_HDR_ID
/
ALTER TABLE KREW_RTE_NODE_INSTN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_RTE_NODE_INSTN_TI1 RENAME TO KREW_RTE_NODE_INSTN_TI1
/
ALTER INDEX EN_RTE_NODE_INSTN_TI2 RENAME TO KREW_RTE_NODE_INSTN_TI2
/
ALTER INDEX EN_RTE_NODE_INSTN_TI3 RENAME TO KREW_RTE_NODE_INSTN_TI3
/
ALTER INDEX EN_RTE_NODE_INSTN_TI4 RENAME TO KREW_RTE_NODE_INSTN_TI4
/
ALTER TABLE EN_RTE_NODE_LNK_T RENAME TO KREW_RTE_NODE_LNK_T
/
ALTER INDEX EN_RTE_NODE_LNK_TI1 RENAME TO KREW_RTE_NODE_LNK_TI1
/
ALTER INDEX EN_RTE_NODE_LNK_TI2 RENAME TO KREW_RTE_NODE_LNK_TI2
/
ALTER TABLE EN_RTE_NODE_T RENAME TO KREW_RTE_NODE_T
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN RTE_NODE_NM TO NM
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN RTE_NODE_TYP TO TYP
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN DOC_RTE_MTHD_NM TO RTE_MTHD_NM
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN DOC_RTE_MTHD_CD TO RTE_MTHD_CD
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN DOC_FNL_APRVR_IND TO FNL_APRVR_IND
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN DOC_MNDTRY_RTE_IND TO MNDTRY_RTE_IND
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN DOC_ACTVN_TYP_TXT TO ACTVN_TYP
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KREW_RTE_NODE_T RENAME COLUMN WRKGRP_ID TO GRP_ID
/
ALTER INDEX EN_RTE_NODE_TI1 RENAME TO KREW_RTE_NODE_TI1
/
ALTER INDEX EN_RTE_NODE_TI2 RENAME TO KREW_RTE_NODE_TI2
/
ALTER INDEX EN_RTE_NODE_TI3 RENAME TO KREW_RTE_NODE_TI3
/
ALTER INDEX EN_RTE_NODE_TI4 RENAME TO KREW_RTE_NODE_TI4
/
ALTER TABLE EN_RULE_ATTRIB_T RENAME TO KREW_RULE_ATTR_T
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_ID TO RULE_ATTR_ID
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_NM TO NM
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_LBL_TXT TO LBL
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_TYP TO RULE_ATTR_TYP_CD
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_DESC TO DESC_TXT
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_CLS_NM TO CLS_NM
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN RULE_ATTRIB_XML_RTE_TXT TO XML
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KREW_RULE_ATTR_T RENAME COLUMN MESSAGE_ENTITY_NM TO SVC_NMSPC
/
ALTER TABLE EN_RULE_BASE_VAL_T RENAME TO KREW_RULE_T
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_ID TO RULE_ID
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_NM TO NM
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_ACTV_IND TO ACTV_IND
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_IGNR_PRVS TO FRC_ACTN
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_FRM_DT TO FRM_DT
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_TO_DT TO TO_DT
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_DACTVN_DT TO DACTVN_DT
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_CUR_IND TO CUR_IND
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_VER_NBR TO RULE_VER_NBR
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_DLGN_IND TO DLGN_IND
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_PREV_VER TO PREV_RULE_VER_NBR
/
ALTER TABLE KREW_RULE_T RENAME COLUMN RULE_BASE_VAL_ACTVN_DT TO ACTVN_DT
/
ALTER TABLE KREW_RULE_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KREW_RULE_T RENAME CONSTRAINT EN_RULE_BASE_VAL_TR1 TO KREW_RULE_TR1
/
ALTER TABLE EN_RULE_EXPR_T RENAME TO KREW_RULE_EXPR_T
/
ALTER TABLE KREW_RULE_EXPR_T RENAME COLUMN RULE_EXPR_TYP TO TYP
/
ALTER TABLE EN_RULE_EXT_T RENAME TO KREW_RULE_EXT_T
/
ALTER TABLE KREW_RULE_EXT_T RENAME COLUMN RULE_TMPL_ATTRIB_ID TO RULE_TMPL_ATTR_ID
/
ALTER TABLE KREW_RULE_EXT_T RENAME COLUMN RULE_BASE_VAL_ID TO RULE_ID
/
ALTER TABLE KREW_RULE_EXT_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_RULE_EXT_T1 RENAME TO KREW_RULE_EXT_T1
/
ALTER TABLE EN_RULE_EXT_VAL_T RENAME TO KREW_RULE_EXT_VAL_T
/
ALTER TABLE KREW_RULE_EXT_VAL_T RENAME COLUMN RULE_EXT_VAL TO VAL
/
ALTER TABLE KREW_RULE_EXT_VAL_T RENAME COLUMN RULE_EXT_VAL_KEY TO KEY_CD
/
ALTER TABLE KREW_RULE_EXT_VAL_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_RULE_EXT_VAL_T1 RENAME TO KREW_RULE_EXT_VAL_T1
/
ALTER INDEX EN_RULE_EXT_VAL_T2 RENAME TO KREW_RULE_EXT_VAL_T2
/
ALTER TABLE EN_RULE_RSP_T RENAME TO KREW_RULE_RSP_T
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_BASE_VAL_ID TO RULE_ID
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_RSP_PRIO_NBR TO PRIO
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN ACTION_RQST_CD TO ACTN_RQST_CD
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_RSP_NM TO NM
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_RSP_TYP TO TYP
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN RULE_RSP_APPR_PLCY TO APPR_PLCY
/
ALTER TABLE KREW_RULE_RSP_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_RULE_RSP_TI1 RENAME TO KREW_RULE_RSP_TI1
/
ALTER TABLE EN_RULE_TMPL_ATTRIB_T RENAME TO KREW_RULE_TMPL_ATTR_T
/
ALTER TABLE KREW_RULE_TMPL_ATTR_T RENAME COLUMN RULE_TMPL_ATTRIB_ID TO RULE_TMPL_ATTR_ID
/
ALTER TABLE KREW_RULE_TMPL_ATTR_T RENAME COLUMN RULE_ATTRIB_ID TO RULE_ATTR_ID
/
ALTER TABLE KREW_RULE_TMPL_ATTR_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_RULE_TMPL_ATTRIB_TI1 RENAME TO KREW_RULE_TMPL_ATTR_TI1
/
ALTER INDEX EN_RULE_TMPL_ATTRIB_TI2 RENAME TO KREW_RULE_TMPL_ATTR_TI2
/
ALTER TABLE EN_RULE_TMPL_OPTN_T RENAME TO KREW_RULE_TMPL_OPTN_T
/
ALTER TABLE KREW_RULE_TMPL_OPTN_T RENAME COLUMN RULE_TMPL_OPTN_KEY TO KEY_CD
/
ALTER TABLE KREW_RULE_TMPL_OPTN_T RENAME COLUMN RULE_TMPL_OPTN_VAL TO VAL
/
ALTER TABLE KREW_RULE_TMPL_OPTN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE EN_RULE_TMPL_T RENAME TO KREW_RULE_TMPL_T
/
ALTER TABLE KREW_RULE_TMPL_T RENAME COLUMN RULE_TMPL_NM TO NM
/
ALTER TABLE KREW_RULE_TMPL_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KREW_RULE_TMPL_T RENAME CONSTRAINT EN_RULE_TMPL_TI1 TO KREW_RULE_TMPL_TI1
/
ALTER TABLE EN_USR_OPTN_T RENAME TO KREW_USR_OPTN_T
/
ALTER TABLE KREW_USR_OPTN_T RENAME COLUMN PRSN_EN_ID TO PRNCPL_ID
/
ALTER TABLE KREW_USR_OPTN_T RENAME COLUMN PRSN_OPTN_VAL TO VAL
/
ALTER TABLE KREW_USR_OPTN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_USR_OPTN_TI1 RENAME TO KREW_USR_OPTN_TI1
/
ALTER TABLE EN_BAM_PARAM_T RENAME TO KRSB_BAM_PARM_T
/
ALTER TABLE KRSB_BAM_PARM_T RENAME COLUMN BAM_PARAM_ID TO BAM_PARM_ID
/
ALTER TABLE KRSB_BAM_PARM_T RENAME COLUMN PARAM TO PARM
/
ALTER INDEX EN_BAM_PARAM_TI1 RENAME TO KREW_BAM_PARM_TI1
/
ALTER TABLE EN_BAM_T RENAME TO KRSB_BAM_T
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN SERVICE_NM TO SVC_NM
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN SERVICE_URL TO SVC_URL
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN METHOD_NM TO MTHD_NM
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN THREAD_NM TO THRD_NM
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN TARGET_TO_STRING TO TGT_TO_STR
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN SRVR_IND_IND TO SRVR_IND
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN EXCEPTION_TO_STRING TO EXCPN_TO_STR
/
ALTER TABLE KRSB_BAM_T RENAME COLUMN EXCEPTION_MSG TO EXCPN_MSG
/
ALTER INDEX EN_BAM_TI1 RENAME TO KRSB_BAM_TI1
/
ALTER INDEX EN_BAM_TI2 RENAME TO KRSB_BAM_TI2
/
ALTER TABLE EN_MSG_PAYLOAD_T RENAME TO KRSB_MSG_PYLD_T
/
ALTER TABLE KRSB_MSG_PYLD_T RENAME COLUMN MESSAGE_QUE_ID TO MSG_QUE_ID
/
ALTER TABLE KRSB_MSG_PYLD_T RENAME COLUMN MESSAGE_PAYLOAD TO MSG_PYLD
/
ALTER TABLE EN_MSG_QUE_T RENAME TO KRSB_MSG_QUE_T
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_ID TO MSG_QUE_ID
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_DT TO DT
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_EXP_DT TO EXP_DT
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_PRIO_NBR TO PRIO
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_STAT_CD TO STAT_CD
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_RTRY_CNT TO RTRY_CNT
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_QUE_IP_NBR TO IP_NBR
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_SERVICE_NM TO SVC_NM
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN MESSAGE_ENTITY_NM TO SVC_NMSPC
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN SERVICE_METHOD_NM TO SVC_MTHD_NM
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN VAL_ONE TO APP_VAL_ONE
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN VAL_TWO TO APP_VAL_TWO
/
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_MSG_QUE_TI1 RENAME TO KRSB_MSG_QUE_TI1
/
ALTER INDEX EN_MSG_QUE_TI2 RENAME TO KRSB_MSG_QUE_TI2
/
ALTER TABLE EN_SERVICE_DEF_DUEX_T RENAME TO KRSB_SVC_DEF_T
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_DEF_ID TO SVC_DEF_ID
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_NM TO SVC_NM
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_URL TO SVC_URL
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVER_IP TO SRVR_IP
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN MESSAGE_ENTITY_NM TO SVC_NMSPC
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_ALIVE TO SVC_ALIVE
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN SERVICE_DEFINITION TO SVC_DEF
/
ALTER TABLE KRSB_SVC_DEF_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX EN_SERVICE_DEF_DUEX_TI1 RENAME TO KRSB_SVC_DEF_TI1
/
ALTER TABLE FP_DOC_HEADER_T RENAME TO KRNS_DOC_HDR_T
/
ALTER TABLE KRNS_DOC_HDR_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
ALTER TABLE KRNS_DOC_HDR_T RENAME COLUMN ORG_DOC_NBR TO ORG_DOC_HDR_ID
/
ALTER TABLE KRNS_DOC_HDR_T RENAME COLUMN FDOC_TMPL_NBR TO TMPL_DOC_HDR_ID
/
ALTER TABLE KRNS_DOC_HDR_T RENAME COLUMN FDOC_EXPLAIN_TXT TO EXPLANATION
/
ALTER INDEX FP_DOC_HEADER_TI3 RENAME TO KRNS_DOC_HDR_TI3
/
ALTER TABLE KRNS_DOC_HDR_T RENAME CONSTRAINT FP_DOC_HEADER_TC0 TO KRNS_DOC_HDR_TI1
/
ALTER TABLE FP_MAINTENANCE_DOCUMENT_T RENAME TO KRNS_MAINT_DOC_T
/
ALTER TABLE KRNS_MAINT_DOC_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
ALTER TABLE KRNS_MAINT_DOC_T RENAME COLUMN DOCUMENT_CONTENTS TO DOC_CNTNT
/
ALTER TABLE KRNS_MAINT_DOC_T RENAME CONSTRAINT FP_MAINTENANCE_DOCUMENT_TC0 TO KRNS_MAINT_DOC_TC1
/
ALTER TABLE KRNS_MAINT_DOC_T RENAME CONSTRAINT FP_MAINTENANCE_DOCUMENT_TR1 TO KRNS_MAINT_DOC_TR1
/
ALTER TABLE FP_MAINT_DOC_ATTACHMENT_T RENAME TO KRNS_MAINT_DOC_ATT_T
/
ALTER TABLE KRNS_MAINT_DOC_ATT_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
ALTER TABLE KRNS_MAINT_DOC_ATT_T RENAME COLUMN ATTACHMENT TO ATT_CNTNT
/
ALTER TABLE KRNS_MAINT_DOC_ATT_T RENAME COLUMN FILE_NAME TO FILE_NM
/
ALTER TABLE KRNS_MAINT_DOC_ATT_T RENAME COLUMN CONTENT_TYPE TO CNTNT_TYP
/
ALTER TABLE KRNS_MAINT_DOC_ATT_T RENAME CONSTRAINT FP_MAINT_DOC_ATTACHMENT_TC0 TO KRNS_MAINT_DOC_ATT_TC1
/
ALTER TABLE FP_MAINT_LOCK_T RENAME TO KRNS_MAINT_LOCK_T
/
ALTER TABLE KRNS_MAINT_LOCK_T RENAME COLUMN LOCK_REPRESENTATION_TXT TO MAINT_LOCK_REP_TXT
/
ALTER TABLE KRNS_MAINT_LOCK_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
ALTER INDEX FP_MAINT_LOCK_TI2 RENAME TO KRNS_MAINT_LOCK_TI2
/
ALTER TABLE KRNS_MAINT_LOCK_T RENAME CONSTRAINT FP_MAINT_LOCK_TC0 TO KRNS_MAINT_LOCK_TC1
/
ALTER TABLE FS_ADHOC_RTE_ACTN_RECP_T RENAME TO KRNS_ADHOC_RTE_ACTN_RECIP_T
/
ALTER TABLE KRNS_ADHOC_RTE_ACTN_RECIP_T RENAME COLUMN ACTN_RQST_RECP_TYP_CD TO RECIP_TYP_CD
/
ALTER TABLE KRNS_ADHOC_RTE_ACTN_RECIP_T RENAME COLUMN ACTN_RQST_RECP_ID TO ACTN_RQST_RECIP_ID
/
ALTER TABLE KRNS_ADHOC_RTE_ACTN_RECIP_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
ALTER INDEX FS_ADHOC_RTE_ACTN_RECP_TI2 RENAME TO KRNS_ADHOC_RTE_ACTN_RECIP_T2
/
ALTER TABLE KRNS_ADHOC_RTE_ACTN_RECIP_T RENAME CONSTRAINT FS_ADHOC_RTE_ACTN_RECP_TC0 TO KRNS_ADHOC_RTE_ACTN_RECIP_TC1
/
ALTER TABLE FS_LOOKUP_RESULTS_MT RENAME TO KRNS_LOOKUP_RSLT_T
/
ALTER TABLE KRNS_LOOKUP_RSLT_T RENAME COLUMN LOOKUP_RESULT_SEQUENCE_NBR TO LOOKUP_RSLT_ID
/
ALTER TABLE KRNS_LOOKUP_RSLT_T RENAME COLUMN PERSON_UNVL_ID TO PRNCPL_ID
/
ALTER TABLE KRNS_LOOKUP_RSLT_T RENAME COLUMN LOOKUP_DATE TO LOOKUP_DT
/
ALTER TABLE KRNS_LOOKUP_RSLT_T RENAME COLUMN SERIALIZED_LOOKUP_RESULTS TO SERIALZD_RSLTS
/
ALTER TABLE KRNS_LOOKUP_RSLT_T RENAME CONSTRAINT FS_LOOKUP_RESULTS_MTC0 TO KRNS_LOOKUP_RSLT_TC0
/
ALTER TABLE FS_LOOKUP_SELECTIONS_MT RENAME TO KRNS_LOOKUP_SEL_T
/
ALTER TABLE KRNS_LOOKUP_SEL_T RENAME COLUMN LOOKUP_RESULT_SEQUENCE_NBR TO LOOKUP_RSLT_ID
/
ALTER TABLE KRNS_LOOKUP_SEL_T RENAME COLUMN PERSON_UNVL_ID TO PRNCPL_ID
/
ALTER TABLE KRNS_LOOKUP_SEL_T RENAME COLUMN LOOKUP_DATE TO LOOKUP_DT
/
ALTER TABLE KRNS_LOOKUP_SEL_T RENAME COLUMN SELECTED_OBJ_IDS TO SEL_OBJ_IDS
/
ALTER TABLE KRNS_LOOKUP_SEL_T RENAME CONSTRAINT FS_LOOKUP_SELECTIONS_MTC0 TO KRNS_LOOKUP_SEL_TC0
/
ALTER TABLE KNS_PESSIMISTIC_LOCK_T RENAME TO KRNS_PESSIMISTIC_LOCK_T
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T RENAME COLUMN LOCK_ID TO PESSIMISTIC_LOCK_ID
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T RENAME COLUMN LOCK_DESCRIPTOR TO LOCK_DESC_TXT
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T RENAME COLUMN LOCK_GENERATED_TS TO GNRT_DT
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T RENAME COLUMN PERSON_UNVL_ID TO PRNCPL_ID
/
ALTER INDEX KNS_PESSIMISTIC_LOCK_TI1 RENAME TO KRNS_PESSIMISTIC_LOCK_TI1
/
ALTER INDEX KNS_PESSIMISTIC_LOCK_TI2 RENAME TO KRNS_PESSIMISTIC_LOCK_TI2
/
ALTER TABLE KRNS_PESSIMISTIC_LOCK_T RENAME CONSTRAINT KNS_PESSIMISTIC_LOCK_TC0 TO KRNS_PESSIMISTIC_LOCK_TC0
/
ALTER TABLE KR_KNS_SESN_DOC_T RENAME TO KRNS_SESN_DOC_T
/
ALTER TABLE KRNS_SESN_DOC_T RENAME COLUMN SESSION_ID TO SESN_DOC_ID
/
ALTER TABLE KRNS_SESN_DOC_T RENAME COLUMN FDOC_NBR TO DOC_HDR_ID
/
ALTER TABLE KRNS_SESN_DOC_T RENAME COLUMN SERIALIZED_DOC_FRM TO SERIALZD_DOC_FRM
/
ALTER TABLE KRNS_SESN_DOC_T RENAME COLUMN LST_UPDATE_DT TO LAST_UPDT_DT
/
ALTER INDEX KR_KNS_SESN_DOC_TI1 RENAME TO KRNS_SESN_DOC_TI1
/
ALTER TABLE SH_ATT_T RENAME TO KRNS_ATT_T
/
ALTER TABLE KRNS_ATT_T RENAME COLUMN ATT_MIME_TYP_CD TO MIME_TYP
/
ALTER TABLE KRNS_ATT_T RENAME COLUMN ATT_FL_NM TO FILE_NM
/
ALTER TABLE KRNS_ATT_T RENAME COLUMN ATT_FL_SZ TO FILE_SZ
/
ALTER TABLE KRNS_ATT_T RENAME CONSTRAINT SH_ATT_TC0 TO KRNS_ATT_TC0
/
ALTER TABLE KRNS_ATT_T RENAME CONSTRAINT SH_ATT_TR1 TO KRNS_ATT_TR1
/
ALTER TABLE SH_NTE_T RENAME TO KRNS_NTE_T
/
ALTER TABLE KRNS_NTE_T RENAME COLUMN NTE_AUTH_ID TO AUTH_PRNCPL_ID
/
ALTER TABLE KRNS_NTE_T RENAME COLUMN NTE_POST_TS TO POST_TS
/
ALTER TABLE KRNS_NTE_T RENAME COLUMN NTE_TXT TO TXT
/
ALTER TABLE KRNS_NTE_T RENAME COLUMN NTE_PRG_CD TO PRG_CD
/
ALTER TABLE KRNS_NTE_T RENAME COLUMN NTE_TPC_TXT TO TPC_TXT
/
ALTER TABLE KRNS_NTE_T RENAME CONSTRAINT SH_NTE_TC0 TO KRNS_NTE_TC0
/
ALTER TABLE KRNS_NTE_T RENAME CONSTRAINT SH_NTE_TR1 TO KRNS_NTE_TR1
/
ALTER TABLE SH_NTE_TYP_T RENAME TO KRNS_NTE_TYP_T
/
ALTER TABLE KRNS_NTE_TYP_T RENAME COLUMN NTE_TYP_DESC TO TYP_DESC_TXT
/
ALTER TABLE KRNS_NTE_TYP_T RENAME COLUMN NTE_TYP_ACTV_IND TO ACTV_IND
/
ALTER TABLE KRNS_NTE_TYP_T RENAME CONSTRAINT SH_NTE_TYP_TC0 TO KRNS_NTE_TYP_TC0
/
ALTER TABLE SH_PARM_DTL_TYP_T RENAME TO KRNS_PARM_DTL_TYP_T
/
ALTER TABLE KRNS_PARM_DTL_TYP_T RENAME COLUMN SH_PARM_NMSPC_CD TO NMSPC_CD
/
ALTER TABLE KRNS_PARM_DTL_TYP_T RENAME COLUMN SH_PARM_DTL_TYP_CD TO PARM_DTL_TYP_CD
/
ALTER TABLE KRNS_PARM_DTL_TYP_T RENAME COLUMN SH_PARM_DTL_TYP_NM TO NM
/
ALTER TABLE KRNS_PARM_DTL_TYP_T RENAME COLUMN ACTIVE_IND TO ACTV_IND
/
ALTER TABLE KRNS_PARM_DTL_TYP_T RENAME CONSTRAINT SH_PARM_DTL_TYP_TC0 TO KRNS_PARM_DTL_TYP_TC0
/
ALTER TABLE KRNS_PARM_DTL_TYP_T RENAME CONSTRAINT SH_PARM_DTL_TYP_TR1 TO KRNS_PARM_DTL_TYP_TR1
/
ALTER TABLE SH_PARM_NMSPC_T RENAME TO KRNS_NMSPC_T
/
ALTER TABLE KRNS_NMSPC_T RENAME COLUMN SH_PARM_NMSPC_CD TO NMSPC_CD
/
ALTER TABLE KRNS_NMSPC_T RENAME COLUMN SH_PARM_NMSPC_NM TO NM
/
ALTER TABLE KRNS_NMSPC_T RENAME COLUMN ACTIVE_IND TO ACTV_IND
/
ALTER TABLE KRNS_NMSPC_T RENAME CONSTRAINT SH_PARM_NMSPC_TC0 TO KRNS_NMSPC_TC1
/
ALTER TABLE SH_PARM_T RENAME TO KRNS_PARM_T
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_NMSPC_CD TO NMSPC_CD
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_DTL_TYP_CD TO PARM_DTL_TYP_CD
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_NM TO PARM_NM
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_TYP_CD TO PARM_TYP_CD
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_TXT TO TXT
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_DESC TO PARM_DESC_TXT
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN SH_PARM_CONS_CD TO CONS_CD
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN WRKGRP_NM TO GRP_NM
/
ALTER TABLE KRNS_PARM_T RENAME COLUMN ACTIVE_IND TO ACTV_IND
/
ALTER TABLE KRNS_PARM_T RENAME CONSTRAINT SH_PARM_TC0 TO KRNS_PARM_TI1
/
ALTER TABLE KRNS_PARM_T RENAME CONSTRAINT SH_PARM_TR1 TO KRNS_PARM_TR1
/
ALTER TABLE KRNS_PARM_T RENAME CONSTRAINT SH_PARM_TR2 TO KRNS_PARM_TR2
/
ALTER TABLE SH_PARM_TYP_T RENAME TO KRNS_PARM_TYP_T
/
ALTER TABLE KRNS_PARM_TYP_T RENAME COLUMN SH_PARM_TYP_CD TO PARM_TYP_CD
/
ALTER TABLE KRNS_PARM_TYP_T RENAME COLUMN SH_PARM_TYP_NM TO NM
/
ALTER TABLE KRNS_PARM_TYP_T RENAME COLUMN ACTIVE_IND TO ACTV_IND
/
ALTER TABLE KRNS_PARM_TYP_T RENAME CONSTRAINT SH_PARM_TYP_TC0 TO KRNS_PARM_TYP_TC0
/
ALTER TABLE KR_QRTZ_BLOB_TRIGGERS RENAME TO KRSB_QRTZ_BLOB_TRIGGERS
/
ALTER TABLE KRSB_QRTZ_BLOB_TRIGGERS RENAME CONSTRAINT KR_QRTZ_BLOB_TRIGGERS_TR1 TO KRSB_QRTZ_BLOB_TRIGGERS_TR1
/
ALTER TABLE KR_QRTZ_CALENDARS RENAME TO KRSB_QRTZ_CALENDARS
/
ALTER TABLE KR_QRTZ_CRON_TRIGGERS RENAME TO KRSB_QRTZ_CRON_TRIGGERS
/
ALTER TABLE KRSB_QRTZ_CRON_TRIGGERS RENAME CONSTRAINT KR_QRTZ_CRON_TRIGGERS_TR1 TO KRSB_QRTZ_CRON_TRIGGERS_TR1
/
ALTER TABLE KR_QRTZ_FIRED_TRIGGERS RENAME TO KRSB_QRTZ_FIRED_TRIGGERS
/
ALTER INDEX IDX_KR_QRTZ_FT_JOB_GROUP RENAME TO KRSB_QRTZ_FIRED_TRIGGERS_TI1
/
ALTER INDEX IDX_KR_QRTZ_FT_JOB_NAME RENAME TO KRSB_QRTZ_FIRED_TRIGGERS_TI2
/
ALTER INDEX IDX_KR_QRTZ_FT_JOB_REQ_RECOV RENAME TO KRSB_QRTZ_FIRED_TRIGGERS_TI3
/
ALTER INDEX IDX_KR_QRTZ_FT_JOB_STATEFUL RENAME TO KRSB_QRTZ_FIRED_TRIGGERS_TI4
/
ALTER INDEX IDX_KR_QRTZ_FT_TRIG_GROUP RENAME TO KRSB_QRTZ_FIRED_TRIGGERS_TI5
/
ALTER INDEX IDX_KR_QRTZ_FT_TRIG_INST_NAME RENAME TO KRSB_QRTZ_FIRED_TRIGGERS_TI6
/
ALTER INDEX IDX_KR_QRTZ_FT_TRIG_NAME RENAME TO KRSB_QRTZ_FIRED_TRIGGERS_TI7
/
ALTER INDEX IDX_KR_QRTZ_FT_TRIG_NM_GP RENAME TO KRSB_QRTZ_FIRED_TRIGGERS_TI8
/
ALTER INDEX IDX_KR_QRTZ_FT_TRIG_VOLATILE RENAME TO KRSB_QRTZ_FIRED_TRIGGERS_TI9
/
ALTER TABLE KR_QRTZ_JOB_DETAILS RENAME TO KRSB_QRTZ_JOB_DETAILS
/
ALTER INDEX IDX_KR_QRTZ_J_REQ_RECOVERY RENAME TO KRSB_QRTZ_JOB_DETAILS_TI1
/
ALTER TABLE KR_QRTZ_JOB_LISTENERS RENAME TO KRSB_QRTZ_JOB_LISTENERS
/
ALTER TABLE KRSB_QRTZ_JOB_LISTENERS RENAME CONSTRAINT KR_QRTZ_JOB_LISTENERS_TR1 TO KRSB_QUARTZ_JOB_LISTENERS_TR1
/
ALTER TABLE KR_QRTZ_LOCKS RENAME TO KRSB_QRTZ_LOCKS
/
ALTER TABLE KR_QRTZ_PAUSED_TRIGGER_GRPS RENAME TO KRSB_QRTZ_PAUSED_TRIGGER_GRPS
/
ALTER TABLE KR_QRTZ_SCHEDULER_STATE RENAME TO KRSB_QRTZ_SCHEDULER_STATE
/
ALTER TABLE KR_QRTZ_SIMPLE_TRIGGERS RENAME TO KRSB_QRTZ_SIMPLE_TRIGGERS
/
ALTER TABLE KRSB_QRTZ_SIMPLE_TRIGGERS RENAME CONSTRAINT KR_QRTZ_SIMPLE_TRIGGERS TO KRSB_QRTZ_SIMPLE_TRIGGERS_TR1
/
ALTER TABLE KR_QRTZ_TRIGGERS RENAME TO KRSB_QRTZ_TRIGGERS
/
ALTER INDEX IDX_KR_QRTZ_T_NEXT_FIRE_TIME RENAME TO KRSB_QRTZ_TRIGGERS_TI1
/
ALTER INDEX IDX_KR_QRTZ_T_NFT_ST RENAME TO KRSB_QRTZ_TRIGGERS_TI2
/
ALTER INDEX IDX_KR_QRTZ_T_STATE RENAME TO KRSB_QRTZ_TRIGGERS_TI3
/
ALTER INDEX IDX_KR_QRTZ_T_VOLATILE RENAME TO KRSB_QRTZ_TRIGGERS_TI4
/
ALTER TABLE KR_QRTZ_TRIGGER_LISTENERS RENAME TO KRSB_QRTZ_TRIGGER_LISTENERS
/
ALTER TABLE KRSB_QRTZ_TRIGGER_LISTENERS RENAME CONSTRAINT KR_QRTZ_TRIGGER_LISTENERS_TR1 TO KRSB_QRTZ_TRIGGER_LISTENE_TR1
/
ALTER TABLE KCB_MESSAGES RENAME TO KREN_MSG_T
/
ALTER TABLE KREN_MSG_T RENAME COLUMN ID TO MSG_ID
/
ALTER TABLE KREN_MSG_T RENAME COLUMN ORIGIN_ID TO ORGN_ID
/
ALTER TABLE KREN_MSG_T RENAME COLUMN DELIVERY_TYPE TO DELIV_TYP
/
ALTER TABLE KREN_MSG_T RENAME COLUMN CREATED_DATETIME TO CRTE_DTTM
/
ALTER TABLE KREN_MSG_T RENAME COLUMN TITLE TO TTL
/
ALTER TABLE KREN_MSG_T RENAME COLUMN CHANNEL TO CHNL
/
ALTER TABLE KREN_MSG_T RENAME COLUMN PRODUCER TO PRODCR
/
ALTER TABLE KREN_MSG_T RENAME COLUMN CONTENT TO CNTNT
/
ALTER TABLE KREN_MSG_T RENAME COLUMN CONTENT_TYPE TO CNTNT_TYP
/
ALTER TABLE KREN_MSG_T RENAME COLUMN USER_RECIPIENT_ID TO RECIP_ID
/
ALTER TABLE KREN_MSG_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KREN_MSG_T RENAME CONSTRAINT KCB_MESSAGES_UK1 TO KREN_MSG_UK1
/
ALTER TABLE KCB_MSG_DELIVS RENAME TO KREN_MSG_DELIV_T
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN ID TO MSG_DELIV_ID
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN MESSAGE_ID TO MSG_ID
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN DELIVERER_TYPE_NAME TO TYP_NM
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN DELIVERER_SYSTEM_ID TO SYS_ID
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN DELIVERY_STATUS TO STAT_CD
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN PROCESS_COUNT TO PROC_CNT
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN LOCKED_DATE TO LOCKD_DTTM
/
ALTER TABLE KREN_MSG_DELIV_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX KCB_MSG_DELIVSI1 RENAME TO KREN_MSG_DELIV_TI1
/
ALTER TABLE KREN_MSG_DELIV_T RENAME CONSTRAINT KCB_MSG_DELIVS_UK1 TO KREN_MSG_DELIV_UK1
/
ALTER TABLE KREN_MSG_DELIV_T RENAME CONSTRAINT KCB_MSG_DELIVS_FK1 TO KREN_MSG_DELIV_FK1
/
ALTER TABLE KCB_RECIP_DELIVS RENAME TO KREN_RECIP_DELIV_T
/
ALTER TABLE KREN_RECIP_DELIV_T RENAME COLUMN ID TO RECIP_DELIV_ID
/
ALTER TABLE KREN_RECIP_DELIV_T RENAME COLUMN RECIPIENT_ID TO RECIP_ID
/
ALTER TABLE KREN_RECIP_DELIV_T RENAME COLUMN CHANNEL TO CHNL
/
ALTER TABLE KREN_RECIP_DELIV_T RENAME COLUMN DELIVERER_NAME TO NM
/
ALTER TABLE KREN_RECIP_DELIV_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KREN_RECIP_DELIV_T RENAME CONSTRAINT KCB_RECIP_DELIVS_UK1 TO KREN_RECIP_DELIV_UK1
/
ALTER TABLE KCB_RECIP_PREFS RENAME TO KREN_RECIP_PREFS_T
/
ALTER TABLE KREN_RECIP_PREFS_T RENAME COLUMN ID TO RECIP_PREFS_ID
/
ALTER TABLE KREN_RECIP_PREFS_T RENAME COLUMN RECIPIENT_ID TO RECIP_ID
/
ALTER TABLE KREN_RECIP_PREFS_T RENAME COLUMN PROPERTY TO PROP
/
ALTER TABLE KREN_RECIP_PREFS_T RENAME COLUMN VALUE TO VAL
/
ALTER TABLE KREN_RECIP_PREFS_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER TABLE KREN_RECIP_PREFS_T RENAME CONSTRAINT KCB_RECIP_PREFS_UK1 TO KREN_RECIP_PREFS_UK1
/
ALTER TABLE NOTIFICATION_PRODUCERS RENAME TO KREN_PRODCR_T
/
ALTER TABLE KREN_PRODCR_T RENAME COLUMN ID TO PRODCR_ID
/
ALTER TABLE KREN_PRODCR_T RENAME COLUMN NAME TO NM
/
ALTER TABLE KREN_PRODCR_T RENAME COLUMN DESCRIPTION TO DESC_TXT
/
ALTER TABLE KREN_PRODCR_T RENAME COLUMN CONTACT_INFO TO CNTCT_INFO
/
ALTER TABLE KREN_PRODCR_T RENAME CONSTRAINT NOTIFICATION_PRODUCERS_UK1 TO KREN_PRODCR_UK1
/
ALTER TABLE NOTIFICATION_CHANNELS RENAME TO KREN_CHNL_T
/
ALTER TABLE KREN_CHNL_T RENAME COLUMN ID TO CHNL_ID
/
ALTER TABLE KREN_CHNL_T RENAME COLUMN NAME TO NM
/
ALTER TABLE KREN_CHNL_T RENAME COLUMN DESCRIPTION TO DESC_TXT
/
ALTER TABLE KREN_CHNL_T RENAME COLUMN SUBSCRIBABLE TO SUBSCRB_IND
/
ALTER TABLE KREN_CHNL_T RENAME CONSTRAINT NOTIFICATION_CHANNELS_UK1 TO KREN_CHNL_UK1
/
ALTER TABLE NOTIFICATION_PRIORITIES RENAME TO KREN_PRIO_T
/
ALTER TABLE KREN_PRIO_T RENAME COLUMN ID TO PRIO_ID
/
ALTER TABLE KREN_PRIO_T RENAME COLUMN NAME TO NM
/
ALTER TABLE KREN_PRIO_T RENAME COLUMN DESCRIPTION TO DESC_TXT
/
ALTER TABLE KREN_PRIO_T RENAME COLUMN PRIORITY_ORDER TO PRIO_ORD
/
ALTER TABLE KREN_PRIO_T RENAME CONSTRAINT NOTIFICATION_PRIORITIES_UK1 TO KREN_PRIO_UK1
/
ALTER TABLE NOTIFICATION_CONTENT_TYPES RENAME TO KREN_CNTNT_TYP_T
/
ALTER TABLE KREN_CNTNT_TYP_T RENAME COLUMN ID TO CNTNT_TYP_ID
/
ALTER TABLE KREN_CNTNT_TYP_T RENAME COLUMN NAME TO NM
/
ALTER TABLE KREN_CNTNT_TYP_T RENAME COLUMN VERSION TO CNTNT_TYP_VER_NBR
/
ALTER TABLE KREN_CNTNT_TYP_T RENAME COLUMN DESCRIPTION TO DESC_TXT
/
ALTER TABLE KREN_CNTNT_TYP_T RENAME COLUMN NAMESPACE TO NMSPC_CD
/
ALTER TABLE KREN_CNTNT_TYP_T RENAME CONSTRAINT NOTIFICATION_CONTENT_TYPE_UK1 TO KREN_CNTNT_TYP_UK1
/
ALTER TABLE NOTIFICATIONS RENAME TO KREN_NTFCTN_T
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN ID TO NTFCTN_ID
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN DELIVERY_TYPE TO DELIV_TYP
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN CREATED_DATETIME TO CRTE_DTTM
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN SEND_DATETIME TO SND_DTTM
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN AUTO_REMOVE_DATETIME TO AUTO_RMV_DTTM
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN PRIORITY_ID TO PRIO_ID
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN TITLE TO TTL
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN CONTENT TO CNTNT
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN CONTENT_TYPE_ID TO CNTNT_TYP_ID
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN NOTIFICATION_CHANNEL_ID TO CHNL_ID
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN PRODUCER_ID TO PRODCR_ID
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN LOCKED_DATE TO LOCKD_DTTM
/
ALTER TABLE KREN_NTFCTN_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX KEN_NOTIFICATIONSI1 RENAME TO KREN_NTFCTN_I1
/
ALTER INDEX KEN_NOTIFICATIONSI2 RENAME TO KREN_NTFCTN_I2
/
ALTER INDEX KEN_NOTIFICATIONSI3 RENAME TO KREN_NTFCTN_I3
/
ALTER TABLE KREN_NTFCTN_T RENAME CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK4 TO KREN_NTFCTN_FK4
/
ALTER TABLE KREN_NTFCTN_T RENAME CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK2 TO KREN_NTFCTN_FK2
/
ALTER TABLE KREN_NTFCTN_T RENAME CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK1 TO KREN_NTFCTN_FK1
/
ALTER TABLE KREN_NTFCTN_T RENAME CONSTRAINT NOTIFICATIONS_NOTIFICATIO_FK3 TO KREN_NTFCTN_FK3
/
ALTER TABLE NOTIFICATION_CHANNEL_PRODUCERS RENAME TO KREN_CHNL_PRODCR_T
/
ALTER TABLE KREN_CHNL_PRODCR_T RENAME COLUMN CHANNEL_ID TO CHNL_ID
/
ALTER TABLE KREN_CHNL_PRODCR_T RENAME COLUMN PRODUCER_ID TO PRODCR_ID
/
ALTER INDEX KEN_CHANNEL_PRODUCERSI1 RENAME TO KREN_CHNL_PRODCR_TI1
/
ALTER INDEX KEN_CHANNEL_PRODUCERSI2 RENAME TO KREN_CHNL_PRODCR_TI2
/
ALTER TABLE KREN_CHNL_PRODCR_T RENAME CONSTRAINT NOTIFICATION_CHANNEL_PROD_FK1 TO KREN_CHNL_PRODCR_FK1
/
ALTER TABLE KREN_CHNL_PRODCR_T RENAME CONSTRAINT NOTIFICATION_CHANNEL_PROD_FK2 TO KREN_CHNL_PRODCR_FK2
/
ALTER TABLE NOTIFICATION_MSG_DELIVS RENAME TO KREN_NTFCTN_MSG_DELIV_T
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN ID TO NTFCTN_MSG_DELIV_ID
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN NOTIFICATION_ID TO NTFCTN_ID
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN USER_RECIPIENT_ID TO RECIP_ID
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN MESSAGE_DELIVERY_STATUS TO STAT_CD
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN DELIVERY_SYSTEM_ID TO SYS_ID
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN LOCKED_DATE TO LOCKD_DTTM
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME COLUMN DB_LOCK_VER_NBR TO VER_NBR
/
ALTER INDEX KEN_MSG_DELIVSI1 RENAME TO KREN_MSG_DELIVSI1
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME CONSTRAINT NOTIF_MSG_DELIVS_UK1 TO KREN_NTFCTN_MSG_DELIVS_UK1
/
ALTER TABLE KREN_NTFCTN_MSG_DELIV_T RENAME CONSTRAINT NOTIF_MSG_DELIVS_FK1 TO KREN_NTFCTN_MSG_DELIV_FK1
/
ALTER TABLE NOTIFICATION_RECIPIENTS RENAME TO KREN_RECIP_T
/
ALTER TABLE KREN_RECIP_T RENAME COLUMN ID TO RECIP_ID
/
ALTER TABLE KREN_RECIP_T RENAME COLUMN NOTIFICATION_ID TO NTFCTN_ID
/
ALTER TABLE KREN_RECIP_T RENAME COLUMN RECIPIENT_TYPE TO RECIP_TYP_CD
/
ALTER TABLE KREN_RECIP_T RENAME COLUMN RECIPIENT_ID TO PRNCPL_ID
/
ALTER INDEX KEN_RECIPIENTSI1 RENAME TO KREN_RECIP_TI1
/
ALTER TABLE KREN_RECIP_T RENAME CONSTRAINT NOTIFICATION_RECIPIENTS_UK1 TO KREN_RECIP_UK1
/
ALTER TABLE KREN_RECIP_T RENAME CONSTRAINT NOTIFICATION_RECIPIENTS_N_FK1 TO KREN_RECIP_FK1
/
ALTER TABLE NOTIFICATION_RECIPIENTS_LISTS RENAME TO KREN_RECIP_LIST_T
/
ALTER TABLE KREN_RECIP_LIST_T RENAME COLUMN ID TO RECIP_LIST_ID
/
ALTER TABLE KREN_RECIP_LIST_T RENAME COLUMN CHANNEL_ID TO CHNL_ID
/
ALTER TABLE KREN_RECIP_LIST_T RENAME COLUMN RECIPIENT_TYPE TO RECIP_TYP_CD
/
ALTER TABLE KREN_RECIP_LIST_T RENAME COLUMN RECIPIENT_ID TO RECIP_ID
/
ALTER INDEX KEN_RECIPIENTS_LISTSI1 RENAME TO KREN_RECIP_LIST_TI1
/
ALTER TABLE KREN_RECIP_LIST_T RENAME CONSTRAINT NOTIFICATION_RECIPIENTS_L_UK1 TO KREN_RECIP_LIST_UK1
/
ALTER TABLE KREN_RECIP_LIST_T RENAME CONSTRAINT NOTIFICATION_RECIPIENTS_L_FK1 TO KREN_RECIP_LIST_FK1
/
ALTER TABLE NOTIFICATION_REVIEWERS RENAME TO KREN_RVWER_T
/
ALTER TABLE KREN_RVWER_T RENAME COLUMN ID TO RVWER_ID
/
ALTER TABLE KREN_RVWER_T RENAME COLUMN CHANNEL_ID TO CHNL_ID
/
ALTER TABLE KREN_RVWER_T RENAME COLUMN REVIEWER_TYPE TO TYP
/
ALTER TABLE KREN_RVWER_T RENAME COLUMN REVIEWER_ID TO PRNCPL_ID
/
ALTER INDEX KEN_REVIEWERSI1 RENAME TO KREN_RVWER_TI1
/
ALTER TABLE KREN_RVWER_T RENAME CONSTRAINT NOTIFICATION_REVIEWERS_UK1 TO KREN_RVWER_UK1
/
ALTER TABLE KREN_RVWER_T RENAME CONSTRAINT NOTIFICATION_REVIEWERS_N_FK1 TO KREN_RVWER_FK1
/
ALTER TABLE NOTIFICATION_SENDERS RENAME TO KREN_SNDR_T
/
ALTER TABLE KREN_SNDR_T RENAME COLUMN ID TO SNDR_ID
/
ALTER TABLE KREN_SNDR_T RENAME COLUMN NOTIFICATION_ID TO NTFCTN_ID
/
ALTER TABLE KREN_SNDR_T RENAME COLUMN NAME TO NM
/
ALTER INDEX KEN_SENDERSI1 RENAME TO KREN_SNDR_TI1
/
ALTER TABLE KREN_SNDR_T RENAME CONSTRAINT NOTIFICATION_SENDERS_UK1 TO KREN_SNDR_UK1
/
ALTER TABLE KREN_SNDR_T RENAME CONSTRAINT NOTIFICATION_SENDERS_NOTI_FK1 TO KREN_SNDR_FK1
/
ALTER TABLE USER_CHANNEL_SUBSCRIPTIONS RENAME TO KREN_CHNL_SUBSCRP_T
/
ALTER TABLE KREN_CHNL_SUBSCRP_T RENAME COLUMN ID TO CHNL_SUBSCRP_ID
/
ALTER TABLE KREN_CHNL_SUBSCRP_T RENAME COLUMN CHANNEL_ID TO CHNL_ID
/
ALTER TABLE KREN_CHNL_SUBSCRP_T RENAME COLUMN USER_ID TO PRNCPL_ID
/
ALTER INDEX KEN_USER_CHAN_SUBSI1 RENAME TO KREN_CHNL_SUBSCRP_TI1
/
ALTER TABLE KREN_CHNL_SUBSCRP_T RENAME CONSTRAINT USER_CHANNEL_SUBSCRIPTION_UK1 TO KREN_CHNL_SUBSCRP_UK1
/
ALTER TABLE KREN_CHNL_SUBSCRP_T RENAME CONSTRAINT USER_CHANNEL_SUBSCRIPTION_FK1 TO KREN_CHAN_SUBSCRP_FK1
/
RENAME BAM_PARAM_SEQ TO KRSB_BAM_PARM_S
/
RENAME BAM_SEQ TO KRSB_BAM_S
/
RENAME SERVICE_DEF_SEQ TO KRSB_SVC_DEF_S
/
RENAME FP_DOC_TYPE_ATTR_ID_SEQ TO KRNS_DOC_TYP_ATTR_S
/
RENAME LOCK_ID_SEQ TO KRNS_LOCK_S
/
RENAME LOOKUP_RESULT_SEQUENCE_NBR_SEQ TO KRNS_LOOKUP_RSLT_S
/
RENAME NTE_ID_SEQ TO KRNS_NTE_S
/
RENAME KCB_MESSAGES_SEQ TO KREN_MSG_S
/
RENAME KCB_MSG_DELIVS_SEQ TO KREN_MSG_DELIV_S
/
RENAME KCB_RECIP_DELIVS_SEQ TO KREN_RECIP_DELIV_S
/
RENAME KCB_RECIP_PREFS_SEQ TO KREN_RECIP_PREF_S
/
RENAME NOTIFICATIONS_SEQ TO KREN_NTFCTN_S
/
RENAME NOTIFICATION_CHANNELS_SEQ TO KREN_CHNL_S
/
RENAME NOTIFICATION_CONTENT_TYPES_SEQ TO KREN_CNTNT_TYP_S
/
RENAME NOTIFICATION_MSG_DELIVS_SEQ TO KREN_NTFCTN_MSG_DELIV_S
/
RENAME NOTIFICATION_PRIORITIES_SEQ TO KREN_PRIO_S
/
RENAME NOTIFICATION_PRODUCERS_SEQ TO KREN_PRODCR_S
/
RENAME NOTIFICATION_RECIPIENTS_SEQ TO KREN_RECIP_S
/
RENAME NOTIFICATION_RECIPS_LISTS_SEQ TO KREN_RECIP_LIST_S
/
RENAME NOTIFICATION_REVIEWERS_SEQ TO KREN_RVWER_S
/
RENAME NOTIFICATION_SENDERS_SEQ TO KREN_SNDR_S
/
RENAME USER_CHANNEL_SUBSCRIPTIONS_SEQ TO KREN_CHNL_SUBSCRP_S
/
RENAME SEQUENCE_EN_USR TO KREW_USR_S
/
RENAME SEQ_ACTION_LIST_OPTN TO KREW_ACTN_LIST_OPTN_S
/
RENAME SEQ_ACTION_REQUEST TO KREW_ACTN_RQST_S
/
RENAME SEQ_ACTION_TAKEN TO KREW_ACTN_TKN_S
/
RENAME SEQ_ACTN_ITM TO KREW_ACTN_ITM_S
/
RENAME SEQ_DOCUMENT_ROUTE_HEADER TO KREW_DOC_HDR_S
/
RENAME SEQ_DOC_NTE TO KREW_DOC_NTE_S
/
RENAME SEQ_EDL_FIELD_DMP TO KREW_EDL_FLD_DMP_S
/
RENAME SEQ_EN_EDOCLT TO KREW_EDL_S
/
RENAME SEQ_HELP_ENTRY TO KREW_HLP_S
/
RENAME SEQ_OUT_BOX_ITM TO KREW_OUT_BOX_ITM_S
/
RENAME SEQ_RESPONSIBILITY_ID TO KREW_RSP_S
/
RENAME SEQ_ROUTE_TEMPLATE TO KREW_RTE_TMPL_S
/
RENAME SEQ_RTE_NODE TO KREW_RTE_NODE_S
/
RENAME SEQ_RTE_NODE_CFG_PARM TO KREW_RTE_NODE_CFG_PARM_S
/
RENAME SEQ_RULE_EXPR TO KREW_RULE_EXPR_S
/
RENAME SEQ_RULE_TMPL_OPTN TO KREW_RULE_TMPL_OPTN_S
/
RENAME SEQ_SEARCHABLE_ATTRIBUTE_VALUE TO KREW_SRCH_ATTR_S
/
