ALTER TABLE KRMS_CNTXT_VLD_ACTN_T DROP FOREIGN KEY KRMS_CNTXT_VLD_ACTN_FK1;
DROP INDEX KRMS_CNTXT_VLD_ACTN_TI1 ON KRMS_CNTXT_VLD_ACTN_T;
RENAME TABLE KRMS_CNTXT_VLD_ACTN_S TO KRMS_CNTXT_VLD_ACTN_TYP_S;
RENAME TABLE KRMS_CNTXT_VLD_ACTN_T TO KRMS_CNTXT_VLD_ACTN_TYP_T;
CREATE INDEX KRMS_CNTXT_VLD_ACTN_TYP_TI1 ON KRMS_CNTXT_VLD_ACTN_TYP_T (CNTXT_ID);
ALTER TABLE KRMS_CNTXT_VLD_ACTN_TYP_T ADD CONSTRAINT KRMS_CNTXT_VLD_ACTN_TYP_FK1
  FOREIGN KEY (CNTXT_ID) REFERENCES KRMS_CNTXT_T (CNTXT_ID);

ALTER TABLE KRMS_CNTXT_VLD_AGENDA_T DROP FOREIGN KEY KRMS_CNTXT_VLD_AGENDA_FK1;
DROP INDEX KRMS_CNTXT_VLD_AGENDA_TI1 ON KRMS_CNTXT_VLD_AGENDA_T;
RENAME TABLE KRMS_CNTXT_VLD_AGENDA_S TO KRMS_CNTXT_VLD_AGENDA_TYP_S;
RENAME TABLE KRMS_CNTXT_VLD_AGENDA_T TO KRMS_CNTXT_VLD_AGENDA_TYP_T;
CREATE INDEX KRMS_CNTXT_VLD_AGENDA_TYP_TI1 ON KRMS_CNTXT_VLD_AGENDA_TYP_T (CNTXT_ID);
ALTER TABLE KRMS_CNTXT_VLD_AGENDA_TYP_T ADD CONSTRAINT KRMS_CNTXT_VLD_AGENDA_TYP_FK1
  FOREIGN KEY (CNTXT_ID) REFERENCES KRMS_CNTXT_T (CNTXT_ID);

ALTER TABLE KRMS_CNTXT_VLD_RULE_T DROP FOREIGN KEY KRMS_CNTXT_VLD_RULE_FK1;
DROP INDEX KRMS_CNTXT_VLD_RULE_TI1 ON KRMS_CNTXT_VLD_RULE_T;
RENAME TABLE KRMS_CNTXT_VLD_RULE_S TO KRMS_CNTXT_VLD_RULE_TYP_S;
RENAME TABLE KRMS_CNTXT_VLD_RULE_T TO KRMS_CNTXT_VLD_RULE_TYP_T;
CREATE INDEX KRMS_CNTXT_VLD_RULE_TYP_TI1 ON KRMS_CNTXT_VLD_RULE_TYP_T (CNTXT_ID);
ALTER TABLE KRMS_CNTXT_VLD_RULE_TYP_T ADD CONSTRAINT KRMS_CNTXT_VLD_RULE_TYP_FK1
  FOREIGN KEY (CNTXT_ID) REFERENCES KRMS_CNTXT_T (CNTXT_ID);

ALTER TABLE KRMS_CNTXT_VLD_RULE_TYP_T CHANGE RULE_ID RULE_TYP_ID VARCHAR(40) NOT NULL;

UPDATE KRMS_AGENDA_T SET TYP_ID = NULL WHERE TYP_ID = 'T5';
UPDATE KRMS_RULE_T SET TYP_ID = NULL;
DELETE FROM KRMS_CNTXT_VLD_RULE_TYP_T;